### PR TITLE
Clarify third party subcommand failure error message

### LINKED ISSUE #2378: Have a more meaningful error message for third party subcommands exiting unsuccessfully
Currently it prints `An unknown error occurred`.

An example where this is surprising, with [`cargo-check`](https://crates.io/crates/cargo-check):

```
$ tmp=$(mktemp -d) && cd $tmp
$ echo "this-=:[won't-parse[]" > Cargo.toml
$ cargo check
failed to parse manifest at `/tmp/tmp.ySuwR73Jbz/Cargo.toml`

Caused by:
  could not parse input as TOML
Cargo.toml:1:7-1:8 expected a value

An unknown error occurred

To learn more, run the command again with --verbose.
```

I think "Third party subcommand `cargo check` failed" or something like that would be good.

### PR DESCRIPTION
**Pull request by JIghtuse**
Fixes #2378

### CODE REVIEW

**Comment by JIghtuse** [comment]
I'm not sure test should live in `test_cargo_install.rs`. Will replace it if needed.

File: src/bin/cargo.rs [hunk 1]
```diff
@@ -205,8 +205,10 @@ fn execute_subcommand(config: &Config,
             }))
         }
     };
-    try!(util::process(&command).args(&args[1..]).exec());
-    Ok(())
+    match util::process(&command).args(&args[1..]).exec() {
+        Err(..) => Err(human(format!("Third party subcommand {:?} exited unsuccessfully.", command))),
```
Comment (alexcrichton) [inline src/bin/cargo.rs]: Perhaps this could use `chain_error` to avoid losing error information here? 

Error messages in Cargo also typically start with a lowercase letter and don't end with punctuation. I'd also recommend using a format string like:

```
third part subcommand `{}` exited unsuccessfully
```

Comment (JIghtuse) [inline src/bin/cargo.rs]: Fixed. Actually, now there is some duplication in error message, but if we suppose one is from 3rd party command and one from the cargo itself, it is probably fine.

    $ cargo check
       Compiling hexadecimal v0.0.0 (file:///home/user/projects/rust/hexadecimal)
    src/lib.rs:1:1: 1:3 error: expected item, found `ub`
    src/lib.rs:1 ub fn hex_to_int(s: &str) -> Option<usize> {
                 ^~
    error: aborting due to previous error
    Could not compile `hexadecimal`.

    To learn more, run the command again with --verbose.
    third party subcommand `cargo-check` exited unsuccessfully

    To learn more, run the command again with --verbose.

**Comment by alexcrichton** [comment]
Hm, what's the extra context there if you pass `--verbose`? It may also be worth having exhaustive output matching in the test to ensure we don't regress too much

**Comment by alexcrichton** [comment]
(also looks like some tests are failing)

**Comment by JIghtuse** [comment]
Ah, it looks like tests failing due to message about RUST_BACKTRACE which appeared recently. I guess, we can just return non-zero result from main instead of panicking to simplify test.

**Comment by JIghtuse** [comment]
Ah, it looks like tests failing due to recently added to `rustc` message about RUST_BACKTRACE:

    note: Run with `RUST_BACKTRACE=1` for a backtrace.

Is it possible to run some test for nightly only and some on beta/stable only? On the other hand, if we run tests separately for channels we will need to tweak them later..

**Comment by alexcrichton** [comment]
Ah you can probably just match the error message specifically with something like:

```rust
.with_stdout_contains("\
error text

Caused by:
  more error text
");
```

The usage of `_contains` should avoid exhaustively matching everything.

**Comment by JIghtuse** [comment]
@alexcrichton now it should be fine, I guess. We check for all stderr contents except of `RUST_BACKTRACE` lines.

**Comment by alexcrichton** [comment]
I think that this may still fail due to `.exe` on Windows and not being present on Unix, but we can see what the CI says

**Comment by JIghtuse** [comment]
@alexcrichton you are right, as always :smile: Amending fix again.

**Comment by JIghtuse** [comment]
This time the only change was to ``cargo-fail`` quote, so it should works.

**Comment by alexcrichton** [comment]
@bors: r+ 00dd4b7674cdd2f5366122b2c5a2859cc34016fb

Thanks!

**Comment by kamalmarhubi** [comment]
@JIghtuse oh nice!
