### PR TITLE
Fixed panic when canonicalizing not-a-base-url, fixes #4394

### LINKED ISSUE #4394: Panic when attempting to `install --git` with Github provided ssh link
First attempt:

```text
$ cargo +nightly install --git git@github.com:rust-lang-nursery/rustfmt.git
error: invalid url `git@github.com:rust-lang-nursery/rustfmt.git`: relative URL without a base
```

Second attempt:

```text
$ cargo +nightly install --git github.com:rust-lang-nursery/rustfmt.git
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

With backtrace:

```text
$ set RUST_BACKTRACE=1 && cargo +nightly install --git github.com:rust-lang-nursery/rustfmt.git
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335:20
stack backtrace:
   0: git_remote_name
   1: git_remote_name
   2: git_remote_name
   3: git_remote_name
   4: git_remote_name
   5: git_remote_name
   6: git_remote_name
   7: git_remote_name
   8: git_remote_name
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: git_remote_name
  17: git_remote_name
  18: git_note_id
  19: BaseThreadInitThunk
```

Expected: Error message because this is an invalid format (or for it to work)

Actual: Panicked, see above

(Note: installing via the https link worked fine.)

I am on Windows.

### PR DESCRIPTION
**Pull request by debris**
Fixes #4394. Majority of the changes are caused by propagating error upstream to `SourceId` and `GitSource`.

### CODE REVIEW

File: src/cargo/sources/git/source.rs [hunk 1]
```diff
@@ -67,13 +69,22 @@ fn ident(url: &Url) -> String {
...
-    format!("{}-{}", ident, short_hash(&url))
+    Ok(format!("{}-{}", ident, short_hash(&url)))
 }
 
 // Some hacks and heuristics for making equivalent URLs hash the same
-pub fn canonicalize_url(url: &Url) -> Url {
+pub fn canonicalize_url(url: &Url) -> CargoResult<Url> {
     let mut url = url.clone();
 
+    if url.cannot_be_a_base() {
```
Comment (debris) [inline src/cargo/sources/git/source.rs]: docs: https://docs.rs/url/1.5.1/url/struct.Url.html#method.cannot_be_a_base

File: src/cargo/sources/git/source.rs [hunk 2]
```diff
@@ -67,13 +69,22 @@ fn ident(url: &Url) -> String {
...
+        if url.scheme() != "github.com" {
+            return Err(format!("invalid url `{}`: cannot-be-a-base-URLs are not supported", url).into());
+        }
+        // it's most likely an attempt to fetch github repo
+        // https://github.com/rust-lang/cargo/issues/4394
+        url = Url::parse(&format!("https://github.com/{}", url.path())).unwrap();
```
Comment (debris) [inline src/cargo/sources/git/source.rs]: I'm not sure about this one, but usually after

```
cargo install --git git@github.com:rust-lang-nursery/rustfmt.git
```

fails, people try

```
cargo install --git github.com:rust-lang-nursery/rustfmt.git
```

Comment (alexcrichton) [inline src/cargo/sources/git/source.rs]: Oh for now I think it may be best to just return an error here, I don't think we're quite at the point where we want to enable these URLs yet (they're typically SSH urls, not git urls)

**Comment by alexcrichton** [comment]
Looks great to me, thanks for taking this on @debris!

**Comment by alexcrichton** [comment]
Could you also add an "integration test case" in `tests/install.rs` in addition to the unit tests added?

**Comment by debris** [comment]
sure

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!
