### PR TITLE
fix(source): Don't warn about unreferenced duplicate packages

### LINKED ISSUE #10752: warning: skipping duplicate package `case` found at `~\.cargo\git\checkouts\cargo-..`
### Problem

When using `cargo install --git`  to install a package like cargo itself, a lot of warnings are emitted about duplicated packages. It seems that these packages are only used for the tests, and not sure if the warnings affect the final build.

```
warning: skipping duplicate package `cargo-list-test-fixture` found at `~\.cargo\git\checkouts\cargo-..`
...
```

It seems that this is caused by this commit:
https://github.com/rust-lang/cargo/commit/e903f7dfc0e50fe3e11dcbc5456094c902fce6ce

image

### Steps

Try to build cargo with itself:
```
cargo install --git https://github.com/rust-lang/cargo
```

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
cargo 1.63.0-nightly (38472bc19 2022-05-31)
```

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

This also improves the message, consolidating multiple duplicates and saying which was loaded instead, as it naturally fell out of the design

Fixes #10752

### Additional information

We're still subject to #13724 and fully load every manifest, even if we don't use it.  I'm exploring that topic at https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Redundant.20code.20in.20.60GitSouce.60.3F/near/450783427

This change builds on
- #13993
- #14169
- #14231
- #14234

### CODE REVIEW

File: src/cargo/sources/path.rs [hunk 1]
```diff
@@ -226,7 +226,8 @@ pub struct RecursivePathSource<'gctx> {
     /// Whether this source has loaded all package information it may contain.
     loaded: bool,
     /// Packages that this sources has discovered.
-    packages: HashMap<PackageId, Package>,
+    packages: HashMap<PackageId, Vec<Package>>,
```
Comment (weihanglo) [inline src/cargo/sources/path.rs:229]: Could we document what the key-value pair for? I can see it a bit unintuitive because `RecurisivePathSource` ignores all but the first.

**Review by weihanglo — APPROVED** [review]
Thanks for the fix.

Review comments added are all minor. `r=weihanglo` when you feel ready.
