### PR TITLE
fix(vendor): trust crate version only when coming from registries

### LINKED ISSUE #8181: cargo vendor doesn't re-vendor if the version number hasn't changed
**Problem**

`cargo vendor` fails to re-vendor a package if:
- the package vendor dir has a version number (eg because it's not the most recent, or `--versioned-dirs` is in use)
- the code has changed

This can happen if the code is coming from a git repo and the `rev` has been updated, if a patch has been added in the `[patch]` section of the Cargo.toml, or when switching between crates.io and git as a source.

This doesn't happen for non-versioned directories because `cargo vendor` unconditionally re-vendors their contents.

**Possible Solution(s)**
Rather than just comparing the version, it should also check for changes to the patch and/or origin specification.

**Notes**

Output of `cargo version`: 1.42, but this hasn't changed in recent versions

### PR DESCRIPTION
**Pull request by stormshield-guillaumed**
### What does this PR try to resolve?

Fixes #8181
Relates to #11897 and #14525

### How should we test and review this PR?

As mentioned in the contribution guide, I made a first commit adding a test that passes with the actual behaviour. Then, I made a second commit with a fix and modified the test with the new expected  behaviour.

### Additional information

The fix doesn't take into account switching from a git dependency to crates.io, which is not handled correctly on master either, and would probably require the vendoring to serialize the source ID to detect source changes.

I specifically limited the trust of immutable version to crates.io, but it could be extended to other registries.

### CODE REVIEW

File: src/cargo/ops/vendor.rs [hunk 1]
```diff
@@ -207,8 +207,10 @@ fn sync(
         let dst = canonical_destination.join(&dst_name);
         to_remove.remove(&dst);
         let cksum = dst.join(".cargo-checksum.json");
-        if dir_has_version_suffix && cksum.exists() {
-            // Always re-copy directory without version suffix in case the version changed
+        // The standard registry is the only immutable source,
+        // path and git dependencies' versions cannot be trusted to mean "no change"
+        if dir_has_version_suffix && id.source_id().is_crates_io() && cksum.exists() {
```
Comment (jsgf) [inline src/cargo/ops/vendor.rs:212]: Will this have the effect of *always* revendoring git-sourced packages even if they haven't changed?

Comment (weihanglo) [reply src/cargo/ops/vendor.rs:212]: Yes. Unfortunately in `.cargo-checksum.json` there is no checksum recorded for git dependencies.

File: src/cargo/ops/vendor.rs [hunk 2]
```diff
@@ -207,8 +207,10 @@ fn sync(
         let dst = canonical_destination.join(&dst_name);
         to_remove.remove(&dst);
         let cksum = dst.join(".cargo-checksum.json");
-        if dir_has_version_suffix && cksum.exists() {
-            // Always re-copy directory without version suffix in case the version changed
+        // The standard registry is the only immutable source,
+        // path and git dependencies' versions cannot be trusted to mean "no change"
```
[the remark this answers is not in the document]
Comment (stormshield-guillaumed) [reply src/cargo/ops/vendor.rs:211]: Could we keep this comment for when they will be or would you prefer I remove the mention to path dependencies ?
I wasn't sure whether to include all registries or not, but you are right, if a registry is not immutable, it will probably cause other problems before that. I'll change this.

File: src/cargo/ops/vendor.rs (hunk 1 above)
Comment (stormshield-guillaumed) [reply src/cargo/ops/vendor.rs:212]: I think there is no way currently to retrieve the git rev of the vendored dependency.

File: src/cargo/ops/vendor.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (weihanglo) [reply src/cargo/ops/vendor.rs:211]: We can leave the comment there. It just a note that Cargo doesn't vendor local path deps.

>  I wasn't sure whether to include all registries or not, but you are right, if a registry is not immutable, it will probably cause other problems before that. I'll change this.

Rebuild detection also holds that assumption, so yeah thanks for the update.

**Review by weihanglo — APPROVED** [review]
While this may affect performance loss as it becomes always-re-vendor for git dependencies, the bug itself is more severe because it vendors the wrong stuff.

To get further for vendor correctness, `cargo vendor` could always compare file checksums, though it implies more non-trivial refactors than this bugfix. I think we can proceed with this simple patch first.

**Comment by ehuss** [comment]
CI issue is tracked in https://github.com/rust-lang/rust/issues/130291, will be blocked until that is fixed.
