### PR TITLE
Be resilient to most IO error and filesystem loop while walking dirs

### LINKED ISSUE #10213: "File system loop found" upon `cargo build`
### Problem

When running `cargo build`, an error is thrown:

```
Caused by:
  failed to determine the most recently modified file in /path/to/package

Caused by:
  failed to determine list of files in /path/to/package

Caused by:
  File system loop found: /path/to/package/node/tools/node_modules/eslint/node_modules/eslint points to an ancestor /path/to/package/node/tools/node_modules/eslint
```

### Steps

1. Clone [`nodejs/node`](https://github.com/nodejs/node) to a package directory
2. Run `cargo build`

### Possible Solution(s)

_No response_

### Notes

This does not occur on Cargo v1.56.0 (I'm experiencing this on 3787309df66b32995f91bbf4d251e17e90fca4af).

### Version

```text
cargo 1.59.0
release: 1.59.0
host: aarch64-apple-darwin
libgit2: 1.3.0 (sys:0.13.25 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:SecureTransport)
os: Mac OS 12.1.0 [64-bit]
```

### PR DESCRIPTION
**Pull request by weihanglo**
Let `PathSource::walk` be resilient to most IO errors and filesystem loop.

This PR also

- Add a test validating the resilience against filesystem loop to prevent regression.
- Emit warning when filesystem loop found while walking the filesystem. This is the only way I can think of now to solve #9528

Fixes #10213.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Is there a way we could detect and filter these cases from `walkdir`, such as ignoring broken symlinks entirely?

**Comment by weihanglo** [comment]
Indeed we can recover from broken symlink and some IO errors. For filesystem loop, I guess we can simply emit a warning inside `fn walk` and skip the entry? At least user stuck in root can be informed that a lot filesystem loops happened. 

The code snippet need to change as below:

```rust
        for entry in walkdir {
            match entry {
                Ok(entry) => {
                    if !entry.file_type().is_dir() {
                        ret.push(entry.into_path());
                    }
                },
                Err(e) => {
                    if e.loop_ancestor().is_some() {
                        // emit some warning!!!!!
                        continue
                    }
                    if let Some(path) = e.path() {
                        ret.push(path.to_path_buf());
                    }
                }
            }
        }
```

**Comment by alexcrichton** [comment]
If a loop is as common as `node_modules` installations we probably don't want to warn about it but otherwise handling it somewhat gracefully seems reasonable.

**Comment by weihanglo** [comment]
From my own experience, a normal Node.js project should not have any nested `node_modules` in its dependencies, so the warning might be rare. I'm ok to remove the warning though if so, #9528 needs a reopen.

File: src/cargo/sources/path.rs [hunk 1]
```diff
@@ -420,9 +421,23 @@ impl<'cfg> PathSource<'cfg> {
...
+                    }
+                }
+                Err(err) if err.loop_ancestor().is_some() => {
+                    self.config.shell().warn(err)?;
+                }
+                Err(err) => match (err.path(), err.io_error()) {
+                    (_, Some(err)) if err.kind() == PermissionDenied => {
+                        return Err(Error::new(PermissionDenied, err.to_string()).into());
+                    }
+                    (Some(path), _) => ret.push(path.to_path_buf()),
```
Comment (alexcrichton) [inline src/cargo/sources/path.rs:438]: I'm curious, what's going on here? This looks like it's ignoring all errors that are not permission denied?

**Comment by alexcrichton** [comment]
Ah ok if we don't expect this to be common then a warning seems fine and we can adjust later if necessary.

File: src/cargo/sources/path.rs (hunk 1 above)
Comment (weihanglo) [reply src/cargo/sources/path.rs]: If cargo doesn't handle permission error intentionally, this [`EACCES` test case](https://github.com/rust-lang/cargo/blob/0.58.0/tests/testsuite/build_script.rs#L4623-L4654) might pass silently. The old behavior before adopting walkdir returns errors from  `fs::read_dir` calls directly, as well as it just unwraps `DirEntry` without handling `Result`.
https://github.com/rust-lang/cargo/blob/a359ce16073401f28b84840da85b268aa3d37c88/src/cargo/sources/path.rs#L413-L416

With walkdir, cargo cannot tell whether the error is permission error or a broken link. Generally, walkdir emits three kinds of errors:

1. **Symlink loop errors**: Cargo already takes care of it and shows a warning in this PR.
2. **IO errors with a path**: I guess cargo can recover from the path, and later let the caller decide to ignore it or if the caller does access the path and hits the error.
3. **IO errros without a path**: Cargo can simply propagate it to callers. This is rare because walkdir only emits this kind for either opening the file to check symlink loop or  handling the `Result<DirEntry>` generated from `read_dir()`.

I've updated this PR to reflect aforementioned change. There is an enhancement can do such as emitting warnings for those recoverable errors, but I doubt its usefulness.

**Comment by alexcrichton** [comment]
@bors: r+

Ok sounds good to me!

**Comment by weihanglo** [comment]
Should this fix be included in next beta? I feel like it should or we need to backport it after 1.59-beta released.

**Comment by alexcrichton** [comment]
Yeah that seems reasonable to me, would you be up for preparing the PR?
