### PR TITLE
fix: Ensure dep/feature activates the dependency on 2024 

### LINKED ISSUE #14016: Bad error message when a strong dep features's depedency is an unused optional dependency
### Problem

If nothing can activate an optional dependency, cargo acts as if the dependency doesn't exist which creates poor error messages.

Also, with how things are arranged, the unused optional dependency lint doesn't get reported which could at least reduce the burden on the error message.

### Steps

Baseline `Cargo.toml`:
```toml
cargo-features = ["edition2024"]
[package]
name = "cargo-14010"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.203", optional = true }
```
```console
$ cargo +nightly check -Zcargo-lints
warning: unused optional dependency
 --> Cargo.toml:8:1
  |
8 | serde = { version = "1.0.203", optional = true }
  | -----
  |
  = note: `cargo::unused_optional_dependency` is set to `warn` by default
  = help: remove the dependency or activate it in a feature with `dep:serde`
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s
```

Add the following to `Cargo.toml`:
```toml

[features]
serde = ["serde/derive"]
```
```console
$ cargo +nightly check -Zcargo-lints
error: failed to parse manifest at `/home/epage/src/personal/dump/cargo-14010-1/Cargo.toml`

Caused by:
  feature `serde` includes `serde/derive`, but `serde` is not a dependency
```

### Possible Solution(s)

- Improve the error message
- Implicitly create `dep:serde` if `serde/derive` is used
- Deprecate `serde/derive` syntax, removing it in a new edition (#10556)

### Notes

This was split out of #14015 assuming we'll go with a different solution than it

### Version

_No response_

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

Fixes #14016

### How should we test and review this PR?

This doesn't revert the last commit of #14018 so that it works properly
on Editions 2021 and 2024.

### CODE REVIEW

**Comment by epage** [comment]
For CI failure, see #14223

File: src/cargo/util/toml/mod.rs [hunk 1]
```diff
@@ -691,11 +691,34 @@ fn default_readme_from_package_root(package_root: &Path) -> Option<String> {
...
 fn resolve_features(
     original_features: Option<&BTreeMap<manifest::FeatureName, Vec<String>>>,
+    edition: Edition,
 ) -> CargoResult<Option<BTreeMap<manifest::FeatureName, Vec<String>>>> {
-    let Some(resolved_features) = original_features.cloned() else {
+    let Some(mut resolved_features) = original_features.cloned() else {
         return Ok(None);
     };
 
+    if Edition::Edition2024 <= edition {
```
Comment (weihanglo) [inline src/cargo/util/toml/mod.rs:700]: I understand you like Yoda style more, but forgot the reason.

Anyway, this is not a blocker.

File: src/cargo/util/toml/mod.rs [hunk 2]
```diff
@@ -686,6 +688,40 @@ fn default_readme_from_package_root(package_root: &Path) -> Option<String> {
...
+) -> CargoResult<Option<BTreeMap<manifest::FeatureName, Vec<String>>>> {
+    let Some(mut resolved_features) = original_features.cloned() else {
+        return Ok(None);
+    };
+
+    if Edition::Edition2024 <= edition {
+        for activations in resolved_features.values_mut() {
+            let mut deps = Vec::new();
+            for feature_value in activations.iter() {
+                let feature_value = FeatureValue::new(InternedString::new(feature_value));
```
Comment (weihanglo) [inline src/cargo/util/toml/mod.rs:704]: So, this PR chose the approach:

> Implicitly create `dep:serde` if `serde/derive` is used

I forgot if we had a conclusion somewhere.

File: src/cargo/util/toml/mod.rs (hunk 1 above)
Comment (epage) [reply src/cargo/util/toml/mod.rs:700]: I actually really dislike Yoda style for equality checks.  For these checks, I prefer number line order (the lower value is always on the left, so `<` and `<=` are only ever used and not `>` or `>=`)

File: src/cargo/util/toml/mod.rs (hunk 2 above)
Comment (epage) [reply src/cargo/util/toml/mod.rs:704]: See https://github.com/rust-lang/cargo/issues/14016#issuecomment-2161083450

> We discussed this in today's team meeting and lean towards `"dep_name/feature_name"` implying `"dep:dep_name"` in Edition 2024 with it being normalized in the published `Cargo.toml` file.

Comment (weihanglo) [reply src/cargo/util/toml/mod.rs:704]: Why did we choose to do it here instead of in `Summary`?

https://github.com/rust-lang/cargo/blob/471287ffed354a468114caa5c72db97da6b6ddfb/src/cargo/util/toml/mod.rs#L1442-L1459

Comment (weihanglo) [reply src/cargo/util/toml/mod.rs:704]: We want everything to be normalized on `resolved_toml`, right?

Comment (epage) [reply src/cargo/util/toml/mod.rs:704]: By doing it here, we get `cargo publish` normalization "for free" and all data-structures are consistent for less chance of bugs (which also makes it easier to introspect for debugging)

**Comment by weihanglo** [comment]
@bors r+

Thanks!

File: src/cargo/util/toml/mod.rs (hunk 2 above)
Comment (TimDiekmann) [reply src/cargo/util/toml/mod.rs:704]: > Implicitly create `dep:serde` if `serde/derive` is used

Doesn't this fail if `serde` is not an optional dependency?
