### PR TITLE
fix: Avoid panic for package specs with an empty fragment

### LINKED ISSUE #16731: `PackageIdSpec::parse` panics on URL package specs with an empty fragment (`...#`)
### Problem

`PackageIdSpec::parse` can panic when given a URL-form package ID specification whose fragment is present but empty, such as `https://example.com/foo#`.

The panic happens in `crates/cargo-util-schemas/src/core/package_id_spec.rs` inside `PackageIdSpec::from_url`, where the code does `fragment.chars().next().unwrap()` without handling the case where `fragment == ""`.

https://github.com/rust-lang/cargo/blob/0263ed6873f209c48914c2de21655295a72a03e1/crates/cargo-util-schemas/src/core/package_id_spec.rs#L159-L169

### Steps

Minimal library-level reproduction:

```rust
use cargo_util_schemas::core::PackageIdSpec;

fn main() {
    // Panics today instead of returning Result::Err(...)
    let _ = PackageIdSpec::parse("https://example.com/foo#");
}
```

Equivalent test:

```rust
#[test]
fn empty_fragment_should_not_panic() {
    let _ = cargo_util_schemas::core::PackageIdSpec::parse("https://example.com/foo#");
}
```

Cargo should not panic on malformed package ID specifications.

For an empty fragment, one of these would be reasonable:

- return a normal `Err(...)` explaining that an empty fragment is invalid, or
- treat an empty fragment the same as no fragment at all.

Returning an error seems preferable, because the package ID spec grammar documents the fragment as `#(pkgname | semver)`, so `#` by itself is not a valid spec.

### Possible Solution(s)

Handle the empty-fragment case before calling `chars().next().unwrap()`.

### Notes

_No response_

### Version

```text

```

### PR DESCRIPTION
**Pull request by Pyr0de**
### What does this PR try to resolve?

Fixes #16731

`PackageIdSpec::parse` panics on URL package specs with an empty fragment (...#)
This change would return `PackageIdSpecError(ErrorKind::EmptyFragment)` instead of panicing

### How to test and review this PR?

Earlier the following code would panic
``` rust
let _ = PackageIdSpec::parse("https://example.com/foo#");
```
but now it should return an error

### CODE REVIEW

File: crates/cargo-util-schemas/src/core/package_id_spec.rs [hunk 1]
```diff
@@ -322,6 +326,9 @@ enum ErrorKind {
     #[error("package ID specification `{spec}` looks like a file path, maybe try {maybe_url}")]
     MaybeFilePath { spec: String, maybe_url: String },
 
+    #[error("pkgid url cannot have an empty fragment")]
+    EmptyFragment,
```
Comment (0xPoe) [inline crates/cargo-util-schemas/src/core/package_id_spec.rs:330]: This is a non-public error kind, so I believe this is acceptable.
cc: @weihanglo Not sure if you have any thoughts on it.

File: crates/cargo-util-schemas/src/core/package_id_spec.rs [hunk 2]
```diff
@@ -764,5 +771,7 @@ mod tests {
         err!("@1.2.3", ErrorKind::NameValidation(_));
         err!("registry+https://github.com", ErrorKind::NameValidation(_));
         err!("https://crates.io/1foo#1.2.3", ErrorKind::NameValidation(_));
+
+        err!("https://example.com/foo#", ErrorKind::EmptyFragment);
```
Comment (0xPoe) [inline crates/cargo-util-schemas/src/core/package_id_spec.rs:774]:
```suggestion
		err!("https://crates.io/1foo#1.2.3", ErrorKind::NameValidation(_));
        err!("https://example.com/foo#", ErrorKind::EmptyFragment);
```

File: crates/cargo-util-schemas/src/core/package_id_spec.rs (hunk 1 above)
Comment (weihanglo) [reply crates/cargo-util-schemas/src/core/package_id_spec.rs:330]: Yeah should be good
