### PR TITLE
Resolve: Be less strict while offline.

### LINKED ISSUE #6014: -Z offline actively breaks building crate offline
````cargo 1.30.0-nightly (b917e3524 2018-09-09)````
I `cargo new`ed a dummy project with cargo as git rependency
````
[dependencies]
cargo = { git = "https://github.com/rust-lang/cargo", rev = "9311f6d439e09da3ab918397a425be57da13f04a" }
````
and built it with a cargo cache starting from scratch:
````
CARGO_HOME=/tmp/cargohome cargo build
````
and waited for everything to be downloaded.
I can see that the cargo git repo is cloned and the respective git commit checked out:
````
$ cd /tmp/cargohome/git
$ fd --max-depth 2

checkouts
checkouts/cargo-e7ff1db891893a9e
db
db/cargo-e7ff1db891893a9e
````

Next I tried to rebuild the dummy package from scratch without net connections.
Surprisingly that worked without `-Z offline` but with `-Z offline`  made it fail:
````
error: no matching package named `core-foundation` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `cargo v0.30.0 (https://github.com/rust-lang/cargo?rev=9311f6d439e09da3ab918397a425be57da13f04a#9311f6d4)`
    ... which is depended on by `a v0.1.0 (file:///tmp/a)`
As a reminder, you're using offline mode (-Z offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may with to retry without the offline flag.
````
Everything needed was already stored in the cache though.

### PR DESCRIPTION
**Pull request by ehuss**
When offline, the resolver was requiring everything to be downloaded, even dependencies that are not used. This changes it so that the resolver can still resolve unavailable dependencies when offline. This pushes the failure to a later stage of Cargo where it attempts to download the dependency. This makes `-Z offline` work for target-cfg or optional dependencies that are not being used.

Fixes #6014.

This changes the error message significantly for the "unavailable" case (see test diff). I personally think the new error message is clearer, although it is shorter and provides less information. The old error message seemed large and scary, and was a little hard for me to grok. However, I'd be willing to look at tweaking the error behavior if not everyone agrees.

### CODE REVIEW

File: tests/testsuite/build.rs [hunk 1]
```diff
@@ -1140,6 +1140,77 @@ fn main(){
...
+            [target.'cfg(unused)'.dependencies]
+            unused_dep = "1.0"
+            "#,
+        )
+        .file("src/lib.rs", "")
+        .build();
+    // Do a build that downloads only what is necessary.
+    p.cargo("build")
+        .with_stderr_contains("[DOWNLOADED] used_dep [..]")
+        .with_stderr_does_not_contain("[DOWNLOADED] unused_dep [..]")
```
Comment (alexcrichton) [inline tests/testsuite/build.rs]: As a meta note, I personally find "assert does not contain" as a not-very-useful assertion in test suites because there's so many output that don't contain the string. For example if `unused_dep` here had a typo the test would pass but not because we thought it would.

That's where all the original tests from long ago do exhaustive checking of the output which allows for easily detecting bugs/changes. The downside of those tests though is that if you change the output it's really annoying to change the tests, and we have quite a few tests now!

(JFYI)

**Comment by alexcrichton** [comment]
@bors: r+

Always wanted to test and see if bors learned comments from pull request reviews, and now I know the answer is "no"

File: tests/testsuite/build.rs (hunk 1 above)
Comment (ehuss) [reply tests/testsuite/build.rs]: I agree. There is a note in the doc that it is dangerous. Whenever I use it, I try to write the test first so it fails, and then it should only pass when fixed.  However, that doesn't really protect from the future when things change.  I'll leave some notes in #6816.
