### PR TITLE
Path deps outside workspace are not members

### LINKED ISSUE #3192: Workspaces: Add a way to disable transitive inclusion of path dependencies
Right now, a workspace root automatically includes all of its path dependencies as workspace members. It would be nice if we could disable this somehow.

This is a follow-up to [#3156](https://github.com/rust-lang/cargo/issues/3156#issuecomment-251475209).

**Use case**:

Assume that we have a local library crate that we don't want to publish (yet). We include it in multiple executable crates through `path = "../our_library"` dependencies:

```
├── our_library
│   ├── Cargo.toml
│   └── src
├── executable_1
│   ├── Cargo.toml
│   └── src
└── executable_2
    ├── Cargo.toml
    └── src
```

Now we want to make the executables workspace roots. This leads to the following errors:

> error: workspace member `/home/…/our_library/Cargo.toml` is not hierarchically below the workspace root `/home/…/executable_{1,2}/Cargo.toml`

So each executable requires that we make `our_library` a workspace member of its own workspace. But a crate can't be part of multiple workspaces.

Right now, there is no way to resolve this problem, since there is no way to disable the automatic inclusion of path dependencies.

### PR DESCRIPTION
**Pull request by matklad**
closes #3192

This implements @Boscop suggestion: path dependencies pointing outside the workspace are never members. 

Not sure that it handled #3192 fully: you can't exclude a path dependency within workspace. Not sure this is super useful though...

### CODE REVIEW

File: src/cargo/core/workspace.rs [hunk 1]
```diff
@@ -293,20 +293,27 @@ impl<'cfg> Workspace<'cfg> {
...
-        self.find_path_deps(&root_manifest)
+        self.find_path_deps(&root_manifest, false)
     }
 
-    fn find_path_deps(&mut self, manifest_path: &Path) -> CargoResult<()> {
+    fn find_path_deps(&mut self, manifest_path: &Path, is_path_dep: bool) -> CargoResult<()> {
         if self.members.iter().any(|p| p == manifest_path) {
             return Ok(())
         }
+        if is_path_dep
```
Comment (matklad) [inline src/cargo/core/workspace.rs]: This check is a bit more complicated that what one would expect. 

Firstly, we want to allow path dependencies outside the wrokspace dir if they have an explicit parent pointer.

Secondly, we want to add explicitelly specified members, even if they are outside and lack a parent pointer. This way we'd bail out with the error in `validate`, instead of simply ignoring a bad member.

**Comment by matklad** [comment]
ping @alexcrichton

**Comment by alexcrichton** [comment]
Thanks for the PR! (and the ping)

I've been noodling on this in the background a bit. I'm unsure if this'll play out nicely. The purpose for the rules around workspaces were basically to ensure that `Cargo.lock` never oscillated or changed spuriously. That is, if you `cargo build` on any crate in a workspace it should always generate the same `Cargo.lock`.

That being said I *think* that this still preserves that invariant. I'm slightly worried about path dependencies like:

    workspace root -> not in a workspace -> back in the workspace

I think with this PR as written such a construction is guaranteed to not work if you run build in the crate "not in a workspace". (right?)

I'm not sure if we should be worried about such cases, though, as they have to be constructed manually anyway. In any case though I don't think that this should fully close out #3192 because I could imagine hierarchical constructions of workspaces still want to explicitly say that some subdirectories aren't workspace members.

**Comment by matklad** [comment]
>In any case though I don't think that this should fully close out #3192 because I could imagine hierarchical constructions of workspaces still want to explicitly say that some subdirectories aren't workspace members.

Yes, this does not add an "explicit exclusion" feature, this just excludes all paths outside of the workspace directory from automatic inclusion. But perhaps we don't need an extra knob to control this? If you don't want a path dep to be a part of workspace, put it alongside, and not inside, the workspace directory, just like in the example from #3192. @phil-opp, will this be convenient enough to you? 

And, by the way, I think there is already a crude explicit exclusion mechanism in the RFC: you can explicitelly specify members, and then Cargo should not include path dependencies automatically.

>I think with this PR as written such a construction is guaranteed to not work if you run build in the crate "not in a workspace". (right?)

Hm, I think this will and should write exactly one lockfile inside `not in a workspace`. Consider a simplified (but equivalent) example

```
not a workspace package -- path dependency --> package in some workspace
```

Executing cargo build inside the first package should completely ignore the lockfiles of the workspace, because lockfiles of dependencies are ignored. 


Random musings: 

Hm, the fact that combinations of `workspace.members` and `workspace.root` allows you to have a package which is a part of the workspace, but is not hierarchically under workspace root worries me a bit. Are there some real world use cases for this, or it is just an artifact of the RFC? Could we have started more conservatively, without the `root` key and with strict directory hierarchy requirements?

**Comment by phil-opp** [comment]
> Yes, this does not add an "explicit exclusion" feature, this just excludes all paths outside of the workspace directory from automatic inclusion. But perhaps we don't need an extra knob to control this? If you don't want a path dep to be a part of workspace, put it alongside, and not inside, the workspace directory, just like in the example from #3192. @phil-opp, will this be convenient enough to you?

I really like this solution. It's a much better and less surprising default.

> And, by the way, I think there is already a crude explicit exclusion mechanism in the RFC: you can explicitelly specify members, and then Cargo should not include path dependencies automatically.

The problem is that the implementation differs from the RFC. The current implementation [implicitly adds all path dependencies to the workspace members](https://github.com/rust-lang/cargo/issues/3156#issuecomment-251504252), so that all path dependencies are included, even with `members = []`.

**Comment by matklad** [comment]
Hm, I think there's another corner case which I am not entirely sure how to deal with.

Consider this directory/package layout:

```
.
├── root
│   
└── member
    │
    └── path_dep
```

Here, `root` is the root of the workspace, and it explicitelly includes `member`. Now, `member` has a path dependency which is hierarchically bellow it. Should this `path_dep` be a member of the workspace? 

I would say yes, but currently the PR does not implement this.

**Comment by matklad** [comment]
Huh, found two more bugs in the **current** (without this PR applied) Cargo while thing about this.

First, in the layout above `path_dep` believes it does not belong to any workspace, because there's no package with `workpsace` above it.

The second is https://github.com/rust-lang/cargo/pull/3489.

**Comment by alexcrichton** [comment]
@matklad yes the current implementation diverges from the RFC, but explicitly so. I found it far more ergonomic and convenient if all path dependencies were included by default, as it ended up being the 90% case of what you wanted anyway. As a result the RFC isn't quite the source of truth here as the current implementation just pulls in all path deps transitively to the workspace.

I think the example I gave actually works fine because the intermediate crate isn't in a workspace, so we won't try to do any workspace inference or anything. Can you add a test to this effect though with some more... "flavorful" workspace constructions?

> Hm, the fact that combinations of workspace.members and workspace.root allows you to have a package which is a part of the workspace, but is not hierarchically under workspace root worries me a bit. Are there some real world use cases for this, or it is just an artifact of the RFC? 

Yes this was intentional. Workspaces like the compiler and Servo don't have a hierarchical workspace root, but it's off on the side.

> Here, root is the root of the workspace, and it explicitelly includes member. Now, member has a path dependency which is hierarchically bellow it, but not below root. Should this path_dep be a member of the workspace?

Functionally, yes, I think it would make sense. As implemented, no, it would not work as you'd have to manually configure the workspace.

The intention with logic around workspace inference and such was to support all constructions via explicit configuration and almost all constructions with little configuration through inference. Right now we don't support all workspace constructions though as there's no way to exclude members from workspaces or turn off path inclusion logic.

**Comment by alexcrichton** [comment]
@matklad thoughts about my most recent comment?

**Comment by matklad** [comment]
Sounds reasonable! I'll rebase this PR and add more tests during the weekend. 

So the end resolve would look like this:

There is workspace root. There is a list of explicit members. They define a set of workspace directories. 
Any path dependencies in the graph which are under any of the ws dirs are workspace members (this means that when reading Cargo.toml traversing the directory upwards we should look for explicit members with `workspace_root = `, and not only for `[workspace]`, this would be handled in another PR).

**Comment by alexcrichton** [comment]
@matklad that sounds about right to me, yeah.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by matklad** [comment]
Wait a minute, @alexcrichton , shouldn't the `test_path_dependency_under_member` fail in validate worksapce at the moment?

See, when writing a test, I did not specify `[workspace]` [here](https://github.com/matklad/cargo/blob/7429347eb377666ae8a9f0583bb1d683b21c8d76/tests/workspaces.rs#L1198), so [this](https://github.com/matklad/cargo/blob/7429347eb377666ae8a9f0583bb1d683b21c8d76/tests/workspaces.rs#L1203) points to the workspace that is isn't a workspace. Should we validate this?

**Comment by alexcrichton** [comment]
@matklad hm yes that is indeed worrisome! Is that an existing bug or an accidental bug here?

**Comment by matklad** [comment]
>Is that an existing bug or an accidental bug here?

It's an existing bug. When we start compilation in the non-workspace package, we don't check workspace configuration of the path dependencies at all. 

I am not 100% sure that that's a bug though. Basically, we work the same way as the pre-workspace Cargo. Though validating this would be helpful.

Are there any plans of making workspaces the default? Like, adding an empty `[workspace]` when doing `cargo new`?

**Comment by alexcrichton** [comment]
I think we need more support before making workspaces the default as `cargo new` should basically "work no matter what". The main thing missing there is Cargo.toml editing support

Also the test here is an invalid workspace, but it's working? That is, the pointer is wrong? I could have sworn that we verified that...

**Comment by matklad** [comment]
>I could have sworn that we verified that...

The root package is **not** a workspace (It was intended to be, but I've forgot to put `[workspace]` there), I believe this just doesn't trigger any workspace verification, despite the fact that we have a path dependency which thinks we are inside a workspace.

**Comment by alexcrichton** [comment]
Oh so a build in `ws`, with no `[workspace]`, works. But a build in `foo`, with a pointer to an invalid root, fails?

If that's the case then that's actually expected behavior, and yeah is largely backcompat business.

**Comment by matklad** [comment]
>Oh so a build in ws, with no [workspace], works. But a build in foo, with a pointer to an invalid root, fails?

Yeah, exactly!

>If that's the case then that's actually expected behavior, and yeah is largely backcompat business.

I think we can safely make this an error, no? There seems to be no backcompat hazards here. Not sure if we **should** make this an error. On the one hand, users can misconfigure the workspace and think that everything is OK (as demonstrated by me:) ). On the other hand, this is a rather obscure failure mode, and seems to require a bit of work to warn about.

**Comment by alexcrichton** [comment]
Yeah I agree that this seems reasonable to generate an error for in terms of it's not backwards incompatible. It seems reasonable as well to just go ahead and generate the error anyway so long as it doesn't impose too much work.

In any case the test failures here are spurious and otherwise I think we still want this PR, so...

@bors: retry

**Comment by matklad** [comment]
Should this be tagged with relnotes?
