### PR TITLE
Fix `links` vars showing up for testing packages

### LINKED ISSUE #9063: DEP_* env variable not set in nightly test run
This happens with the nightly version, but not with the stable.

```
> cargo +nightly version
cargo 1.51.0-nightly (329895f5b 2021-01-06)
```
### Reproduce
Cargo.toml
``` toml
[package]
name = "asdf"
version = "0.1.0"
authors = ["xyxy"]
edition = "2018"

[dependencies]
libsodium-sys = "0.2"

[build-dependencies]
cc = "1.0"
```

test.c
``` c
void test() {}
```

build.rs
``` rust
fn main() {
    cc::Build::new()
        .file("test.c")
        .include(std::env::var_os("DEP_SODIUM_INCLUDE").expect("DEP_SODIUM_INCLUDE is not set"))
        .compile("test.a");
}
```

Now just run `cargo +nighly test`. With stable this works perfectly, with nightly the `DEP_SODIUM_INCLUDE` env variable is not set.

### PR DESCRIPTION
**Pull request by alexcrichton**
If a package is tested and the library for the package wasn't built
(e.g. only tested or it wasn't present) then the `links` env vars from
dependencies weren't showing up to the build script by accident. This
was an accidental regression from #8969.

The intention of #8969 was to exclude connections to build scripts
connected via dev-dependencies, but it only applied a heuristic because
the unit graph doesn't retain information about dev-dependencies. The
fix here is to instead actually retain information about
dev-dependencies which is only used for constructing the unit graph and
connecting build script executions to one another.

Closes #9063

### CODE REVIEW

File: tests/testsuite/build_script.rs [hunk 1]
```diff
@@ -4158,3 +4158,49 @@ fn rerun_if_directory() {
     dirty();
     fresh();
 }
+
+#[cargo_test]
+fn test_with_dep_metadata() {
+    // rerun-if-changed of a directory should rerun if any file in the directory changes.
```
Comment (ehuss) [inline tests/testsuite/build_script.rs:4164]: Copy/paste error?

Comment (alexcrichton) [reply tests/testsuite/build_script.rs]: Oops, indeed!

**Comment by ehuss** [comment]
Ugh, I see what you were saying about this on Zulip.  I've been trying various different approaches such as fundamentally revisiting #5711, but every solution I can think of is as complex as this or worse.  This is a precarious path to go down, where it will be near impossible to understand this file in the future.  That being said, we can't remove or redesign these features from Cargo, and I don't see many other options.  At least things are pretty well commented. 😄 

@bors r+

@alexcrichton Do you want to backport this to beta?

**Comment by alexcrichton** [comment]
Indeed yeah the code at this point definitely doesn't speak for itself and we're really only left to rely on comments and tests at this point... I wish I knew a better way out of this quagmire!

Sure yeah though, I'll do the backport
