### PR TITLE
Use listed dependency name for feature names

### LINKED ISSUE #5753: Renamed optional dependency should use the renamed name
Given a Cargo.toml dependency stated like this:

```toml
[dependencies.dalek]
package = "ed25519-dalek"
version = "0.7.0"
optional = true
```

I expected to be able to turn the dependency on with `cargo build --features dalek`. However, this does not work. `cargo build --features ed25519-dalek` does work.

I think we should be consistent here in treating the dependency name, not the package name, as the name of this optional dependency.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates the implementation of renamed dependencies to use the listed
name of a dependency in Cargo.toml for the name of the associated feature,
rather than using the package name. This'll allow disambiguating between
different packages of the same name and was the intention all along!

Closes #5753

### CODE REVIEW

File: src/cargo/core/dependency.rs [hunk 1]
```diff
@@ -209,7 +209,11 @@ impl Dependency {
         &self.inner.req
     }
 
-    pub fn name(&self) -> InternedString {
+    pub fn name_in_toml(&self) -> InternedString {
```
Comment (ehuss) [inline src/cargo/core/dependency.rs]: Would you mind adding a short docstring to `name_in_toml`, `package_name`, and `rename`?  Perhaps with a little hint on when to use which?  I suspect future me is going to forget and be confused.

Comment (alexcrichton) [reply src/cargo/core/dependency.rs]: Sure thing!

File: src/cargo/core/dependency.rs [hunk 2]
```diff
@@ -209,7 +209,49 @@ impl Dependency {
...
+        self.rename().unwrap_or(self.inner.name)
+    }
+
+    /// The name of the package that this `Dependency` depends on.
+    ///
+    /// Usually this is what's written on the left hand side of a dependencies
+    /// section, but it can also be renamed via the `package` key.
+    ///
+    /// Both of the dependencies below return `foo` for `name_in_toml`:
```
Comment (dwijnand) [inline src/cargo/core/dependency.rs]: "for `package`", surely?

File: src/cargo/core/dependency.rs [hunk 3]
```diff
@@ -240,8 +282,12 @@ impl Dependency {
         self.inner.platform.as_ref()
     }
 
-    pub fn rename(&self) -> Option<&str> {
-        self.inner.rename.as_ref().map(|s| &**s)
+    /// The renamed name of this dependency, if any.
+    ///
+    /// If the `package` key is used in `Cargo.toml` then this returns the same
+    /// value as `name_in_toml`.
```
Comment (dwijnand) [inline src/cargo/core/dependency.rs]: I don't want to stall this PR, but after several attempts I still can't wrap my head around this explanation.

Comment (alexcrichton) [reply src/cargo/core/dependency.rs]: Ah sorry about that! I'll try to get around to cleaning this up soon.
