### PR TITLE
Never include use extra-filename in build scripts

### LINKED ISSUE #16854: Build scripts fail to run with new build dir layout when __CARGO_DEFAULT_LIB_METADATA is set
### Problem

Build scripts fail to run with new build dir layout when `__CARGO_DEFAULT_LIB_METADATA` is set

This is a recent regression, probably introduced by https://github.com/rust-lang/cargo/pull/16812.

### Steps

1. Set up a project with a `libc` dependency (or anything else that needs a build script)
2. Run `CARGO_UNSTABLE_BUILD_DIR_NEW_LAYOUT=true __CARGO_DEFAULT_LIB_METADATA=foo cargo build`

Expected behavior: A successful build.

Actual behavior:
```
error: failed to run custom build command for `getrandom v0.4.2`

Caused by:
  could not execute process `/home/r/src/rust/lib-crates/rustc-build-sysroot/target/debug/build/getrandom/0b53632d37620753/out/build_script_build` (never executed)

Caused by:
  No such file or directory (os error 2)
```

I'm aware that `__CARGO_DEFAULT_LIB_METADATA` is internal and unstable, but it is used for the sysroot build, so this causes cargo-based sysroot builds to break. Rustc bootstrap doesn't use the new build dir layout yet so it is not affected at this time, but Miri (which uses https://github.com/RalfJung/rustc-build-sysroot/) is affected when `CARGO_UNSTABLE_BUILD_DIR_NEW_LAYOUT` is set.

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text

```

### PR DESCRIPTION
**Pull request by ranger-ross**
### What does this PR try to resolve?

See: #16854

This is that in #16812 we stopped adding the metadata hash to build script names and just call them `build_script_build[EXE]` since they are already contained within a directory with the hash.

However, I didn't take into consideration `__CARGO_DEFAULT_LIB_METADATA`, so if it is passed with a build script in the build graph it will get the wrong path (`build_script_build-[HASH][EXE]`) when it tries to execute and fail.

Looking at [the comments](https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/build_runner/compilation_files.rs#L922) about `__CARGO_DEFAULT_LIB_METADATA` I get the impression there is no usecase for using it with a build script.
So I modified the logic to never include the meta in the build script file names even when `__CARGO_DEFAULT_LIB_METADATA`.
Let me know if this is a bad assumption.

closes #16854

### How to test and review this PR?

See the included test.

Also double checked on https://github.com/RalfJung/rustc-build-sysroot/ and this change fixes the issue for me

cc: @RalfJung 

r? @epage

### CODE REVIEW

File: src/cargo/core/compiler/build_runner/compilation_files.rs [hunk 1]
```diff
@@ -914,9 +914,14 @@ fn use_extra_filename(bcx: &BuildContext<'_, '_>, unit: &Unit) -> bool {
             // These always use metadata.
             return true;
         }
+
+        if unit.target.is_custom_build() {
+            // Build scripts never never use metadata
```
Comment (RalfJung) [inline src/cargo/core/compiler/build_runner/compilation_files.rs]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16855/35f8202bfe47f954a4613a846cfd406bda9d3b8c..2a4d0fdf1141dcfab10b3c58829e95125a9097ef)*

```suggestion
            // Build scripts never use metadata
```

File: tests/testsuite/build_dir.rs [hunk 2]
```diff
@@ -1219,6 +1219,61 @@ CARGO_BIN_FILE_BAR_bar=[ROOT]/foo/build-dir/debug/build/bar/[HASH]/artifact/bin/
 "#]]);
 }
 
+/// __CARGO_DEFAULT_LIB_METADATA is internal but used by rustc bootstrap and https://github.com/RalfJung/rustc-build-sysroot/
```
Comment (RalfJung) [inline tests/testsuite/build_dir.rs]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16855/35f8202bfe47f954a4613a846cfd406bda9d3b8c..2a4d0fdf1141dcfab10b3c58829e95125a9097ef)*

```suggestion
/// __CARGO_DEFAULT_LIB_METADATA is internal but used by rustc bootstrap and Miri.
```

**Comment by weihanglo** [comment]
besides suggestions from Ralf, looks good

File: src/cargo/core/compiler/build_runner/compilation_files.rs (hunk 1 above)
Comment (ranger-ross) [reply src/cargo/core/compiler/build_runner/compilation_files.rs]: thanks, `typos` can only save me from so much :laughing:

**Review by weihanglo — APPROVED** [review]
Thanks!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16855/35f8202bfe47f954a4613a846cfd406bda9d3b8c..3cc34d60dec90b50045502d7d71a3e297dc4652b)*
