### PR TITLE
fix(fingerprint): Don't throwaway the cache on RUSTFLAGS changes 

### LINKED ISSUE #8716: Reconsider RUSTFLAGS artifact caching.
When RUSTFLAGS is changed between invocations, this can trigger a complete rebuild. This can be annoying, and the only workaround is to use a separate target directory for each RUSTFLAGS setting. I think we should revisit how this works, and see if there is a way to address the problems.

**Motivation**:
* Changing RUSTFLAGS can be very expensive time-wise, and frustrating if your project relies on being able to swap between different settings.
* Supporting a shared build directory cache would be thwarted any time someone changes RUSTFLAGS.

**History**:
* #6503 added RUSTFLAGS to the metadata hash, allowing independent caching. 1.33 (2019-02-28)
* #6966 Removed `--remap-path-prefix` from the hash, because it broke reproducible builds. 1.37 (2019-08-15)
* #7417 Reverted #6503 because it broke profile guided optimization. 1.39 (2019-11-07)

**Solutions?**
I am uncertain what a good approach would be. Some rough ideas:

* Go back to hashing RUSTFLAGS, but only in the `-C extra-filename`, and *not* `-C metadata`. This should (probably) avoid the PGO problems, since the symbols won't change. However, this could still cause problems with reproducible builds if the rlib filename somehow leaks into the resulting binary (I don't have a reason to think it does, but it seems risky).
* Add a mechanism for specifying RUSTFLAGS so that the user can decide whether or not it gets hashed. (Maybe a separate env var, or some string in the current one, or a side setting?)  I feel like there is a problem that specifying RUSTFLAGS is already too complicated (considering the multiple overrides) and at the same time not flexible enough.
* Provide first-class support for some of the things that people use RUSTFLAGS for today.  For example, Cargo could have a "reproducible" mode where it tries to create a reproducible build, making whatever sacrifices are necessary. First class support for remap-path-prefix and PGO could also alleviate some of the problems.

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

Fixes #8716

This splits `-C metdata` and `-C extra-filename` and adds `RUSTFLAGS` to `-C extra-filename` in the hope that we can still make PGO and reproducible builds work while caching artifacts per RUSTFLAGS used.

### CODE REVIEW

File: src/cargo/core/compiler/build_runner/compilation_files.rs
Comment (epage) [inline src/cargo/core/compiler/build_runner/compilation_files.rs:1]:
```
---- rustflags::remap_path_prefix_ignored stdout ----
running `/home/epage/src/personal/cargo/target/debug/cargo build`
running `/home/epage/src/personal/cargo/target/debug/cargo clean`
running `/home/epage/src/personal/cargo/target/debug/cargo build`
thread 'rustflags::remap_path_prefix_ignored' panicked at tests/testsuite/rustflags.rs:1496:9:
assertion `left == right` failed
  left: ["/home/epage/src/personal/cargo/target/tmp/cit/t148/foo/target/debug/deps/libfoo-b85ff4ba90446466.rlib"]
 right: ["/home/epage/src/personal/cargo/target/tmp/cit/t148/foo/target/debug/deps/libfoo-e48aa920a5a0ef3c.rlib"]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

See https://github.com/rust-lang/cargo/issues/8716#issuecomment-2479980727

**Comment by epage** [comment]
```
2024-11-21T20:12:17.8415980Z ---- prop_passes_validation stdout ----
2024-11-21T20:12:17.8418295Z proptest: FileFailurePersistence::SourceParallel set, but failed to find lib.rs or main.rs
2024-11-21T20:12:17.8421106Z thread 'prop_passes_validation' panicked at src/cargo/core/resolver/types.rs:72:13:
2024-11-21T20:12:17.8422265Z got to 50_000 ticks in 8.884444187s
2024-11-21T20:12:17.8423242Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-11-21T20:12:17.8572504Z Part used befor drop: vec![pkg!(("A0NQ_d_0___e7-sys", "0.2.0")),pkg!(("A0NQ_d_0___e7-sys", "0.19.4")),pkg!(("A0NQ_d_0___e7-sys", "1.5.19")),pkg!(("A0NQ_d_0___e7-sys", "4.8.13")),pkg!(("A0NQ_d_0___e7-sys", "8.14.2")),pkg!(("A0NQ_d_0___e7-sys", "9.1.0")),pkg!(("A0NQ_d_0___e7-sys", "10.5.3")),pkg!(("A0NQ_d_0___e7-sys", "13.12.13")),pkg!(("A0NQ_d_0___e7-sys", "18.19.2")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "0.13.6")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "2.0.5") => [dep("A0NQ_d_0___e7-sys"),]),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "4.13.11")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "8.15.7")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "9.8.1")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "12.6.12")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "14.7.16")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "14.9.2")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "16.15.7")),pkg!(("DZ-NA_W8C7-B__s__", "0.0.6")),pkg!(("DZ-NA_W8C7-B__s__", "0.19.7")),pkg!(("DZ-NA_W8C7-B__s__", "4.12.16")),pkg!(("DZ-NA_W8C7-B__s__", "7.3.12") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=1.5.19"),]),pkg!(("DZ-NA_W8C7-B__s__", "9.7.8")),pkg!(("DZ-NA_W8C7-B__s__", "14.19.3")),pkg!(("DZ-NA_W8C7-B__s__", "17.1.14")),pkg!(("DZ-NA_W8C7-B__s__", "18.16.2") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=9.8.1, <=12.6.12"),]),pkg!(("DZ-NA_W8C7-B__s__", "19.19.4") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=1.5.19, <=4.8.13", DepKind::Build, false),dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=12.6.12"),]),pkg!(("JtWi-_---z-sys", "0.0.6")),pkg!(("JtWi-_---z-sys", "0.18.15") => [dep_req("DZ-NA_W8C7-B__s__", ">=4.12.16, <=9.7.8"),]),pkg!(("JtWi-_---z-sys", "2.15.14")),pkg!(("JtWi-_---z-sys", "2.19.13")),pkg!(("JtWi-_---z-sys", "6.8.16") => [dep_req("A0NQ_d_0___e7-sys", "<=9.1.0"),]),pkg!(("JtWi-_---z-sys", "8.8.13")),pkg!(("JtWi-_---z-sys", "11.14.19")),pkg!(("JtWi-_---z-sys", "12.0.18") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=0.19.4", DepKind::Build, false),dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=4.13.11, <=14.9.2"),]),pkg!(("JtWi-_---z-sys", "12.4.2") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=8.15.7, <=12.6.12"),]),pkg!(("JtWi-_---z-sys", "16.3.14") => [dep_req_kind("DZ-NA_W8C7-B__s__", "<=17.1.14", DepKind::Build, false),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "0.15.5") => [dep_req("DZ-NA_W8C7-B__s__", ">=4.12.16"),dep_req_kind("JtWi-_---z-sys", "=8.8.13", DepKind::Build, false),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "3.18.10") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", "<=2.0.5"),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "7.8.2") => [dep_req("DZ-NA_W8C7-B__s__", ">=9.7.8, <=17.1.14"),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "7.8.6")),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "8.0.8")),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "8.17.1")),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "11.7.18") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=14.7.16"),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "12.17.2") => [dep_req("DZ-NA_W8C7-B__s__", ">=17.1.14"),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "13.19.0") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", "=12.6.12"),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "14.10.18") => [dep_req("A0NQ_d_0___e7-sys", "<=0.2.0"),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "16.14.16")),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "19.12.7")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "0.2.11")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "1.18.3")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "2.12.15") => [dep_req("JtWi-_---z-sys", "=12.0.18"),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.2, <=14.10.18", DepKind::Build, false),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "3.16.0") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", "<=9.8.1"),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "4.16.14")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "5.11.18") => [dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.6", DepKind::Build, false),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "5.17.7")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "11.17.8") => [dep_req("A0NQ_d_0___e7-sys", ">=1.5.19"),dep_req("DZ-NA_W8C7-B__s__", "<=17.1.14"),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "12.3.17") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=1.5.19, <=4.8.13", DepKind::Build, false),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "12.18.19")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "12.19.1")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "13.7.9") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=4.12.16, <=18.16.2", DepKind::Build, false),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "14.0.15")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "14.3.15") => [dep_req_kind("DZ-NA_W8C7-B__s__", "<=14.19.3", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=8.0.8"),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "15.0.4") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=14.7.16, <=14.9.2", DepKind::Build, false),dep_req_kind("JtWi-_---z-sys", ">=0.18.15, <=12.0.18", DepKind::Build, false),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "18.10.0") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=7.3.12, <=9.7.8", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "=13.19.0"),]),pkg!(("MRI_y5Vek37_YSb_8-L-x-_-sys", "4.7.1") => [dep_req("DZ-NA_W8C7-B__s__", ">=9.7.8, <=18.16.2"),]),pkg!(("MRI_y5Vek37_YSb_8-L-x-_-sys", "15.10.11") => [dep("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys"),]),pkg!(("MRI_y5Vek37_YSb_8-L-x-_-sys", "16.16.1") => [dep_req("JtWi-_---z-sys", ">=2.19.13"),]),pkg!(("MRI_y5Vek37_YSb_8-L-x-_-sys", "19.12.0") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "=11.7.18"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "1.2.3") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "=13.19.0"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.19.1, <=14.3.15", DepKind::Build, false),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", "*", DepKind::Build, false),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "1.18.14")),pkg!(("RSV_z6-s_OJHUQ2z-sys", "2.0.12") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", "<=0.13.6", DepKind::Build, false),dep_req_kind("DZ-NA_W8C7-B__s__", ">=0.19.7, <=14.19.3", DepKind::Build, false),dep_req_kind("JtWi-_---z-sys", "<=12.0.18", DepKind::Build, false),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=2.12.15, <=15.0.4"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "2.10.5") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=8.0.8"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "6.3.4") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4"),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=3.18.10, <=7.8.6", DepKind::Build, false),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "8.10.19") => [dep_req_kind("JtWi-_---z-sys", ">=6.8.16, <=11.14.19", DepKind::Build, false),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "9.1.13") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=3.18.10, <=8.0.8"),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=16.16.1", DepKind::Build, false),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "12.4.7") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=4.8.13"),dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=14.7.16", DepKind::Build, false),dep_req_kind("DZ-NA_W8C7-B__s__", ">=0.19.7, <=17.1.14", DepKind::Build, false),dep_req_kind("JtWi-_---z-sys", "<=11.14.19", DepKind::Build, false),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "13.15.12") => [dep("B-30LKxtEB___gt1x-u-o--sys"),dep("MRI_y5Vek37_YSb_8-L-x-_-sys"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "14.3.15")),pkg!(("RSV_z6-s_OJHUQ2z-sys", "15.3.5")),pkg!(("RSV_z6-s_OJHUQ2z-sys", "15.11.19") => [dep_req_kind("JtWi-_---z-sys", "<=6.8.16", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=13.19.0, <=14.10.18"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "17.2.5") => [dep_req("DZ-NA_W8C7-B__s__", ">=7.3.12, <=14.19.3"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "17.10.17") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=0.19.7, <=4.12.16", DepKind::Build, false),dep_req("JtWi-_---z-sys", ">=0.18.15, <=12.4.2"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "18.6.19") => [dep_req("JtWi-_---z-sys", ">=6.8.16, <=12.4.2"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=2.12.15", DepKind::Build, false),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "19.3.3") => [dep_req("JtWi-_---z-sys", "=12.4.2"),]),pkg!(("S7v_2R-6-_qb-R6U--sys", "0.3.12")),pkg!(("S7v_2R-6-_qb-R6U--sys", "10.7.5")),pkg!(("S7v_2R-6-_qb-R6U--sys", "11.13.7") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.17.1"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=14.3.15"),]),pkg!(("S7v_2R-6-_qb-R6U--sys", "12.6.14")),pkg!(("S7v_2R-6-_qb-R6U--sys", "13.10.15") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=4.16.14", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=9.1.13, <=14.3.15", DepKind::Build, false),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "0.4.19")),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "1.18.3") => [dep_req("A0NQ_d_0___e7-sys", "<=9.1.0"),dep_req("B-30LKxtEB___gt1x-u-o--sys", "<=12.6.12"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "2.9.4") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=19.12.7"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=1.18.3, <=14.3.15", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=13.15.12, <=18.6.19"),dep_req("S7v_2R-6-_qb-R6U--sys", ">=13.10.15"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "4.2.5") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=12.6.12", DepKind::Build, false),dep_req("JtWi-_---z-sys", "<=11.14.19"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=2.12.15, <=14.3.15", DepKind::Build, false),dep_req_kind("S7v_2R-6-_qb-R6U--sys", ">=11.13.7, <=12.6.14", DepKind::Build, false),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "7.15.1") => [dep_req("DZ-NA_W8C7-B__s__", "<=0.0.6"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "8.0.2") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=4.8.13, <=8.14.2", DepKind::Build, false),dep_req_kind("DZ-NA_W8C7-B__s__", "<=17.1.14", DepKind::Build, false),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "9.19.1") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=0.19.4, <=1.5.19", DepKind::Build, false),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "12.18.17") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=4.16.14, <=14.0.15", DepKind::Build, false),dep_req("MRI_y5Vek37_YSb_8-L-x-_-sys", "<=4.7.1"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "14.2.8") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=4.13.11, <=14.7.16", DepKind::Build, false),dep_req("DZ-NA_W8C7-B__s__", ">=4.12.16, <=17.1.14"),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=11.7.18, <=14.10.18"),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=12.4.7, <=17.2.5"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "15.10.15") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", "<=4.13.11", DepKind::Build, false),dep_req_kind("DZ-NA_W8C7-B__s__", ">=17.1.14", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=9.1.13, <=12.4.7", DepKind::Build, false),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "16.13.14") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.19.1, <=13.7.9"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "19.12.3") => [dep_req_kind("JtWi-_---z-sys", ">=0.18.15, <=8.8.13", DepKind::Build, false),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=8.17.1", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.11.18, <=12.19.1", DepKind::Build, false),dep("MRI_y5Vek37_YSb_8-L-x-_-sys"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "19.14.12") => [dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "=8.17.1", DepKind::Build, false),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", "<=4.7.1", DepKind::Build, false),]),pkg!(("T_", "0.9.10") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=1.18.3, <=5.11.18"),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=15.10.11", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=8.10.19, <=9.1.13"),]),pkg!(("T_", "0.19.19") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=12.6.12"),]),pkg!(("T_", "3.3.3")),pkg!(("T_", "14.11.6") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=9.8.1", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=14.3.15, <=15.0.4", DepKind::Build, false),]),pkg!(("T_", "15.5.17") => [dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=13.19.0, <=16.14.16", DepKind::Build, false),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=2.12.15, <=5.17.7"),dep_req("SrYOB_H2G__pYll8_9Q---sys", "<=9.19.1"),]),pkg!(("T_", "16.7.1") => [dep_req_kind("A0NQ_d_0___e7-sys", "<=1.5.19", DepKind::Build, false),dep_req_kind("JtWi-_---z-sys", ">=12.4.2", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=5.11.18", DepKind::Build, false),dep_req_kind("S7v_2R-6-_qb-R6U--sys", "<=11.13.7", DepKind::Build, false),]),pkg!(("T_", "16.15.15") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=14.7.16, <=14.9.2"),dep_req_kind("DZ-NA_W8C7-B__s__", ">=4.12.16, <=9.7.8", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.0.8, <=14.10.18"),]),pkg!(("T_", "18.12.8") => [dep_req("JtWi-_---z-sys", ">=0.18.15, <=8.8.13"),]),pkg!(("T_", "18.12.13") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", "=4.13.11", DepKind::Build, false),dep_req_kind("DZ-NA_W8C7-B__s__", ">=0.19.7, <=18.16.2", DepKind::Build, false),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", "<=15.10.11", DepKind::Build, false),]),pkg!(("T_", "19.10.6") => [dep("DZ-NA_W8C7-B__s__"),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=3.18.10, <=8.0.8"),]),pkg!(("U5_ZbZ7c1_K-u-sys", "0.4.13") => [dep_req("A0NQ_d_0___e7-sys", "=9.1.0"),]),pkg!(("U5_ZbZ7c1_K-u-sys", "2.7.11") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.3.17, <=15.0.4", DepKind::Build, false),]),pkg!(("U5_ZbZ7c1_K-u-sys", "6.6.11") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=1.5.19"),dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=9.8.1, <=14.9.2"),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=7.15.1"),]),pkg!(("U5_ZbZ7c1_K-u-sys", "9.16.6")),pkg!(("U5_ZbZ7c1_K-u-sys", "10.19.12") => [dep_req("RSV_z6-s_OJHUQ2z-sys", ">=9.1.13, <=17.2.5"),]),pkg!(("U5_ZbZ7c1_K-u-sys", "11.12.19") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=4.16.14, <=12.18.19"),]),pkg!(("U5_ZbZ7c1_K-u-sys", "13.6.18") => [dep_req_kind("RSV_z6-s_OJHUQ2z-sys", "=12.4.7", DepKind::Build, false),]),pkg!(("U5_ZbZ7c1_K-u-sys", "18.2.13") => [dep_req_kind("RSV_z6-s_OJHUQ2z-sys", "<=17.2.5", DepKind::Build, false),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", "<=9.19.1", DepKind::Build, false),dep_req_kind("T_", ">=3.3.3", DepKind::Build, false),]),pkg!(("U5_ZbZ7c1_K-u-sys", "19.4.6") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=9.8.1"),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "2.6.2") => [dep_req("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=16.16.1"),dep_req_kind("T_", ">=16.7.1", DepKind::Build, false),dep_req_kind("U5_ZbZ7c1_K-u-sys", ">=10.19.12, <=18.2.13", DepKind::Build, false),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "4.6.3") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "=8.17.1"),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12, <=15.11.19"),dep_req("SrYOB_H2G__pYll8_9Q---sys", "=9.19.1"),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "5.17.3") => [dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.0.8, <=8.17.1", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12"),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "11.9.2") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.18.19, <=15.0.4", DepKind::Build, false),dep_req("T_", ">=16.15.15"),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "11.19.10") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=4.13.11, <=14.9.2", DepKind::Build, false),dep("JtWi-_---z-sys"),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "12.8.4") => [dep_req("JtWi-_---z-sys", "<=8.8.13"),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "14.7.17")),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "14.19.19")),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "15.11.2") => [dep_req("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=16.16.1"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=6.3.4, <=15.11.19", DepKind::Build, false),]),pkg!(("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "4.1.4") => [dep_req("RSV_z6-s_OJHUQ2z-sys", ">=9.1.13, <=15.3.5"),]),pkg!(("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "11.6.19")),pkg!(("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "12.1.17") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=1.18.3, <=14.0.15"),]),pkg!(("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "15.13.1") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=8.14.2"),dep_req_kind("DZ-NA_W8C7-B__s__", "=18.16.2", DepKind::Build, false),dep_req("JtWi-_---z-sys", "<=0.18.15"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", "<=1.2.3", DepKind::Build, false),]),pkg!(("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "18.16.2") => [dep_req("JtWi-_---z-sys", ">=12.0.18, <=12.4.2"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=12.4.7, <=15.3.5", DepKind::Build, false),]),pkg!(("aYui-X86_c8-g", "5.1.17") => [dep_req_kind("A0NQ_d_0___e7-sys", "=9.1.0", DepKind::Build, false),dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=7.15.1, <=15.10.15", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=4.6.3, <=11.9.2"),]),pkg!(("aYui-X86_c8-g", "7.6.6") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.2, <=11.7.18"),]),pkg!(("aYui-X86_c8-g", "9.5.2") => [dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=11.9.2, <=12.8.4"),]),pkg!(("aYui-X86_c8-g", "9.6.13") => [dep_req("A0NQ_d_0___e7-sys", "<=9.1.0"),dep_req("JtWi-_---z-sys", ">=2.19.13"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=4.2.5", DepKind::Build, false),dep_req("T_", ">=14.11.6, <=15.5.17"),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=11.19.10"),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "=11.6.19", DepKind::Build, false),]),pkg!(("aYui-X86_c8-g", "11.8.8") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=14.19.3, <=18.16.2", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=14.0.15, <=14.3.15", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", "<=14.2.8"),]),pkg!(("aYui-X86_c8-g", "13.13.15") => [dep_req("MRI_y5Vek37_YSb_8-L-x-_-sys", "=16.16.1"),dep_req_kind("U5_ZbZ7c1_K-u-sys", "=13.6.18", DepKind::Build, false),]),pkg!(("aYui-X86_c8-g", "14.17.3") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.17.7"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", "<=7.15.1", DepKind::Build, false),dep_req("U5_ZbZ7c1_K-u-sys", "<=2.7.11"),]),pkg!(("aYui-X86_c8-g", "15.7.12") => [dep_req("JtWi-_---z-sys", ">=2.19.13, <=8.8.13"),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=1.18.3, <=2.9.4"),]),pkg!(("aYui-X86_c8-g", "19.16.13") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=13.12.13"),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.0.8, <=12.17.2", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.17.7, <=12.3.17", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=4.6.3, <=12.8.4"),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=11.6.19"),]),pkg!(("aYui-X86_c8-g", "19.19.17") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", "=2.0.5", DepKind::Build, false),dep_req("DZ-NA_W8C7-B__s__", ">=7.3.12, <=14.19.3"),dep_req_kind("JtWi-_---z-sys", ">=2.15.14", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=11.17.8", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=9.1.13, <=14.3.15", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "0.7.7") => [dep_req("A0NQ_d_0___e7-sys", "<=0.19.4"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=1.18.3, <=7.15.1", DepKind::Build, false),dep_req_kind("U5_ZbZ7c1_K-u-sys", ">=11.12.19, <=18.2.13", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "1.4.16") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=18.19.2", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=14.3.15, <=15.0.4", DepKind::Build, false),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=16.16.1", DepKind::Build, false),dep_req_kind("U5_ZbZ7c1_K-u-sys", "*", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", ">=7.6.6, <=11.8.8", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "2.6.6") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=2.12.15, <=15.0.4"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=1.18.3, <=9.19.1", DepKind::Build, false),dep_req("U5_ZbZ7c1_K-u-sys", ">=6.6.11, <=13.6.18"),]),pkg!(("eR_TVK_I_-J", "2.13.0") => [dep("bad"),]),pkg!(("eR_TVK_I_-J", "4.15.17") => [dep_req_kind("JtWi-_---z-sys", ">=2.19.13, <=12.4.2", DepKind::Build, false),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=15.13.1", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "9.13.2") => [dep_req_kind("T_", ">=19.10.6", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "9.19.13") => [dep_req_kind("T_", ">=0.19.19", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "10.1.4") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=9.1.0"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=4.16.14", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=9.19.1, <=12.18.17"),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "<=14.7.17", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "10.17.16") => [dep_req_kind("JtWi-_---z-sys", ">=12.4.2", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=1.18.3, <=12.18.19", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12, <=17.10.17", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "12.10.5") => [dep_req_kind("JtWi-_---z-sys", ">=6.8.16, <=8.8.13", DepKind::Build, false),dep_req("U5_ZbZ7c1_K-u-sys", ">=19.4.6"),dep_req("aYui-X86_c8-g", ">=11.8.8, <=13.13.15"),]),pkg!(("eR_TVK_I_-J", "13.13.4") => [dep_req("A0NQ_d_0___e7-sys", ">=1.5.19, <=10.5.3"),dep_req_kind("T_", "<=0.19.19", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "14.10.10") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=4.12.16, <=17.1.14", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.2, <=13.19.0"),]),pkg!(("eR_TVK_I_-J", "16.19.17") => [dep_req("DZ-NA_W8C7-B__s__", ">=7.3.12, <=17.1.14"),dep_req("JtWi-_---z-sys", ">=2.15.14, <=12.4.2"),dep_req("aYui-X86_c8-g", ">=5.1.17, <=9.5.2"),]),pkg!(("eR_TVK_I_-J", "17.10.1") => [dep_req("DZ-NA_W8C7-B__s__", "<=0.0.6"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=4.16.14, <=15.0.4"),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=15.3.5"),]),pkg!(("eR_TVK_I_-J", "18.3.11") => [dep_req_kind("JtWi-_---z-sys", ">=11.14.19, <=12.0.18", DepKind::Build, false),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "=13.19.0", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=14.7.17"),]),pkg!(("eR_TVK_I_-J", "18.9.1") => [dep_req_kind("JtWi-_---z-sys", ">=6.8.16, <=11.14.19", DepKind::Build, false),dep_req_kind("T_", ">=0.19.19, <=18.12.13", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", ">=13.13.15", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "18.13.3") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=4.16.14, <=5.17.7", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=8.10.19, <=13.15.12"),dep_req_kind("S7v_2R-6-_qb-R6U--sys", "<=11.13.7", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "19.3.9") => [dep_req("RSV_z6-s_OJHUQ2z-sys", ">=17.10.17"),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=4.2.5, <=12.18.17"),]),pkg!(("g-R9E_nf__-sys", "0.15.2")),pkg!(("g-R9E_nf__-sys", "3.11.10") => [dep_req_kind("A0NQ_d_0___e7-sys", "<=10.5.3", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", "<=2.10.5"),]),pkg!(("g-R9E_nf__-sys", "5.2.1") => [dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=12.18.17", DepKind::Build, false),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "<=14.7.17", DepKind::Build, false),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=11.6.19, <=15.13.1"),dep_req_kind("aYui-X86_c8-g", ">=13.13.15, <=14.17.3", DepKind::Build, false),dep_req("eR_TVK_I_-J", ">=13.13.4, <=16.19.17"),]),pkg!(("g-R9E_nf__-sys", "5.12.2") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.11.18, <=12.18.19", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=11.9.2, <=14.19.19"),]),pkg!(("g-R9E_nf__-sys", "7.5.15") => [dep_req_kind("A0NQ_d_0___e7-sys", "<=8.14.2", DepKind::Build, false),dep_req_kind("JtWi-_---z-sys", "=6.8.16", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=14.0.15, <=14.3.15", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=4.2.5, <=7.15.1"),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=5.17.3, <=11.9.2", DepKind::Build, false),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=15.13.1"),dep("eR_TVK_I_-J"),]),pkg!(("g-R9E_nf__-sys", "8.19.8") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=17.1.14, <=18.16.2", DepKind::Build, false),]),pkg!(("g-R9E_nf__-sys", "9.1.10") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=4.12.16, <=17.1.14", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=9.19.1, <=14.2.8"),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=11.6.19, <=15.13.1", DepKind::Build, false),dep_req("aYui-X86_c8-g", ">=9.5.2, <=11.8.8"),]),pkg!(("g-R9E_nf__-sys", "9.15.4") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", "<=8.15.7", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=11.7.18, <=13.19.0"),dep_req_kind("aYui-X86_c8-g", ">=11.8.8, <=14.17.3", DepKind::Build, false),dep_req_kind("eR_TVK_I_-J", ">=10.1.4, <=18.13.3", DepKind::Build, false),]),pkg!(("g-R9E_nf__-sys", "10.0.8") => [dep_req("DZ-NA_W8C7-B__s__", "<=17.1.14"),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=3.18.10, <=16.14.16"),dep_req("U5_ZbZ7c1_K-u-sys", ">=2.7.11, <=6.6.11"),dep_req("aYui-X86_c8-g", ">=14.17.3"),dep_req("eR_TVK_I_-J", ">=4.15.17, <=16.19.17"),]),pkg!(("g-R9E_nf__-sys", "10.6.2") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=4.8.13, <=13.12.13", DepKind::Build, false),dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=14.7.16, <=14.9.2", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=9.19.1"),]),pkg!(("g-R9E_nf__-sys", "11.10.7") => [dep_req("A0NQ_d_0___e7-sys", ">=4.8.13, <=8.14.2"),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.2, <=14.10.18", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", "=5.1.17", DepKind::Build, false),]),pkg!(("g-R9E_nf__-sys", "13.3.3") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=8.15.7"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=4.16.14", DepKind::Build, false),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=12.1.17", DepKind::Build, false),dep_req_kind("eR_TVK_I_-J", ">=2.13.0, <=4.15.17", DepKind::Build, false),]),pkg!(("g-R9E_nf__-sys", "14.15.5") => [dep_req_kind("JtWi-_---z-sys", "=2.15.14", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=16.14.16"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.11.18, <=11.17.8", DepKind::Build, false),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=15.10.11, <=16.16.1", DepKind::Build, false),dep_req("U5_ZbZ7c1_K-u-sys", "<=9.16.6"),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=11.9.2, <=14.7.17", DepKind::Build, false),]),pkg!(("g-R9E_nf__-sys", "16.11.6") => [dep_req("A0NQ_d_0___e7-sys", ">=1.5.19, <=8.14.2"),dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=12.6.12, <=14.9.2"),dep_req_kind("DZ-NA_W8C7-B__s__", "<=18.16.2", DepKind::Build, false),dep_req("S7v_2R-6-_qb-R6U--sys", "=11.13.7"),]),pkg!(("g-R9E_nf__-sys", "16.13.18") => [dep_req_kind("JtWi-_---z-sys", ">=0.18.15, <=12.4.2", DepKind::Build, false),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.19.1, <=14.3.15"),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=12.1.17"),]),pkg!(("g-R9E_nf__-sys", "16.16.16") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=9.1.0", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=1.18.3", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "=4.6.3"),dep_req("aYui-X86_c8-g", ">=11.8.8, <=19.16.13"),dep_req_kind("eR_TVK_I_-J", ">=9.19.13, <=14.10.10", DepKind::Build, false),]),pkg!(("g-R9E_nf__-sys", "16.18.9") => [dep_req("DZ-NA_W8C7-B__s__", ">=7.3.12"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=11.17.8, <=12.19.1"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=16.13.14", DepKind::Build, false),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "6.15.16") => [dep_req("JtWi-_---z-sys", ">=6.8.16"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "*", DepKind::Build, false),dep_req_kind("T_", ">=15.5.17", DepKind::Build, false),dep_req("aYui-X86_c8-g", ">=7.6.6, <=9.5.2"),dep_req("eR_TVK_I_-J", ">=2.6.6"),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "7.0.5") => [dep_req("T_", ">=0.19.19, <=15.5.17"),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "9.15.3") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4"),dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=4.13.11, <=8.15.7", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=12.17.2, <=16.14.16"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "=1.18.3"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12, <=15.11.19", DepKind::Build, false),dep_req("eR_TVK_I_-J", ">=9.19.13, <=12.10.5"),dep_req_kind("g-R9E_nf__-sys", ">=3.11.10, <=13.3.3", DepKind::Build, false),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "13.1.14") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=14.9.2", DepKind::Build, false),dep_req("JtWi-_---z-sys", "=11.14.19"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=4.2.5", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=12.8.4, <=14.19.19"),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=4.1.4", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", ">=13.13.15, <=19.16.13", DepKind::Build, false),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "13.9.13") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=9.1.0, <=13.12.13", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=9.1.13, <=17.2.5"),dep("T_"),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "13.14.3") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=12.17.2, <=16.14.16"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=1.18.14, <=9.1.13", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=1.18.3, <=14.2.8"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "0.17.7") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=8.14.2, <=9.1.0", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=2.12.15, <=14.0.15", DepKind::Build, false),dep_req("MRI_y5Vek37_YSb_8-L-x-_-sys", "<=4.7.1"),dep_req_kind("S7v_2R-6-_qb-R6U--sys", ">=10.7.5", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "2.11.1") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4"),dep_req_kind("DZ-NA_W8C7-B__s__", ">=7.3.12, <=17.1.14", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=15.10.15"),dep_req("eR_TVK_I_-J", "<=16.19.17"),dep_req("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=6.15.16"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "5.18.4") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=12.6.12", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12, <=15.3.5", DepKind::Build, false),dep_req("T_", ">=3.3.3, <=14.11.6"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "6.2.9") => [dep_req_kind("JtWi-_---z-sys", "=11.14.19", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=8.0.2, <=14.2.8"),dep_req_kind("T_", ">=16.15.15", DepKind::Build, false),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=4.1.4"),dep_req_kind("eR_TVK_I_-J", "<=18.3.11", DepKind::Build, false),dep_req_kind("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=9.15.3", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "6.3.17") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=3.18.10, <=16.14.16"),dep_req_kind("o_i_P-bCR9KAN4O___FCe__NHCDDv", "=1.19.14", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "6.12.3") => [dep_req_kind("eR_TVK_I_-J", ">=10.1.4", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "8.8.8") => [dep("bad"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "10.12.13") => [dep_req_kind("RSV_z6-s_OJHUQ2z-sys", "=15.11.19", DepKind::Build, false),dep_req("S7v_2R-6-_qb-R6U--sys", "<=12.6.14"),dep_req_kind("T_", ">=16.15.15, <=18.12.8", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=4.6.3"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "12.6.2") => [dep_req("T_", ">=3.3.3, <=15.5.17"),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "*", DepKind::Build, false),dep_req("aYui-X86_c8-g", ">=0.10.16, <=9.5.2"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "12.6.9") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.0.8, <=11.7.18"),dep_req_kind("U5_ZbZ7c1_K-u-sys", ">=6.6.11, <=11.12.19", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", "=9.6.13", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "12.16.15") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.18.19, <=14.3.15"),dep_req("U5_ZbZ7c1_K-u-sys", ">=11.12.19, <=13.6.18"),dep_req_kind("aYui-X86_c8-g", ">=5.1.17", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "12.19.6") => [dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=12.18.17, <=14.2.8"),dep_req("eR_TVK_I_-J", ">=4.15.17, <=13.13.4"),dep_req("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=4.6.10, <=13.1.14"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "15.4.9") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.6"),dep_req("U5_ZbZ7c1_K-u-sys", ">=6.6.11, <=13.6.18"),dep_req_kind("aYui-X86_c8-g", ">=14.17.3, <=15.7.12", DepKind::Build, false),]),pkg!(("rZ7", "15.7.17") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "=14.3.15"),dep_req_kind("S7v_2R-6-_qb-R6U--sys", "<=10.7.5", DepKind::Build, false),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=7.15.1, <=12.18.17", DepKind::Build, false),dep_req("U5_ZbZ7c1_K-u-sys", "=18.2.13"),dep_req_kind("g-R9E_nf__-sys", ">=5.2.1, <=9.1.10", DepKind::Build, false),]),pkg!(("sP6-L-", "14.0.12") => [dep_req("JtWi-_---z-sys", "<=2.15.14"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.11.18"),dep_req("pY-bP___j3V_bgGkw-D4-sys", "=12.6.2"),]),pkg!(("sP6-L-", "17.11.15") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=4.13.11"),dep_req_kind("JtWi-_---z-sys", ">=11.14.19", DepKind::Build, false),dep_req_kind("S7v_2R-6-_qb-R6U--sys", ">=10.7.5", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "11.16.8") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=9.8.1"),dep_req_kind("DZ-NA_W8C7-B__s__", "=17.1.14", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", ">=14.17.3, <=19.16.13", DepKind::Build, false),dep_req("g-R9E_nf__-sys", ">=10.0.8"),dep_req_kind("sP6-L-", ">=14.0.12, <=17.11.15", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "13.2.18") => [dep_req("A0NQ_d_0___e7-sys", ">=4.8.13"),dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", "<=4.13.11", DepKind::Build, false),dep_req("DZ-NA_W8C7-B__s__", ">=7.3.12, <=18.16.2"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12, <=17.2.5", DepKind::Build, false),dep_req("S7v_2R-6-_qb-R6U--sys", ">=11.13.7"),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=12.8.4, <=14.7.17"),dep_req_kind("eR_TVK_I_-J", ">=2.13.0, <=18.9.1", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "14.13.9") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.17.1, <=16.14.16"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12, <=12.4.7", DepKind::Build, false),dep_req_kind("T_", ">=15.5.17", DepKind::Build, false),dep_req("U5_ZbZ7c1_K-u-sys", ">=2.7.11, <=11.12.19"),]),pkg!(("w_knohZMQB6u-sys", "15.7.11") => [dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.6", DepKind::Build, false),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=15.10.15", DepKind::Build, false),dep_req_kind("T_", "<=0.19.19", DepKind::Build, false),dep_req("eR_TVK_I_-J", "=13.13.4"),dep_req_kind("g-R9E_nf__-sys", ">=9.1.10, <=16.13.18", DepKind::Build, false),dep_req_kind("rZ7", "=15.7.17", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "15.16.15") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.18.19, <=15.0.4", DepKind::Build, false),dep_req_kind("T_", "<=0.19.19", DepKind::Build, false),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=11.6.19"),dep_req_kind("aYui-X86_c8-g", ">=11.8.8", DepKind::Build, false),dep_req("g-R9E_nf__-sys", ">=16.13.18"),]),pkg!(("w_knohZMQB6u-sys", "16.15.13") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=4.13.11", DepKind::Build, false),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=15.0.4"),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=14.2.8, <=15.10.15"),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=11.6.19"),dep_req("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=6.15.16, <=7.0.5"),]),pkg!(("w_knohZMQB6u-sys", "17.8.1") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=8.14.2, <=10.5.3", DepKind::Build, false),dep_req("DZ-NA_W8C7-B__s__", ">=7.3.12"),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.6, <=8.17.1", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12", DepKind::Build, false),dep_req_kind("T_", ">=14.11.6, <=18.12.8", DepKind::Build, false),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "=14.19.19", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "18.0.13") => [dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=6.3.4, <=17.2.5", DepKind::Build, false),dep_req("eR_TVK_I_-J", ">=2.13.0, <=9.13.2"),dep_req_kind("g-R9E_nf__-sys", ">=0.15.2, <=7.5.15", DepKind::Build, false),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", "<=15.4.9", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "18.8.1") => [dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=16.13.14, <=19.12.3"),dep_req("g-R9E_nf__-sys", ">=9.15.4, <=16.13.18"),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", "=8.8.8", DepKind::Build, false),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "11.19.4") => [dep_req("RSV_z6-s_OJHUQ2z-sys", ">=15.3.5, <=17.10.17"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=1.18.3", DepKind::Build, false),dep_req("T_", ">=15.5.17, <=16.7.1"),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=11.19.10", DepKind::Build, false),dep_req_kind("g-R9E_nf__-sys", ">=7.5.15, <=14.15.5", DepKind::Build, false),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", "=2.11.1", DepKind::Build, false),dep_req("w_knohZMQB6u-sys", ">=11.16.8"),]),]
2024-11-21T20:12:17.8694969Z error: test failed, to rerun pass `-p resolver-tests --test proptests`
2024-11-21T20:12:17.8696352Z proptest: Aborting shrinking after the PROPTEST_MAX_SHRINK_ITERS environment variable or ProptestConfig.max_shrink_iters iterations (set 0 to a large(r) value to shrink more; current configuration: 0 iterations)
2024-11-21T20:12:17.8697759Z proptest: FileFailurePersistence::SourceParallel set, but failed to find lib.rs or main.rs
2024-11-21T20:12:17.8698971Z proptest: Saving this and future failures in /home/runner/work/cargo/cargo/crates/resolver-tests/tests/proptests.proptest-regressions
2024-11-21T20:12:17.8700347Z proptest: If this test was run on a CI system, you may wish to add the following line to your copy of the file. (You may need to create it.)
2024-11-21T20:12:17.8701310Z cc cda6c1ea4a4d67d9f7591edf978f52cf228f11afc422a1658c75bcdfb456c230
2024-11-21T20:12:17.8702392Z thread 'prop_passes_validation' panicked at crates/resolver-tests/tests/proptests.rs:22:1:
2024-11-21T20:12:17.8703171Z Test failed: got to 50_000 ticks in 8.884444187s.
2024-11-21T20:12:17.8902299Z minimal failing input: PrettyPrintRegistry(input) = vec![pkg!(("A0NQ_d_0___e7-sys", "0.2.0")),pkg!(("A0NQ_d_0___e7-sys", "0.19.4")),pkg!(("A0NQ_d_0___e7-sys", "1.5.19")),pkg!(("A0NQ_d_0___e7-sys", "4.8.13")),pkg!(("A0NQ_d_0___e7-sys", "8.14.2")),pkg!(("A0NQ_d_0___e7-sys", "9.1.0")),pkg!(("A0NQ_d_0___e7-sys", "10.5.3")),pkg!(("A0NQ_d_0___e7-sys", "13.12.13")),pkg!(("A0NQ_d_0___e7-sys", "18.19.2")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "0.13.6")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "2.0.5") => [dep("A0NQ_d_0___e7-sys"),]),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "4.13.11")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "8.15.7")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "9.8.1")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "12.6.12")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "14.7.16")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "14.9.2")),pkg!(("B-30LKxtEB___gt1x-u-o--sys", "16.15.7")),pkg!(("DZ-NA_W8C7-B__s__", "0.0.6")),pkg!(("DZ-NA_W8C7-B__s__", "0.19.7")),pkg!(("DZ-NA_W8C7-B__s__", "4.12.16")),pkg!(("DZ-NA_W8C7-B__s__", "7.3.12") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=1.5.19"),]),pkg!(("DZ-NA_W8C7-B__s__", "9.7.8")),pkg!(("DZ-NA_W8C7-B__s__", "14.19.3")),pkg!(("DZ-NA_W8C7-B__s__", "17.1.14")),pkg!(("DZ-NA_W8C7-B__s__", "18.16.2") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=9.8.1, <=12.6.12"),]),pkg!(("DZ-NA_W8C7-B__s__", "19.19.4") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=1.5.19, <=4.8.13", DepKind::Build, false),dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=12.6.12"),]),pkg!(("JtWi-_---z-sys", "0.0.6")),pkg!(("JtWi-_---z-sys", "0.18.15") => [dep_req("DZ-NA_W8C7-B__s__", ">=4.12.16, <=9.7.8"),]),pkg!(("JtWi-_---z-sys", "2.15.14")),pkg!(("JtWi-_---z-sys", "2.19.13")),pkg!(("JtWi-_---z-sys", "6.8.16") => [dep_req("A0NQ_d_0___e7-sys", "<=9.1.0"),]),pkg!(("JtWi-_---z-sys", "8.8.13")),pkg!(("JtWi-_---z-sys", "11.14.19")),pkg!(("JtWi-_---z-sys", "12.0.18") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=0.19.4", DepKind::Build, false),dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=4.13.11, <=14.9.2"),]),pkg!(("JtWi-_---z-sys", "12.4.2") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=8.15.7, <=12.6.12"),]),pkg!(("JtWi-_---z-sys", "16.3.14") => [dep_req_kind("DZ-NA_W8C7-B__s__", "<=17.1.14", DepKind::Build, false),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "0.15.5") => [dep_req("DZ-NA_W8C7-B__s__", ">=4.12.16"),dep_req_kind("JtWi-_---z-sys", "=8.8.13", DepKind::Build, false),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "3.18.10") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", "<=2.0.5"),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "7.8.2") => [dep_req("DZ-NA_W8C7-B__s__", ">=9.7.8, <=17.1.14"),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "7.8.6")),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "8.0.8")),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "8.17.1")),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "11.7.18") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=14.7.16"),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "12.17.2") => [dep_req("DZ-NA_W8C7-B__s__", ">=17.1.14"),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "13.19.0") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", "=12.6.12"),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "14.10.18") => [dep_req("A0NQ_d_0___e7-sys", "<=0.2.0"),]),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "16.14.16")),pkg!(("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "19.12.7")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "0.2.11")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "1.18.3")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "2.12.15") => [dep_req("JtWi-_---z-sys", "=12.0.18"),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.2, <=14.10.18", DepKind::Build, false),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "3.16.0") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", "<=9.8.1"),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "4.16.14")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "5.11.18") => [dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.6", DepKind::Build, false),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "5.17.7")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "11.17.8") => [dep_req("A0NQ_d_0___e7-sys", ">=1.5.19"),dep_req("DZ-NA_W8C7-B__s__", "<=17.1.14"),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "12.3.17") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=1.5.19, <=4.8.13", DepKind::Build, false),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "12.18.19")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "12.19.1")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "13.7.9") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=4.12.16, <=18.16.2", DepKind::Build, false),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "14.0.15")),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "14.3.15") => [dep_req_kind("DZ-NA_W8C7-B__s__", "<=14.19.3", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=8.0.8"),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "15.0.4") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=14.7.16, <=14.9.2", DepKind::Build, false),dep_req_kind("JtWi-_---z-sys", ">=0.18.15, <=12.0.18", DepKind::Build, false),]),pkg!(("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "18.10.0") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=7.3.12, <=9.7.8", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "=13.19.0"),]),pkg!(("MRI_y5Vek37_YSb_8-L-x-_-sys", "4.7.1") => [dep_req("DZ-NA_W8C7-B__s__", ">=9.7.8, <=18.16.2"),]),pkg!(("MRI_y5Vek37_YSb_8-L-x-_-sys", "15.10.11") => [dep("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys"),]),pkg!(("MRI_y5Vek37_YSb_8-L-x-_-sys", "16.16.1") => [dep_req("JtWi-_---z-sys", ">=2.19.13"),]),pkg!(("MRI_y5Vek37_YSb_8-L-x-_-sys", "19.12.0") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "=11.7.18"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "1.2.3") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "=13.19.0"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.19.1, <=14.3.15", DepKind::Build, false),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", "*", DepKind::Build, false),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "1.18.14")),pkg!(("RSV_z6-s_OJHUQ2z-sys", "2.0.12") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", "<=0.13.6", DepKind::Build, false),dep_req_kind("DZ-NA_W8C7-B__s__", ">=0.19.7, <=14.19.3", DepKind::Build, false),dep_req_kind("JtWi-_---z-sys", "<=12.0.18", DepKind::Build, false),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=2.12.15, <=15.0.4"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "2.10.5") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=8.0.8"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "6.3.4") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4"),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=3.18.10, <=7.8.6", DepKind::Build, false),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "8.10.19") => [dep_req_kind("JtWi-_---z-sys", ">=6.8.16, <=11.14.19", DepKind::Build, false),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "9.1.13") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=3.18.10, <=8.0.8"),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=16.16.1", DepKind::Build, false),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "12.4.7") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=4.8.13"),dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=14.7.16", DepKind::Build, false),dep_req_kind("DZ-NA_W8C7-B__s__", ">=0.19.7, <=17.1.14", DepKind::Build, false),dep_req_kind("JtWi-_---z-sys", "<=11.14.19", DepKind::Build, false),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "13.15.12") => [dep("B-30LKxtEB___gt1x-u-o--sys"),dep("MRI_y5Vek37_YSb_8-L-x-_-sys"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "14.3.15")),pkg!(("RSV_z6-s_OJHUQ2z-sys", "15.3.5")),pkg!(("RSV_z6-s_OJHUQ2z-sys", "15.11.19") => [dep_req_kind("JtWi-_---z-sys", "<=6.8.16", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=13.19.0, <=14.10.18"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "17.2.5") => [dep_req("DZ-NA_W8C7-B__s__", ">=7.3.12, <=14.19.3"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "17.10.17") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=0.19.7, <=4.12.16", DepKind::Build, false),dep_req("JtWi-_---z-sys", ">=0.18.15, <=12.4.2"),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "18.6.19") => [dep_req("JtWi-_---z-sys", ">=6.8.16, <=12.4.2"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=2.12.15", DepKind::Build, false),]),pkg!(("RSV_z6-s_OJHUQ2z-sys", "19.3.3") => [dep_req("JtWi-_---z-sys", "=12.4.2"),]),pkg!(("S7v_2R-6-_qb-R6U--sys", "0.3.12")),pkg!(("S7v_2R-6-_qb-R6U--sys", "10.7.5")),pkg!(("S7v_2R-6-_qb-R6U--sys", "11.13.7") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.17.1"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=14.3.15"),]),pkg!(("S7v_2R-6-_qb-R6U--sys", "12.6.14")),pkg!(("S7v_2R-6-_qb-R6U--sys", "13.10.15") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=4.16.14", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=9.1.13, <=14.3.15", DepKind::Build, false),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "0.4.19")),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "1.18.3") => [dep_req("A0NQ_d_0___e7-sys", "<=9.1.0"),dep_req("B-30LKxtEB___gt1x-u-o--sys", "<=12.6.12"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "2.9.4") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=19.12.7"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=1.18.3, <=14.3.15", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=13.15.12, <=18.6.19"),dep_req("S7v_2R-6-_qb-R6U--sys", ">=13.10.15"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "4.2.5") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=12.6.12", DepKind::Build, false),dep_req("JtWi-_---z-sys", "<=11.14.19"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=2.12.15, <=14.3.15", DepKind::Build, false),dep_req_kind("S7v_2R-6-_qb-R6U--sys", ">=11.13.7, <=12.6.14", DepKind::Build, false),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "7.15.1") => [dep_req("DZ-NA_W8C7-B__s__", "<=0.0.6"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "8.0.2") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=4.8.13, <=8.14.2", DepKind::Build, false),dep_req_kind("DZ-NA_W8C7-B__s__", "<=17.1.14", DepKind::Build, false),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "9.19.1") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=0.19.4, <=1.5.19", DepKind::Build, false),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "12.18.17") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=4.16.14, <=14.0.15", DepKind::Build, false),dep_req("MRI_y5Vek37_YSb_8-L-x-_-sys", "<=4.7.1"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "14.2.8") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=4.13.11, <=14.7.16", DepKind::Build, false),dep_req("DZ-NA_W8C7-B__s__", ">=4.12.16, <=17.1.14"),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=11.7.18, <=14.10.18"),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=12.4.7, <=17.2.5"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "15.10.15") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", "<=4.13.11", DepKind::Build, false),dep_req_kind("DZ-NA_W8C7-B__s__", ">=17.1.14", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=9.1.13, <=12.4.7", DepKind::Build, false),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "16.13.14") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.19.1, <=13.7.9"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "19.12.3") => [dep_req_kind("JtWi-_---z-sys", ">=0.18.15, <=8.8.13", DepKind::Build, false),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=8.17.1", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.11.18, <=12.19.1", DepKind::Build, false),dep("MRI_y5Vek37_YSb_8-L-x-_-sys"),]),pkg!(("SrYOB_H2G__pYll8_9Q---sys", "19.14.12") => [dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "=8.17.1", DepKind::Build, false),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", "<=4.7.1", DepKind::Build, false),]),pkg!(("T_", "0.9.10") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=1.18.3, <=5.11.18"),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=15.10.11", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=8.10.19, <=9.1.13"),]),pkg!(("T_", "0.19.19") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=12.6.12"),]),pkg!(("T_", "3.3.3")),pkg!(("T_", "14.11.6") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=9.8.1", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=14.3.15, <=15.0.4", DepKind::Build, false),]),pkg!(("T_", "15.5.17") => [dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=13.19.0, <=16.14.16", DepKind::Build, false),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=2.12.15, <=5.17.7"),dep_req("SrYOB_H2G__pYll8_9Q---sys", "<=9.19.1"),]),pkg!(("T_", "16.7.1") => [dep_req_kind("A0NQ_d_0___e7-sys", "<=1.5.19", DepKind::Build, false),dep_req_kind("JtWi-_---z-sys", ">=12.4.2", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=5.11.18", DepKind::Build, false),dep_req_kind("S7v_2R-6-_qb-R6U--sys", "<=11.13.7", DepKind::Build, false),]),pkg!(("T_", "16.15.15") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=14.7.16, <=14.9.2"),dep_req_kind("DZ-NA_W8C7-B__s__", ">=4.12.16, <=9.7.8", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.0.8, <=14.10.18"),]),pkg!(("T_", "18.12.8") => [dep_req("JtWi-_---z-sys", ">=0.18.15, <=8.8.13"),]),pkg!(("T_", "18.12.13") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", "=4.13.11", DepKind::Build, false),dep_req_kind("DZ-NA_W8C7-B__s__", ">=0.19.7, <=18.16.2", DepKind::Build, false),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", "<=15.10.11", DepKind::Build, false),]),pkg!(("T_", "19.10.6") => [dep("DZ-NA_W8C7-B__s__"),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=3.18.10, <=8.0.8"),]),pkg!(("U5_ZbZ7c1_K-u-sys", "0.4.13") => [dep_req("A0NQ_d_0___e7-sys", "=9.1.0"),]),pkg!(("U5_ZbZ7c1_K-u-sys", "2.7.11") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.3.17, <=15.0.4", DepKind::Build, false),]),pkg!(("U5_ZbZ7c1_K-u-sys", "6.6.11") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=1.5.19"),dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=9.8.1, <=14.9.2"),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=7.15.1"),]),pkg!(("U5_ZbZ7c1_K-u-sys", "9.16.6")),pkg!(("U5_ZbZ7c1_K-u-sys", "10.19.12") => [dep_req("RSV_z6-s_OJHUQ2z-sys", ">=9.1.13, <=17.2.5"),]),pkg!(("U5_ZbZ7c1_K-u-sys", "11.12.19") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=4.16.14, <=12.18.19"),]),pkg!(("U5_ZbZ7c1_K-u-sys", "13.6.18") => [dep_req_kind("RSV_z6-s_OJHUQ2z-sys", "=12.4.7", DepKind::Build, false),]),pkg!(("U5_ZbZ7c1_K-u-sys", "18.2.13") => [dep_req_kind("RSV_z6-s_OJHUQ2z-sys", "<=17.2.5", DepKind::Build, false),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", "<=9.19.1", DepKind::Build, false),dep_req_kind("T_", ">=3.3.3", DepKind::Build, false),]),pkg!(("U5_ZbZ7c1_K-u-sys", "19.4.6") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=9.8.1"),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "2.6.2") => [dep_req("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=16.16.1"),dep_req_kind("T_", ">=16.7.1", DepKind::Build, false),dep_req_kind("U5_ZbZ7c1_K-u-sys", ">=10.19.12, <=18.2.13", DepKind::Build, false),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "4.6.3") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "=8.17.1"),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12, <=15.11.19"),dep_req("SrYOB_H2G__pYll8_9Q---sys", "=9.19.1"),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "5.17.3") => [dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.0.8, <=8.17.1", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12"),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "11.9.2") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.18.19, <=15.0.4", DepKind::Build, false),dep_req("T_", ">=16.15.15"),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "11.19.10") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=4.13.11, <=14.9.2", DepKind::Build, false),dep("JtWi-_---z-sys"),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "12.8.4") => [dep_req("JtWi-_---z-sys", "<=8.8.13"),]),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "14.7.17")),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "14.19.19")),pkg!(("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "15.11.2") => [dep_req("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=16.16.1"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=6.3.4, <=15.11.19", DepKind::Build, false),]),pkg!(("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "4.1.4") => [dep_req("RSV_z6-s_OJHUQ2z-sys", ">=9.1.13, <=15.3.5"),]),pkg!(("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "11.6.19")),pkg!(("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "12.1.17") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=1.18.3, <=14.0.15"),]),pkg!(("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "15.13.1") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=8.14.2"),dep_req_kind("DZ-NA_W8C7-B__s__", "=18.16.2", DepKind::Build, false),dep_req("JtWi-_---z-sys", "<=0.18.15"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", "<=1.2.3", DepKind::Build, false),]),pkg!(("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "18.16.2") => [dep_req("JtWi-_---z-sys", ">=12.0.18, <=12.4.2"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=12.4.7, <=15.3.5", DepKind::Build, false),]),pkg!(("aYui-X86_c8-g", "0.9.14") => [dep_req_kind("A0NQ_d_0___e7-sys", "*", DepKind::Build, false),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.17.7, <=12.19.1"),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", "<=15.10.11", DepKind::Build, false),]),pkg!(("aYui-X86_c8-g", "0.10.16") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=16.14.16"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=3.16.0, <=15.0.4"),]),pkg!(("aYui-X86_c8-g", "5.1.17") => [dep_req_kind("A0NQ_d_0___e7-sys", "=9.1.0", DepKind::Build, false),dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=7.15.1, <=15.10.15", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=4.6.3, <=11.9.2"),]),pkg!(("aYui-X86_c8-g", "7.6.6") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.2, <=11.7.18"),]),pkg!(("aYui-X86_c8-g", "9.5.2") => [dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=11.9.2, <=12.8.4"),]),pkg!(("aYui-X86_c8-g", "9.6.13") => [dep_req("A0NQ_d_0___e7-sys", "<=9.1.0"),dep_req("JtWi-_---z-sys", ">=2.19.13"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=4.2.5", DepKind::Build, false),dep_req("T_", ">=14.11.6, <=15.5.17"),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=11.19.10"),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "=11.6.19", DepKind::Build, false),]),pkg!(("aYui-X86_c8-g", "11.8.8") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=14.19.3, <=18.16.2", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=14.0.15, <=14.3.15", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", "<=14.2.8"),]),pkg!(("aYui-X86_c8-g", "13.13.15") => [dep_req("MRI_y5Vek37_YSb_8-L-x-_-sys", "=16.16.1"),dep_req_kind("U5_ZbZ7c1_K-u-sys", "=13.6.18", DepKind::Build, false),]),pkg!(("aYui-X86_c8-g", "14.17.3") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.17.7"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", "<=7.15.1", DepKind::Build, false),dep_req("U5_ZbZ7c1_K-u-sys", "<=2.7.11"),]),pkg!(("aYui-X86_c8-g", "15.7.12") => [dep_req("JtWi-_---z-sys", ">=2.19.13, <=8.8.13"),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=1.18.3, <=2.9.4"),]),pkg!(("aYui-X86_c8-g", "19.16.13") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=13.12.13"),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.0.8, <=12.17.2", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.17.7, <=12.3.17", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=4.6.3, <=12.8.4"),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=11.6.19"),]),pkg!(("aYui-X86_c8-g", "19.19.17") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", "=2.0.5", DepKind::Build, false),dep_req("DZ-NA_W8C7-B__s__", ">=7.3.12, <=14.19.3"),dep_req_kind("JtWi-_---z-sys", ">=2.15.14", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=11.17.8", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=9.1.13, <=14.3.15", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "0.7.7") => [dep_req("A0NQ_d_0___e7-sys", "<=0.19.4"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=1.18.3, <=7.15.1", DepKind::Build, false),dep_req_kind("U5_ZbZ7c1_K-u-sys", ">=11.12.19, <=18.2.13", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "1.4.16") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=18.19.2", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=14.3.15, <=15.0.4", DepKind::Build, false),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=16.16.1", DepKind::Build, false),dep_req_kind("U5_ZbZ7c1_K-u-sys", "*", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", ">=7.6.6, <=11.8.8", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "2.6.6") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=2.12.15, <=15.0.4"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=1.18.3, <=9.19.1", DepKind::Build, false),dep_req("U5_ZbZ7c1_K-u-sys", ">=6.6.11, <=13.6.18"),]),pkg!(("eR_TVK_I_-J", "2.13.0") => [dep("bad"),]),pkg!(("eR_TVK_I_-J", "4.15.17") => [dep_req_kind("JtWi-_---z-sys", ">=2.19.13, <=12.4.2", DepKind::Build, false),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=15.13.1", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "9.13.2") => [dep_req_kind("T_", ">=19.10.6", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "9.19.13") => [dep_req_kind("T_", ">=0.19.19", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "10.1.4") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=9.1.0"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=4.16.14", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=9.19.1, <=12.18.17"),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "<=14.7.17", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "10.17.16") => [dep_req_kind("JtWi-_---z-sys", ">=12.4.2", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=1.18.3, <=12.18.19", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12, <=17.10.17", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "12.10.5") => [dep_req_kind("JtWi-_---z-sys", ">=6.8.16, <=8.8.13", DepKind::Build, false),dep_req("U5_ZbZ7c1_K-u-sys", ">=19.4.6"),dep_req("aYui-X86_c8-g", ">=11.8.8, <=13.13.15"),]),pkg!(("eR_TVK_I_-J", "13.13.4") => [dep_req("A0NQ_d_0___e7-sys", ">=1.5.19, <=10.5.3"),dep_req_kind("T_", "<=0.19.19", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "14.10.10") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=4.12.16, <=17.1.14", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.2, <=13.19.0"),]),pkg!(("eR_TVK_I_-J", "16.19.17") => [dep_req("DZ-NA_W8C7-B__s__", ">=7.3.12, <=17.1.14"),dep_req("JtWi-_---z-sys", ">=2.15.14, <=12.4.2"),dep_req("aYui-X86_c8-g", ">=5.1.17, <=9.5.2"),]),pkg!(("eR_TVK_I_-J", "17.10.1") => [dep_req("DZ-NA_W8C7-B__s__", "<=0.0.6"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=4.16.14, <=15.0.4"),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=15.3.5"),]),pkg!(("eR_TVK_I_-J", "18.3.11") => [dep_req_kind("JtWi-_---z-sys", ">=11.14.19, <=12.0.18", DepKind::Build, false),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "=13.19.0", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=14.7.17"),]),pkg!(("eR_TVK_I_-J", "18.9.1") => [dep_req_kind("JtWi-_---z-sys", ">=6.8.16, <=11.14.19", DepKind::Build, false),dep_req_kind("T_", ">=0.19.19, <=18.12.13", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", ">=13.13.15", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "18.13.3") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=4.16.14, <=5.17.7", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=8.10.19, <=13.15.12"),dep_req_kind("S7v_2R-6-_qb-R6U--sys", "<=11.13.7", DepKind::Build, false),]),pkg!(("eR_TVK_I_-J", "19.3.9") => [dep_req("RSV_z6-s_OJHUQ2z-sys", ">=17.10.17"),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=4.2.5, <=12.18.17"),]),pkg!(("g-R9E_nf__-sys", "0.12.3") => [dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=9.19.1, <=16.13.14", DepKind::Build, false),dep_req_kind("T_", ">=14.11.6, <=16.7.1", DepKind::Build, false),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=12.1.17"),dep_req("eR_TVK_I_-J", "<=9.13.2"),]),pkg!(("g-R9E_nf__-sys", "0.15.2")),pkg!(("g-R9E_nf__-sys", "3.11.10") => [dep_req_kind("A0NQ_d_0___e7-sys", "<=10.5.3", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", "<=2.10.5"),]),pkg!(("g-R9E_nf__-sys", "5.2.1") => [dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=12.18.17", DepKind::Build, false),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "<=14.7.17", DepKind::Build, false),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=11.6.19, <=15.13.1"),dep_req_kind("aYui-X86_c8-g", ">=13.13.15, <=14.17.3", DepKind::Build, false),dep_req("eR_TVK_I_-J", ">=13.13.4, <=16.19.17"),]),pkg!(("g-R9E_nf__-sys", "5.12.2") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.11.18, <=12.18.19", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=11.9.2, <=14.19.19"),]),pkg!(("g-R9E_nf__-sys", "7.5.15") => [dep_req_kind("A0NQ_d_0___e7-sys", "<=8.14.2", DepKind::Build, false),dep_req_kind("JtWi-_---z-sys", "=6.8.16", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=14.0.15, <=14.3.15", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=4.2.5, <=7.15.1"),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=5.17.3, <=11.9.2", DepKind::Build, false),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=15.13.1"),dep("eR_TVK_I_-J"),]),pkg!(("g-R9E_nf__-sys", "8.19.8") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=17.1.14, <=18.16.2", DepKind::Build, false),]),pkg!(("g-R9E_nf__-sys", "9.1.10") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=4.12.16, <=17.1.14", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=9.19.1, <=14.2.8"),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=11.6.19, <=15.13.1", DepKind::Build, false),dep_req("aYui-X86_c8-g", ">=9.5.2, <=11.8.8"),]),pkg!(("g-R9E_nf__-sys", "9.15.4") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", "<=8.15.7", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=11.7.18, <=13.19.0"),dep_req_kind("aYui-X86_c8-g", ">=11.8.8, <=14.17.3", DepKind::Build, false),dep_req_kind("eR_TVK_I_-J", ">=10.1.4, <=18.13.3", DepKind::Build, false),]),pkg!(("g-R9E_nf__-sys", "10.0.8") => [dep_req("DZ-NA_W8C7-B__s__", "<=17.1.14"),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=3.18.10, <=16.14.16"),dep_req("U5_ZbZ7c1_K-u-sys", ">=2.7.11, <=6.6.11"),dep_req("aYui-X86_c8-g", ">=14.17.3"),dep_req("eR_TVK_I_-J", ">=4.15.17, <=16.19.17"),]),pkg!(("g-R9E_nf__-sys", "10.6.2") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=4.8.13, <=13.12.13", DepKind::Build, false),dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=14.7.16, <=14.9.2", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=9.19.1"),]),pkg!(("g-R9E_nf__-sys", "11.10.7") => [dep_req("A0NQ_d_0___e7-sys", ">=4.8.13, <=8.14.2"),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.2, <=14.10.18", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", "=5.1.17", DepKind::Build, false),]),pkg!(("g-R9E_nf__-sys", "13.3.3") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=8.15.7"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=4.16.14", DepKind::Build, false),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=12.1.17", DepKind::Build, false),dep_req_kind("eR_TVK_I_-J", ">=2.13.0, <=4.15.17", DepKind::Build, false),]),pkg!(("g-R9E_nf__-sys", "14.15.5") => [dep_req_kind("JtWi-_---z-sys", "=2.15.14", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=16.14.16"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.11.18, <=11.17.8", DepKind::Build, false),dep_req_kind("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=15.10.11, <=16.16.1", DepKind::Build, false),dep_req("U5_ZbZ7c1_K-u-sys", "<=9.16.6"),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=11.9.2, <=14.7.17", DepKind::Build, false),]),pkg!(("g-R9E_nf__-sys", "16.11.6") => [dep_req("A0NQ_d_0___e7-sys", ">=1.5.19, <=8.14.2"),dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=12.6.12, <=14.9.2"),dep_req_kind("DZ-NA_W8C7-B__s__", "<=18.16.2", DepKind::Build, false),dep_req("S7v_2R-6-_qb-R6U--sys", "=11.13.7"),]),pkg!(("g-R9E_nf__-sys", "16.13.18") => [dep_req_kind("JtWi-_---z-sys", ">=0.18.15, <=12.4.2", DepKind::Build, false),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.19.1, <=14.3.15"),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=12.1.17"),]),pkg!(("g-R9E_nf__-sys", "16.16.16") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=9.1.0", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=1.18.3", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "=4.6.3"),dep_req("aYui-X86_c8-g", ">=11.8.8, <=19.16.13"),dep_req_kind("eR_TVK_I_-J", ">=9.19.13, <=14.10.10", DepKind::Build, false),]),pkg!(("g-R9E_nf__-sys", "16.18.9") => [dep_req("DZ-NA_W8C7-B__s__", ">=7.3.12"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=11.17.8, <=12.19.1"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=16.13.14", DepKind::Build, false),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "0.11.6") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=1.5.19"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=14.3.15, <=15.0.4", DepKind::Build, false),dep_req("eR_TVK_I_-J", ">=4.15.17, <=12.10.5"),dep_req_kind("g-R9E_nf__-sys", ">=0.15.2, <=16.13.18", DepKind::Build, false),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "1.19.14") => [dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=6.3.4, <=9.1.13", DepKind::Build, false),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=15.10.15, <=16.13.14", DepKind::Build, false),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "3.11.1") => [dep_req_kind("DZ-NA_W8C7-B__s__", "<=17.1.14", DepKind::Build, false),dep_req_kind("JtWi-_---z-sys", ">=0.18.15", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.0.8, <=13.19.0"),dep_req("aYui-X86_c8-g", ">=15.7.12, <=19.16.13"),dep_req_kind("g-R9E_nf__-sys", ">=5.12.2, <=7.5.15", DepKind::Build, false),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "4.6.10") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=1.5.19", DepKind::Build, false),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=8.0.2, <=9.19.1", DepKind::Build, false),dep_req("T_", ">=0.19.19, <=16.7.1"),dep_req("eR_TVK_I_-J", ">=9.13.2, <=10.17.16"),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "4.19.6") => [dep_req_kind("A0NQ_d_0___e7-sys", "=1.5.19", DepKind::Build, false),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=9.19.1", DepKind::Build, false),dep_req_kind("g-R9E_nf__-sys", "<=13.3.3", DepKind::Build, false),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "6.15.16") => [dep_req("JtWi-_---z-sys", ">=6.8.16"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "*", DepKind::Build, false),dep_req_kind("T_", ">=15.5.17", DepKind::Build, false),dep_req("aYui-X86_c8-g", ">=7.6.6, <=9.5.2"),dep_req("eR_TVK_I_-J", ">=2.6.6"),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "7.0.5") => [dep_req("T_", ">=0.19.19, <=15.5.17"),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "9.15.3") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4"),dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=4.13.11, <=8.15.7", DepKind::Build, false),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=12.17.2, <=16.14.16"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "=1.18.3"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12, <=15.11.19", DepKind::Build, false),dep_req("eR_TVK_I_-J", ">=9.19.13, <=12.10.5"),dep_req_kind("g-R9E_nf__-sys", ">=3.11.10, <=13.3.3", DepKind::Build, false),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "13.1.14") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=14.9.2", DepKind::Build, false),dep_req("JtWi-_---z-sys", "=11.14.19"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=4.2.5", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=12.8.4, <=14.19.19"),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=4.1.4", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", ">=13.13.15, <=19.16.13", DepKind::Build, false),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "13.9.13") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=9.1.0, <=13.12.13", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=9.1.13, <=17.2.5"),dep("T_"),]),pkg!(("o_i_P-bCR9KAN4O___FCe__NHCDDv", "13.14.3") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=12.17.2, <=16.14.16"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=1.18.14, <=9.1.13", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=1.18.3, <=14.2.8"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "0.17.7") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=8.14.2, <=9.1.0", DepKind::Build, false),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=2.12.15, <=14.0.15", DepKind::Build, false),dep_req("MRI_y5Vek37_YSb_8-L-x-_-sys", "<=4.7.1"),dep_req_kind("S7v_2R-6-_qb-R6U--sys", ">=10.7.5", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "2.11.1") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4"),dep_req_kind("DZ-NA_W8C7-B__s__", ">=7.3.12, <=17.1.14", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=15.10.15"),dep_req("eR_TVK_I_-J", "<=16.19.17"),dep_req("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=6.15.16"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "5.18.4") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=12.6.12", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12, <=15.3.5", DepKind::Build, false),dep_req("T_", ">=3.3.3, <=14.11.6"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "6.2.9") => [dep_req_kind("JtWi-_---z-sys", "=11.14.19", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=8.0.2, <=14.2.8"),dep_req_kind("T_", ">=16.15.15", DepKind::Build, false),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=4.1.4"),dep_req_kind("eR_TVK_I_-J", "<=18.3.11", DepKind::Build, false),dep_req_kind("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=9.15.3", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "6.3.17") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=3.18.10, <=16.14.16"),dep_req_kind("o_i_P-bCR9KAN4O___FCe__NHCDDv", "=1.19.14", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "6.12.3") => [dep_req_kind("eR_TVK_I_-J", ">=10.1.4", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "8.8.8") => [dep("bad"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "10.12.13") => [dep_req_kind("RSV_z6-s_OJHUQ2z-sys", "=15.11.19", DepKind::Build, false),dep_req("S7v_2R-6-_qb-R6U--sys", "<=12.6.14"),dep_req_kind("T_", ">=16.15.15, <=18.12.8", DepKind::Build, false),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=4.6.3"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "12.6.2") => [dep_req("T_", ">=3.3.3, <=15.5.17"),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "*", DepKind::Build, false),dep_req("aYui-X86_c8-g", ">=0.10.16, <=9.5.2"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "12.6.9") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.0.8, <=11.7.18"),dep_req_kind("U5_ZbZ7c1_K-u-sys", ">=6.6.11, <=11.12.19", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", "=9.6.13", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "12.16.15") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.18.19, <=14.3.15"),dep_req("U5_ZbZ7c1_K-u-sys", ">=11.12.19, <=13.6.18"),dep_req_kind("aYui-X86_c8-g", ">=5.1.17", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "12.19.6") => [dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=12.18.17, <=14.2.8"),dep_req("eR_TVK_I_-J", ">=4.15.17, <=13.13.4"),dep_req("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=4.6.10, <=13.1.14"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "15.4.9") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.6"),dep_req("U5_ZbZ7c1_K-u-sys", ">=6.6.11, <=13.6.18"),dep_req_kind("aYui-X86_c8-g", ">=14.17.3, <=15.7.12", DepKind::Build, false),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "15.14.4") => [dep_req("DZ-NA_W8C7-B__s__", ">=9.7.8"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.18.19, <=13.7.9"),dep_req("U5_ZbZ7c1_K-u-sys", ">=6.6.11, <=10.19.12"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "16.14.5") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.11.18, <=15.0.4"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=17.2.5, <=18.6.19", DepKind::Build, false),dep_req_kind("eR_TVK_I_-J", ">=9.13.2, <=18.3.11", DepKind::Build, false),dep_req("g-R9E_nf__-sys", ">=5.2.1, <=10.0.8"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "17.10.9") => [dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.17.1", DepKind::Build, false),dep_req("aYui-X86_c8-g", ">=9.5.2, <=15.7.12"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "18.7.14") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=9.8.1, <=14.7.16", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=19.12.3"),dep_req_kind("aYui-X86_c8-g", ">=5.1.17, <=11.8.8", DepKind::Build, false),dep_req("eR_TVK_I_-J", ">=10.1.4, <=14.10.10"),dep_req("o_i_P-bCR9KAN4O___FCe__NHCDDv", "<=4.19.6"),]),pkg!(("pY-bP___j3V_bgGkw-D4-sys", "18.16.16") => [dep_req("A0NQ_d_0___e7-sys", "=1.5.19"),dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=4.13.11, <=14.7.16"),dep_req_kind("JtWi-_---z-sys", ">=11.14.19", DepKind::Build, false),dep_req_kind("U5_ZbZ7c1_K-u-sys", ">=11.12.19, <=13.6.18", DepKind::Build, false),dep_req("aYui-X86_c8-g", ">=13.13.15"),dep_req("eR_TVK_I_-J", "<=9.19.13"),dep_req("g-R9E_nf__-sys", ">=11.10.7, <=16.11.6"),dep_req("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=3.11.1, <=13.9.13"),]),pkg!(("rZ7", "1.12.9") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=4.13.11", DepKind::Build, false),dep_req_kind("DZ-NA_W8C7-B__s__", ">=0.19.7, <=9.7.8", DepKind::Build, false),dep_req("aYui-X86_c8-g", "=9.6.13"),dep_req_kind("eR_TVK_I_-J", ">=2.13.0, <=14.10.10", DepKind::Build, false),dep_req("g-R9E_nf__-sys", ">=3.11.10, <=9.15.4"),]),pkg!(("rZ7", "2.17.12") => [dep_req("JtWi-_---z-sys", ">=2.19.13, <=6.8.16"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=13.15.12, <=17.2.5", DepKind::Build, false),dep_req("g-R9E_nf__-sys", ">=7.5.15, <=10.6.2"),]),pkg!(("rZ7", "9.11.17") => [dep_req_kind("DZ-NA_W8C7-B__s__", ">=4.12.16, <=17.1.14", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", "=19.16.13", DepKind::Build, false),]),pkg!(("rZ7", "15.6.14") => [dep_req("JtWi-_---z-sys", ">=6.8.16"),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=7.8.2"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=5.17.7"),dep_req("aYui-X86_c8-g", "<=5.1.17"),dep_req("eR_TVK_I_-J", "<=18.9.1"),]),pkg!(("rZ7", "15.7.17") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "=14.3.15"),dep_req_kind("S7v_2R-6-_qb-R6U--sys", "<=10.7.5", DepKind::Build, false),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=7.15.1, <=12.18.17", DepKind::Build, false),dep_req("U5_ZbZ7c1_K-u-sys", "=18.2.13"),dep_req_kind("g-R9E_nf__-sys", ">=5.2.1, <=9.1.10", DepKind::Build, false),]),pkg!(("rZ7", "16.10.16") => [dep_req("DZ-NA_W8C7-B__s__", ">=9.7.8, <=17.1.14"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.18.19, <=14.3.15", DepKind::Build, false),dep_req("aYui-X86_c8-g", ">=11.8.8, <=13.13.15"),dep_req("eR_TVK_I_-J", ">=12.10.5, <=18.3.11"),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", ">=12.16.15, <=12.19.6", DepKind::Build, false),]),pkg!(("rZ7", "19.7.8") => [dep_req("A0NQ_d_0___e7-sys", "=4.8.13"),dep_req_kind("DZ-NA_W8C7-B__s__", "=14.19.3", DepKind::Build, false),dep_req_kind("JtWi-_---z-sys", ">=2.15.14, <=11.14.19", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=1.18.14, <=2.10.5"),dep_req("T_", ">=0.19.19, <=15.5.17"),dep_req_kind("aYui-X86_c8-g", "=0.10.16", DepKind::Build, false),dep_req_kind("g-R9E_nf__-sys", ">=8.19.8, <=16.16.16", DepKind::Build, false),]),pkg!(("sP6-L-", "0.0.11") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=3.16.0, <=11.17.8", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", "<=13.15.12", DepKind::Build, false),dep_req_kind("S7v_2R-6-_qb-R6U--sys", ">=10.7.5", DepKind::Build, false),dep_req_kind("T_", "<=16.15.15", DepKind::Build, false),]),pkg!(("sP6-L-", "2.6.7") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4, <=13.12.13"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.17.7, <=14.3.15", DepKind::Build, false),dep_req_kind("o_i_P-bCR9KAN4O___FCe__NHCDDv", "=13.1.14", DepKind::Build, false),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", ">=12.19.6, <=17.10.9", DepKind::Build, false),]),pkg!(("sP6-L-", "4.12.4") => [dep_req("A0NQ_d_0___e7-sys", "<=8.14.2"),dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.17.1, <=12.17.2"),dep_req_kind("eR_TVK_I_-J", ">=16.19.17, <=18.9.1", DepKind::Build, false),dep_req("pY-bP___j3V_bgGkw-D4-sys", "=6.3.17"),]),pkg!(("sP6-L-", "6.7.11") => [dep_req("A0NQ_d_0___e7-sys", "<=8.14.2"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=14.3.15, <=15.0.4"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=6.3.4, <=18.6.19", DepKind::Build, false),dep_req_kind("S7v_2R-6-_qb-R6U--sys", "*", DepKind::Build, false),dep_req_kind("T_", "<=16.15.15", DepKind::Build, false),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "=15.13.1"),]),pkg!(("sP6-L-", "13.10.0") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=1.18.3, <=5.11.18"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=15.3.5, <=17.2.5", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", "<=16.13.14"),dep_req_kind("aYui-X86_c8-g", ">=0.10.16, <=11.8.8", DepKind::Build, false),dep_req("eR_TVK_I_-J", "<=10.17.16"),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", "=10.12.13", DepKind::Build, false),]),pkg!(("sP6-L-", "14.0.12") => [dep_req("JtWi-_---z-sys", "<=2.15.14"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=5.11.18"),dep_req("pY-bP___j3V_bgGkw-D4-sys", "=12.6.2"),]),pkg!(("sP6-L-", "17.11.15") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=4.13.11"),dep_req_kind("JtWi-_---z-sys", ">=11.14.19", DepKind::Build, false),dep_req_kind("S7v_2R-6-_qb-R6U--sys", ">=10.7.5", DepKind::Build, false),]),pkg!(("sP6-L-", "18.2.0") => [dep_req("DZ-NA_W8C7-B__s__", "=17.1.14"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=8.0.2, <=16.13.14", DepKind::Build, false),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=11.9.2, <=11.19.10", DepKind::Build, false),dep_req_kind("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=9.15.3, <=13.9.13", DepKind::Build, false),]),pkg!(("sP6-L-", "18.4.10") => [dep_req_kind("S7v_2R-6-_qb-R6U--sys", "<=11.13.7", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=12.18.17"),dep_req("g-R9E_nf__-sys", ">=14.15.5, <=16.11.6"),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", ">=6.12.3, <=12.19.6", DepKind::Build, false),]),pkg!(("sP6-L-", "19.7.7") => [dep_req_kind("T_", ">=3.3.3, <=15.5.17", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "0.10.7") => [dep_req_kind("T_", ">=16.7.1", DepKind::Build, false),dep_req("o_i_P-bCR9KAN4O___FCe__NHCDDv", "=13.1.14"),]),pkg!(("w_knohZMQB6u-sys", "0.16.11") => [dep_req("DZ-NA_W8C7-B__s__", ">=0.19.7"),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=8.17.1", DepKind::Build, false),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", "<=5.17.7"),dep_req("SrYOB_H2G__pYll8_9Q---sys", "<=7.15.1"),dep_req("eR_TVK_I_-J", ">=1.4.16, <=16.19.17"),]),pkg!(("w_knohZMQB6u-sys", "2.11.11") => [dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=8.0.8", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", "<=12.4.7", DepKind::Build, false),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=12.1.17", DepKind::Build, false),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", ">=5.18.4, <=12.19.6", DepKind::Build, false),dep_req_kind("sP6-L-", "=4.12.4", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "4.14.12") => [dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.18.19, <=14.0.15"),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=14.3.15, <=17.10.17"),dep_req_kind("aYui-X86_c8-g", ">=9.5.2, <=11.8.8", DepKind::Build, false),dep_req("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=4.6.10, <=6.15.16"),dep_req("pY-bP___j3V_bgGkw-D4-sys", ">=12.16.15"),dep_req_kind("rZ7", ">=15.6.14, <=16.10.16", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "6.7.10") => [dep_req("A0NQ_d_0___e7-sys", "<=13.12.13"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.3.17, <=15.0.4", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=15.3.5, <=17.10.17"),dep_req_kind("S7v_2R-6-_qb-R6U--sys", ">=13.10.15", DepKind::Build, false),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=4.2.5", DepKind::Build, false),dep_req_kind("U5_ZbZ7c1_K-u-sys", ">=11.12.19", DepKind::Build, false),dep_req_kind("o_i_P-bCR9KAN4O___FCe__NHCDDv", "<=1.19.14", DepKind::Build, false),dep_req("pY-bP___j3V_bgGkw-D4-sys", "<=2.11.1"),]),pkg!(("w_knohZMQB6u-sys", "7.0.13") => [dep_req("S7v_2R-6-_qb-R6U--sys", ">=11.13.7"),dep_req("U5_ZbZ7c1_K-u-sys", ">=10.19.12"),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=12.1.17", DepKind::Build, false),dep_req_kind("eR_TVK_I_-J", "<=0.7.7", DepKind::Build, false),dep_req_kind("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=1.19.14, <=4.19.6", DepKind::Build, false),dep_req("pY-bP___j3V_bgGkw-D4-sys", ">=12.19.6"),]),pkg!(("w_knohZMQB6u-sys", "9.2.0") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=2.0.5, <=14.9.2", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", "<=1.18.14", DepKind::Build, false),dep_req_kind("T_", ">=15.5.17, <=18.12.8", DepKind::Build, false),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=11.19.10", DepKind::Build, false),dep_req("aYui-X86_c8-g", ">=9.5.2, <=19.16.13"),dep_req("g-R9E_nf__-sys", ">=5.12.2, <=9.15.4"),dep_req("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=4.19.6, <=9.15.3"),]),pkg!(("w_knohZMQB6u-sys", "9.14.13") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.19.1, <=15.0.4", DepKind::Build, false),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=4.2.5, <=12.18.17"),dep_req("T_", ">=18.12.8"),dep_req("sP6-L-", ">=4.12.4, <=18.2.0"),]),pkg!(("w_knohZMQB6u-sys", "11.6.13") => [dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=11.6.19, <=15.13.1", DepKind::Build, false),dep_req("eR_TVK_I_-J", ">=16.19.17, <=17.10.1"),dep_req("g-R9E_nf__-sys", ">=3.11.10, <=5.2.1"),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", ">=12.19.6, <=17.10.9", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "11.16.8") => [dep_req("B-30LKxtEB___gt1x-u-o--sys", ">=9.8.1"),dep_req_kind("DZ-NA_W8C7-B__s__", "=17.1.14", DepKind::Build, false),dep_req_kind("aYui-X86_c8-g", ">=14.17.3, <=19.16.13", DepKind::Build, false),dep_req("g-R9E_nf__-sys", ">=10.0.8"),dep_req_kind("sP6-L-", ">=14.0.12, <=17.11.15", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "13.2.18") => [dep_req("A0NQ_d_0___e7-sys", ">=4.8.13"),dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", "<=4.13.11", DepKind::Build, false),dep_req("DZ-NA_W8C7-B__s__", ">=7.3.12, <=18.16.2"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12, <=17.2.5", DepKind::Build, false),dep_req("S7v_2R-6-_qb-R6U--sys", ">=11.13.7"),dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=12.8.4, <=14.7.17"),dep_req_kind("eR_TVK_I_-J", ">=2.13.0, <=18.9.1", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "14.13.9") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=8.17.1, <=16.14.16"),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12, <=12.4.7", DepKind::Build, false),dep_req_kind("T_", ">=15.5.17", DepKind::Build, false),dep_req("U5_ZbZ7c1_K-u-sys", ">=2.7.11, <=11.12.19"),]),pkg!(("w_knohZMQB6u-sys", "15.7.11") => [dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.6", DepKind::Build, false),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=2.9.4, <=15.10.15", DepKind::Build, false),dep_req_kind("T_", "<=0.19.19", DepKind::Build, false),dep_req("eR_TVK_I_-J", "=13.13.4"),dep_req_kind("g-R9E_nf__-sys", ">=9.1.10, <=16.13.18", DepKind::Build, false),dep_req_kind("rZ7", "=15.7.17", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "15.16.15") => [dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.18.19, <=15.0.4", DepKind::Build, false),dep_req_kind("T_", "<=0.19.19", DepKind::Build, false),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=11.6.19"),dep_req_kind("aYui-X86_c8-g", ">=11.8.8", DepKind::Build, false),dep_req("g-R9E_nf__-sys", ">=16.13.18"),]),pkg!(("w_knohZMQB6u-sys", "16.15.13") => [dep_req_kind("B-30LKxtEB___gt1x-u-o--sys", ">=4.13.11", DepKind::Build, false),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=15.0.4"),dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=14.2.8, <=15.10.15"),dep_req("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", ">=11.6.19"),dep_req("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=6.15.16, <=7.0.5"),]),pkg!(("w_knohZMQB6u-sys", "17.8.1") => [dep_req_kind("A0NQ_d_0___e7-sys", ">=8.14.2, <=10.5.3", DepKind::Build, false),dep_req("DZ-NA_W8C7-B__s__", ">=7.3.12"),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", ">=7.8.6, <=8.17.1", DepKind::Build, false),dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=2.0.12", DepKind::Build, false),dep_req_kind("T_", ">=14.11.6, <=18.12.8", DepKind::Build, false),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", "=14.19.19", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "18.0.13") => [dep_req_kind("RSV_z6-s_OJHUQ2z-sys", ">=6.3.4, <=17.2.5", DepKind::Build, false),dep_req("eR_TVK_I_-J", ">=2.13.0, <=9.13.2"),dep_req_kind("g-R9E_nf__-sys", ">=0.15.2, <=7.5.15", DepKind::Build, false),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", "<=15.4.9", DepKind::Build, false),]),pkg!(("w_knohZMQB6u-sys", "18.8.1") => [dep_req("SrYOB_H2G__pYll8_9Q---sys", ">=16.13.14, <=19.12.3"),dep_req("g-R9E_nf__-sys", ">=9.15.4, <=16.13.18"),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", "=8.8.8", DepKind::Build, false),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "2.18.7") => [dep_req("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=14.7.17, <=14.19.19"),dep_req_kind("g-R9E_nf__-sys", "=11.10.7", DepKind::Build, false),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "4.10.11") => [dep_req("A0NQ_d_0___e7-sys", ">=1.5.19, <=8.14.2"),dep_req_kind("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "*", DepKind::Build, false),dep_req("aYui-X86_c8-g", "<=0.10.16"),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", ">=12.6.2, <=15.14.4", DepKind::Build, false),dep_req_kind("rZ7", ">=9.11.17", DepKind::Build, false),dep_req("w_knohZMQB6u-sys", "=13.2.18"),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "4.14.19") => [dep_req("DZ-NA_W8C7-B__s__", ">=0.19.7, <=4.12.16"),dep_req("RSV_z6-s_OJHUQ2z-sys", "<=14.3.15"),dep_req("S7v_2R-6-_qb-R6U--sys", ">=11.13.7, <=12.6.14"),dep_req("g-R9E_nf__-sys", ">=9.1.10, <=10.0.8"),dep_req_kind("o_i_P-bCR9KAN4O___FCe__NHCDDv", ">=3.11.1, <=13.1.14", DepKind::Build, false),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "5.2.13") => [dep_req("A0NQ_d_0___e7-sys", ">=0.19.4"),dep_req_kind("JtWi-_---z-sys", ">=6.8.16, <=12.4.2", DepKind::Build, false),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=16.13.14, <=19.12.3", DepKind::Build, false),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "6.13.10") => [dep_req_kind("T_", "<=18.12.8", DepKind::Build, false),dep_req("aYui-X86_c8-g", ">=0.10.16, <=9.5.2"),dep_req("rZ7", ">=15.6.14, <=15.7.17"),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "7.18.5") => [dep_req("JtWi-_---z-sys", ">=2.15.14"),dep_req("MRI_y5Vek37_YSb_8-L-x-_-sys", ">=15.10.11, <=16.16.1"),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=14.19.19", DepKind::Build, false),dep_req_kind("eR_TVK_I_-J", ">=9.19.13, <=12.10.5", DepKind::Build, false),dep_req_kind("g-R9E_nf__-sys", ">=8.19.8, <=16.16.16", DepKind::Build, false),dep_req("sP6-L-", "<=4.12.4"),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "8.6.15") => [dep_req_kind("A0NQ_d_0___e7-sys", "=9.1.0", DepKind::Build, false),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=1.18.3, <=14.3.15"),dep_req_kind("w_knohZMQB6u-sys", ">=11.6.13, <=11.16.8", DepKind::Build, false),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "10.10.7") => [dep_req("A0NQ_d_0___e7-sys", ">=4.8.13, <=9.1.0"),dep_req("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.3.17, <=13.7.9"),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "<=15.13.1", DepKind::Build, false),dep_req("sP6-L-", "<=18.2.0"),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "10.18.1") => [dep_req("RSV_z6-s_OJHUQ2z-sys", ">=8.10.19"),dep_req("eR_TVK_I_-J", ">=14.10.10"),dep_req_kind("w_knohZMQB6u-sys", "=18.0.13", DepKind::Build, false),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "11.19.4") => [dep_req("RSV_z6-s_OJHUQ2z-sys", ">=15.3.5, <=17.10.17"),dep_req_kind("SrYOB_H2G__pYll8_9Q---sys", ">=1.18.3", DepKind::Build, false),dep_req("T_", ">=15.5.17, <=16.7.1"),dep_req_kind("V5VB-_8mpO_D-9e--FbsWQ_9OzVb-2-sys", ">=11.19.10", DepKind::Build, false),dep_req_kind("g-R9E_nf__-sys", ">=7.5.15, <=14.15.5", DepKind::Build, false),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", "=2.11.1", DepKind::Build, false),dep_req("w_knohZMQB6u-sys", ">=11.16.8"),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "12.3.14") => [dep_req("Kt_HQQ-mI2a_UJ5Fm-En5693-8n_-aP-sys", "<=11.7.18"),dep_req_kind("LsT_aR_s_FT0_ZDw7F_i-K8I_Lu_-sys", ">=12.3.17, <=14.0.15", DepKind::Build, false),dep_req("RSV_z6-s_OJHUQ2z-sys", ">=15.11.19, <=17.10.17"),dep_req_kind("W-0gH-Ps0rs20Pk96-Y-Izs_P6_--sys", "=15.13.1", DepKind::Build, false),dep_req("aYui-X86_c8-g", ">=5.1.17, <=7.6.6"),dep_req("eR_TVK_I_-J", ">=14.10.10"),dep_req("g-R9E_nf__-sys", ">=11.10.7"),dep_req_kind("pY-bP___j3V_bgGkw-D4-sys", ">=6.12.3, <=12.6.2", DepKind::Build, false),dep_req("sP6-L-", ">=19.7.7"),]),pkg!(("wc47-nzseKD8_tOGg_h_k-_FT-zYR--sys", "19.5.5") => [dep_req_kind("JtWi-_---z-sys", ">=0.18.15, <=6.8.16", DepKind::Build, false),dep_req_kind("g-R9E_nf__-sys", ">=8.19.8", DepKind::Build, false),dep_req_kind("rZ7", ">=2.17.12", DepKind::Build, false),]),]
2024-11-21T20:12:17.9072932Z 	successes: 144
2024-11-21T20:12:17.9073239Z 	local rejects: 0
2024-11-21T20:12:17.9073572Z 	global rejects: 0
```

**Comment by cbiffle** [comment]
FWIW, I *think* this should resolve an issue in the Hubris build system. Currently we bypass Cargo's dirtiness checks for building deps in certain circumstances (to get maximum reuse of objects despite small controlled changes to `RUSTFLAGS`), and pay for our sins by doing a total clean when changing between firmware images. This should make the dirtiness check smart enough for our purposes so that we could stop doing both of those things.

Haven't tested it yet though.

File: src/cargo/core/compiler/fingerprint/mod.rs [hunk 1]
```diff
@@ -83,7 +83,7 @@
 //! Target flags (test/bench/for_host/edition) | ✓           |                     |                        |
 //! -C incremental=… flag                      | ✓           |                     |                        |
 //! mtime of sources                           | ✓[^3]       |                     |                        |
-//! RUSTFLAGS/RUSTDOCFLAGS                     | ✓           |                     |                        |
```
Comment (weihanglo) [inline src/cargo/core/compiler/fingerprint/mod.rs]: Seems like `unit_id` is generally the same as `c_extra_filename` at this moment. Do we anticipate in anything in the future of separating them? I think it worth some docs for future us and contributors.

File: src/cargo/core/compiler/build_runner/compilation_files.rs
Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:1]: Resolved via <https://github.com/rust-lang/cargo/pull/14846>

File: src/cargo/core/compiler/build_runner/compilation_files.rs [hunk 2]
```diff
@@ -677,12 +676,45 @@ fn compute_metadata(
...
+    // Mix in the target-metadata of all the dependencies of this target.
+    let mut dep_c_extra_filename_hashes = deps_metadata
+        .iter()
+        .map(|m| m.c_extra_filename)
+        .collect::<Vec<_>>();
+    dep_c_extra_filename_hashes.sort();
+    dep_c_extra_filename_hashes.hash(&mut c_extra_filename_hasher);
+    // Avoid trashing the caches on RUSTFLAGS changing via `c_extra_filename`
+    //
+    // Limited to `c_extra_filename` to help with reproducible build / PGO issues.
```
Comment (weihanglo) [inline src/cargo/core/compiler/build_runner/compilation_files.rs:701]: > This should (probably) avoid the PGO problems, since the symbols won't change. However, this could still cause problems with reproducible builds if the rlib filename somehow leaks into the resulting binary (I don't have a reason to think it does, but it seems risky).

> I believe this does because the filenames of object files show up as the codegen unit names in dwarf debug info (and probably PDB?). I suspect that everything else in the binary will be the same, but builds differing only in extra-filename are likely to still produce different binaries.

Have we checked if it doesn't affect PGO?
We would like to check if anything is leaking rlib filename in debug info files.

Comment (epage) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:701]: Any idea how to go about that?  I have no experience with PGO and we have no tests focusing on it.

Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:705]: I'll do some experiments this week and see if we can have tests written down!

Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:705]: Posted https://github.com/rust-lang/cargo/pull/14859

Comment (epage) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:705]: The test passes with this PR for me

Comment (epage) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:705]: For most rustflags, changing them changes the binary anyway. Remap is special in that it takes a build-specific value and removes it, making builds more reproducible.

Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:705]: Do you suggest that we consider `--remap-path-refix` case as unsupported?

Comment (epage) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:705]: ... we generate debug files per code-gen unit?  Yikes

This isn't present for `cargo b --config 'profile.dev.strip="debuginfo"'` but I assume that is not a relevant case for build reproducibility folks.  Are `dwp` files considered important for those cases?

Anyways, some options for moving this forward
- Move forward as-is, requiring build-reproducibility people to use the unstable feature
- Block until the unstable feature is stable
- Parse rustc flags enough to ignore `--remap-path-prefix`, like #6966
- Assume even less knowledge of rustc flags and don't include RUSTFLAGS in `-Cextra-filename` if `--remap-path-prefix` is present, meaning people using it don't get this benefit but most people will get the benefit

Thoughts?

Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:705]: @epage the conclusion from Monday's meeting is that we're going to reintroduce #6966 along with this PR, right?

Comment (epage) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:705]: In the meeting notes, it says we were going to move forward with the hack where we conditionally add RUSTFLAGS to `-Cextra-filename`

Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:705]: Thanks. I am forgetting things more often recently…
Given that, this PR is ready to go!

**Review by weihanglo — APPROVED** [review]

File: src/cargo/core/compiler/build_runner/compilation_files.rs (hunk 2 above)
Comment (epage) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:705]: I removed this from the queue as I'd like to add that hack before this gets merged so we don't accidentally break people.

Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:705]: > Will move forward with ed's hack.


I am confused by the meeting note. I assumed Ed's hack is this PR. The “hack” you are going to add is #6966, no?

Comment (epage) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:705]: #6966 filters out `--remap-path-prefix` from being hashed.

The hack I proposed is that we skip hashing *all* RUSTFLAGS if something that looks like `--remap-path-prefix` is present.

**Review by weihanglo — APPROVED** [review]
Thanks!

**Comment by weihanglo** [comment]
```
---- build::cargo_compile_with_nested_deps_longhand stdout ----
running `D:\a\cargo\cargo\target\debug\cargo.exe build`
thread 'build::cargo_compile_with_nested_deps_longhand' panicked at tests\testsuite\build.rs:1236:22:

test failed running `D:\a\cargo\cargo\target\debug\cargo.exe build`
error: process exited with code 101 (expected 0)
--- stdout

--- stderr
warning: path `src\foo.rs` was erroneously implicitly accepted for binary `foo`,
please set bin.path in Cargo.toml
warning: unused manifest key: dependencies.bar.edition
     Locking 2 packages to latest compatible versions
   Compiling baz v0.5.0 (D:\a\cargo\cargo\target\tmp\cit\t332\foo\baz)
   Compiling bar v0.5.0 (D:\a\cargo\cargo\target\tmp\cit\t332\foo\bar)
error: couldn't create a temp dir: Access is denied. (os error 5) at path "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\rustcs1AZlH"
```

Doesn't seem relevant. Re-queue it.
