### PR TITLE
fix(job_queue): Handle Clippy CLI arguments in `fix` message

### LINKED ISSUE #16637: Include CLI lints on `cargo fix` suggestions when running Clippy
### Problem

cc https://github.com/rust-lang/rust-clippy/issues/16547

On Clippy lints can be enabled via the command line via `cargo clippy -- -Wclippy::lint`, and these need to be included in the `cargo fix` for the emitting lints to actually be fixed.

### Steps

If I have some code that raises an allow-by-default lint:
```rs
fn foo(s: &str) {
    dbg!(s); // would raise `dbg_macro`
}
```
and run Clippy with that lint explicitly enabled:
```
cargo clippy -- -W clippy::dbg_macro
```
then I get the following output:
```
warning: the `dbg!` macro is intended as a debugging tool
 --> src/main.rs:3:5
  |
3 |     dbg!(s);
  |     ^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html#dbg_macro
  = note: requested on the command line with `-W clippy::dbg-macro`
help: remove the invocation before committing it to a version control system
  |
3 -     dbg!(s);
3 +     s;
  |

warning: `tst` (bin "tst") generated 1 warning (run `cargo clippy --fix --bin "tst" -p tst` to apply 1 suggestion)
```
but running the suggested command (`cargo clippy --fix --bin "tst" -p tst`) won't _actually_ apply the suggestion, as Clippy won't even think about linting on `dbg!()` -- what's needed is `cargo clippy --fix --bin "tst" -p tst -- -W clippy::dbg_macro`

### Possible Solution(s)

_No response_

### Notes

The relevant code is in `src/cargo/core/compiler/job_queue/mod.rs:1085~1112`.

### Version

```text
cargo 1.93.0-nightly (636800288 2025-10-31)
release: 1.93.0-nightly
commit-hash: 6368002885a04cbeae39a82cf5118f941559a40a
commit-date: 2025-10-31
host: x86_64-unknown-linux-gnu
libgit2: 1.9.1 (sys:0.20.2 vendored)
libcurl: 8.15.0-DEV (sys:0.4.83+curl-8.15.0 vendored ssl:OpenSSL/3.5.4)
ssl: OpenSSL 3.5.4 30 Sep 2025
os: Garuda Linux Soaring (Broadwing) [64-bit]
```

### PR DESCRIPTION
**Pull request by blyxyas**
fixes #16637

### What does this PR try to resolve?

Clippy lints can be enabled via the command line via `cargo clippy -- -Wclippy::lint`, and these need to be included in the `cargo fix` command (because if a lint is not emitted, it's not fixed, and some lints are allow-by-default)

---

When `cargo clippy` is executed, Clippy sets the env. var `CLIPPY_ARGS` to the arguments that were passed to Clippy, separated by the string `__CLIPPY_HACKERY__`. To avoid breaking behaviour in between runs (like in `fix`), we should maintain those arguments.

This PR takes that `CLIPPY_ARGS` env var (if it exists), replaces the `__CLIPPY_HACKERY__` separator and appends it to the suggested `cargo clippy --fix` command when emitting fixable warnings.

### How to test and review this PR?

Via copying a crate (in my case, `tokio-1.38.1`) and executing the following commands:

```bash
rustup run nightly ~/git/cargo/target/debug/cargo clippy -- -Wclippy::pedantic -Aclippy::allow_attributes -Wclippy::dbg_macro -Wclippy::eq_op
```

In order to get some warnings. If any fixable warning is emitted, the output message should end with:

```text
warning: `tokio` (lib) generated 42 warnings (run `cargo clippy --fix --lib -p tokio -- -Wclippy::pedantic -Aclippy::allow_attributes -Wclippy::dbg_macro -Wclippy::eq_op` to apply 16 suggestions)
```

Now, testing with the suggested command (in this case, also with the version pinned @1.38.1):

```bash
rustup run nightly ~/git/cargo/target/debug/cargo clippy --fix --lib -p tokio@1.38.1 -- -Wclippy::pedantic -Aclippy::allow_attributes -Wclippy::dbg_macro -Wclippy::eq_op
```

All warnings (including those allow-by-default `pedantic` lints!) should be fixed now.

### CODE REVIEW

File: src/cargo/core/compiler/job_queue/mod.rs [hunk 1]
```diff
@@ -1105,9 +1105,18 @@ impl<'gctx> DrainState<'gctx> {
                     if fixable > 1 {
                         suggestions.push_str("s")
                     }
+
                     let _ = write!(
                         message,
-                        " (run `{command} --{args}` to apply {suggestions})"
+                        " (run `{command} --{args}{}` to apply {suggestions})",
```
Comment (epage) [inline src/cargo/core/compiler/job_queue/mod.rs:1116]: We generally expect tests to be written for changes.

`check_fixable_warning_for_clippy` is an existing test you can use as scaffolding for the test for this.

We also [ask](https://doc.crates.io/contrib/process/working-on-cargo.html#submitting-a-pull-request) that when adding tests, add them in the commit before the feature/fix, *with them passing*, showing the existing behavior.  The feature/fix commit would then update the tests to show the new behavior.  This helps with showing the tests are testing the right thing *and* makes it very clear how behavior changed.

File: src/cargo/core/compiler/job_queue/mod.rs [hunk 2]
```diff
@@ -1105,9 +1105,18 @@ impl<'gctx> DrainState<'gctx> {
...
+                        if let Ok(cli_lints) = gctx.get_env("CLIPPY_ARGS") {
```
Comment (epage) [inline src/cargo/core/compiler/job_queue/mod.rs]: The reason cargo lints you away from using `std::env::var_os` is that we want to load environment variables in a way that use our config system.  As our config system does not apply to this, we should probably use `std::env::var_os` directly and have an `#[expect(..., reason = ...)]` on it.  You'll find many examples of this, usually with reasons along the lines of "consistent behavior with upstream".

Comment (epage) [inline src/cargo/core/compiler/job_queue/mod.rs]: Should we also gate this by the above which for if clippy is active?

File: src/cargo/core/compiler/job_queue/mod.rs [hunk 3]
```diff
@@ -1105,9 +1105,18 @@ impl<'gctx> DrainState<'gctx> {
...
+                            // Clippy can take lints through the CLI, each lint flag is separated by "__CLIPPY_HACKER__".
```
Comment (epage) [inline src/cargo/core/compiler/job_queue/mod.rs]:
```suggestion
                            // Clippy can take lints through the CLI, each lint flag is separated by `__CLIPPY_HACKERY__`.
```

**Comment by epage** [comment]
Thanks!

File: src/cargo/core/compiler/job_queue/mod.rs (hunk 2 above)
Comment (blyxyas) [reply src/cargo/core/compiler/job_queue/mod.rs]: We shouldn't, allowing more flexibility by the user in weird workflows (and doesn't hurt for the average user, as nothing that isn't Clippy sets the environment var.).

Also, we use this in our `lintcheck` tool, and we'd prefer to avoid breakage in that.

Comment (epage) [reply src/cargo/core/compiler/job_queue/mod.rs]: I'm not sure I understand the reasons you gave and weird workflows was in fact one of the concerns I had
- I assume that we should suggest `cargo clippy --fix` and append `CLIPPY_ARGS` together rather than having situations where we show one or the other
- There can be weird cases with nested cargo's, like a build script calling cargo, where `CLIPPY_ARGS` might still be present but isn't relevant to the current command

Comment (blyxyas) [reply src/cargo/core/compiler/job_queue/mod.rs]: I was thinking about checking for the executable name (which would disable us from testing), so I didn't think of using `rustc_workspace_wrapper` in line `mod.rs:1092`

Yeah, we can use it, and it wouldn't break tests.

**Comment by blyxyas** [comment]
Sorry for so much force-pushing, but the commit reordering seems to have messed up the git history, so I had to rebase.

File: src/cargo/core/compiler/job_queue/mod.rs [hunk 4]
```diff
@@ -1089,11 +1089,11 @@ impl<'gctx> DrainState<'gctx> {
...
-                    let command = match rustc_workspace_wrapper.as_ref().and_then(|x| x.file_stem())
-                    {
-                        Some(wrapper) if wrapper == clippy => "cargo clippy --fix",
-                        _ => "cargo fix",
-                    };
+                    let (clippy_invocation, command) =
+                        match rustc_workspace_wrapper.as_ref().and_then(|x| x.file_stem()) {
+                            Some(wrapper) if wrapper == clippy => (true, "cargo clippy --fix"),
+                            _ => (false, "cargo fix"),
+                        };
```
Comment (epage) [inline src/cargo/core/compiler/job_queue/mod.rs]: Wouldn't this be simpler / easier to read if checking if its clippy is decoupled from getting the command:
```rust
let is_clippy = matches!(rustc_workspace_wrapper.as_ref().and_then(|x| x.file_stem()), Some(wrapper) if wrapper == clippy);

let command = if is_clippy {
    "cargo clippy --fix"
} else {
    "cargo fix"
};
```

File: src/cargo/core/compiler/job_queue/mod.rs
Comment (epage) [inline src/cargo/core/compiler/job_queue/mod.rs:1]: We generally ask that commits reflect how the PR should be reviewed and merged.  This seems more about how it was developed (a change to how a previous commit works) and should be squashed.

Mostly mentioning since there was already other feedback,

**Review by epage — APPROVED** [review]
Thanks!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16652/3ca292befbc3585084922c1592ea3d17e423f035..4e786ef0e52e251c7cd740f7835a02783d522e2a)*
