### PR TITLE
fix: env table config can't trigger rebuild with `rerun-if-env-changed`.

### LINKED ISSUE #10358: `cargo:rerun-if-env-changed` doesn't work with `env` configuration
### Problem

When a `build.rs` script emits `cargo:rerun-if-env-changed`, it is not re-run when the value of the specified variable is changed via the `env` configuration.

### Steps

`build.rs`:
```rust
pub fn main() {
    println!("cargo:rerun-if-env-changed=FOO");
    if let Ok(foo) = std::env::var("FOO") {
        assert!(&foo != "bad");
    }
}
```

`.cargo/config.toml`:
```toml
[env]
FOO = "good"
```

1. Run `cargo build`, it succeeds.
2. Change `.cargo/config.toml` to this:
```toml
[env]
FOO = "bad"
```
3. Run `cargo build` again, and it uses the cached build and succeeds. It should run `build.rs` again, and it should fail.

# Workaround

4. Run `FOO=bar cargo build`, ignore the result.
5. Run `cargo build` again, now it runs `build.rs` with `FOO=bad` from the config and fails as expected.

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
cargo 1.58.0 (7f08ace4f 2021-11-24)
release: 1.58.0
commit-hash: 7f08ace4f1305de7f3b1b0e2f765911957226bd4
commit-date: 2021-11-24
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Debian 11 (bullseye) [64-bit]
```

### PR DESCRIPTION
**Pull request by linyihai**
### What does this PR try to resolve?

As #10358 said, `When a build.rs script emits cargo:rerun-if-env-changed, it is not re-run when the value of the specified variable is changed via the env configuration.`  

Fixes #10358 

### How should we test and review this PR?
Add test bofore fixing to reflect the issue, the next commit fixed it.

### Additional information

The PR is a sucessor of https://github.com/rust-lang/cargo/pull/14058, so the previous dicussion can be refer to it.

### CODE REVIEW

File: src/cargo/core/compiler/fingerprint/mod.rs [hunk 1]
```diff
@@ -376,6 +377,7 @@ use anyhow::format_err;
 use anyhow::Context as _;
 use cargo_util::paths;
 use filetime::FileTime;
+use lazycell::LazyCell;
```
Comment (epage) [inline src/cargo/core/compiler/fingerprint/mod.rs:380]: imo we should not be adding any new uses of lazycell but should instead be trying to remove it in favor of OnceCell

File: src/cargo/core/compiler/fingerprint/mod.rs [hunk 2]
```diff
@@ -796,14 +798,36 @@ pub enum StaleItem {
...
+        env_config: &Arc<HashMap<String, OsString>>,
+        env_config_insensitive: &Arc<LazyCell<HashMap<String, OsString>>>,
+    ) -> LocalFingerprint {
         let key = key.as_ref();
         let var = key.to_owned();
-        let val = env::var(key).ok();
+        let val = if let Some(val) = env::var(key).ok() {
+            Some(val)
+        } else {
+            match env_config.get(key) {
```
Comment (epage) [inline src/cargo/core/compiler/fingerprint/mod.rs:812]: which is supposed to have higher precedence?

File: src/cargo/core/compiler/fingerprint/mod.rs [hunk 3]
```diff
@@ -1701,6 +1725,7 @@ fn build_script_local_fingerprints(
     // obvious.
     let pkg_root = unit.pkg.root().to_path_buf();
     let target_dir = target_root(build_runner);
+    let env_config = Arc::clone(build_runner.bcx.gctx.env_config().unwrap());
```
Comment (epage) [inline src/cargo/core/compiler/fingerprint/mod.rs:1728]: Whats the assumption we are operating under that its safe to `unwrap`?

File: src/cargo/core/compiler/fingerprint/mod.rs [hunk 4]
```diff
@@ -796,14 +798,36 @@ pub enum StaleItem {
...
+                    if cfg!(windows) {
+                        env_config_insensitive
+                            .borrow_with(|| {
+                                env_config
+                                    .iter()
+                                    .map(|(k, v)| (k.to_uppercase().clone(), v.clone()))
+                                    .collect::<HashMap<String, OsString>>()
+                            })
+                            .get(&key.to_uppercase())
+                            .and_then(|s| s.to_str().map(|s| s.to_string()))
```
Comment (epage) [inline src/cargo/core/compiler/fingerprint/mod.rs:824]: Please use a more specific conversion than `to_string` as it can mask incidental semantic conversions

File: src/cargo/core/compiler/fingerprint/mod.rs [hunk 5]
```diff
@@ -796,14 +798,36 @@ pub enum StaleItem {
...
         let var = key.to_owned();
-        let val = env::var(key).ok();
+        let val = if let Some(val) = env::var(key).ok() {
+            Some(val)
+        } else {
+            match env_config.get(key) {
+                Some(value) => value.to_str().map(|s| s.to_string()),
+                None => {
+                    if cfg!(windows) {
+                        env_config_insensitive
```
Comment (epage) [inline src/cargo/core/compiler/fingerprint/mod.rs:816]: Rather than having to do all of this extra work, I wonder if we should make the env map itself case insensitive.  Looking at how `env_config()` is used, I think we have several places where we don't handle case sensitivity and maybe we should?

What we could do is define a type def for `EnvMap` where the key is `unicase::Ascii<String>` and have the global context return that.

@weihanglo thoughts?

Comment (weihanglo) [reply src/cargo/core/compiler/fingerprint/mod.rs:816]: That should be conditioned on platform, maybe only on Windows?

Cargo does that upfront for environment variables from configuration enviornment: https://github.com/rust-lang/cargo/blob/master/src/cargo/util/context/environment.rs

Comment (epage) [reply src/cargo/core/compiler/fingerprint/mod.rs:816]: Sorry, Yes, I meant conditioned on the platform (which is why the typedef would be there)

Comment (epage) [reply src/cargo/core/compiler/fingerprint/mod.rs:816]: Hmm, if we also have a normalization process, I wonder if we should apply that more generally

File: src/cargo/core/compiler/fingerprint/mod.rs (hunk 2 above)
Comment (linyihai) [reply src/cargo/core/compiler/fingerprint/mod.rs]: I think `env_config` should have higer precedence as `env_config`  may contains the env that needs  force overwrite or that doesn't exist in the env snapshot

File: src/cargo/core/compiler/fingerprint/mod.rs (hunk 3 above)
Comment (linyihai) [reply src/cargo/core/compiler/fingerprint/mod.rs]: Updated.

File: src/cargo/core/compiler/fingerprint/mod.rs (hunk 4 above)
Comment (linyihai) [reply src/cargo/core/compiler/fingerprint/mod.rs]: I guessed you intention is explictly to use `str::to_string` instead ?

Comment (epage) [reply src/cargo/core/compiler/fingerprint/mod.rs]: For myself, I tend to prefer `to_owned` as that signals the intent

File: src/cargo/core/compiler/fingerprint/dep_info.rs
Comment (epage) [inline src/cargo/core/compiler/fingerprint/dep_info.rs:1]: >  refactor: env_config supports resolve case insensitive env. 

What was the intention with this last commit?

Comment (linyihai) [reply src/cargo/core/compiler/fingerprint/dep_info.rs:1]: Its intention is https://github.com/rust-lang/cargo/pull/14756#discussion_r1824555604.  Should I squash it into the previous fixing commit ?

Comment (epage) [reply src/cargo/core/compiler/fingerprint/dep_info.rs:1]: The intention behind that is to abstract away the platform-specific logic and make it easier to do the right thing across cargo.  I don't feel the current implementation meets that need. Granted, this might be a bigger change, so depending on  the direction we should take with it, maybe its better to defer out of this

Comment (linyihai) [reply src/cargo/core/compiler/fingerprint/dep_info.rs:1]: Ok,  I leave this as a future PR.

**Comment by linyihai** [comment]
I removed the code that makes `env_config` case insensitivity in Windows.  Resolving env_config's case sensitivity due to operating system platform differences is far more complicated than fixing this issue, so I left it to a possible future PR and made this PR easier to merge.

**Review by weihanglo — APPROVED** [review]
This all makes sense. Thank you.

**Review by weihanglo — APPROVED** [review]
