### PR TITLE
Don't error if no binaries were installed

### LINKED ISSUE #10289: cargo install --bins errors if no binaries were matched with default features
### Problem

`cargo install --bins` currently fails with a helpful error message if trying to run `cargo install` on a library package

https://github.com/rust-lang/cargo/blob/4a166de89ffb78c8206da22e50f4b5b4ce53fb6a/src/cargo/ops/cargo_install.rs#L208-L213

However, it _also_ fails (with a less helpful error message) if trying to `cargo install` on a package that _has_ binaries, but where none of them are matched by the given specifier/feature combinations:

https://github.com/rust-lang/cargo/blob/4a166de89ffb78c8206da22e50f4b5b4ce53fb6a/src/cargo/ops/cargo_install.rs#L324-L326

It's unclear to me whether this should be an error in general since we already emit a warning if no binaries are matched and since cargo _succeeded_ at what it was asked to do ("install no binaries"). But there is a specific case in which I think Cargo exiting with an error is particularly unwanted: `cargo install --bins` when all binaries require non-default features. For example:

```toml
[package]
name = "ex"
version = "0.1.0"
edition = "2021"

[features]
ex = []

[[bin]]
name = "main"
path = "src/ex.rs"
required-features = ["ex"]
```
```console
$ cargo install --path . --bins
  Installing ex v0.1.0 (/Users/jongje/ex)
warning: Target filter `bins` specified, but no targets matched. This is a no-op
    Finished release [optimized] target(s) in 0.00s
error: no binaries are available for install using the selected features
```

In this case, the user asked to install "all binaries with default features", and did not specify any "selected features", and so "install nothing" seems like the correct thing for Cargo to do, and an error seems unwarranted. It also presents a challenge for "default" build scripts (think Rust CI job templates and the like) that want to "install binaries if there are any", which cannot just blanket run `cargo install --bins --path .` since it will fail the job for a crate with only non-default binaries. Instead, such scripts have to both search for _and_ resolve features to figure out whether `cargo install` is "safe" to run.

### Steps

_No response_

### Possible Solution(s)

My take here is that `cargo install --bins` should never fail due to selecting no binaries, _even if_ the crate has no binaries in the first place. It should just warn. I think there may be an exception to a library-only crate to help newcomers who are confused about what `install` does in the first place, but otherwise `--bins` says (to me) "install all selected", which is true even if none were selected.

### Notes

/cc https://github.com/rust-lang/cargo/pull/9576

### Version

```text
cargo 1.57.0 (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: x86_64-apple-darwin
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.64.1 (sys:0.4.49+curl-7.79.1 system ssl:(SecureTransport) LibreSSL/2.8.3)
os: Mac OS 11.6.2 [64-bit]
```

### PR DESCRIPTION
**Pull request by jonhoo**
### What does this PR try to resolve?

Fixes #10289, which contains a thorough description of the problem.

Briefly, if we interpret `cargo install` and `cargo install --bins` as "install
the binaries that are available", it should not be considered an error
if no binaries ended up being installed due to required features.
Instead, this should provide the user with a warning that this may not
have been what they intended.

### Additional information

Given that #9576 seems to have stalled, I figured I'd try to land this first [after all](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/cargo.20install.20--bins.20when.20no.20binaries.20match).

### CODE REVIEW

**Review by weihanglo — COMMENTED** [review]
Look reasonable to me! 

Only one thing left we need to handle: `cargo-install` can install binaries from example targets. You might want to check those conditions as well.

**Comment by jonhoo** [comment]
Good catch! Fixed in newest commit, and I added a bit to an existing test to exercise it.

File: src/cargo/ops/cargo_install.rs [hunk 1]
```diff
@@ -322,7 +323,43 @@ impl<'cfg, 'a> InstallablePackage<'cfg, 'a> {
...
+                    bail!("no binaries are available for install using the selected features");
+                }
+            }
+
+            // If there _are_ binaries available, but none were selected given the current set of
+            // features, let the user know.
+            //
+            // Note that we know at this point that _if_ bins or examples is set to `::Just`,
+            // they're `::Just([])`, which is `FilterRule::none()`.
+            if self.pkg.targets().iter().any(|t| t.is_bin()) {
```
Comment (weihanglo) [inline src/cargo/ops/cargo_install.rs:356]: Just one corner case and we're good to go!

```suggestion
            if self.pkg.targets().iter().any(|t| t.is_executable()) {
```

Comment (jonhoo) [reply src/cargo/ops/cargo_install.rs]: Ah, good catch!

**Comment by weihanglo** [comment]
Thanks!

@bors r+
