### PR TITLE
Show an error messager for invalid semver spec for packages in the [replace] section.

### LINKED ISSUE #3129: `cargo build` with `[replace]` with a `*` version number fails
Using `[replace]` without a specific version number but a `*` fails with a `Parse error`. For example running `cargo build` when the following is in the `Cargo.toml`:

```
[dependencies]
winapi = "*"
[replace]
"winapi:*" = { git = "https://github.com/oconnor0/winapi-rs.git", rev = "textbox" }
```

Gives:

```
error: failed to parse manifest at `/home/moconnor/Source/build-your-own-editor/textbox/Cargo.toml`

Caused by:
  Parse error
```

If this is intended behavior, an improved error message would be greatly appreciated.

### PR DESCRIPTION
**Pull request by jhbabon**
The `[replace]` section in the `Cargo.toml` file doesn't allow invalid semver specsfor packages, so something like this:

```toml
[dependencies]
foo = "*"

[replace]
"foo:*" = { git = 'https://example.com' }
```

It's not valid. In this case we will display an error message like this:

```
error: failed to parse manifest at `Cargo.toml`

Caused by:
  replacements must specify a valid semver version to replace, but `foo:*` does not

Caused by:
  Parse error
```

closes #3129

### CODE REVIEW

File: src/cargo/util/toml.rs [hunk 1]
```diff
@@ -737,7 +737,12 @@ impl TomlManifest {
                -> CargoResult<Vec<(PackageIdSpec, Dependency)>> {
         let mut replace = Vec::new();
         for (spec, replacement) in self.replace.iter().flat_map(|x| x) {
-            let spec = try!(PackageIdSpec::parse(spec));
+            let spec = match PackageIdSpec::parse(spec) {
+                Ok(spec) => spec,
+                Err(_)   => bail!("replacements must specify a \
+                                   valid semver version \
+                                   to replace, but `{}` does not", spec),
+            };
```
Comment (alexcrichton) [inline src/cargo/util/toml.rs]: Could this actually use `chain_error`? That way we don't lose the previous error context and can just chain more information onto it

**Comment by alexcrichton** [comment]
Looks good to me, thanks @jhbabon!

File: src/cargo/util/toml.rs (hunk 1 above)
Comment (jhbabon) [inline src/cargo/util/toml.rs]: I tried that but It was just displaying:

```
Caused by:
  Parser Error
```

And I couldn't find that very helpful. But I can use `chain_error` if you think is better.

Comment (alexcrichton) [inline src/cargo/util/toml.rs]: Yeah it's true that it's not *too* helpful, but one day it may be! In general it's also just good hygiene to not throw away errors.

Comment (jhbabon) [inline src/cargo/util/toml.rs]: @alexcrichton yes, that sounds like a good practice. I made the change here https://github.com/rust-lang/cargo/pull/3139/commits/89b2d267244b244776aa12bbae9bd0441a350ef6

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!
