### PR TITLE
Be more permissive while packaging unpublishable crates.

### LINKED ISSUE #14356: `-Zpackage-workspace` is not smart about `publish = false`
### Problem

I was hoping to include `-Zpackage-workspace` as part of a workspace's CI so that it doesn't repeat certain embarrassing mistakes, but it didn't work as expected with respect to certain crates that have `publish = false` on them.

### Steps

After bumping the versions of all packages I wished to publish a new release for, I used this on the workspace with the following command:
```console
$ cargo +nightly package --workspace -Zpackage-workspace
     Locking 7 packages to latest compatible versions
    Updating cargo-pgrx v0.12.0-beta.3 (/home/jubilee/tcdi/pgrx/cargo-pgrx) -> v0.12.0-beta.4
    Updating pgrx v0.12.0-beta.3 (/home/jubilee/tcdi/pgrx/pgrx) -> v0.12.0-beta.4
    Updating pgrx-macros v0.12.0-beta.3 (/home/jubilee/tcdi/pgrx/pgrx-macros) -> v0.12.0-beta.4
    Updating pgrx-pg-config v0.12.0-beta.3 (/home/jubilee/tcdi/pgrx/pgrx-pg-config) -> v0.12.0-beta.4
    Updating pgrx-pg-sys v0.12.0-beta.3 (/home/jubilee/tcdi/pgrx/pgrx-pg-sys) -> v0.12.0-beta.4
    Updating pgrx-sql-entity-graph v0.12.0-beta.3 (/home/jubilee/tcdi/pgrx/pgrx-sql-entity-graph) -> v0.12.0-beta.4
    Updating pgrx-tests v0.12.0-beta.3 (/home/jubilee/tcdi/pgrx/pgrx-tests) -> v0.12.0-beta.4
error: `aggregate` cannot be packaged.
The registry `crates-io` is not listed in the `package.publish` value in Cargo.toml.
```

### Possible Solution(s)

This seems a curious error, given that this is intentional? I wish to not publish that crate and thus do not wish to package it for publishing?

Cargo has the option of doing the "smart" thing ("What I mean") here and simply ignoring such packages. The other obvious alternative is that it can simply continue to fail-fast, but if so it should probably have a more helpful error message. Note these are "leaf" packages on which nothing depends, so automatically excluding them _would_ work.

### Notes

I do have the option of simply removing it from the workspace, but it all gets a bit awkward. To complicate matters further, these packages being in the workspace does affect feature resolution which also affects whether or not basic `cargo check` or `cargo test` work (as the library is one of those "you must enable one and only one of these features" sorts).

Related:
- https://github.com/rust-lang/cargo/issues/10948

### Version

```text
cargo 1.82.0-nightly (b5d44db1d 2024-07-26)
release: 1.82.0-nightly
commit-hash: b5d44db1daf0469b227a6211b987162a39a54730
commit-date: 2024-07-26
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.8.0-DEV (sys:0.4.73+curl-8.8.0 vendored ssl:OpenSSL/3.3.1)
ssl: OpenSSL 3.3.1 4 Jun 2024
os: Arch Linux Rolling Release [64-bit]
```

### PR DESCRIPTION
**Pull request by jneem**
This PR allows for packaging workspaces that include `publish = false` crates, in some circumstances:

- unpublishable crates are ignored when inferring the publish registry
- when checking whether the publish registry is valid, we ignore unpublishable crates
- we don't put unpublishable crates in the local registry overlay, so if any workspace crates depend on an unpublishable crate then they will fail to verify.

This PR also contains a refactor, moving the registry inference logic to `registry/mod.rs`, where it will be reused by the upcoming publish-workspace feature. I put the refactor and the logic changes in different commits.

Fixes #14356

### CODE REVIEW

File: src/cargo/ops/cargo_package.rs [hunk 1]
```diff
@@ -354,6 +316,12 @@ impl LocalDependencies {
             .map(|name| self.packages[&name].clone())
             .collect()
     }
+
+    pub fn has_no_dependencies(&self) -> bool {
```
Comment (epage) [inline src/cargo/ops/cargo_package.rs:325]: This commit seems to have multiple refactors in it, not just moving of a function.  I'm having a hard time following what each change is intended to do.  Could you split this further up?

File: src/cargo/ops/registry/mod.rs [hunk 2]
```diff
@@ -325,39 +325,52 @@ pub(crate) struct RegistrySourceIds {
...
-                regs.dedup();
-                // unwrap: the match block ensures that there's more than one reg.
-                let (last_reg, regs) = regs.split_last().unwrap();
-                bail!(
-                    "--registry is required to disambiguate between {} or {} registries",
-                    regs.join(", "),
-                    last_reg
-                )
+    // Ignore "publish = false" packages while inferring the registry.
+    let pkgs: Vec<_> = pkgs
```
Comment (epage) [inline src/cargo/ops/registry/mod.rs:329]: While I'm a big fan of shadowing, its generally best when the meanings are the same.  These have two different meanings.

File: src/cargo/ops/registry/mod.rs [hunk 3]
```diff
@@ -325,39 +325,52 @@ pub(crate) struct RegistrySourceIds {
...
+        .iter()
+        .filter(|p| p.publish() != &Some(Vec::new()))
+        .collect();
+
+    match &pkgs[..] {
+        [] => Ok(None),
+        [first, rest @ ..] => {
```
Comment (epage) [inline src/cargo/ops/registry/mod.rs:336]: If these are our only cases, this seems better served as a guard statement.  This causes a lot of unnecessary rightward drift and it gives the impression there will be other interesting cases when there aren't, breaking users expectations when reading the code, making it harder to read.

File: src/cargo/ops/cargo_package.rs (hunk 1 above)
Comment (jneem) [reply src/cargo/ops/cargo_package.rs:325]: I've split the second commit into a pure move, followed by some changes. "Refactor" was probably the wrong word; there are a few logic changes because I wanted to reuse `publish`'s `get_source_id` logic for `package`.

File: src/cargo/ops/registry/mod.rs (hunk 3 above)
Comment (epage) [reply src/cargo/ops/registry/mod.rs]: By guard statement, I was referring to an early return, something like changing
```rust
if let Some((first, rest)) = publishable_pkgs.split_first() {
```
to
```rust
let Some((first, rest)) = publishable_pkgs.split_first()  else {
    return Ok(None);
};
```

**Comment by jneem** [comment]
Ok, I've split that commit further. We can drop the "Use the shared source building..." commit if you want; it changes some behavior mostly just to get some more code re-use.

File: src/cargo/ops/cargo_package.rs [hunk 4]
```diff
@@ -202,19 +202,34 @@ pub fn package(ws: &Workspace<'_>, opts: &PackageOpts<'_>) -> CargoResult<Vec<Fi
...
+        Ok(sid) => {
+            debug!("packaging for registry {}", sid);
+            Some(sid)
+        }
+        Err(e) => {
+            if deps.has_no_dependencies() && opts.reg_or_index.is_none() {
+                // The publish registry doesn't matter unless there are local dependencies,
+                // so ignore any errors if we don't need it. If they explicitly passed a registry
+                // on the CLI, we check it no matter what.
+                None
```
Comment (epage) [inline src/cargo/ops/cargo_package.rs:218]: I feel uncomfortable taking any error a function may return and ignoring it based on certain criteria, assuming its a very specific case.  Someone could refactor that function, changing error cases and not realize that it doesn't propagate through.

**Comment by epage** [comment]
Thank you for splitting things out further.  That was a big help in following what is happening!

File: src/cargo/ops/cargo_package.rs (hunk 4 above)
Comment (jneem) [reply src/cargo/ops/cargo_package.rs]: Good point, what about this new version? It just avoids calling the function altogether instead of ignoring the error.
