### PR TITLE
fix(layout): Put examples in their unit dir in new layout

### LINKED ISSUE #16302: `cargo clean -Zbuild-dir-new-layout -p foo` does not clean uplifted example depinfo files
### Problem

#16300 mirrors some `clean.rs` tests into `clean_new_layout` but `assert_all_clean` fails on several tests because dep info files remain.

#16300 introduces support for removing uplifted files but the examples have a hash in them and so doesn't get removed.

For some reason, it looks like the non-upllifted content in the old build layout is what is deleting the uplifted dep info?

### Steps

```
$ cargo new foo
$ cd foo
$ mkdir examples
$ echo "fn main() {}" > examples/foo.rs
$ cargo +nightly build -Zbuild-dir-new-layout
$ cargo clean -Zbuild-dir-new-layout -p foo
$ ls target/debug/examples
```
And see the dep info files still there

Or

Uncommit the `assert_all_clean` lines from `clean_new_layout.rs` and add the assert function in from `clean.rs`

### Possible Solution(s)

_No response_

### Notes

Conditionally add a glob for hashes based on the `TargetKind`

### Version

```text

```

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

Before, pre-uplifted examples were being written to `{build-dir}/{profile}/examples/{name}-{hash}`.
Now they are being written to
`{build-dir}/{profile}/build/{pkgname}/{hash}/{name}-{hash}`.

This does not affect uplifted examples (they lack the `-{hash}`).

Pre-build-dir, these were placed in a "public" location but I don't see a reason for that to be the case (otherwise, we'd need to switch them to `{target-dir}/{profile}/examples/{name}-{hash}`).
In that case, I don't see a reason to treat examples as any different than any other artifact and going in their unique build init directory.

Fixes #16302

### CODE REVIEW

**Comment by epage** [comment]
CC @ranger-ross

File: src/cargo/core/compiler/build_runner/compilation_files.rs [hunk 1]
```diff
@@ -220,7 +220,7 @@ impl<'a, 'gctx: 'a> CompilationFiles<'a, 'gctx> {
             panic!("doc tests do not have an out dir");
         } else if unit.target.is_custom_build() {
             self.build_script_dir(unit)
-        } else if unit.target.is_example() {
+        } else if unit.target.is_example() && !self.ws.gctx().cli_unstable().build_dir_new_layout {
             self.layout(unit.kind).build_dir().examples().to_path_buf()
         } else if unit.artifact.is_true() {
             self.artifact_dir(unit)
```
Comment (epage) [inline src/cargo/core/compiler/build_runner/compilation_files.rs:226]: I'm assuming we should eventually revisit this design as well so that artifact-deps doesn't affect the atomic nature of build units to allow for #5931.

**Comment by ranger-ross** [comment]
Thanks! This makes sense to me.
