### PR TITLE
Do not add home bin path to PATH if it's already there

### LINKED ISSUE #11020: `cargo cmd` preferefs `cargo-cmd` bin from it's home directory which makes sandboxing difficult
### Problem

We are using Nix (`nix develop`) to prepare a reproducible build environment for the Rust codebase. Some users report that `cargo clippy` fails due to incompatible version of Rust compiler(?), while it works for other users as the `cargo-clippy` is reproducibly available in the `$PATH`.

After some debugging it turns out that users that have `cargo-clippy` installed in `$HOME/.cargo/bin` are affected because `cargo` [prefers such binaries over those in `$PATH`](https://github.com/rust-lang/cargo/blob/471b80df64ce80e80c45a0add0eb902f1e15d271/src/bin/cargo/main.rs#L223), breaking out of the "sandbox".

### Steps

N/A

### Possible Solution(s)

* Change the order of variables in https://github.com/rust-lang/cargo/blob/471b80df64ce80e80c45a0add0eb902f1e15d271/src/bin/cargo/main.rs#L223 so that Rust home binaries are tried last.

### Notes

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by dpc**
This is to allow users to control the order via PATH if they so desire.

Tested by preparing two different `cargo-foo` scripts in `$HOME/.cargo/bin` and `$HOME/bin`:

```
> env PATH="/usr/bin/:$HOME/bin:$HOME/.cargo/bin" ./target/debug/cargo foo
Inside ~/bin/
> env PATH="$HOME/.cargo/bin:/usr/bin/:$HOME/bin" ./target/debug/cargo foo
Inside ~/.cargo/bin/
> env PATH="/usr/bin/:$HOME/bin" ./target/debug/cargo foo
Inside ~/.cargo/bin/
```

and trailing slash:

```
> env PATH="$HOME/.cargo/bin/:/usr/bin/:$HOME/bin" ./target/debug/cargo foo
Inside ~/.cargo/bin/
> env PATH="/usr/bin/:$HOME/bin:$HOME/.cargo/bin/" ./target/debug/cargo foo
Inside ~/bin/
```

Fix https://github.com/rust-lang/cargo/issues/11020

### CODE REVIEW

File: src/bin/cargo/main.rs [hunk 1]
```diff
@@ -220,10 +220,30 @@ fn is_executable<P: AsRef<Path>>(path: P) -> bool {
 }
 
 fn search_directories(config: &Config) -> Vec<PathBuf> {
-    let mut dirs = vec![config.home().clone().into_path_unlocked().join("bin")];
-    if let Some(val) = env::var_os("PATH") {
-        dirs.extend(env::split_paths(&val));
-    }
+    let path_dirs = if let Some(val) = env::var_os("PATH") {
```
Comment (epage) [inline src/bin/cargo/main.rs:223]: We should probably add a test for this.  See ` tests/testsuite/cargo_command.rs` for ideas on how to possibly go about this.

File: src/bin/cargo/main.rs [hunk 2]
```diff
@@ -220,10 +220,30 @@ fn is_executable<P: AsRef<Path>>(path: P) -> bool {
...
+
+    // If any of that PATH elements contains `home_bin`, do not
+    // add it again. This is so that the users can control priority
+    // of it using PATH, while preserving the historical
+    // behavior of preferring it over system global directories even
+    // when not in PATH at all.
+    // See https://github.com/rust-lang/cargo/issues/11020 for details.
+    //
+    // Note: `p == home_bin` will ignore trailing slash, but we don't
+    // `canonicalize` the paths.
```
Comment (epage) [inline src/bin/cargo/main.rs:239]: I'm trying to think through if there is any case where this might cause problems.  I can't.  Even if a situation does come up, it just means that the user is stuck with the original behavior.

Comment (dpc) [reply src/bin/cargo/main.rs:239]: My understanding is that it would undesirable.

File: tests/testsuite/cargo_command.rs [hunk 3]
```diff
@@ -341,6 +341,58 @@ fn cargo_subcommand_env() {
...
+        .env("CARGO_HOME", &root)
+        .with_stdout_contains("INSIDE")
+        .run();
+
+    println!("{}", root.display());
+    println!("{}", bin.display());
+    println!("{}", format!("{}:{}", root.display(), bin.display()));
+    cargo_process("foo")
+        .env("PATH", format!("{}:{}", root.display(), bin.display()))
+        .env("CARGO_HOME", &root)
```
Comment (epage) [inline tests/testsuite/cargo_command.rs:390]: `cargo-test-support` is creating a `CARGO_HOME` for you, could you use that instead of creating your own and setting `CARGO_HOME` explicitly?

File: tests/testsuite/cargo_command.rs [hunk 4]
```diff
@@ -341,6 +341,58 @@ fn cargo_subcommand_env() {
...
+        .with_stdout_contains("OUTSIDE")
+        .run();
```
Comment (epage) [inline tests/testsuite/cargo_command.rs:392]: Could you document the intention of each case?  Generally, I would do this by making them distinct tests and having the test name describe the intent

**Comment by epage** [comment]
@rfcbot merge

I feel like this solves the problem in #11020 in a reasonable way though wanted to check-in with everyone due to the slight behavior change (we'll respect `CARGO_HOME/.bin`'s precedence if its in the path) and the potential for brittleness (no normalization is done).

**Comment by epage** [comment]
@rfcbot merge

I feel like this solves the problem in #11020 in a reasonable way though wanted to check-in with everyone due to the slight behavior change (we'll respect `CARGO_HOME/.bin`'s precedence if its in the path) and the potential for brittleness (no normalization is done).

File: tests/testsuite/cargo_command.rs (hunk 3 above)
Comment (dpc) [reply tests/testsuite/cargo_command.rs:390]: Done. I wasn't aware how it all works.

File: tests/testsuite/cargo_command.rs (hunk 4 above)
Comment (dpc) [reply tests/testsuite/cargo_command.rs:392]: I've split it in two, added some comments. Can split again or add more if you want.

File: tests/testsuite/cargo_command.rs [hunk 5]
```diff
@@ -341,6 +341,58 @@ fn cargo_subcommand_env() {
         .run();
 }
 
+#[cfg(unix)]
```
Comment (ehuss) [inline tests/testsuite/cargo_command.rs:344]: I would prefer to not have this be Unix-only if possible. I think something like the following should be sufficient for creating some executables to run.

```rust
    let p = project()
        .at("cargo-foo")
        .file("Cargo.toml", &basic_manifest("cargo-foo", "1.0.0"))
        .file("src/bin/cargo-foo.rs", r#"fn main() { println!("INSIDE"); }"#)
        .file("src/bin/cargo-foo2.rs", r#"fn main() { println!("OUTSIDE"); }"#)
        .build();
    p.cargo("build").run();
    let cargo_bin_dir = paths::home().join(".cargo/bin");
    cargo_bin_dir.mkdir_p();
    let root_bin_dir = paths::root().join("bin");
    root_bin_dir.mkdir_p();
    let exe_name = format!("cargo-foo{}", env::consts::EXE_SUFFIX);
    fs::rename(p.bin("cargo-foo"), cargo_bin_dir.join(&exe_name)).unwrap();
    fs::rename(p.bin("cargo-foo2"), root_bin_dir.join(&exe_name)).unwrap();
```

and use join_paths below.  This example also doesn't require setting `CARGO_HOME`.

This will fail on restricted systems that don't have bash, for example.

File: tests/testsuite/cargo_command.rs [hunk 6]
```diff
@@ -341,6 +341,58 @@ fn cargo_subcommand_env() {
...
+    println!("{}", bin.display());
+    println!("{}", format!("{}:{}", root.display(), bin.display()));
+    cargo_process("foo")
+        .env("PATH", format!("{}:{}", root.display(), bin.display()))
+        .env("CARGO_HOME", &root)
+        .with_stdout_contains("OUTSIDE")
+        .run();
+}
+
+#[test]
```
Comment (ehuss) [inline tests/testsuite/cargo_command.rs:395]: This attribute shouldn't be added.

```suggestion
```

**Comment by ehuss** [comment]
I'm a bit confused about the status and history here, can someone clarify?

It looks like @jonhoo tried to fix something almost identical in https://github.com/rust-lang/rustup/pull/2978 (for a slightly different use case). @weihanglo closed #7431, which I think is a duplicate of #11020.

Is it correct that those two issues are duplicates? Was Jon's use case just different enough that this wasn't an issue on the cargo side?

I can't immediately think of when this will cause a particular issue, though it seems somewhat risky.

**Comment by dpc** [comment]
> It looks like @jonhoo tried to fix something almost identical in [rust-lang/rustup#2978](https://github.com/rust-lang/rustup/pull/2978) (for a slightly different use case). @weihanglo closed #7431, which I think is a duplicate of #11020.

I might be missing something but they look somewhat similar in nature. [rust-lang/rustup#2978](https://github.com/rust-lang/rustup/pull/2978) is about  `PATH` being modified needlessly by adding `.cargo/bin` to `PATH` even when it's already there,  while this one is about how cargo needlessly prefers binaries from `.cargo/bin` even when `.cargo/bin` is already in the `PATH`.

File: src/bin/cargo/main.rs [hunk 7]
```diff
@@ -220,10 +220,30 @@ fn is_executable<P: AsRef<Path>>(path: P) -> bool {
...
+    let mut dirs = if path_dirs.iter().any(|p| p == &home_bin) {
+        vec![]
+    } else {
+        vec![home_bin]
+    };
+
+    dirs.extend(path_dirs);
     dirs
```
[the remark this answers is not in the document]
Comment (dpc) [reply src/bin/cargo/main.rs:247]: Nicer, but slower. (I don't know if we care)

**Review by weihanglo — COMMENTED** [review]
Would it worth to have a doc about subcommand searching algorithm in [cargo user guide here](https://doc.rust-lang.org/nightly/cargo/reference/external-tools.html#custom-subcommands)? This can be a separate pull request though.


> I can't immediately think of when this will cause a particular issue, though it seems somewhat risky.

One risk (?) is that some Linux distros provide cargo subcommand via their own repositories, but those packages usually get outdated. User
with env such as `PATH="/usr/bin/:$HOME/bin:$HOME/.cargo/bin"` might execute the outdated one provided by distros.

File: tests/testsuite/cargo_command.rs (hunk 5 above)
Comment (dpc) [reply tests/testsuite/cargo_command.rs:377]: Done

**Comment by dpc** [comment]
> User with env such as `PATH="/usr/bin/:$HOME/bin:$HOME/.cargo/bin"` might execute the outdated one provided by distros.

If they've included `$HOME/.cargo/bin` in their `PATH` after system directories they've made their choice explicitly, even if by mistake.

File: src/bin/cargo/main.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (epage) [reply src/bin/cargo/main.rs:247]: I don't have a preference on which route is taken but I wanted to clarify that the performance for this doesn't matter.  Items are being moved either way, so I would only trust a performance determination with a benchmark.  Either way, it is probably drop in a bucket compared everything else cargo is doing (rustup's proxy, parsing manifests, resolving, etc)

**Review by epage — APPROVED** [review]

**Comment by jonhoo** [comment]
I agree with this change.

https://github.com/rust-lang/rustup/pull/2978 came up from me in a slightly different context where it caused Rustup-fueled invocations to use `rustc` and `cargo` from `~/.cargo/bin` even if I had `rustc` in some _other_ location earlier in `$PATH`. I think this issue would likely _also_ have hit us internally, but our workaround of setting `CARGO_HOME` to a directory where `bin/` is empty happened to mask it.

I'll also add that this also ties in to the `$PATH` handling in https://github.com/rust-lang/cargo/pull/10780, though I don't think that needs to be a consideration in landing this.

File: tests/testsuite/cargo_command.rs (hunk 4 above)
Comment (ehuss) [reply tests/testsuite/cargo_command.rs]: Personally I would prefer to keep it as a single test since there is a significant setup for this test.  There is a nontrivial overhead cost for each test, and this one in particular is building multiple executables which can take on the order of a second or two. With thousands of tests, that starts to add up to be very significant.

Comment (epage) [reply tests/testsuite/cargo_command.rs]: In that case, I guess comments and/or code blocks to help clarify intent.

Really wish we had pytest's fixture system. since the test doesn't mutate the fixture...

**Comment by ehuss** [comment]
@rfcbot concern code-review

There's still some outstanding review comments:
* Collection style in `search_directories`
* `cargo_cmd_bin_respect_path_when_included` is still `cfg(unix)`
* Merge to a single test due to large overhead

File: src/bin/cargo/main.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (dpc) [reply src/bin/cargo/main.rs]: Done, i think.

**Comment by dpc** [comment]
@ehuss All addressed now.

**Review by ehuss — COMMENTED** [review]
Looks great, just one last nit.

File: tests/testsuite/cargo_command.rs [hunk 8]
```diff
@@ -341,6 +344,83 @@ fn cargo_subcommand_env() {
...
+    let (outside_dir, inside_dir) = set_up_cargo_foo();
+
+    // If `$CARGO_HOME/bin` is not in a path, prefer it over anything in `$PATH`.
+    //
+    // This is the historical behavior we don't want to break.
+    cargo_process("foo").with_stdout_contains("INSIDE").run();
+
+    // When `$CARGO_HOME/bin` is in the `$PATH`
+    // use only `$PATH` so the user-defined ordering is respected.
+    {
```
[the remark this answers is not in the document]
Comment (dpc) [reply tests/testsuite/cargo_command.rs:386]: Just a logical grouping for what used to be a separate function.

[the remark this answers is not in the document]
Comment (ehuss) [reply tests/testsuite/cargo_command.rs:386]: Ah. That's not usually my preferred style (to avoid rightwards drift and it's not entirely clear that's the intent), but seems fine.

**Comment by ehuss** [comment]
@rfcbot resolve code-review

File: tests/testsuite/cargo_command.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (epage) [reply tests/testsuite/cargo_command.rs:386]: I'm fine with it.  For me, rightward drift is best reserved for business logic (in constrast to bookkeeping) and making independent test cases distinct I think falls into that category.

**Comment by epage** [comment]
Like with #10807, I feel like there isn't any harm in ending the FCP early as this was to get a straw poll of the team.

All blockers have been resolved and the only remaining conversation is more on the `nit` level, has no user impact for us to change later, and two experienced developers can reasonably come to different opinions on, so it doesn't seem worth blocking forward progress on it.

@bors r+

Thanks @dpc for working with us through this process!

**Comment by tiagolobocastro** [comment]
How will this work with pure shells? In this case it's actually the opposite, where the user PATH is removed, so the user cargo bin will not be in the PATH and yet cargo will attempt to use it.
```
       • --pure
         If this flag is specified, the environment is almost entirely cleared before the interactive shell is started, so you get an environment that more closely corresponds to the “real” Nix build. 
         A few variables, in  particular HOME, USER and DISPLAY, are retained.
```

**Comment by dpc** [comment]
> How will this work with pure shells? In this case it's actually the opposite, where the user `PATH` is removed, so the user cargo bin will not be in the `PATH` and yet cargo will attempt to use it, unless I misunderstand?

Yes. The outside `PATH` will be wiped, so `cargo` will use the normal behavior of using binaries from `$HOME/.cargo/bin`.

Usually when using pure shells, something inside the shell (like `shellHook` in `flake.nix` is responsible for reproducibly setting up `PATH`. My plan is to just add `$HOME/.cargo/bin` there (at the end) from there.

**Comment by tiagolobocastro** [comment]
> My plan is to just add $HOME/.cargo/bin there (at the end) from there.

That also kind "breaks" the purity of the shell because if a binary does not exist in the nix-shell environment, now you'd be pulling out of $HOME/.cargo/bin which is what the pure is meant to avoid?

**Comment by weihanglo** [comment]
> now you'd be pulling out of $HOME/.cargo/bin which is what the pure is meant to avoid?

As I understand it, this is sadly the old Cargo behaviour existing for a while. It's not a new feature introduced by this PR. Conversely, this PR tries to relax the behaviour a bit. Removing it (search in default cargo home bins dir) results in a breaking change.

(I am not a nix user and may be wrong about nix)

**Comment by tiagolobocastro** [comment]
No I don't think this PR is breaking things - I'm simply suggesting we haven't solved the "issue" for nix-shell in a general manner, but rather for a uses case where the cargo home bin will be in the path which is why nix-shell --pure tries to avoid in the first place.

Don't know if this was discussed before, but what about a new env variable that basically tells cargo not to search for binaries in the cargo home, unless it's in the path? 
Granted it's not a nice solution but we only need it because we can't break existing "bad" behaviour IMHO.

**Comment by dpc** [comment]
> That also kind "breaks" the purity of the shell because if a binary does not exist in the nix-shell environment, now you'd be pulling out of $HOME/.cargo/bin which is what the pure is meant to avoid?


That's why for full purity Nix sets `HOME=/homeless-shelter`. Pretty much all Unix software will refer to their config files under `$HOME` which can change their behavior breaking purity.

Full purity is often undesirable for my use case - when the developers are working on a project in `nix develop` shell, I do want them to have access to their local cargo-installed tools, just like I want them to be able to launch their favorite shell, text editor and IDE and other tools.

The scripts and tools inside dev shell should not call binaries the shell does not already provide. So the only requirement that I see is that script in cargo home bin do not take precedence over the tools provided by the shell.

**Comment by tiagolobocastro** [comment]
> Full purity is often undesirable for my use case - when the developers are working on a project in `nix develop` shell, I do want them to have access to their local cargo-installed tools, just like I want them to be able to launch their favorite shell, text editor and IDE and other tools.

That's reasonable, we also work like that most of the time, that's why there's the --pure flag which is not mandatory.
However, when we want a "pure" environment for whatever reason, we don't want to add unnecessary things to the path which might end up being picked up inadvertently.
