### PR TITLE
fix(cargo-update): `--precise` accept arbitrary git revisions

### LINKED ISSUE #13188: Update a Github dependency with `--precise <short_id>` fails
### Problem

Updating a Github dependency with a short commit id fails with such log:
```log
error: Unable to update https://github.com/rust-lang/regex#837fd85

Caused by:
  object not found - no match for id (837fd85000000000000000000000000000000000); class=Odb (9); code=NotFound (-3)
```

### Steps

```bash
cargo new test-cargo-precise 
cd test-cargo-precise 
cargo add --git https://github.com/rust-lang/regex regex 
CARGO_LOG=trace cargo update -p regex --precise 837fd85
```

Resulting `cargo update` log:
```log
   0.000038417s TRACE cargo: start="2023-12-21T07:57:53.908041000Z"
   0.000538542s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_ALIAS_UPDATE", parts: [("alias", 5), ("update", 11)] }
   0.000570375s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_TERM", parts: [("term", 5)] }
   0.000589250s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_NET", parts: [("net", 5)] }
   0.001122417s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_HTTP", parts: [("http", 5)] }
   0.001523083s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_BUILD", parts: [("build", 5)] }
   0.001558208s TRACE cargo::util::toml: read_manifest; path=/Users/julienenoch/tmp/test-cargo-precise/Cargo.toml; source-id=/Users/julienenoch/tmp/test-cargo-precise
   0.001857042s DEBUG cargo::core::workspace: find_members - only me as a member
   0.002212917s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_PATCH", parts: [("patch", 5)] }
   0.002268583s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_REGISTRY_INDEX", parts: [("registry", 5), ("index", 14)] }
   0.002286292s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_REGISTRIES_CRATES_IO_PROTOCOL", parts: [("registries", 5), ("crates-io", 16), ("protocol", 26)] }
   0.002298250s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_REGISTRIES_CRATES_IO_PROTOCOL", parts: [("registries", 5), ("crates-io", 16), ("protocol", 26)] }
   0.002305875s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_REGISTRY_INDEX", parts: [("registry", 5), ("index", 14)] }
   0.002316875s TRACE cargo::util::config: get cv ConfigKey { env: "CARGO_SOURCE", parts: [("source", 5)] }
   0.002328917s DEBUG cargo::core::registry: load/missing  https://github.com/rust-lang/regex#837fd85
   0.002347417s DEBUG cargo::core::registry: loading source https://github.com/rust-lang/regex#837fd85
   0.002353417s DEBUG cargo::sources::config: loading: https://github.com/rust-lang/regex#837fd85
   0.002360000s TRACE cargo::core::source_id: loading SourceId; https://github.com/rust-lang/regex#837fd85
    Updating git repository `https://github.com/rust-lang/regex`
   0.009446625s TRACE cargo::sources::git::source: updating git source `GitRemote { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/rust-lang/regex", query: None, fragment: None } }`
   0.010665208s DEBUG cargo::sources::git::utils: attempting GitHub fast path for https://api.github.com/repos/rust-lang/regex/commits/837fd85000000000000000000000000000000000
   0.225184458s DEBUG cargo::sources::git::utils: skipping gc as there's only 2 pack files
   0.225689625s DEBUG cargo::sources::git::utils: doing a fetch for https://github.com/rust-lang/regex
   0.226630292s DEBUG cargo::sources::git::utils: initiating fetch of ["+refs/heads/*:refs/remotes/origin/*", "+HEAD:refs/remotes/origin/HEAD"] from https://github.com/rust-lang/regex
   0.716648583s DEBUG cargo::sources::git::utils: attempting GitHub fast path for https://api.github.com/repos/rust-lang/regex/commits/837fd85000000000000000000000000000000000
   0.739785417s DEBUG cargo::sources::git::utils: skipping gc as there's only 0 pack files
   0.739872500s DEBUG cargo::sources::git::utils: doing a fetch for https://github.com/rust-lang/regex
   0.740022625s DEBUG cargo::sources::git::utils: initiating fetch of ["+refs/heads/*:refs/remotes/origin/*", "+HEAD:refs/remotes/origin/HEAD"] from https://github.com/rust-lang/regex
   2.332392833s DEBUG cargo: exit_with_error; err=CliError { error: Some(Unable to update https://github.com/rust-lang/regex#837fd85

Caused by:
    object not found - no match for id (837fd85000000000000000000000000000000000); class=Odb (9); code=NotFound (-3)), exit_code: 101 }
   2.332410958s DEBUG cargo: display_error; err=Unable to update https://github.com/rust-lang/regex#837fd85

Caused by:
    object not found - no match for id (837fd85000000000000000000000000000000000); class=Odb (9); code=NotFound (-3)
error: Unable to update https://github.com/rust-lang/regex#837fd85

Caused by:
  object not found - no match for id (837fd85000000000000000000000000000000000); class=Odb (9); code=NotFound (-3)
```

### Possible Solution(s)

_No response_

### Notes

This Github API URL used by `cargo` returns an error:
https://api.github.com/repos/rust-lang/regex/commits/837fd85000000000000000000000000000000000

While the same but with short commit id succeeds:
https://api.github.com/repos/rust-lang/regex/commits/837fd85

What's strange is that I successfully used such `cargo update -p <dep> --precise <short_id>` few weeks ago.
Could it be that Github changed its API ?

### Version

```text
cargo 1.74.1 (ecb9851af 2023-10-18)
release: 1.74.1
commit-hash: ecb9851afd3095e988daaa35a48bc7f3cb748e04
commit-date: 2023-10-18
host: aarch64-apple-darwin
libgit2: 1.7.1 (sys:0.18.0 vendored)
libcurl: 8.1.2 (sys:0.4.68+curl-8.4.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Mac OS 14.1.2 [64-bit]

--
Also same issue with:

cargo 1.71.0 (cfd3bbd8f 2023-06-08)
release: 1.71.0
commit-hash: cfd3bbd8fe4fd92074dfad04b7eb9a923646839f
commit-date: 2023-06-08
host: aarch64-apple-darwin
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.1.2 (sys:0.4.61+curl-8.0.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1t  7 Feb 2023
os: Mac OS 14.1.2 [64-bit]
```

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

`cargo update --precise` might pass in any arbitrary Git reference,
and `git2::Oid::from_str` would always zero-pad the given str if it is
not a full SHA hex string.

This introduces an enum `Revision` to represent `locked_rev`
that is either deferred or resolved to an actual object ID.
When `locked_rev` is a short ID or any other Git reference,
Cargo first performs a Git fetch to resolve it (without --offline),
and then locks it to an actual commit object ID.

This behavior is [documented](https://doc.rust-lang.org/nightly/cargo/commands/cargo-update.html#option-cargo-update---precise):

> <dt class="option-term" id="option-cargo-update---precise"><a class="option-anchor" href="#option-cargo-update---precise"></a><code>--precise</code> <em>precise</em></dt>
> <dd class="option-desc">When used with <em>spec</em>, allows you to specify a specific version number to set
> the package to. If the package comes from a git repository, this can be a git
> revision (such as a SHA hash or tag).</dd>

### How should we test and review this PR?

Review it commit by commit.

Run the repro steps in #13188.

### Additional information

Resolves #13188

### CODE REVIEW

File: src/cargo/sources/git/source.rs [hunk 1]
```diff
@@ -155,6 +160,49 @@ impl<'cfg> GitSource<'cfg> {
...
+impl Revision {
+    fn new(rev: &str) -> Revision {
+        let oid = git2::Oid::from_str(rev).ok();
+        match oid {
+            // Git object ID is supposed to be a hex string of 20 (SHA1) or 32 (SHA256) bytes.
+            // Its length must be double to the underlying bytes (40 or 64),
+            // otherwise libgit2 would happily zero-pad the returned oid.
+            // See rust-lang/cargo#13188
+            Some(oid) if oid.as_bytes().len() * 2 == rev.len() => Revision::Locked(oid),
+            _ => Revision::Deferred(GitReference::Rev(rev.to_string())),
```
Comment (epage) [inline src/cargo/sources/git/source.rs:182]: Could you add a test for when a tag looks like an Oid?

File: tests/testsuite/git.rs [hunk 2]
```diff
@@ -757,13 +757,11 @@ fn update_with_shared_deps() {
...
             "\
+[UPDATING] git repository [..]
 [ERROR] Unable to update [..]
 
 Caused by:
-  precise value for git is not a git revision: 0.1.2
-
-Caused by:
-  unable to parse OID - contains invalid characters; class=Invalid (3)
+  revspec '0.1.2' not found; class=Reference (4); code=NotFound (-3)
```
Comment (epage) [inline tests/testsuite/git.rs:764]: > When used with spec, allows you to specify a specific version number to set the package to. If the package comes from a git repository, this can be a git revision (such as a SHA hash or tag).

The documentation only says SHA and doesn't specify if shorts are allowed.

I almost wonder if the reference to `tag` is the bug, especially when I see errors like this...

Comment (weihanglo) [reply tests/testsuite/git.rs:764]: It worked in 1.45.0 before #8363 merged and [was documented since then](https://doc.rust-lang.org/1.45.0/cargo/commands/cargo-update.html). The doc mentions [git revisions](https://git-scm.com/docs/revisions), which could be like anything. This could be considered as an old regression that nobody reported until recent.

File: src/cargo/sources/git/source.rs (hunk 1 above)
Comment (weihanglo) [reply src/cargo/sources/git/source.rs:182]: Added in e6f2dfd4524ae50eaf6c243077aae3b72a545c1e

File: tests/testsuite/git.rs (hunk 2 above)
Comment (weihanglo) [reply tests/testsuite/git.rs:764]: BTW the test was added to prevent panic when revision is missing: <https://github.com/rust-lang/cargo/pull/2097/commits/1ad6f785ca1f32871666497d437183c79c32ebc6>.

File: src/cargo/ops/cargo_generate_lockfile.rs [hunk 3]
```diff
@@ -167,7 +167,7 @@ pub fn update_lockfile(ws: &Workspace<'_>, opts: &UpdateOptions<'_>) -> CargoRes
                 format!(
                     "{} -> #{}",
                     removed[0],
-                    &added[0].source_id().precise_git_fragment().unwrap()
+                    &added[0].source_id().precise_git_fragment().unwrap()[..8],
```
Comment (ehuss) [inline src/cargo/ops/cargo_generate_lockfile.rs:170]: Just a side comment, to be pedantically correct this should probably be using [`Object::short_id`](https://docs.rs/git2/latest/git2/struct.Object.html#method.short_id) to avoid collisions, but that seems pretty unlikely.
