### PR TITLE
Fix: `cargo package` failed on bare commit git repo.

### LINKED ISSUE #14354: Failed to `cargo package --allow-dirty` for repo with no commit
### Problem

<https://github.com/rust-lang/cargo/pull/13960> unconditionally checks VCS status when doing `cargo package`.
However, a VCS (Git specifically) repository could have no commit history, and then it fails `cargo package` with such an error:

```
cargo +beta package --allow-dirty
warning: manifest has no description, license, license-file, documentation, homepage or repository.
See https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info.
error: revspec 'HEAD' not found; class=Reference (4); code=NotFound (-3)
```

### Steps

1. `cargo new foo`
2. cd foo
3. `cargo package --allow-dirty`

### Possible Solution(s)

The current `.cargo_vcs_info.json` format looks like:

```json
{
 "git": {
   "sha1": "aac20b6e7e543e6dd4118b246c77225e3a3a1302",
   "dirty": true
 },
 "path_in_vcs": ""
}
```

If the `HEAD` hash cannot be determined, should we instead emit a JSON like

```json
{
 "git": {
   "dirty": true
 },
 "path_in_vcs": ""
}
```

or just don't generate `.cargo_vcs_info.json` at all?

### Notes

_No response_

### Version

```text
cargo 1.81.0-beta.2 (a2b58c3da 2024-07-16)
release: 1.81.0-beta.2
commit-hash: a2b58c3dad4d554ba01ed6c45c41ff85390560f2
commit-date: 2024-07-16
```

### PR DESCRIPTION
**Pull request by linyihai**
### What does this PR try to resolve?
Fixes #14354 

This approach chose to not generate a `.cargo_vcs_info.json` for bare commit git repo.

### How should we test and review this PR?
Compare the test changes before and after the two commits

### CODE REVIEW

**Comment by linyihai** [comment]
It hits the API limit 

> #2 [internal] load metadata for docker.io/library/alpine:3.20
#2 ERROR: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/alpine/manifests/sha256:eddacbc7e24bf8799a4ed3cdcfa50d4b88a323695ad80f317b6629883b2c2a78: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Review by weihanglo — APPROVED** [review]
Thank you!

**Comment by weihanglo** [comment]
@rfcbot fcp merge

This insta-stabilizes an edge case of `.cargo_vcs_info.json`:

When a Git repo has no commits, the file content would be

```json5
{
  "git": {
    # there is no "sha1" field because `HEAD` is missing
    "dirty": true
  },
  "path_in_vcs": ""
}
```

**Comment by epage** [comment]
@weihanglo there are several solutions for this
- Don't include the file
- Do whatever non-git locations do
- not have the git table

and likely more.

Is there a motivation for the proposed solution?  I didn't see it here or in the issue.

**Comment by weihanglo** [comment]
I am sorry that I just did a really quick FCP without thinking hard on it.

I don't have a good answer. Thinking backward from #13695, the requirement is to have commit hash as well as the `path_in_vcs` field for other tools if they want to post-process further. The current approach this PR takes, generating vcs info file even with no `sha` field, is still useful for preserving `path_in_vcs`.

However, I personally doubt it is useful in real life, since that happens on in an edge case that no commit exists. I am fine with whatever approach we choose. We just need to fix the regression.

**Comment by linyihai** [comment]
@weihanglo Thanks you rapidly response.

Sorry for that, I had change my mind. I'm not sure if the absence of this field will cause problems in other ways,  so it's better to not include/generate the `.cargo_vcs_info.json` in this case.

Of course, this is only a reasonable change that I currently feel, which should be very rare for this scenario, and it may be better to maintain the consistency with the previous

File: src/cargo/ops/cargo_package.rs [hunk 1]
```diff
@@ -743,10 +744,12 @@ fn check_repo_state(
                         .and_then(|p| p.to_str())
                         .unwrap_or("")
                         .replace("\\", "/");
-                    return Ok(Some(VcsInfo {
-                        git: git(p, src_files, &repo, &opts)?,
-                        path_in_vcs,
-                    }));
+                    let git = git(p, src_files, &repo, &opts)?;
```
Comment (weihanglo) [inline src/cargo/ops/cargo_package.rs:747]: Could `fn git()` return a `None` when nothing needed to be recorded? So that we don't need `skip_serializing_if`  for `sha1` field.

**Comment by weihanglo** [comment]
Agree that not generating vcs info file is also a reasonable approach to take. It stays with the old behavior (not generating when `--allow-dirty` presents) without blocking `cargo package`.

**Comment by weihanglo** [comment]
Let's discuss different approaches in the issue then.

File: src/cargo/ops/cargo_package.rs (hunk 1 above)
Comment (linyihai) [reply src/cargo/ops/cargo_package.rs]: Agree with you and updated it

**Review by weihanglo — APPROVED** [review]

**Comment by weihanglo** [comment]
Thanks for the contribution. This should be the least controversial way to fix this. See the  discussion in #14354.

@bors r+
