### PR TITLE
Remove `run_expect_error` to avoid tests incorrectly passing

### LINKED ISSUE #14076: test: `with_stderr_(data|contains)` has no effect when chained with `run_expect_error()`
### Problem

While working on #14060, I noticed a test case with both `with_stderr_contains` and `run_expect_error` would always pass no matter what's passed to `with_stderr_contains(...)`.

```rust
  cargo_process("help empty-alias")
        .env("PATH", Path::new(""))
        .with_stderr_contains("THIS RANDOM SENTENCE SHOULD FAIL THIS TEST BUT DIDN'T [..] The subcommand 'empty-alias' wasn't recognized [..]",
        )
        .run_expect_error();
```

The all 3 usages of `run_expect_error` in the codebase have the same false positive issue: https://github.com/choznerol/cargo/commit/18f4c3f3d1f90d88c3ea667f51b093d4e1b8deec

### Steps

1. Run `cargo test --test testsuite help_alias; cargo test --test testsuite config_invalid_empty; cargo test --test testsuite use_mtime_cache_in_cargo_home;`. All 3 tests should pass.
2. Check out this reproduce commit https://github.com/choznerol/cargo/commit/18f4c3f3d1f90d88c3ea667f51b093d4e1b8deec on my fork. It just puts random stuff into `with_stderr_contains`. Rerun step 1 and notice all 3 tests still passed.
3. (Optional) Same issue even if replacing `with_stderr_contains` with `with_stderr_data`. To validate this, you may checkout #14060 and run `cargo test --test testsuite help_alias`.

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
cargo 1.79.0-nightly (0637083df 2024-04-02)
release: 1.79.0-nightly
commit-hash: 0637083df5bbdcc951845f0d2eff6999cdb6d30a
commit-date: 2024-04-02
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.4.0 (sys:0.4.72+curl-8.6.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 3.2.1 30 Jan 2024
os: Mac OS 14.4.1 [64-bit]
```

### PR DESCRIPTION
**Pull request by choznerol**
### What does this PR try to resolve?

Fixes #14076

### How should we test and review this PR?

I pushed commits separately so the CI status can show the reproduction and the fix:

- bc5d57c reproduce the bug: Its CI shouldn't have passed.
- 3c473b5 fixes the issue, so the CI for d9d11c4 is now correctly [failing tests](https://github.com/rust-lang/cargo/actions/runs/9529301554/job/26267905188#step:11:4072).
- Turns out these test already have regression. 79a7bf4 fixes them.

### Additional information

Thanks @weihanglo for suggesting the fix 3c473b5 in https://github.com/rust-lang/cargo/issues/14076#issuecomment-2169593172.

### CODE REVIEW

File: tests/testsuite/freshness.rs [hunk 1]
```diff
@@ -2934,7 +2934,7 @@ fn use_mtime_cache_in_cargo_home() {
     p.cargo("check -v")
         .env("CARGO_HOME", &cargo_home)
         .with_status(101)
-        .with_stderr(
+        .with_stderr_contains(
```
Comment (choznerol) [inline tests/testsuite/freshness.rs:2937]: I know 79a7bf4 didn't fix these regressions the latest #14039 way. However, to avoid introducing more unrelated diff (redaction, larger snapshot, etc.) to this PR, I thought minimum fix might be more suitable.

**Review by weihanglo — APPROVED** [review]

**Comment by weihanglo** [comment]
Thank you for your prompt fix!


@bors r+
