### PR TITLE
Fix [patch] causing updates with a virtual manifest

### LINKED ISSUE #4552: [patch] forces registry update at every build
I’m currently working from a moving train (with spotty connectivity) on testing Servo with local cssparser modifications:

```toml
[patch.crates-io]
cssparser = { path = "../rust-cssparser" }
```

On every iteration of the edit-compile-test cycle, Cargo spends a few seconds updating the registry even though everything needed to build is already available in cache:

```
$ cargo check
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling selectors v0.19.0 (file:///home/simon/projects/servo/components/selectors)
[…]
```

It looks like I wouldn’t be able to work at all without connectivity. Adding `--frozen` doesn’t help, even though `Cargo.lock` wouldn’t change:

```
$ cargo check --frozen
error: failed to load source for a dependency on `cssparser`

Caused by:
  Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  attempting to make an HTTP request, but --frozen was specified
```

Is it perhaps having `[patch]` in place that makes Cargo over-eager to check if a seconds-old cache is out of date?

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit fixes the [patch] implementation to avoid causing spurious updates
of the registry when specified inside of a virtual manifest via a path
dependency that was otherwise outside of the workspace.

Cargo previously attempted to learn about path dependencies through the
configuration of the workspace by looking at members, their path dependencies,
and their replace sections. The replace/patch sections, however, only matter at
the root of the workspace and those weren't looked at! This commit fixes this
problem by explicitly looking at the workspace's replace/patch sections and
avoiding looking at other manifest replace/patch which shouldn't matter.

Closes #4552

### CODE REVIEW

**Comment by alexcrichton** [comment]
If this looks good to go, I'd also like to backport this to beta to ensure it goes out with the initial implementation of `[patch]`.

File: src/cargo/core/resolver/encode.rs [hunk 1]
```diff
@@ -199,34 +204,49 @@ fn build_path_deps(ws: &Workspace) -> HashMap<String, SourceId> {
...
     for member in members.iter() {
-        build(member, ws.config(), &mut ret, &mut visited);
+        build_pkg(member, ws.config(), &mut ret, &mut visited);
+    }
+    for (_, deps) in ws.root_patch() {
+        for dep in deps {
+            build_dep(dep, ws.config(), &mut ret, &mut visited);
+        }
+    }
+    for &(_, ref dep) in ws.root_replace() {
```
Comment (matklad) [inline src/cargo/core/resolver/encode.rs]: Hm, previously this looked at replace sections of other packages, so this might be a change of behavior. Is this intentional? I thinks it might cause problems for someone...

Perhaps we should leave replace behavior as is, add a test for it, and change only patch?

Comment (alexcrichton) [reply src/cargo/core/resolver/encode.rs]: Yeah it's intentional to avoid looking at replace/patch in all packages. That was actually a bug that was never intended! I don't think this'll cause problems because nothing else in Cargo looks at those sections, so it won't cause spurious updates or anything like that
