### PR TITLE
Fix race condition in local registry crate unpacking

### LINKED ISSUE #6588: Build failures executing Cargo concurrently using a local registry
**Problem**

There is a race condition when building multiple projects concurrently that depend on the same crates. When extracting crates **from a local registry**, the crate is opened as read-only with shared locks (https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/registry/local.rs#L74). Unpacking the crate is assumed to be safe due to the tar file being locked (https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/registry/mod.rs#L428).

Output of build failure:
```
   Unpacking form v0.4.0 (registry `file:///home/builduser/cargo_registry/latest`)
   Unpacking svd2rust v0.14.0 (registry `file:///home/builduser/cargo_registry/latest`)
  Installing svd2rust v0.14.0
  Installing form v0.4.0
   Unpacking log v0.4.6 (registry `file:///home/builduser/cargo_registry/latest`)
   Unpacking cast v0.2.2 (registry `file:///home/builduser/cargo_registry/latest`)
   Unpacking getopts v0.2.18 (registry `file:///home/builduser/cargo_registry/latest`)
   Unpacking svd-parser v0.6.0 (registry `file:///home/builduser/cargo_registry/latest`)
   Unpacking failure v0.1.3 (registry `file:///home/builduser/cargo_registry/latest`)
   Unpacking quote v0.3.15 (registry `file:///home/builduser/cargo_registry/latest`)
   Unpacking env_logger v0.5.13 (registry `file:///home/builduser/cargo_registry/latest`)
   Unpacking clap v2.32.0 (registry `file:///home/builduser/cargo_registry/latest`)
   Unpacking syn v0.11.11 (registry `file:///home/builduser/cargo_registry/latest`)
   Unpacking syn v0.11.11 (registry `file:///home/builduser/cargo_registry/latest`)
error: failed to compile `form v0.4.0`, intermediate artifacts can be found at `/tmp/cargo-installKeMHuZ`

Caused by:
  unable to get packages from source

Caused by:
  failed to download replaced source registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to unpack package `syn v0.11.11 (registry `file:///home/builduser/cargo_registry/latest`)`

Caused by:
  failed to unpack entry at `syn-0.11.11/src/aster/mod.rs`

Caused by:
  failed to unpack `/home/builduser/.cargo/registry/src/-39fe0c9a09214cd4/syn-0.11.11/src/aster/mod.rs`
```

**Steps**

1. Create a local registry.
2. Clear the local crate source cache.
3. Execute two builds at the same time.

**Possible Solution(s)**

* Lock the crate file on the local registry. This is not ideal, as the local registry might be read-only or an NFS mount.
* Copy the crate file to the registry cache in `$CARGO_HOME`, exclusively locking that copy.
* Locking an empty file in `$CARGO_HOME`.

**Notes**

Output of `cargo version`:
`cargo 1.29.0 (524a578d7 2018-08-05)`

### PR DESCRIPTION
**Pull request by hugwijst**
Copy crate and keep exclusive lock to it with local registries. Ensures
that only one instance will try to extract the source of a new package.

Fixes #6588.

### CODE REVIEW

File: src/cargo/sources/registry/local.rs [hunk 1]
```diff
@@ -70,38 +70,39 @@ impl<'cfg> RegistryData for LocalRegistry<'cfg> {
...
+
+        // Attempt to open an read-only lock first to avoid an exclusive write lock.
+        //
+        // If this fails then we fall through to the exclusive path where we copy
+        // the file.
+        if let Ok(dst) = self.cache_path.open_ro(&filename, self.config, &filename) {
+            let meta = dst.file().metadata()?;
+            if meta.len() > 0 {
+                return Ok(MaybeLock::Ready(dst));
+            }
```
Comment (hugwijst) [inline src/cargo/sources/registry/local.rs]: This is directly copied from `RemoteRegistry`. Probably not necessary, though I'm wondering how necessary it is in the current version of `RemoteRegistry` anyway.

**Comment by dwijnand** [comment]
r? @alexcrichton 

(Sorry, travelling)

**Comment by alexcrichton** [comment]
Thanks for the PR! I'm may be confused though as I'm not sure how the original implementation here suffered from a bug. In the original implementation it's just calculating the checksum for a tarball, so I'm not sure where the race is for concurrent builds?

**Comment by hugwijst** [comment]
The race is in the unpacking, I think. `LocalRegistry::download` always returned a `FileLock` that was shared. If I understand correctly, the unpack logic in `RegistrySource::unpack_package` assumes though that the lock of the tarball implies that the destination directory that is being unpacked into is being locked too. This holds for remote registries, but not for local registries.

I think a better solution might be to actually lock the unpacking instead of the tarball. This could be fairly easily done by locking the `.cargo-ok` file, maybe writing "ok" to it when it is correctly unpacked to detect an interrupted unpacking job? The main issue with this solution is upgrading from an older version of Cargo, as I'm not sure if unpacking over existing files would work correctly.

**Comment by alexcrichton** [comment]
I'm trying to make sense of this, but I don't think this PR as-is is the right solution. It looks like unpacking is actually already racy even for remote downloads because the unpacking step isn't synchronized at all. We do some synchronization to ensure that only one Cargo downloads the crate during remote downloads, but even for remote downloads a shared read lock can be returned (as expected local registries always do). 

Looking at the original bug report again it looks like there's a bug in Cargo's error reporting, because there should be an I/O error in the error message as to what actually failed in the underlying system. Currently it just shows that something failed to unpack, but it doesn't say why (or what os error hapened).

Perhaps the locking here could be moved to the unpacking step instead of the downloading step?

**Comment by hugwijst** [comment]
I've spent some more time on this and I think I understand a lot better what the issue is now.

Imagine two instances trying to use a package that is not yet unpacked:
1. Instance 1 is first and starts unpacking.
2. Instance 2 reaches `RegistrySource::unpack_package`, sees no `.cargo-ok` file and also starts unpacking.
3. Instance 2 trying to unpack the same file instance 1 is trying to unpack results in an IO error.
Alternatively:
3. Instance 1 finishes unpacking an creates the `.cargo-ok` file.
4. Instance 1 stars compiling the crate that instance 2 is still unpacking. As some files are only half unpacked, compilation fails.

This only happens when using a local registry. With a remote registry the registry index gets locked, allowing only one instance at a time to access the registry cache.

I was able to reproduce this by:
1. Create a local registry mirror of the crates needed by Cargo.
2. Set CARGO_HOME to a hard disk or some other slower file system, as this will significantly increase the chance of the race resulting in issues.
3. Create a `.cargo/config` to point to the local registry mirror.
4. `cargo clean`
5. Execute two cargo commands in parallel that don't share a build directory, eg `cargo check & cargo check --release`.
You might need to execute the last two commands a couple of times, but it fails about 50% of the time on my machine.

My latest commit fixes the issue locally.

**Comment by alexcrichton** [comment]
That sounds right to me, and the fix looks almost there!

The only other thing I think we need to handle is that `open_rw` shouldn't happen first. In the fast path we should only use `open_ro` because this handles cases like:

* Avoids unnecessary contention when the filesystem is actually ready to go (most of the time)
* Avoids failing for already-unpacked packages on readonly filesystems (can happen in docker for example)

I think we'll want to start with an `open_ro`, and if that succeeds check the size of the file. If the file is zero size or nonexistent then we drop the lock and `open_rw`. After the `open_rw` we check the size again before proceeding to handle something else grabbing the lock in the middle.
