### PR TITLE
Try to improve "version not found" error

### LINKED ISSUE #6111: Error message should be more informative when build fails due to missing vendored dependencies
We use 'replace-with' in mozilla-central [1] to force all dependencies to be vendored. However, if somebody does |cargo update| and then does not re-vendor the sources, the provided error message is pretty opaque:

> 0:10.34 error: no matching version `= 1.0.23` found for package `libz-sys`
> 0:10.34 location searched: registry `https://github.com/rust-lang/crates.io-index`
> 0:10.34 versions found: 1.0.16
> 0:10.34 required by package `mozjs_sys v0.0.0 (file:///files/mozilla/mc/b/js/src)`

It would be nice to inform the user that a replace-with is active for source.crates-io and that they may want to revendor. This bit @ekr today.

CC @alexcrichton @aturon 

[1] https://searchfox.org/mozilla-central/rev/819cd31a93fd50b7167979607371878c4d6f18e8/.cargo/config.in#6

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit tweaks the wording for when versions aren't found in a
source, notably including more location information other than the
source id but rather also taking into account replaced sources and such.
It's hoped that this gives more information to make it a bit more clear
what's going on.

Closes #6111

### CODE REVIEW

File: tests/testsuite/registry.rs [hunk 1]
```diff
@@ -520,10 +520,11 @@ fn relying_on_a_yank_is_bad() {
...
         .with_stderr_contains(
             "\
-error: no matching version `= 0.0.2` found for package `baz`
-location searched: registry `[..]`
-versions found: 0.0.1
+error: failed to select a version for `baz` satisfying the requirement `= 0.0.2`
+  candidate versions found which didn't match: 0.0.1
+  location searched: `[..]` index (which is replacing registry `[..]`)
 required by package `bar v0.0.1`
+    ... which is depended on by `foo [..]`
```
Comment (Eh2406) [inline tests/testsuite/registry.rs]: Why did this change? I am not objecting, just mechanically, what changed making us print `which is depended on by`?

File: tests/testsuite/resolve.rs [hunk 2]
```diff
@@ -17,12 +17,7 @@ use proptest::prelude::*;
 
 proptest! {
     #![proptest_config(ProptestConfig {
-        cases:
-            if env::var("CI").is_ok() {
-                256 // we have a lot of builds in CI so one or another of them will find problems
-            } else {
-                1024 // but locally try and find it in the one build
-            },
+        cases: 256,
```
Comment (Eh2406) [inline tests/testsuite/resolve.rs]: Why did you choose to change this?

I assume it was running to slowly locally. If that is correct can we atleast add back in a comment on how running repeatedly or increasing this number will increase the chance of finding a bug at the expense of time?

File: tests/testsuite/directory.rs [hunk 3]
```diff
@@ -683,3 +683,44 @@ fn workspace_different_locations() {
 ",
         ).run();
 }
+
+#[test]
+fn version_missing() {
```
Comment (Eh2406) [inline tests/testsuite/directory.rs]: In general the error messages are not nearly adequately tested. I'd like one day to be sure we have all the code branches tested. Thank you for adding this test!

File: src/cargo/core/resolver/mod.rs [hunk 4]
```diff
@@ -933,13 +933,13 @@ fn activation_error(
         };
 
         let mut msg = format!(
-            "no matching version `{}` found for package `{}`\n\
-             location searched: {}\n\
-             versions found: {}\n",
-            dep.version_req(),
+            "failed to select a version for `{}` satisfying the requirement `{}`\n  \
```
Comment (Eh2406) [inline src/cargo/core/resolver/mod.rs]: I found this sentence structure convoluted the first time I looked at this PR, but it has grown on me. I thought about putting the concepts in the other order, but that leads to the existing wording which many people report as confusing.

A more radical thought is to use the cargo.toml syntax:
`failed to select a version satisfying the requirement 'foo = "2"'`
But I do not know if that is a good thought.

File: tests/testsuite/resolve.rs (hunk 2 above)
Comment (alexcrichton) [reply tests/testsuite/resolve.rs]: Ah yeah I found this was taking ~4m or so on my local machine which made a full test run sort of unbearable unfortunately :(. And sure I'll add a comment!

File: tests/testsuite/registry.rs (hunk 1 above)
Comment (alexcrichton) [reply tests/testsuite/registry.rs]: Oh I just expanded the error message a bit here, only a subset of the output was previously tested with `with_stderr_contains` (vs `with_stderr`)

File: src/cargo/core/resolver/mod.rs (hunk 4 above)
Comment (alexcrichton) [reply src/cargo/core/resolver/mod.rs]: Oh I like that actually, everyone's quite familiar with it!

File: tests/testsuite/registry.rs (hunk 1 above)
Comment (Eh2406) [reply tests/testsuite/registry.rs]: Ah. 👍

File: tests/testsuite/resolve.rs (hunk 2 above)
Comment (Eh2406) [reply tests/testsuite/resolve.rs]: That makes sense. It is new and we are still experimenting with how it fits into the workflow. I am ok with running fewer iterations, for the better ergonomics of running the test.

**Comment by alexcrichton** [comment]
Ok updated!

**Comment by Eh2406** [comment]
Lgtm.

cc the last discussion of the error messages in #5452, although I can't quite map how our thoughts from then apply now.
