### PR TITLE
Fix dep_targets for tests depending on libraries

### LINKED ISSUE #1289: tests are not rebuilt when the crate changes
I observe a problem with cargo 0.0.1-pre-nightly (9404539 2015-02-09 20:54:26 +0000).
The 'integration' test crates in the `tests` subdirectory are not automatically rebuilt on `cargo test` when the main crate gets rebuilt. This may result in some of the test crates becoming stale with regard to the changes in the crate under test, but they still run OK if they have linked a previous build of the crate statically.

### PR DESCRIPTION
**Pull request by alexcrichton**
Before this commit the `dep_targets` function of `Context` didn't actually
return all dependencies in the sense that unit tests (and likely examples) would
not have the same package's library listed as a dependency. This commit
rectifies the situation by ensuring that the package's library is included
whenever necessary in the dependency list.

Closes #1289

### CODE REVIEW

File: src/cargo/ops/cargo_rustc/mod.rs [hunk 1]
```diff
@@ -678,16 +678,16 @@ fn build_deps_args(cmd: &mut CommandPrototype, target: &Target,
...
-        target.is_lib() && target.profile().is_compile()
-    });
-
-    if (target.is_bin() || target.is_example()) &&
-       !target.profile().is_custom_build() {
-        for target in targets.filter(|f| f.is_rlib() || f.is_dylib()) {
-            try!(link_to(cmd, package, target, cx, kind));
-        }
-    }
+    // let targets = package.targets().iter().filter(|target| {
```
Comment (huonw) [inline src/cargo/ops/cargo_rustc/mod.rs]: Why commented?

Comment (alexcrichton) [inline src/cargo/ops/cargo_rustc/mod.rs]: Oops, forgot to delete, it's gone now.

File: src/cargo/ops/cargo_rustc/context.rs [hunk 2]
```diff
@@ -305,7 +305,20 @@ impl<'a, 'b: 'a> Context<'a, 'b> {
         }).filter_map(|pkg| {
             pkg.targets().iter().find(|&t| self.is_relevant_target(t))
                .map(|t| (pkg, t))
-        }).collect()
+        }).collect::<Vec<_>>();
+
+        if !target.profile().is_custom_build() &&
```
Comment (huonw) [inline src/cargo/ops/cargo_rustc/context.rs]: Could you add a comment about the high-level thing that is happening here? 

Is it something like:

> Ensure that the main package is considered a dependency of "subtargets" like tests and examples.

**Comment by huonw** [comment]
r=me with a comment, if my interpretation is approximately correct.
