### PR TITLE
Change diesel compatibility messages

### LINKED ISSUE #9450: Building diesel fails using `resolver = "2"`
**Problem**
Building diesel with `resolver = "2"` enabled fails, while builds using the old resolver succeed. It's unclear from the documentation if something in diesel needs to be changed or if this is a bug in the new resolver.  See https://github.com/diesel-rs/diesel/issues/2753 for the initial report.

I believe that this is an issue in cargo rather than in diesel for the following reason:

Building with `resolver = "2"` issues the following rustc invocation:

```
rustc --crate-name diesel ~/.cargo/registry/github.com-1ecc6299db9ec823/diesel-1.4.6/src/lib.rs 
--error-format=json 
--json=diagnostic-rendered-ansi,artifacts 
--crate-type lib 
--emit=dep-info,metadata,link 
-C embed-bitcode=no 
-C debuginfo=2 
-C metadata=8e83eb228db88a74 
-C extra-filename=-8e83eb228db88a74 
--out-dir /tmp/diesel-issue/target/debug/deps 
-L dependency=/tmp/diesel-issue/target/debug/deps 
--extern byteorder=/tmp/diesel-issue/target/debug/deps/libbyteorder-3ba0d986ba1f8d3d.rmeta 
--extern diesel_derives=/tmp/diesel-issue/target/debug/deps/libdiesel_derives-d5f5028a84dbe804.so 
--cap-lints allow 
```

which misses all specified and default features for diesel.

Building without `resolver = "2"` issues the following rustc invocation:

```
rustc --crate-name diesel ~/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.6/src/lib.rs 
--error-format=json 
--json=diagnostic-rendered-ansi,artifacts 
--crate-type lib 
--emit=dep-info,metadata,link 
-C embed-bitcode=no 
-C debuginfo=2 
--cfg 'feature="32-column-tables"' 
--cfg 'feature="bitflags"' 
--cfg 'feature="default"' 
--cfg 'feature="postgres"' 
--cfg 'feature="pq-sys"' 
--cfg 'feature="with-deprecated"' 
-C metadata=e4c51cf46b9b40ed 
-C extra-filename=-e4c51cf46b9b40ed 
--out-dir /tmp/diesel-issue/target/debug/deps 
-L dependency=/tmp/diesel-issue/target/debug/deps 
--extern bitflags=/tmp/diesel-issue/target/debug/deps/libbitflags-2a943fc4d3e795d7.rmeta 
--extern byteorder=/tmp/diesel-issue/target/debug/deps/libbyteorder-3ba0d986ba1f8d3d.rmeta 
--extern diesel_derives=/tmp/diesel-issue/target/debug/deps/libdiesel_derives-d5f5028a84dbe804.so 
--extern pq_sys=/tmp/diesel-issue/target/debug/deps/libpq_sys-2f8097271b957b37.rmeta 
--cap-lints allow 
-L native=/usr/lib/x86_64-linux-gnu
```

which contains the specified feature flags.

**Steps**

1. Clone [this](https://github.com/ThouCheese/diesel-issue) repository. (Or create a new project depending on [diesel](https://crates.io/crates/diesel), enabling the "postgres" feature for diesel)
2. Change into the project directory
3. Issue `cargo check`

**Notes**

Output of `cargo version`:

```
cargo 1.51.0 (43b129a20 2021-03-16)
```

### PR DESCRIPTION
**Pull request by weiznich**
Diesel 1.4.8 fixes the critical behaviour. This commit changes the
corresponding messages for `cargo fix` and normal builds to prompt the
user to just update the diesel version to fix the corresponding
compilation errors.

As discussed in https://github.com/rust-lang/rust/issues/88903#issuecomment-923061946

Fixes https://github.com/rust-lang/rust/issues/88903
Fixes #9450

### CODE REVIEW

File: src/cargo/ops/fix.rs [hunk 1]
```diff
@@ -321,17 +322,31 @@ fn check_resolver_change(ws: &Workspace<'_>, opts: &FixOptions) -> CargoResult<(
...
+            return false;
+        }
+        Comparator {
+            op: Op::Less,
+            major: 1,
+            minor: Some(4),
+            patch: Some(8),
+            pre: Prerelease::EMPTY,
+        }
+        .matches(pid.version())
```
Comment (ehuss) [inline src/cargo/ops/fix.rs:336]: I think this can be simplified a bit by just comparing with a Version:

```suggestion
        pid.name() == "diesel" && pid.version() < &Version::new(1, 4, 8)
```

**Review by ehuss — COMMENTED** [review]
Thanks for preparing the PR!

File: src/cargo/ops/fix.rs (hunk 1 above)
Comment (weiznich) [reply src/cargo/ops/fix.rs]: Done :+1:

**Comment by ehuss** [comment]
Thanks!  I'll take care of backporting this to beta later this week.

@bors r+

**Comment by weiznich** [comment]
@ehuss What's the state of the beta backport?

**Comment by ehuss** [comment]
The beta update is waiting to be batched with a curl update, which we wanted to let ride on nightly for a bit to detect any major issues. It will probably happen next week.
