### PR TITLE
fix(add): Update the lock file

### LINKED ISSUE #10901: cargo add: update `Cargo.lock`
### Problem

`cargo add` current does not update `Cargo.lock` after updating `Cargo.toml`. That means that the user needs to run some other command to update it. In *most* cases, this is fine, as most users will then run `build` or `check` to use their new dependency. However, some commands do not work (such as `cargo pkgid`, `cargo update -p NEW_DEP`, etc.). Additionally, it may be possible that the new dependency doesn't resolve at all (such as a conflict with another dependency).

### Proposed Solution

Update `Cargo.lock` for just the new dependency (essentially, the equivalent of what `cargo build` and friends do when `Cargo.toml` changes).

If the update fails, I'm not sure what it should do, but I would lean towards backing out any changes made.

### Notes

`cargo 1.64.0-nightly (d8d30a753 2022-07-19)`

### PR DESCRIPTION
**Pull request by epage**
This is done in the command, rather than in the op,
- To consistently construct the `Workspace`
- It is more composable as an API

A downside is we update the git dependencies a second time and any sources we didn't initially update.

Unlike the proposal in the attached issue, this does not roll back on error.
- For some errors, the user might want to debug what went wrong.  Losing the intermediate state makes that difficult
- Rollback adds its own complications and risks, including since its
  non-atomic

We've already tried to address most potential errors during `cargo add`s processing.  To meet this desire, we now error if `--locked` is passed in and we would change the manifest.  See that individual commit's message for more details.

Fixes #10901

### CODE REVIEW

File: src/bin/cargo/commands/add.rs [hunk 1]
```diff
@@ -193,6 +194,12 @@ pub fn exec(config: &mut Config, args: &ArgMatches) -> CliResult {
     };
     add(&ws, &options)?;
 
+    if !dry_run {
+        // Reload the workspace since we've changed dependencies
+        let ws = args.workspace(config)?;
+        generate_lockfile(&ws)?;
```
Comment (ehuss) [inline src/bin/cargo/commands/add.rs:200]: My original intent is that this will only do the minimal changes necessary to update the lockfile. This function will update every dependency (similar to a blanket `cargo update`). This could potentially move unrelated dependency versions past what the user wanted.

I think using [`resolve_ws`](https://github.com/rust-lang/cargo/blob/85b500ccad8cd0b63995fd94a03ddd4b83f7905b/src/cargo/ops/resolve.rs#L63) will accomplish what I was thinking.

Otherwise, can you say more if this was chosen deliberately?

**Review by ehuss — COMMENTED** [review]
Thanks!

File: src/bin/cargo/commands/add.rs (hunk 1 above)
Comment (epage) [reply src/bin/cargo/commands/add.rs:200]: Misunderstood.  I had assume `cargo generate-lockfile` did not do an update.

Comment (epage) [reply src/bin/cargo/commands/add.rs]: Updated

**Comment by ehuss** [comment]
Thanks!  Can you add a test that shows `Cargo.lock` being updated?  And, preferably, have that test also demonstrate that an unrelated outdated dependency isn't affected.

**Comment by epage** [comment]
>  Can you add a test that shows Cargo.lock being updated? And, preferably, have that test also demonstrate that an unrelated outdated dependency isn't affected.

To test my test, I rolled back to `generate_lockfile` but the test still passes.  Wanted to double check in case I missed anything (the PR still uses `resolve_ws`)

**Comment by ehuss** [comment]
> To test my test, I rolled back to `generate_lockfile` but the test still passes. Wanted to double check in case I missed anything (the PR still uses `resolve_ws`)

I think to show that it doesn't affect `unrelateed-crate`, there needs to be two semver-compatible versions in the registry, and the `Cargo.lock` needs to be locked to the older version. It looks like there is currently only one version. I think adding something like `Package::new("unrelateed-crate", "0.2.4")` would be sufficient to demonstrate that.

BTW, is there a particular reason it is spelled "unrelateed"? Am I misreading what it is intended?

**Comment by ehuss** [comment]
Thanks!

@bors r+
