### PR TITLE
fix(tree): clarify error message when `-i` is used without a package name

### LINKED ISSUE #8840: `cargo tree -i --workspace` doesn't work even if you specify a package
**Problem**

`cargo tree -i` can't be used in a workspace.

**Steps**

```
$ cargo tree --workspace -p winapi -i
error: The `-i` flag requires a package name.

The `-i` flag is used to inspect the reverse dependencies of a specific
package. It will invert the tree and display the packages that depend on the
given package.

Note that in a workspace, by default it will only display the package's
reverse dependencies inside the tree of the workspace member in the current
directory. The --workspace flag can be used to extend it so that it will show
the package's reverse dependencies across the entire workspace. The -p flag
can be used to display the package's reverse dependencies only with the
subtree of the package given to -p.
```

Note that both `cargo tree -i -p winapi` and `cargo tree --workspace` work fine individually.

**Notes**

Output of `cargo version`: `cargo 1.49.0-nightly (d5556aeb8 2020-11-04)`

### PR DESCRIPTION
**Pull request by raushan728**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/cargo/pull/16818)*

Fixes #8840 

Clarify the error message when `-i` is used without a package name,
and add tests for both the basic and `--workspace` cases

### CODE REVIEW

**Comment by epage** [comment]
Note the last comment on #8840 before it was accepted was

> The error message definitely could stand some clarification, though.

Similarly, the issue is tagged as a diagnostic issue.

**Comment by raushan728** [comment]
> Note the last comment on #8840 before it was accepted was
> 
> > The error message definitely could stand some clarification, though.
> 
> Similarly, the issue is tagged as a diagnostic issue.

Understood, updated to only fix the diagnostic.

File: src/bin/cargo/commands/tree.rs [hunk 1]
```diff
@@ -204,18 +204,17 @@ pub fn exec(gctx: &mut GlobalContext, args: &ArgMatches) -> CliResult {
             }
             _ => {
                 return Err(format_err!(
-                    "The `-i` flag requires a package name.\n\
+                    "the `-i` flag requires a package name\n\
 \n\
-The `-i` flag is used to inspect the reverse dependencies of a specific\n\
-package. It will invert the tree and display the packages that depend on the\n\
-given package.\n\
+To inspect the reverse dependencies of a specific package, pass the name directly to `-i`:\n\
```
Comment (epage) [inline src/bin/cargo/commands/tree.rs]:
```suggestion
help: to inspect the reverse dependencies of a specific package, pass the name directly to `-i`:\n\
```

File: src/bin/cargo/commands/tree.rs [hunk 2]
```diff
@@ -204,18 +204,17 @@ pub fn exec(gctx: &mut GlobalContext, args: &ArgMatches) -> CliResult {
...
 \n\
-Note that in a workspace, by default it will only display the package's\n\
-reverse dependencies inside the tree of the workspace member in the current\n\
-directory. The --workspace flag can be used to extend it so that it will show\n\
-the package's reverse dependencies across the entire workspace. The -p flag\n\
-can be used to display the package's reverse dependencies only with the\n\
-subtree of the package given to -p.\n\
+    cargo tree -i <spec>\n\
+\n\
+If you are in a workspace and want to search across all members, use:\n\
```
Comment (epage) [inline src/bin/cargo/commands/tree.rs]:
```suggestion
help: if you are in a workspace and want to search across all members, use:\n\
```

File: src/bin/cargo/commands/tree.rs [hunk 3]
```diff
@@ -204,18 +204,17 @@ pub fn exec(gctx: &mut GlobalContext, args: &ArgMatches) -> CliResult {
...
+\n\
+    cargo tree --workspace -i <spec>\n\
+\n\
+Note: `-p <spec> -i` is not supported; pass the package name to `-i` directly.\n\
```
Comment (epage) [inline src/bin/cargo/commands/tree.rs]:
```suggestion
note: `-p <spec> -i` is not supported; pass the package name to `-i` directly.\n\
```

File: src/bin/cargo/commands/tree.rs [hunk 4]
```diff
@@ -204,18 +204,17 @@ pub fn exec(gctx: &mut GlobalContext, args: &ArgMatches) -> CliResult {
             }
             _ => {
                 return Err(format_err!(
-                    "The `-i` flag requires a package name.\n\
+                    "the `-i` flag requires a package name\n\
```
Comment (epage) [inline src/bin/cargo/commands/tree.rs]: Hmm, apparently we don't have an existing test for the main case of this.

We at least need a test for this `--workspace` situation,  I would also add one for the main case.

File: src/bin/cargo/commands/tree.rs (hunk 3 above)
Comment (epage) [inline src/bin/cargo/commands/tree.rs]: Should this go before the `help:`s?

File: src/bin/cargo/commands/tree.rs (hunk 4 above)
Comment (raushan728) [reply src/bin/cargo/commands/tree.rs]: Yes, I had thought about adding a test, but I ignored it because there was no change in the production code only the error message was changed.

File: src/bin/cargo/commands/tree.rs (hunk 3 above)
Comment (raushan728) [reply src/bin/cargo/commands/tree.rs]: I think after the `help:`s makes more sense show the correct usage first, then clarify the unsupported pattern.

File: src/bin/cargo/commands/tree.rs (hunk 4 above)
Comment (raushan728) [reply src/bin/cargo/commands/tree.rs]: Added tests for both cases

Comment (epage) [reply src/bin/cargo/commands/tree.rs]: Error messages are production code.  They have an important impact on the user.

File: src/bin/cargo/commands/tree.rs [hunk 5]
```diff
@@ -204,18 +204,17 @@ pub fn exec(gctx: &mut GlobalContext, args: &ArgMatches) -> CliResult {
...
-given package.\n\
+help: to inspect the reverse dependencies of a specific package, pass the name directly to `-i`:\n\
 \n\
-Note that in a workspace, by default it will only display the package's\n\
-reverse dependencies inside the tree of the workspace member in the current\n\
-directory. The --workspace flag can be used to extend it so that it will show\n\
-the package's reverse dependencies across the entire workspace. The -p flag\n\
-can be used to display the package's reverse dependencies only with the\n\
-subtree of the package given to -p.\n\
+\x20\x20\x20\x20cargo tree -i <spec>\n\
```
Comment (epage) [inline src/bin/cargo/commands/tree.rs]: Instead of `\x20`, just stop escaping everything.  It will be much easier to inspect and update.

File: tests/testsuite/cargo_tree/deps.rs [hunk 6]
```diff
@@ -765,18 +765,17 @@ fn invert_without_package_name() {
     p.cargo("tree -i")
         .with_status(101)
         .with_stderr_data(str![[r#"
-[ERROR] The `-i` flag requires a package name.
+[ERROR] the `-i` flag requires a package name
```
Comment (epage) [inline tests/testsuite/cargo_tree/deps.rs]: At https://github.com/rust-lang/cargo/issues/8840#issuecomment-723640404 it was suggested to change

> error: The `-i` flag requires a package name.

to

> error: The argument `-i <SPEC>` requires a package name, but none was supplied.

In clap, the wording would instead be:

> error: a package name is required for '-i <SPEC>' but none was supplied

I would lean towards that last one.

File: src/bin/cargo/commands/tree.rs (hunk 5 above)
Comment (raushan728) [reply src/bin/cargo/commands/tree.rs]: Ok sir, wil update tomorrow

File: tests/testsuite/cargo_tree/deps.rs (hunk 6 above)
Comment (raushan728) [reply tests/testsuite/cargo_tree/deps.rs]: Agreed, will update it to match the clap wording

**Comment by raushan728** [comment]
Done. Please take a look

File: src/bin/cargo/commands/tree.rs (hunk 3 above)
Comment (epage) [reply src/bin/cargo/commands/tree.rs]: That feels backward to me. This feels coupled to the error message and the helps are then aides on top.

Comment (raushan728) [reply src/bin/cargo/commands/tree.rs]: I think you are right note should come first because the user is doing something unsupported, so it makes sense to explain why it failed before showing the correct usage

Comment (raushan728) [reply src/bin/cargo/commands/tree.rs]: Done, moved the note before the `help:`s.
