### PR TITLE
artifact deps should works when target field specified coexists with `optional = true`

### LINKED ISSUE #10526: Binary dependency is never built if specified with both `optional` and `target` keys
### Problem

For convenience I have also uploaded the failing code here: https://github.com/bstrie/bindeperror2 

For the following code:

```
# Cargo.toml
[package]
name = "mycrate"
version = "0.0.0"
edition = "2021"

[dependencies]
mybindep = { path = "mybindep", artifact = "bin", optional = true, target = "x86_64-unknown-linux-gnu" }

[features]
default = ["mybindep"]
```

```rust
// src/main.rs
fn main() {
    env!("CARGO_BIN_FILE_MYBINDEP");
}
```

```
# mybindep/Cargo.toml
[package]
name = "mybindep"
version = "0.0.0"
edition = "2021"
```

```rust
// mybindep/src/main.rs
fn main() {}
```

I expected this code to build. However, `cargo build` produces the following:

```
 > cargo build
   Compiling mycrate v0.0.0 (/home/ben/code/scrap/bindeperror2)
error: environment variable `CARGO_BIN_FILE_MYBINDEP` not defined
 --> src/main.rs:2:5
  |
2 |     env!("CARGO_BIN_FILE_MYBINDEP");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `mycrate` due to previous error
```

As we can see from the output, it is not merely that the environment variable is missing; only mycrate is ever built, and mybindep is skipped.

Note that mybindep is an optional dependency, but is specified as a default feature.

In addition, neither `cargo build --features mybindep` nor `cargo build --all-features` will result in mybindep being built.

The following causes the code to compile:

```diff
- mybindep = { path = "mybindep", artifact = "bin", optional = true, target = "x86_64-unknown-linux-gnu" 
+ mybindep = { path = "mybindep", artifact = "bin", optional = true }
```

Furthermore, with this (along with removing the default feature) we can observe that `cargo build --features mybindep` and `cargo build --all-features` now functions as expected. Leaving the `target` key and removing the `optional` key also causes the code to build. It is the presence of both these keys simultaneously that results in the issue.

cc @Byron 

### Version

```text
cargo 1.61.0-nightly (109bfbd 2022-03-17)
release: 1.61.0-nightly
commit-hash: 109bfbd055325ef87a6e7f63d67da7e838f8300b
commit-date: 2022-03-17
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Pop!_OS 21.10 (impish) [64-bit]
```

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

Another attempt to fix #10526 after #11183 failed. 
You can find an explanation of the bug in #11183 or in the commit message.

### How should we test and review this PR?

This first two commits log the current "incorrect" behaviour.
Other commits contain fixes respectively.

You may find more details in the commit messages.

### CODE REVIEW

File: src/cargo/core/compiler/unit_dependencies.rs [hunk 1]
```diff
@@ -1103,7 +1103,7 @@ impl<'a, 'cfg> State<'a, 'cfg> {
                         // If this is an optional dependency, and the new feature resolver
                         // did not enable it, don't include it.
                         if dep.is_optional() {
-                            let features_for = unit_for.map_to_features_for(dep.artifact());
+                            let features_for = unit_for.map_to_features_for(None);
```
Comment (ehuss) [inline src/cargo/core/compiler/unit_dependencies.rs:1106]: Perhaps to stay consistent with the rest of the usage in this file, this const helps explain what the parameter is (instead of a nondescript `None`).

```suggestion
                            let features_for = unit_for.map_to_features_for(IS_NO_ARTIFACT_DEP);
```

Also, maybe a comment could be useful here to explain why `None` is being passed?

**Comment by ehuss** [comment]
Was a regression test ever added that would catch the regression in #11330?

**Comment by weihanglo** [comment]
I believe the regression test was done in https://github.com/rust-lang/cargo/pull/11342

**Comment by ehuss** [comment]
Thanks!

@bors r+
