### PR TITLE
fix(toml): Add `default-features` to `TomlWorkspaceDependency`

### LINKED ISSUE #11329: workspaces.dependencies causes ignore of default-features = false in crate
### Problem

When specifying a workspace dependency it is not obvious, and rather surprising that, not specifying `default-features = false` in the workspace dependency, means that any `default-features = false` is ignored in any member crate.

This I assume is because the features of workspace dependencies are additive, and by not specifying `default-features = false`, the default features are automatically and always enabled.

### Steps

1. Create a workspace with a workspace dependency that has default features.
2. Add a crate that also specifies the dependency, inherits it from the workspace, and specifies `default-features = false`.

### Possible Solution(s)

There are I think a couple solutions to this problem:

#### Possible Solution 1: Change the Default in workspace dependencies

This is probably not possible now that the feature is released, but it seems reasonable that workspace depenencies by default should not contribute any features unless explicitly specified. This would mean `default-features = false` by default in the workspace dependency.

#### Position Solution 2: Display a warning if a member crate has default-features = false when workspace doesn't

If a workspace doesn't specify `default-features = false`, but a member crate does, this seems like an error, since the member crate will never achieve the effect of `default-features = false`. A warning would go a long way to help educate and catch this mistake. The warning for this would be similar to how cargo warns if you include patch entries that aren't getting used.

### Notes

_No response_

### Version

```text
cargo 1.64.0 (387270bc7 2022-09-16)
release: 1.64.0
commit-hash: 387270bc7f446d17869c7f208207c73231d6a252
commit-date: 2022-09-16
host: aarch64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.84.0 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 13.0.0 [64-bit]
```

### PR DESCRIPTION
**Pull request by Muscraft**
In #11329 it was noted that `default-features` is ignored when used in a dependency that inherits from a workspace i.e. 
```toml
[workspace]
members = []
[workspace.dependencies]
dep = "0.1"

[package]
name = "bar"
version = "0.2.0"
authors = []
[dependencies]
dep = { workspace = true, default-features = false }
```

This problem is caused by problems with deserializing a `TomlDependency` and not emitting an unused manifest key correctly. When discussed in a recent Cargo team meeting we felt the best course of action was to allow `default-features = false` when inheriting a dependency, but it does not change actually set `default-features`. It will be used to warn when there is a difference between the definition in `[workspace.dependencies]` and `[dependencies]` i.e.
```toml
[package]
name = "bar"
version = "0.2.0"
[dependencies]
dep = { workspace = true, default-features = false }

[workspace]
members = []
[workspace.dependencies]
dep = { version = "0.1", default-features = true }
```

This does not entirely resolve the problem with unused manifest keys. A follow up PR and issue will be created to address those concerns.

close #11329

### CODE REVIEW

File: src/cargo/util/toml/mod.rs [hunk 1]
```diff
@@ -269,9 +269,18 @@ impl<'de, P: Deserialize<'de> + Clone> de::Deserialize<'de> for TomlDependency<P
                 let details: IntermediateDependency<P> = IntermediateDependency::deserialize(mvd)?;
                 if let Some(workspace) = details.workspace {
                     if workspace {
+                        if details.default_features.unwrap_or(false)
+                            || details.default_features2.unwrap_or(false)
+                        {
+                            return Err(de::Error::custom(
+                                "`default-features` cannot be `true` for a workspace dependency",
+                            ));
```
Comment (ehuss) [inline src/cargo/util/toml/mod.rs:277]: Since this was previously accepted, I'm not sure this should be initially an error. What do you think about making it a warning that it may become an error in the future?

Also, I'm a bit confused why `true` would be an error, but `false` is a warning.  Since `default-features=true` is the default, why would there be an error if someone specifies it?

**Comment by ehuss** [comment]
I'm overall a bit uncertain about the behaviors here, so I'm going to write out what my expectations would be:

workspace: `foo = { version="1.0", default-features = false }`
member: `foo = { workspace = true }`
expectation: The `foo` dependency should have default-features disabled. There should not be any warning, as this was the expected syntax that was decided in the RFC, and is generally the natural way to write it. That is, the user wanted whatever was defined in the workspace.

workspace: `foo = { version="1.0", default-features = false }`
member: `foo = { workspace = true, default-features = true }`
expectation: The `foo` dependency should have default-features enabled. There should not be any warning. This allows different members to decide whether or not they have the default-features enabled. (If this is a warning/error, users could circumvent it with `features=["default"]` which seems unnecessary.)

workspace: `foo = { version="1.0", default-features = false }`
member: `foo = { workspace = true, default-features = false }`
expectation: The `foo` default-features should be disabled. I think it should be allowed without warning, it is just re-iterating the workspace value.

----

workspace: `foo = { version="1.0", default-features = true }` or `foo = "1.0"`
member: `foo = { workspace = true }`
expectation: The `foo` dependency should have default-features enabled. No warning/error.

workspace: `foo = { version = "1.0", default-features = true }` or `foo = "1.0"`
member: `foo = { workspace = true, default-features = false }`
expectation: This should have been an error, but since it was erroneously accepted in the past, it should be a warning that the `default-features` is ignored, and may be an error in the future.

workspace: `foo = { version = "1.0", default-features = true }` or `foo = "1.0"`
member: `foo = { workspace = true, default-features = true }`
expectation: This should have been an error, but since it was erroneously accepted in the past, I think we should just accept it without a warning/error. It is just re-iterating the default. It is also I think a bit unlikely (I don't see `default-features = true` done very often).

WDYT?

**Comment by smmalis37** [comment]
I personally would agree with @ehuss on expectations, however it's worth noting that the RFC does specify different behavior currently:

>For now if a workspace = true dependency is specified then also specifying the default-features value is disallowed. The default-features value for a directive is inherited from the [workspace.dependencies] declaration, which defaults to true if nothing else is specified."

I would very much like to have the ability to use the second case in the posted list however, despite it being against the RFC as currently written.

**Comment by Muscraft** [comment]
I agree with what was talked about above. It is the best way forward with minimal changes to the expected behavior. I have implemented tests for the changed behavior. Let me know if you want me to add tests for the unchanged behaviors.

File: src/cargo/util/toml/mod.rs [hunk 2]
```diff
@@ -2553,6 +2578,29 @@ impl TomlDependency {
...
                             let mut dep = d.clone();
+                            match (
+                                default_features.or(default_features2),
+                                d.default_features.or(d.default_features2)
+                            ) {
+                                // member: default-features = true and
+                                // workspace: default-features = false should turn on
+                                // default-features
+                                (Some(true), Some(false)) => {
+                                    dep.default_features = default_features.or(default_features2);
```
Comment (ehuss) [inline src/cargo/util/toml/mod.rs:2589]: I think this might be a little simpler or clearer:

```suggestion
                                    dep.default_features = Some(true);
```

File: tests/testsuite/inheritable_workspace_fields.rs [hunk 3]
```diff
@@ -1356,3 +1356,145 @@ Caused by:
...
+            [workspace]
+            members = []
+            [workspace.dependencies]
+            dep = { version = "0.1.0", default-features = true }
+        "#,
+        )
+        .file("src/main.rs", "fn main() {}")
+        .build();
+
+    p.cargo("build")
```
Comment (ehuss) [inline tests/testsuite/inheritable_workspace_fields.rs:1390]: Can you switch to "check" in tests like this? `build` is a little slower and uses more disk space.

**Review by ehuss — COMMENTED** [review]
Thanks, just a few style nits.

**Comment by ehuss** [comment]
BTW, when you are ready for a review, you can use `@rustbot ready`, and it will update the PR labels.

**Comment by ehuss** [comment]
@rust-lang/cargo This makes some changes to the way `default-features=…` is handled with workspace inheritance. Since this is a small change in behavior, and a small deviation from the RFC, I'm going to go ahead and do an FCP to run it by everyone. The table below should summarize the behavior.

| Workspace | Member | Old Default | New Default | Reasoning |
|-----------|--------|--------------|--------------|-----------|
| *nothing* | df=false | Enabled | Enabled, warning that it is ignored. | Should have been an error in the past since the field is ignored. May change to an error in the future. |
| df=true | df=false | Enabled | Enabled, warning | ^Same |
| *nothing* | df=true  | Enabled | Enabled | There is no conflict about default being enabled. |
| df=true | df=true  | Enabled | Enabled | ^Same |
| *nothing* | *nothing*  | Enabled | Enabled | No ambiguity. |
| df=true | *nothing*  | Enabled | Enabled | ^Same |
| df=false | df=false  | Disabled | Disabled | No ambiguity. |
| df=false | df=true  | Disabled | 💥Enabled | This allows members to decide whether or not they want default features. The workaround of `features=["default"]` seems unnecessary. |
| df=false | *nothing*  | Disabled | Disabled | Natural way to write "give me whatever was written in workspace".

@rfcbot fcp merge

**Comment by epage** [comment]
Wanted to make clear some points
- The deviation from the RFC is we allow the package to have `default-features` in the dependency
- We are maintaining the additive nature of the package dependency, it can enable default features but it can't disable them

With those, I think this makes sense and I'm fine with it.

As for the warning, at worse, it can be an error in the next edition.  If we feel the impact is minimal, we can change it sooner.
