### PR TITLE
Emit warning on env variable case mismatch

### LINKED ISSUE #8285: CARGO_TARGET_<triple>_LINKER environment variable is ignored during build
## Problem

Setting the `CARGO_TARGET_<triple>_LINKER` [environment variable](https://doc.rust-lang.org/cargo/reference/config.html#targettriplelinker) has no affect on `cargo build`. 

I am targeting `x86_64-unknown-linux-musl` and I need to be able to build on both macOS (for development) and Linux (for CI). The linker is named differently on the two platforms: `x86_64-linux-musl-gcc` on macOS and `musl-gcc` on Linux (which is the what `rustc` expects by default). I would like to be able to the CARGO_TARGET_<triple>_LINKER environment variable to override the default on macOS only.

## Steps (macOS)

1. `rustup default stable` (fails for nightly too)
1. `rustup target add x86_64-unknown-linux-musl`
2. `brew install filosottile/musl-cross/musl-cross`
3. `cargo new envtest`
3. `cd envtest`
3. `export CARGO_TARGET_x86_64_unknown_linux_musl_LINKER=x86_64-linux-musl-gcc`
3. `cargo build --target x86_64-unknown-linux-musl`

**Result**: `error: linking with ``cc`` failed: exit code: 1`

**Expected Result**: a binary linked with x86_64-linux-musl-gcc

## Suggested Fix

Rather than just being able to specify target specific configurations in `.cargo/config`, it would be nice to be able to specify configurations by target and host combinations. 

For example I want this rule to only apply when building for the musl target on macOS:
```toml
[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
```
If narrow this rule by host would be amazing. Something like:
```toml
[target.x86_64-unknown-linux-musl.cfg(host_os = "macos")]
linker = "x86_64-linux-musl-gcc"
```

That said, being able to use the `CARGO_TARGET_<triple>_LINKER` environment variable is more than enough for my needs. Thank you.

## Notes

Output of `cargo version`: cargo 1.43.0 (2cbe9048e 2020-05-03)

Release channels tested:
- stable-x86_64-apple-darwin unchanged - rustc 1.43.1 (8d69840ab 2020-05-04)
- nightly-x86_64-apple-darwin unchanged - rustc 1.45.0-nightly (a74d1862d 2020-05-14)

OSes tested on: 
- macOS Catalina 10.15.5 Beta (19F83c)
- debian buster -- from the official [rust:latest](https://hub.docker.com/_/rust) docker image

### PR DESCRIPTION
**Pull request by Liberatys**
When running a command like `cargo --target TRIPPLE` cargo expects to find the environment variable CARGO_TARGET_[TRIPPLE]_* with uppercase and underscores. This check emits a warning if the checked environment variable has a mismatching case and/or contains dashes rather than underscores. The warning contains the given env variable as well as an explanation for the cause of the warning.

The check is skipped on windows as environment variables are treated as case insensitive on the platform.

Fixes #8285

### CODE REVIEW

File: src/cargo/util/config/mod.rs [hunk 1]
```diff
@@ -211,6 +213,16 @@ impl Config {
...
 
+        let mut upper_case_env: HashMap<String, String> = HashMap::new();
+
+        if !cfg!(windows) {
+            upper_case_env = env
+                .clone()
+                .into_iter()
+                .map(|(k, _)| (k.to_uppercase().replace("-", "_"), k))
+                .collect();
+        }
```
Comment (ehuss) [inline src/cargo/util/config/mod.rs:224]: This is just a minor stylistic choice, but I think it is a little clearer to initialize only once, something like this:

```rust
        let upper_case_env = if cfg!(windows) {
            HashMap::new()
        } else {
            env.clone()
                .into_iter()
                .map(|(k, _)| (k.to_uppercase().replace("-", "_"), k))
                .collect()
        };
```

File: src/cargo/util/config/mod.rs [hunk 2]
```diff
@@ -545,9 +561,27 @@ impl Config {
...
     }
 
+    fn check_environment_key_case_mismatch(&self, key: &ConfigKey) {
+        if cfg!(windows) {
+            return;
+        }
+        match self.upper_case_env.get(key.as_env_key()) {
+            Some(env_key) => {
+                let _ = self.shell().warn(format!(
+                    "Variables in environment require uppercase,
```
Comment (ehuss) [inline src/cargo/util/config/mod.rs:576]: This needs a backslash to continue on the next line.

```suggestion
                    "Variables in environment require uppercase, \
```

File: src/cargo/util/config/mod.rs [hunk 3]
```diff
@@ -545,9 +561,27 @@ impl Config {
...
             }
         }
+        self.check_environment_key_case_mismatch(key);
+
         false
     }
 
+    fn check_environment_key_case_mismatch(&self, key: &ConfigKey) {
+        if cfg!(windows) {
+            return;
```
Comment (ehuss) [inline src/cargo/util/config/mod.rs:571]: I think it might be good to have a comment here explaining why this is ignored on windows (for those who may not be familiar that windows automatically ASCII upper-cases keys).

(Hopefully nobody uses lower-case non-ASCII characters 😄.)

File: src/cargo/util/config/mod.rs [hunk 4]
```diff
@@ -545,9 +561,27 @@ impl Config {
...
+        }
+        match self.upper_case_env.get(key.as_env_key()) {
+            Some(env_key) => {
+                let _ = self.shell().warn(format!(
+                    "Variables in environment require uppercase,
+                        but given variable: {}, contains lowercase or dash.",
```
Comment (ehuss) [inline src/cargo/util/config/mod.rs:577]: Typically Cargo's error message style uses backticks to wrap a literal value.

```suggestion
                        but the variable `{}` contains lowercase letters or dash.",
```

File: src/cargo/util/config/mod.rs (hunk 2 above)
Comment (ehuss) [inline src/cargo/util/config/mod.rs:576]: Just a stylistic suggestion:

```suggestion
                    "Environment variables require uppercase,
```

File: tests/testsuite/tool_paths.rs [hunk 5]
```diff
@@ -353,6 +353,29 @@ fn custom_linker_env() {
         .run();
 }
 
+#[cargo_test]
+#[cfg(not(windows))]
```
Comment (ehuss) [inline tests/testsuite/tool_paths.rs:357]: Would it be possible to add a test to ensure that windows doesn't emit the warning, and works with a lowercase value?

File: src/cargo/util/config/mod.rs [hunk 6]
```diff
@@ -167,6 +167,8 @@ pub struct Config {
     target_dir: Option<Filesystem>,
     /// Environment variables, separated to assist testing.
     env: HashMap<String, String>,
+    /// Environment variables, converted to uppercase to check for case mismatch
+    upper_case_env: HashMap<String, String>,
```
[the remark this answers is not in the document]
Comment (Liberatys) [reply src/cargo/util/config/mod.rs:171]: The intention of using a HashMap instead of a HashSet was to use the value for the warning output. 

Taking the key.as_env_key() will result in the 'correct' key format.

[the remark this answers is not in the document]
Comment (ehuss) [reply src/cargo/util/config/mod.rs:171]: Oh, sorry, I missed that!

File: src/cargo/util/config/mod.rs [hunk 7]
```diff
@@ -545,9 +560,30 @@ impl Config {
...
+        if cfg!(windows) {
+            // In the case of windows the check for case mismatch in keys can be skipped
+            // as windows already converts its environment keys into the desired format.
+            return;
+        }
+
+        match self.upper_case_env.get(key.as_env_key()) {
+            Some(env_key) => {
+                let _ = self.shell().warn(format!(
+                    "Environment variables require uppercase letters, \
```
Comment (lukaslueg) [inline src/cargo/util/config/mod.rs:578]: Maybe the language can be improved here: "Environment variables are expected to use uppercase letters and underscores, the variable `{}` will be ignored and have no effect".

**Comment by ehuss** [comment]
Thanks!  I pushed a small change to combine the two tests into one.

@bors r+
