### PR TITLE
skip test if not nightly; fix for #5648

### LINKED ISSUE #5648: cargo v0.27 tests failed when build rust 1.26.2 on "stable" channel
If rust configured with 
```
[rust]
channel = "stable"
```
then test `test_resolving_minimum_version_with_transitive_deps` from `cargo/tests/testsuite/resolve.rs` will fail with next error:

```
---- resolve::test_resolving_minimum_version_with_transitive_deps stdout ----
        thread 'resolve::test_resolving_minimum_version_with_transitive_deps' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "the `-Z` flag is only accepted on the nightly channel of Cargo" }', libcore/result.rs:945:5
```

### PR DESCRIPTION
**Pull request by Eh2406**
closes #5648
The alternative was to use `set_var` to emulate `masquerade_as_nightly_cargo` but we worried that it would not get unset correctly. Although I think each test is its own process, so it should work.

### CODE REVIEW

File: tests/testsuite/resolve.rs [hunk 1]
```diff
@@ -354,6 +354,12 @@ fn test_resolving_minimum_version_with_transitive_deps() {
         pkg!("bar" => [dep_req("util", ">=1.0.1")]),
     ]);
 
+    if !nightly_features_allowed() {
```
Comment (Mark-Simulacrum) [inline tests/testsuite/resolve.rs]: I feel like I've seen other cargo tests use something like `is_nightly` already, perhaps grep for `#![feature`?

Comment (Eh2406) [reply tests/testsuite/resolve.rs]: good call switched to `is_nightly`

**Comment by ehuss** [comment]
I'm wondering if all the `advanced-env` config tests need this as well (everything that calls `new_config()`).  It's not clear to me in what situation this is actually needed, though.

**Comment by Eh2406** [comment]
probably, update on the way.

**Comment by matklad** [comment]
Question: why these tests pass Cargo's own CI, which uses stable, in the first place?

**Comment by Eh2406** [comment]
@matklad I don't fully understand ether, the best explanation so far is https://github.com/rust-lang/cargo/issues/5648#issuecomment-400063521

**Comment by alexcrichton** [comment]
Hm I agree with @matklad that it's a little worrisome how these tests are passing today. Could we perhaps:

* Unconditionally set the release channel to "stable" for all tests
* Have specific tests opt-out to using the nightly/dev version of Cargo

That way we should proactively catch this and it's clear which tests are opting in to nightly?

**Comment by Eh2406** [comment]
@alexcrichton I do not, at this time, know this stuff well enough to make that happen. When we have a plan of action, someone could give mentoring instructions, or just submit an alternative PR. I made this PR as a quick fix, I was unclear if this was a crises (like blocking the 1.27 release.) that needed a fix before the knowledgeable people returned.

**Comment by alexcrichton** [comment]
@Eh2406 oh no worries! I can try to help guide you through this if you want as well.

It actually looks like we [already do this](https://github.com/rust-lang/cargo/blob/9e4845e6ba2d3bdfc8b8d7028100afc47ba5597c/tests/testsuite/cargotest/mod.rs#L128-L131) for everything using `project(...)` and invoking the Cargo executable. In that sense this may be exclusive to these tests which *aren't* using that and may just mean that `new_config` needs to change?

**Comment by Eh2406** [comment]
Can we just call `set_var` in that method or will other test get to see that we changed it?

**Comment by ehuss** [comment]
One idea to ensure everything tests on stable by default is to change this line to "stable":

https://github.com/rust-lang/cargo/blob/9e4845e6ba2d3bdfc8b8d7028100afc47ba5597c/src/cargo/core/features.rs#L368

I tested it, and only the tests fixed in this PR fail.  That way, unittests that need nightly will be be explicit (either by overriding the channel or just ignoring the test).

**Comment by Eh2406** [comment]
@ehuss dose that means that cargo built from source does not allow nightly things?

**Comment by ehuss** [comment]
> @ehuss dose that means that cargo built from source does not allow nightly things?

Ah, yea, that probably would be annoying.  Nevermind. 😛

**Comment by Eh2406** [comment]
I tried `.unwrap_or_else(|| String::from(if cfg!(test) {"stable"} else {"dev"} ))` but tests in the `cfg!(test)` is false for tests in `cargo\tests` directory. So that is a nogo.

**Comment by Eh2406** [comment]
Also this is buggy as `nightly_features_allowed` != `is_nightly`. I was wrong. `is_nightly` checks if `rustc` can compile nightly things. We want `nightly_features_allowed` that checks if `cargo` can use nightly things. But it is not worth fixing If we are going to use a different approach.

**Comment by alexcrichton** [comment]
Could a global variable be added to `src/cargo/core/features.rs` with a function like `disable_nightly_features()`? That way all these tests would call that function (or the helper all these tests use would call that function). I think that'd be relatively uninvasive?

**Comment by Eh2406** [comment]
@alexcrichton I don't quite understand your suggestion. Witch is ok, you could elaborate or make an alternative PR, whichever is easier for you.

The design constraints I see are:
1. test see "stable" unless they opt out. (or we are likely to regress on this with the next nightly thing.)
2. test do not get to see the setting from previous test. (or debugging with bee a nightmare.)
3. a `cargo build` gives a binary that has nightly things. (or developing new feachers with be hard.)

So I think you are suggesting a global mutable variable, that defaults to "dev" (so we get 3) and can be changed to "stable" using the helper function `disable_nightly_features`. Isn't that the wrong default for 1, and how do we ensure it is reset between test for 2?

**Comment by alexcrichton** [comment]
Ah yes those constraints are indeed correct! I think my idea wasn't quite what we wanted but I whipped this up -- https://gist.github.com/alexcrichton/9c878e9d1c81a1956af9323657dacf2b -- which is somewhat similar. I think that should solve everything?

**Comment by Eh2406** [comment]
Clever!
