### PR TITLE
Use locked_version more

### LINKED ISSUE #10391: Unhelpful error message when lockfile prevents version matching
### Problem

If `Cargo.lock` pins version 1.x.y of a dependency, and `--locked` or `--frozen` is passed, but 1.x.y is not available in the underlying registry, the error Cargo produces is fairly confusing. For example:
```
error: failed to select a version for the requirement `autocfg = "^1"`
candidate versions found which didn't match: 1.1.0
```
Nothing in the error mentions the lockfile or the use of `--locked` or `--frozen`.

### Steps

```console
$ cargo new --bin issue
$ cd issue
$ echo 'autocfg = "<1.1.0"' >> Cargo.toml
$ cargo generate-lockfile
$ cp Cargo.lock Cargo.lock.orig
$ sed -i.bkp 's/<1.1.0/1/' Cargo.toml
$ mkdir -p .cargo
$ cargo vendor > .cargo/config
$ cp Cargo.lock.orig Cargo.lock
$ cargo check --frozen # also happens with --locked
error: failed to select a version for the requirement `autocfg = "^1"`
candidate versions found which didn't match: 1.1.0
location searched: directory source `/local/home/jongje/issue/vendor` (which is replacing registry `crates-io`)
required by package `issue v0.1.0 (/local/home/jongje/issue)`
perhaps a crate was updated and forgotten to be re-vendored?
```

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
cargo 1.58.0 (f01b232bc 2022-01-19)
release: 1.58.0
commit-hash: f01b232bc7f4d94f0c4603930a5a96277715eb8c
commit-date: 2022-01-19
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Amazon Linux AMI 2.0.0 [64-bit]
```

### PR DESCRIPTION
**Pull request by Eh2406**
In #9847 we added better tracking for when a requirement came from a lockfile. This uses that tracking in a few more error messages.

Closes #10391

### CODE REVIEW

File: tests/testsuite/directory.rs [hunk 1]
```diff
@@ -762,7 +762,7 @@ fn version_missing() {
 error: failed to compile [..]
 
 Caused by:
-  failed to select a version for the requirement `foo = \"^2\"`
+  failed to select a version for the requirement `foo = \"^2\"`
```
Comment (alexcrichton) [inline tests/testsuite/directory.rs:765]: Could this avoid having trailing whitespace in the error messages? (most editors I know of remove trailing whitespace which will otherwise make editing these files pretty difficult

**Review by alexcrichton — COMMENTED** [review]
Nice! Could you gist a snippet of what the new error messages look like and/or update or add a test to show off the new messages?

**Comment by Eh2406** [comment]
I fixed the white space. Our existing error message testing is pretty slim. I will work on adding the test tomorrow.

**Comment by Eh2406** [comment]
I have not yet turned this into a test, but as an anecdote following the steps in #10391
master gives:
```
error: failed to select a version for the requirement `autocfg = "^1"`
candidate versions found which didn't match: 1.0.1
location searched: directory source `/local/home/jfinkelm/Cargo/issue/vendor` (which is replacing registry `crates-io`)
required by package `issue v0.1.0 (/local/home/jfinkelm/Cargo/issue)`
perhaps a crate was updated and forgotten to be re-vendored?
```
Pr gives:
```
error: failed to select a version for the requirement `autocfg = "^1"` (locked to 1.1.0)
candidate versions found which didn't match: 1.0.1
location searched: directory source `/local/home/jfinkelm/Cargo/issue/vendor` (which is replacing registry `crates-io`)
required by package `issue v0.1.0 (/local/home/jfinkelm/Cargo/issue)`
perhaps a crate was updated and forgotten to be re-vendored?
```

**Comment by alexcrichton** [comment]
@bors: r+

👍
