### PR TITLE
fix(embedded): Always generate valid package names

### LINKED ISSUE #12330: cargo -Zscript uses invalid package names when the file name starts with a digit
### Problem

When the file name starts with a digit, e.g. `0.rs`, `cargo -Zscript 0.rs` defaults the package name to `-0` and fails

### Steps

```bash
echo 'fn main() {}' > 0.rs
cargo -Zscript 0.rs
```

```console
warning: `package.edition` is unspecifiead, defaulting to `2021`
error: failed to parse manifest at `<...>/0.rs`

Caused by:
  invalid character `-` in package name: `-0`, the first character must be a Unicode XID start character (most letters or `_`)
```

### Possible Solution(s)

When the first character of the file name is invalid, insert `_` instead of `-`, which makes the package name valid. So for `0.rs`, the package name would default to `_0`. This is #12329's approach

### Notes

Related: #12207, https://github.com/rust-lang/cargo/pull/12329#issuecomment-1620857167

### Version

```text
cargo 1.72.0-nightly (5b377cece 2023-06-30)
release: 1.72.0-nightly
commit-hash: 5b377cece0e0dd0af686cf53ce4637d5d85c2a10
commit-date: 2023-06-30
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: NixOS 23.11.0 [64-bit]
```

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

The sanitization logic uses a placeholder for the first character that isn't valid in the first character position.  #12329 took the approach of always using `_` which has the problem of mixing separators if the user used `-` or we had other placeholders to insert.  Instead, this takes the approach of stripping the leading invalid characters and using a placeholder name if nothing is left.

Fixes #12330

### How should we test and review this PR?

Per-commit.  The first adds tests so the change in behavior can be observed over each additional commit.

### Additional information

I was also hoping to make the binary name not use placeholders by setting `bin.name` to `file_stem` but then I got
```
   Compiling s-h-w-c- v0.0.0 (/home/epage/src/personal/cargo/target/tmp/cit/t133/foo)
error: invalid character `'.'` in crate name: `s_h.w§c!`

error: invalid character `'§'` in crate name: `s_h.w§c!`

error: invalid character `'!'` in crate name: `s_h.w§c!`

error: could not compile `s-h-w-c-` (bin "s-h.w§c!") due to 3 previous errors
```
I decided to not get into what are or aren't valid characters according to rustc.

### CODE REVIEW

File: src/cargo/util/restricted_names.rs [hunk 1]
```diff
@@ -87,23 +87,22 @@ pub fn validate_package_name(name: &str, what: &str, help: &str) -> CargoResult<
...
-    for ch in chars {
+    while let Some(ch) = chars.next() {
         if unicode_xid::UnicodeXID::is_xid_continue(ch) || ch == '-' {
             slug.push(ch);
         } else {
             slug.push(placeholder);
         }
     }
+    if slug.is_empty() {
+        slug.push_str("package");
```
Comment (weihanglo) [inline src/cargo/util/restricted_names.rs:104]: I might prefer `script` but never mind it's not a big deal.

**Review by weihanglo — APPROVED** [review]
Looks reasonable. Thanks!

File: src/cargo/util/restricted_names.rs (hunk 1 above)
Comment (epage) [reply src/cargo/util/restricted_names.rs:104]: I'm avoiding "script" in user-facing contexts because I feel it can be misleading.

Comment (epage) [reply src/cargo/util/restricted_names.rs:104]: I'm avoiding "script" in user-facing contexts because I feel it can be misleading.
