### PR TITLE
Fix confusing error messages when using -Zsparse-registry

### LINKED ISSUE #11277: sparse-registry errors talk about "replaced source registry"
### Problem

Errors when sparse-registry is enabled talk about a "replaced source", which I think is confusing. For example:

```
    Updating crates.io index
error: failed to select a version for the requirement `bitflags = "^3"`
candidate versions found which didn't match: 1.3.2, 1.3.1, 1.2.1, ...
location searched: crates.io index (which is replacing registry `crates-io`)
required by package `z20 v0.1.0 (/Users/eric/Temp/z20)`
perhaps a crate was updated and forgotten to be re-vendored?
```

I think when sparse-registry is enabled that it shouldn't behave as-if it is a replacement. I'm not sure if this is unique to how crates-io is implemented. Is there some way we can work around this?

### Steps

Perform an action that would trigger one of the errors in https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/replaced.rs. For example:

1. `cargo new foo`
2. `cd foo`
3. `echo 'bitflags = "99"' >> Cargo.toml`
4. `cargo generate-lockfile -Zsparse-registry`

### Possible Solution(s)

_No response_

### Notes

cargo 1.66.0-nightly (3ff044334 2022-10-17)
release: 1.66.0-nightly
commit-hash: 3ff044334f0567ce1481c78603aeee7211b91623
commit-date: 2022-10-17
host: x86_64-apple-darwin
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.79.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.6.0 [64-bit]

### Version

_No response_

### PR DESCRIPTION
**Pull request by arlosi**
Built-in replacements of crates.io have confusing a description:
> crates.io index (which is replacing registry `crates-io`)

This adds a special case for built-in source replacements of `crates-io`. User-defined replacements of crates.io continue to use the existing description.

Also fixes the test framework `__CARGO_TEST_CRATES_IO_URL_DO_NOT_USE_THIS` variable to strip the `sparse+` prefix when checking if a url `is_crates_io`.

Fixes #11277

### CODE REVIEW

File: src/cargo/sources/replaced.rs [hunk 1]
```diff
@@ -100,11 +100,15 @@ impl<'cfg> Source for ReplacedSource<'cfg> {
     }
 
     fn describe(&self) -> String {
-        format!(
-            "{} (which is replacing {})",
-            self.inner.describe(),
-            self.to_replace
-        )
+        if self.replace_with.is_crates_io() {
+            self.inner.describe()
```
Comment (weihanglo) [inline src/cargo/sources/replaced.rs:104]: Should we explain somewhere what's going on and why we need this special case? It's not clear why a source is replaced with crates.io and doesn't need to display the replacement to users.

**Review by weihanglo — COMMENTED** [review]
Thanks for the fix. 

One sort-of off-topic question: Will it be possible to ditch `ReplacedSource` in the future once sparse registry gets stabilized?

**Review by weihanglo — APPROVED** [review]
Looks nice. Thank you!
