### PR TITLE
Don't abort resolution on transitive updates 

### LINKED ISSUE #4127: Transitive minor updates of deps shouldn't fail `cargo update`
Let's say you've got the following project structure:

* Top level project, A
* A depends on `log = "0.3.6"`
* A depends on B, a sub-project in this same directory
* B depends on `log = "0.3.6"`

When you generate a lock file for this project let's say you get `log = "0.3.6"`. If you then later edit B's `Cargo.toml` to instead say `log = "0.3.8"` then if you run `cargo update -p a` Cargo will inform you:

```
error: failed to select a version for `log` (required by `b`):
all possible versions conflict with previously selected versions of `log`
  version 0.3.6 in use by log v0.3.6
  possible versions to select: 0.3.8
```

Cargo should gracefully handle this and not generate an error!

I'm not sure whether this is 100% related to path dependencies. Some more info can also be [found here](https://bugzilla.mozilla.org/show_bug.cgi?id=1361005).

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit is directed at fixing #4127, allowing the resolver to automatically
perform transitive updates when required. A few use casese and tagged links are
hanging off #4127 itself, but the crux of the issue happens when you either add
a dependency or update a version requirement in `Cargo.toml` which conflicts
with something listed in your `Cargo.lock`. In this case Cargo would previously
provide an obscure "cannot resolve" error whereas this commit updates Cargo to
automatically perform a conservative re-resolution of the dependency graph.

It's hoped that this commit will help reduce the number of "unresolvable"
dependency graphs we've seen in the wild and otherwise make Cargo a little more
ergonomic to use as well. More details can be found in the source's comments!

Closes #4127

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @Eh2406, most of the work you've been doing has been in the resolver itself and while this only lightly touches the resolver you might be interested to see how lock files interact with the resolver!

File: src/cargo/ops/resolve.rs [hunk 1]
```diff
@@ -325,3 +321,118 @@ fn get_resolved_packages<'a>(resolve: &Resolve,
...
+        }
+        let path = match node.source_id().url().to_file_path() {
+            Ok(path) => path,
+            Err(_) => continue,
+        };
+        let pkg = match ws.load(&path.join("Cargo.toml")) {
+            Ok(p) => p,
+            Err(_) => continue,
+        };
+        for dep in resolve.deps_not_replaced(node) {
```
Comment (matklad) [inline src/cargo/ops/resolve.rs]: So, here we are solving the case of "don't lock potentially changed dependencies". Another similar scenario might happen, I think, when the version of the pacakge itself changes (you literally change Cargo.toml from `[pacakge] name = foo version = 1` to `[package] name = foo version = 2`). So, perhaps we need something like 

```Rust
if pkg.package_id() != node {
  avoid_locking.insert(node);
}
```

is needed as well?

File: tests/testsuite/update.rs [hunk 2]
```diff
@@ -0,0 +1,149 @@
...
+        .publish();
+
+    // Note that `serde` isn't actually updated here! The default behavior for
+    // `update` right now is to as conservatively as possible attempt to satisfy
+    // an update. In this case we previously locked the dependency graph to `log
+    // 0.1.0`, but nothing on the command line says we're allowed to update
+    // that. As a result the update of `serde` here shouldn't update to `serde
+    // 0.1.1` as that would also force an update to `log 0.1.1`.
+    //
+    // Also note that this is probably counterintuitive and weird. We may wish
```
Comment (matklad) [inline tests/testsuite/update.rs]: Most definitely weird. Would be producing a warning here challenging?

**Comment by Eh2406** [comment]
Thanks for the cc!

In general I am really glad this bug is getting dealt with! I have helped a number of persons on irc with this. Most recently, I depend on `A` witch depends on `B`. Now I, for some inexplicable reason, want to specify a version of `B` that is not the one in the lock file. So I add `B = "=..."` to the toml and done. Well not done, hit this bug. But regenerate the lock file and done.

File: src/cargo/ops/resolve.rs [hunk 3]
```diff
@@ -325,3 +321,118 @@ fn get_resolved_packages<'a>(resolve: &Resolve,
...
+            add_deps(resolve, node, &mut avoid_locking);
+            continue
+        }
+        let path = match node.source_id().url().to_file_path() {
+            Ok(path) => path,
+            Err(_) => continue,
+        };
+        let pkg = match ws.load(&path.join("Cargo.toml")) {
+            Ok(p) => p,
+            Err(_) => continue,
```
Comment (matklad) [inline src/cargo/ops/resolve.rs]: So, this looks for path dependencies, already present in resolve. But about newly added path dependencies? They probably would be handled when their parent crate is processed. Hm, nope, the following test fails:

```Rust
#[test]
fn update_via_new_dep() {
    Package::new("log", "0.1.0").publish();
    let p = project("foo")
        .file("Cargo.toml", r#"
            [package]
            name = "bar"
            version = "0.0.1"
            authors = []

            [dependencies]
            log = "0.1"
            # foo = { path = "foo" }
        "#)
        .file("src/lib.rs", "")
        .file("foo/Cargo.toml", r#"
            [package]
            name = "foo"
            version = "0.0.1"
            authors = []

            [dependencies]
            log = "0.1.1"
        "#)
        .file("foo/src/lib.rs", "")
        .build();

    assert_that(p.cargo("build"), execs().with_status(0));
    Package::new("log", "0.1.1").publish();

    File::create(p.root().join("Cargo.toml")).unwrap().write_all(br#"
        [package]
        name = "bar"
        version = "0.0.1"
        authors = []

        [dependencies]
        log = "0.1"
        foo = { path = "foo" }
    "#).unwrap();

    assert_that(p.cargo("build"), execs().with_status(0));
}
```


A similar situation happens when you add a new workspace member (which isn't necessary a path dependency of anything):

```rust
#[test]
fn update_via_new_member() {
    Package::new("log", "0.1.0").publish();
    let p = project("foo")
        .file("Cargo.toml", r#"
            [package]
            name = "bar"
            version = "0.0.1"
            authors = []

            [workspace]
            # members = [ "foo" ]

            [dependencies]
            log = "0.1"
        "#)
        .file("src/lib.rs", "")
        .file("foo/Cargo.toml", r#"
            [package]
            name = "foo"
            version = "0.0.1"
            authors = []

            [dependencies]
            log = "0.1.1"
        "#)
        .file("foo/src/lib.rs", "")
        .build();

    assert_that(p.cargo("build"), execs().with_status(0));
    Package::new("log", "0.1.1").publish();

    File::create(p.root().join("Cargo.toml")).unwrap().write_all(br#"
            [package]
            name = "bar"
            version = "0.0.1"
            authors = []

            [workspace]
            members = [ "foo" ]

            [dependencies]
            log = "0.1"
    "#).unwrap();

    assert_that(p.cargo("build"), execs().with_status(0));
}
```

**Comment by alexcrichton** [comment]
Some excellent thinking! This is gonna be a trick one... I think that would [explain this as well](https://botbot.me/mozilla/cargo/2018-03-14/?msg=97813003&page=3) where it seems that empirically this patch doesn't handle everything. I don't think it's 100% related to only adding new path dependencies as well, on IRC I believe it was just adding a dependency locally to a preexisting package. I'll try to come up with a test case for that as well before pushing another update.

As to how to fix this... I'm not sure! Unfortunately the logic for preferring previous version isn't quite so easy as it also affects whether we update a source (aka print `Updating registry ...`) which is something we generally avoid at all costs. The way the lockfile interacts with resolve has grown more and more complicated over time, so it's difficult to imagine a hugely different way to do it at this point. I'm gonna see if I can tack it on, hopefully there's something salvageable here...

File: tests/testsuite/update.rs (hunk 2 above)
Comment (alexcrichton) [reply tests/testsuite/update.rs]: Yeah for now I think we want to keep this as is (afaik we've never gotten a bug report about this?) and is "easily fixable" with `cargo update --aggressive`, albeit not exactly a discoverable solution.

**Comment by alexcrichton** [comment]
Ok I've pushed an update which I believe should be much more robust yet still preserve Cargo's original properties (and also fixes #5182 to boot).

I think that this commit is basically starting to hammer the nails in the coffin for the current strategy of dealing with lock files. At a fundamental level if you add *any* dependency then you have to reresolve the entire dependency graph as that new dependency could bring in anything from any source, conflicting with a previous activation that we don't actually want to conflict. 

This iteration leverages @matklad's idea of leveraging the "sort candidates based on whether they were previously in  the lock file" idea. If any dependency isn't resolvable with the current set of packages in the lock file then the dependency's source is "poisoned" in the lock file. All lock file entries from the same source aren't actually locked (aka become candidate for update). We still try to avoid updating most of them via the sorting strategy, however.

I realized as I was typing this up, however, that this still isn't quite right. While I think it's unambiguously better than what we have today it still doesn't handle cases, for example, where you add a git dependency which then adds new constraints on crates.io dependencies.

**Comment by alexcrichton** [comment]
I think I'd prefer to fix what's here and land it now as I think it's a huge improvement over what we have today (sometimes you add a crates.io dependency and Cargo refuses to budge). Fixing the git issue I think is going to be very invasive...

File: src/cargo/core/resolver/mod.rs [hunk 4]
```diff
@@ -675,10 +709,16 @@ impl<'a> RegistryQueryer<'a> {
...
-        // When we attempt versions for a package, we'll want to start at
-        // the maximum version and work our way down.
+        // When we attempt versions for a package we'll want to do so in a
+        // sorted fashion to pick the "best candidates" first. Currently we try
+        // prioritized summaries (those in `try_to_use`) and failing that we
+        // list everything from the maximum version to the lowest version.
         ret.sort_unstable_by(|a, b| {
-            b.summary.version().cmp(a.summary.version())
+            let a_in_previous = self.try_to_use.contains(a.summary.package_id());
+            let b_in_previous = self.try_to_use.contains(b.summary.package_id());
```
Comment (matklad) [inline src/cargo/core/resolver/mod.rs]: Hm, maybe let’s change try_to_use to hash set to have better O?

File: src/cargo/ops/resolve.rs [hunk 5]
```diff
@@ -325,3 +320,140 @@ fn get_resolved_packages<'a>(resolve: &Resolve,
...
+    let mut visited = HashSet::new();
+    while let Some(member) = path_deps.pop() {
+        if !visited.insert(member.package_id().clone()) {
+            continue
+        }
+        for dep in member.dependencies() {
+            let source = dep.source_id();
+
+            // If this is a path dependency then try to push it onto our worklist
+            if let Ok(path) = source.url().to_file_path() {
```
Comment (matklad) [inline src/cargo/ops/resolve.rs]: Note that the comment is not 100% accurate. In particular, git dependencies for local repositories will also pass this check! This I think is important, because the git dependencies in Cargo own tests are local, and, so, during the tests, would use a non-realistic code path. Lets add an `if source.is_path()` condition, which checks `kind`?

**Comment by matklad** [comment]
r=me with https://github.com/rust-lang/cargo/pull/5180#discussion_r174693916 and https://github.com/rust-lang/cargo/pull/5180#discussion_r174682700 addressed

File: src/cargo/core/resolver/mod.rs (hunk 4 above)
Comment (alexcrichton) [reply src/cargo/core/resolver/mod.rs]: Ah it is indeed here! The argument coming in is a slice but it's switched to a `HashSet` for precisely this reason :)

**Comment by Eh2406** [comment]
@alexcrichton you may want to do a perf run with `x.py` incase this removes some optimizations. Specifically I think, a lot more deps with `has_another` leading to more clones.

**Comment by alexcrichton** [comment]
@Eh2406 true! My intention, though, was that this behavior (aka lots more `has_another`) only happens when the dependency graph changes, in theory none of this logic should kick in if manifests are unchanged

**Comment by alexcrichton** [comment]
Ok yeah looks like `./x.py` isn't much slower, and the `perf` run shows cloning nowhere near the top.

It still takes 4 seconds for a null build, which is crazy long, but that's another problem for another day

**Comment by Eh2406** [comment]
Thanks for checking!
