### PR TITLE
Document the lib if a lib and bin have the same name

### LINKED ISSUE #4341: For a package where a library and a binary have the same name, have `cargo doc` ignore the bin
Ok, so it's a common pattern (and one we use a bunch in the book) to have both a `src/lib.rs` and a `src/main.rs` and have the binary crate use the library crate.

[Unfortunately](https://github.com/rust-lang/book/issues/847), when you run `cargo doc` in one of these projects, you get:

```
error: cannot document a package where a library and a binary have the same name. Consider
renaming one or marking the target as `doc = false`
```

Those suggestions work; moving `src/main.rs` to `src/bin/main.rs` also lets you `cargo doc` the library.

But this is Yet Another Thing, with 3 options on how to fix it with no clear "best" option for a beginner (I went with moving main into bin for the book, I think that's easiest).

And since documenting binary crates isn't valid *anyway*, are there any reasons why, in this situation with a lib and a bin crate with the same name, `cargo doc` couldn't ignore the binary crate and happily document the lib crate?

### PR DESCRIPTION
**Pull request by carols10cents**
Fixes #4341, as discussed in that issue.

- Removes the check that bailed if there was a  bin and lib with the
  same name
- Exclude bins with the same name as libs from the proposed targets to
  build when compiling docs
- Adjust tests to expect this behavior

### CODE REVIEW

File: tests/doc.rs [hunk 1]
```diff
@@ -267,12 +269,17 @@ fn doc_multiple_targets_same_name() {
...
-                    .with_stderr_contains("[..] target `foo_lib` [..]")
-                    .with_stderr_contains("[..] binary by package `foo v0.1.0[..]`[..]")
-                    .with_stderr_contains("[..] library by package `bar v0.1.0[..]` [..]"));
+                    .with_status(0)
+                    .with_stderr_contains(&format!("[DOCUMENTING] foo v0.1.0 ({}[/]foo)", root))
+                    .with_stderr_contains(&format!("[DOCUMENTING] bar v0.1.0 ({}[/]bar)", root))
+                    .with_stderr_contains("[FINISHED] dev [unoptimized + debuginfo] target(s) in [..]"));
+        assert_that(&p.root().join("target/doc"), existing_dir());
+        let doc_file = p.root().join("target/doc/foo_lib/index.html");
+        assert_that(&doc_file, existing_file());
```
Comment (matklad) [inline tests/doc.rs]: 👍 ❤️

File: tests/rustdoc.rs [hunk 2]
```diff
@@ -147,7 +147,7 @@ fn rustdoc_only_bar_dependency() {
 
 
 #[test]
-fn rustdoc_same_name_err() {
+fn rustdoc_same_name_documents_lib() {
```
Comment (matklad) [inline tests/rustdoc.rs]: Wow, I didn't realize we have separate `cargo doc` and `cargo rustdoc` commands!

**Comment by carols10cents** [comment]
> What do you think about adding a tests, where bin and lib have the same name, but you invoke cargo doc as cargo doc --lib and cargo doc --bin? Presumably, these forms should both work?

I'm into it! I tested them manually and they work, will add tests :)

File: tests/rustdoc.rs (hunk 2 above)
Comment (carols10cents) [reply tests/rustdoc.rs]: Yup! 🤷‍♀️

**Comment by carols10cents** [comment]
More tests for you @matklad! ❤️

**Comment by matklad** [comment]
Tests always make me happy, yay!

@bors r+

**Comment by carols10cents** [comment]
ummmmm why is this failing on appveyor...?

```
---- build_script_needed_for_host_and_target stdout ----
	thread 'build_script_needed_for_host_and_target' panicked at 'Cannot cross compile to i686-pc-windows-msvc.
This failure can be safely ignored. If you would prefer to not see this
failure, you can set the environment variable CFG_DISABLE_CROSS_TESTS to "1".
Alternatively, you can install the necessary libraries for cross-compilation with
    rustup target add i686-pc-windows-msvc
', tests\cargotest\support\cross_compile.rs:88:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    build_script_needed_for_host_and_target
test result: FAILED. 18 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
error: test failed, to rerun pass '--test cross-compile'
Command exited with code 101
```

Shouldn't appveyor have `i686-pc-windows-msvc`...?

**Comment by matklad** [comment]
@carols10cents failure seems legit, but mysterious. 

```
failures:
---- doc_multiple_targets_same_name stdout ----
	running `C:\projects\cargo\target\debug\cargo.exe doc --all`
thread 'doc_multiple_targets_same_name' panicked at '
Expected: execs
    but: expected to find:
[DOCUMENTING] foo v0.1.0 (file:///C:/projects/cargo/target/cit/t10/foo[/]foo)
did not find in output:
 Documenting bar v0.1.0 (file:///C:/projects/cargo/target/cit/t10/foo/bar)
 Documenting foo v0.1.0 (file:///C:/projects/cargo/target/cit/t10/foo/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.68 secs
', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\hamcrest-0.1.1\src\core.rs:31:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by matklad** [comment]
>@carols10cents failure seems legit, but mysterious.

Ah, I think I know what's going on: the real code prints paths with `/`, despite the fact that we are on windows. There then check for `[/]` which is translated to `\` on windows. Looks like this is a bug, `DOCUMENTING` messages should ideally use `\` on window.

**Comment by carols10cents** [comment]
ahhhh i'll take out the square brackets and file a bug for the bug.
