### PR TITLE
fix: detect circular publish dependency cycle in workspace publish

### LINKED ISSUE #16682: "timed out waiting for  to be available in registry `crates-io`"
### Problem

I started using `cargo publish --workspace` and while it seemed to have worked, I hit a timeout. I suppose that can happen, but the warning emitted seems to lack details that should have been there:
> warning: timed out waiting for  to be available in registry `crates-io`

I suppose it should list one more or crates instead of `<nothing>`?

### Steps

See https://github.com/d-e-s-o/gui/actions/runs/22526759569/job/65260128474

[logs_58907019893.zip](https://github.com/user-attachments/files/25638203/logs_58907019893.zip)

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
rustc 1.93.1 (01f6ddf75 2026-02-11)
```

### PR DESCRIPTION
**Pull request by raushan728**
Fixes #16682

### What does this PR try to resolve?
Detects circular publish dependency early and bails 
with a clear error instead of silently timing out 
with a blank warning message.

### CODE REVIEW

File: tests/testsuite/publish.rs [hunk 1]
```diff
@@ -4595,3 +4595,80 @@ Caused by:
...
+
+#[cargo_test]
+fn workspace_circular_publish_dependency() {
+    let registry = registry::RegistryBuilder::new()
+        .http_api()
+        .http_index()
+        .build();
+
+    cargo_test_support::registry::Package::new("foo", "0.1.0").publish();
+    cargo_test_support::registry::Package::new("bar", "0.1.0").publish();
```
Comment (epage) [inline tests/testsuite/publish.rs:4608]: Do we need these for the test?

File: src/cargo/ops/registry/publish.rs [hunk 2]
```diff
@@ -197,6 +197,19 @@ pub fn publish(ws: &Workspace<'_>, opts: &PublishOpts<'_>) -> CargoResult<()> {
         // the following pass through the outer loop nothing will be ready for
         // upload.
         let mut ready = plan.take_ready();
+
+        if ready.is_empty() && to_confirm.is_empty() {
+            let unpublishable = package_list(plan.iter(), "and");
+            bail!(
+                "circular dependency detected while publishing {}\n\
+                 hint: a dev-dependency with a `version` field \
+                 creates a publish cycle\n\
```
Comment (epage) [inline src/cargo/ops/registry/publish.rs]: This would be a `note:`

File: src/cargo/ops/registry/publish.rs [hunk 3]
```diff
@@ -197,6 +197,19 @@ pub fn publish(ws: &Workspace<'_>, opts: &PublishOpts<'_>) -> CargoResult<()> {
...
+                 hint: remove the `version` field from the \
+                 dev-dependency to fix this (see https://github.com/rust-lang/cargo/issues/4242)",
```
Comment (epage) [inline src/cargo/ops/registry/publish.rs]: This would be a `help:`

File: tests/testsuite/publish.rs [hunk 4]
```diff
@@ -4662,12 +4662,9 @@ fn workspace_circular_publish_dependency() {
...
 [PACKAGED] 4 files, [FILE_SIZE]B ([FILE_SIZE]B compressed)
-[NOTE] waiting for  to be available at registry `crates-io`.
-      2 remaining crates to be published
-[WARNING] timed out waiting for  to be available in registry `crates-io`
-  |
-  = [NOTE] the registry may have a backlog that is delaying making the crates available. The crates should be available soon.
-[ERROR] unable to publish bar v0.1.1 and foo v0.1.1 due to a timeout while waiting for published dependencies to be available.
+[ERROR] circular dependency detected while publishing bar v0.1.1 and foo v0.1.1
+hint: a dev-dependency with a `version` field creates a publish cycle
+hint: remove the `version` field from the dev-dependency to fix this (see https://github.com/rust-lang/cargo/issues/4242)
```
Comment (epage) [inline tests/testsuite/publish.rs]: These presuppose that the cycle involves a dev-dependency.  They also feel a bit redundant

maybe

```
help: to break a cycle between dev-dependencies and other dependencies, remove the version field on the dev-dependency so it will be implicitly stripped it on publish
```

File: src/cargo/ops/registry/publish.rs [hunk 5]
```diff
@@ -197,6 +197,19 @@ pub fn publish(ws: &Workspace<'_>, opts: &PublishOpts<'_>) -> CargoResult<()> {
         // the following pass through the outer loop nothing will be ready for
         // upload.
         let mut ready = plan.take_ready();
+
+        if ready.is_empty() && to_confirm.is_empty() {
```
Comment (epage) [inline src/cargo/ops/registry/publish.rs]: > A quick fix is to turn "nothing to block on" into an error, assuming its a cycle. This however can mean that people are in a partially-published state. The idea situation is to detect this before publish.

Is there a reason you did the check here, in this way, rather than what was mentioned?

Is there a reason you didn't do the check before any publishes like this also mentions?

File: tests/testsuite/publish.rs (hunk 1 above)
Comment (raushan728) [reply tests/testsuite/publish.rs:4608]: these lines are actually needed. Without pre-seeding the registry with foo v0.1.0 and bar v0.1.0, Cargo fails during packaging with 
"no matching package named bar found" before reaching the circular dependency check

**Comment by raushan728** [comment]
I moved the cycle detection before the publish loop by adding a has_cycles() method to PublishPlan that checks if all packages have unmet dependencies 
(weight > 0) but none are ready.

This way the error is thrown before any crate gets published, avoiding a partially-published state.

File: src/cargo/ops/registry/publish.rs [hunk 6]
```diff
@@ -190,13 +190,35 @@ pub fn publish(ws: &Workspace<'_>, opts: &PublishOpts<'_>) -> CargoResult<()> {
...
         let mut ready = plan.take_ready();
+
+        if ready.is_empty() {
+            // This situation should not be a circular dependency,
+            // since those are caught before the loop.
+            // It could be that waiting for confirmation timed out, or something else.
+            // But if `waiting` does not unlock anything, it might just break.
+            break;
+        }
+
```
Comment (epage) [inline src/cargo/ops/registry/publish.rs:223]: iirc there are valid reasons to have an empty `ready`.  It's an empty wait that is invalid.  If we want to catch that, we likely should report an `InternalError` rather than silently moving on.

File: src/cargo/ops/registry/publish.rs [hunk 7]
```diff
@@ -190,13 +190,35 @@ pub fn publish(ws: &Workspace<'_>, opts: &PublishOpts<'_>) -> CargoResult<()> {
...
+    if plan.has_cycles() {
+        let unpublishable = package_list(plan.iter(), "and");
+        bail!(
+            "circular dependency detected while publishing {}\n\
+             help: to break a cycle between dev-dependencies \
+             and other dependencies, remove the version field \
+             on the dev-dependency so it will be implicitly \
+             stripped on publish",
+            unpublishable
+        );
```
Comment (epage) [inline src/cargo/ops/registry/publish.rs]: Would be nice to be more precise on the cycle

File: tests/testsuite/publish.rs [hunk 8]
```diff
@@ -4595,3 +4595,80 @@ Caused by:
 "#]])
         .run();
 }
+
+#[cargo_test]
+fn workspace_circular_publish_dependency() {
```
Comment (epage) [inline tests/testsuite/publish.rs:4600]: We should have a test with a cycle that depends on packages that are not part of the cycle.

**Comment by raushan728** [comment]
- Added cycle_members() to report only packages 
   actually forming the cycle, not all blocked ones
-  Replaced break with crate::util::internal() 
   for unexpected empty ready state
- Added a second test verifying non-cycle package 
   is not mentioned in the error

File: tests/testsuite/publish.rs [hunk 9]
```diff
@@ -4662,12 +4664,101 @@ fn workspace_circular_publish_dependency() {
...
-  = [NOTE] the registry may have a backlog that is delaying making the crates available. The crates should be available soon.
-[ERROR] unable to publish bar v0.1.1 and foo v0.1.1 due to a timeout while waiting for published dependencies to be available.
+[ERROR] circular dependency detected while publishing bar v0.1.1 and foo v0.1.1
+[HELP] to break a cycle between dev-dependencies and other dependencies, remove the version field on the dev-dependency so it will be implicitly stripped on publish
+
+"#]])
+        .run();
+}
+#[cargo_test]
+fn workspace_circular_publish_dependency_with_non_cycle_package() {
```
Comment (epage) [inline tests/testsuite/publish.rs:4672]: This needs to be on the commit before

Comment (raushan728) [reply tests/testsuite/publish.rs:4672]: > This needs to be on the commit before

Done! Moved it to the first commit along with 
the other test. Both tests now show the broken 
timeout behavior in commit 1, and commit 2 
updates them with the fixed output.

File: tests/testsuite/publish.rs (hunk 8 above)
Comment (epage) [reply tests/testsuite/publish.rs:4600]: The latest commits add:
- a -> b
- b -> a
- c -> b

What I was asking for was
- a -> b, c
- b -> a, c
- c

Comment (raushan728) [reply tests/testsuite/publish.rs:4600]: @epage  the pre-loop check works for the first test (pure cycle), but the second test has c as a standalone package that publishes first.

With only pre-loop check:
- c publishes successfully
- a and b get stuck
- pre-loop check already passed
- hits InternalError instead of cycle detection

First test expected (works with pre-loop check):
[ERROR] circular dependency detected while publishing bar v0.1.1 and foo v0.1.1
[HELP] to break a cycle between dev-dependencies and other dependencies, remove the version field on the dev-dependency so it will be implicitly stripped on publish

Second test expected (fails with pre-loop check):
[ERROR] circular dependency detected while publishing a v1.0.1 and b v1.0.1
[HELP] to break a cycle between dev-dependencies and other dependencies, remove the version field on the dev-dependency so it will be implicitly stripped on publish

Should we add has_cycles() check inside the loop after mark_confirmed? —  I checked and the test passes

Please look current code of second test which are passed with this current code 

Appreciate your guidance

Comment (epage) [reply tests/testsuite/publish.rs:4600]: I think the problem is that the pre-loop check is only checking for loops within the first batch of packages and not checking for all loops.

Comment (raushan728) [reply tests/testsuite/publish.rs:4600]: The pre-loop check misses the case where c 
publishes first and a, b are left in a cycle.

This is because has_cycles() returns false when 
c has weight 0, even though a and b form a cycle.

Should I fix has_cycles() to use cycle_members():

fn has_cycles(&self) -> bool {
    !self.cycle_members().is_empty()
}

This way the pre-loop check will correctly detect 
cycles even when standalone packages like c exist.
Second test expected output will also need to be 
updated to show circular dependency error instead 
of InternalError

Please guide

**Comment by raushan728** [comment]
@epage  cycle_members() now uses topological sort 
with the original graph (dependent -> dependency).

- c is correctly excluded from cycle members
- Error is reported before any uploads occur

**Comment by raushan728** [comment]
@epage 
cycle_members() now uses topological sort 
with the original graph (dependent -> dependency).

- c is correctly excluded from cycle members
- Error is reported before any uploads occur

**Review by epage — APPROVED** [review]
Thanks!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16722/f7345d66ff247c4dcd5b877b2e8c62a90c44acb9..ad74e1c5160b721132e436ab96832a6e13a0ef7a)*
