### PR TITLE
Prevent the use of "test" as a crate name

### LINKED ISSUE #2432: Can't use `cargo test` to run tests in the "tests" directory if the Cargo project is named "test"
### STR

```
$ cargo new test
$ cd test

### OK
$ cargo test
   Compiling test v0.1.0 (file:///home/japaric/tmp/test)
     Running target/debug/test-c61dbbb1cdb26dbe

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests test

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

### Not OK
$ mkdir tests
$ touch tests/foo.rs
$ cargo test --verbose
   Compiling test v0.1.0 (file:///home/japaric/tmp/test)
     Running `rustc tests/foo.rs --crate-name foo --crate-type bin -g --test -C metadata=4fd43b24d22d2be7 -C extra-filename=-4fd43b24d22d2be7 --out-dir /home/japaric/tmp/test/target/debug --emit=dep-info,link -L dependency=/home/japaric/tmp/test/target/debug -L dependency=/home/japaric/tmp/test/target/debug/deps --extern test=/home/japaric/tmp/test/target/debug/libtest.rlib`
tests/foo.rs:0:1: 0:1 error: unresolved name `test::test_main_static` [E0425]
error: internal compiler error: Error constructed but not emitted
thread panicked while panicking. aborting.
Could not compile `test`.

Caused by:
  Process didn't exit successfully: `rustc tests/foo.rs --crate-name foo --crate-type bin -g --test -C metadata=4fd43b24d22d2be7 -C extra-filename=-4fd43b24d22d2be7 --out-dir /home/japaric/tmp/test/target/debug --emit=dep-info,link -L dependency=/home/japaric/tmp/test/target/debug -L dependency=/home/japaric/tmp/test/target/debug/deps --extern test=/home/japaric/tmp/test/target/debug/libtest.rlib` (signal: 4, SIGILL: illegal instruction)

### More errors
$ echo '#[test] fn ok() {}' > tests/foo.rs
$ cargo test --verbose
   Compiling test v0.1.0 (file:///home/japaric/tmp/test)
     Running `rustc tests/foo.rs --crate-name foo --crate-type bin -g --test -C metadata=4fd43b24d22d2be7 -C extra-filename=-4fd43b24d22d2be7 --out-dir /home/japaric/tmp/test/target/debug --emit=dep-info,link -L dependency=/home/japaric/tmp/test/target/debug -L dependency=/home/japaric/tmp/test/target/debug/deps --extern test=/home/japaric/tmp/test/target/debug/libtest.rlib`
tests/foo.rs:1:1: 1:1 error: unresolved name `test::test_main_static` [E0425]
tests/foo.rs:1 #[test] fn ok() {}
               ^
tests/foo.rs:1:1: 1:1 help: run `rustc --explain E0425` to see a detailed explanation
error: type name `self::test::TestDescAndFn` is undefined or not in scope [E0412]
tests/foo.rs:1:1: 1:1 help: no candidates by the name of `TestDescAndFn` found in your project; maybe you misspelled the name or forgot to import an external crate?
tests/foo.rs:1:9: 1:19 error: `self::test::TestDescAndFn` does not name a structure [E0422]
tests/foo.rs:1 #[test] fn ok() {}
                       ^~~~~~~~~~
tests/foo.rs:1:9: 1:19 help: run `rustc --explain E0422` to see a detailed explanation
tests/foo.rs:1:9: 1:19 error: `self::test::TestDesc` does not name a structure [E0422]
tests/foo.rs:1 #[test] fn ok() {}
                       ^~~~~~~~~~
tests/foo.rs:1:9: 1:19 help: run `rustc --explain E0422` to see a detailed explanation
tests/foo.rs:1:9: 1:19 error: unresolved name `self::test::StaticTestName` [E0425]
tests/foo.rs:1 #[test] fn ok() {}
                       ^~~~~~~~~~
tests/foo.rs:1:9: 1:19 help: run `rustc --explain E0425` to see a detailed explanation
tests/foo.rs:1:9: 1:19 error: failed to resolve. Could not find `ShouldPanic` in `__test::test` [E0433]
tests/foo.rs:1 #[test] fn ok() {}
                       ^~~~~~~~~~
tests/foo.rs:1:9: 1:19 help: run `rustc --explain E0433` to see a detailed explanation
tests/foo.rs:1:9: 1:19 error: unresolved name `self::test::ShouldPanic::No` [E0425]
tests/foo.rs:1 #[test] fn ok() {}
                       ^~~~~~~~~~
tests/foo.rs:1:9: 1:19 help: run `rustc --explain E0425` to see a detailed explanation
tests/foo.rs:1:9: 1:19 error: unresolved name `self::test::StaticTestFn` [E0425]
tests/foo.rs:1 #[test] fn ok() {}
                       ^~~~~~~~~~
tests/foo.rs:1:9: 1:19 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to 8 previous errors
Could not compile `test`.

Caused by:
  Process didn't exit successfully: `rustc tests/foo.rs --crate-name foo --crate-type bin -g --test -C metadata=4fd43b24d22d2be7 -C extra-filename=-4fd43b24d22d2be7 --out-dir /home/japaric/tmp/test/target/debug --emit=dep-info,link -L dependency=/home/japaric/tmp/test/target/debug -L dependency=/home/japaric/tmp/test/target/debug/deps --extern test=/home/japaric/tmp/test/target/debug/libtest.rlib` (exit code: 101)
```

### Meta

```
$ rustc -V
rustc 1.9.0-nightly (7b0b80ae2 2016-03-02)

$ cargo -V
cargo 0.9.0-nightly (8fc3fd8 2016-02-29)
```

I guess this is more of a problem with `rustc` testing functionality. It seems that `rustc --test` injects extra source code to use the standard `test` crate, but because Cargo passes the `--extern test=...` to its `rustc` invocation that extra code ends up using the `test` crate under test instead of the standard `test` crate and generates a bunch of resolve errors (because the `test` crate under test is empty in this example).

cc @alexcrichton

### PR DESCRIPTION
**Pull request by ThinTim**
Fixes #2432

?r @alexcrichton

### CODE REVIEW

File: src/cargo/ops/cargo_new.rs [hunk 1]
```diff
@@ -89,6 +89,12 @@ fn get_name<'a>(path: &'a Path, opts: &'a NewOptions, config: &Config) -> CargoR
 }
 
 fn check_name(name: &str) -> CargoResult<()> {
+    if name == "test" {
+        bail!("The name `{}` cannot be used as a crate name\n\
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_new.rs]: stylistically Cargo error messages tend to start with a lowercase letter (like the compiler) rather than an uppercase letter

**Comment by alexcrichton** [comment]
Just a small nit but otherwise looks good to me, thanks!

**Comment by alexcrichton** [comment]
@bors: r+ 969d495c044f19e5f2fecff337478113e3e4b77f

Ah sorry! Feel free to ping a PR whenever you update it, unfortunately github doesn't send out notifications for that kind of event :(

**Comment by ThinTim** [comment]
@alexcrichton The format of error messages seems to have changed while this pull request has been pending, so I've updated my changes & rebased them into a new commit.
