### PR TITLE
add a note that some warnings (and/or errors) can be auto-fixed

### LINKED ISSUE #10976: Output which errors are automatically correctable, to improve discoverability of `cargo fix` and `cargo clippy --fix`
### Problem

`cargo fix` and `cargo clippy --fix` can be great tools for sparing developer cycles, especially when a new version of cargo is released. However, the discoverability of these tools is a problem: not everyone knows they exist.

### Proposed Solution

To improve discoverability, we could do something similar to what [rubocop](https://github.com/rubocop/rubocop) does: each error could include info about whether it's automatically correctable or not. This may prompt users who don't know about this feature to go find it. It also helps users who *do* know about the feature: they can avoid running the fix command in situations where it'll be useless because the tool actually can't automatically fix those particular errors.

For reference, here's a screenshot of rubocop's output:
image (1)

### Notes

_No response_

### PR DESCRIPTION
**Pull request by Muscraft**
This adds a note that some warnings (and/or errors) can be auto-fixed by running `cargo --fix`. This only supports `cargo check` as we can't show the same note for `cargo clippy` since it is an external subcommand.

The message for the note was taken from [#10976 (comment)](https://github.com/rust-lang/cargo/issues/10976#issuecomment-1212517765).

### CODE REVIEW

**Review by epage — APPROVED** [review]

**Comment by ehuss** [comment]
I'm reluctant to add something like this for a few reasons:

* I never run `cargo fix`. Something like this will just be constant noise for me. I think it is good to be very cautious about being too verbose or too prodding.
* `cargo fix` often won't work correctly if there are any errors in the code.
* `cargo fix` won't work with changes in the user's repo. They have to run with `--allow-dirty` and/or `--allow-staged`, which can be awkward. Also, there is a moderate risk that `cargo fix` will damage or otherwise mess up the user's code with no way to revert (the reason `--allow-dirty` is there).  If there is no git repo, then it is doubly more dangerous. Or if the files haven't been added yet, `cargo fix` may overwrite them without confirmation.
* Even filtering on machine-fixable errors, it is moderately common that the fix fails for one reason or another. I'm not particularly confident in pushing large numbers of people to use it more often. (Minor concern.)
* This doesn't really make it clear to the user *which* issues will be fixed.

I appreciate it can be difficult to educate people on the existence of tools or options for performing certain tasks. I'm wondering, though, does rust-analyzer not show a quick-fix for fixable suggestions? Perhaps that would be a better route to make it easier for people to apply suggestions, or otherwise have easy access to it?

**Comment by Muscraft** [comment]
> I'm wondering, though, does rust-analyzer not show a quick-fix for fixable suggestions? Perhaps that would be a better route to make it easier for people to apply suggestions, or otherwise have easy access to it?

I haven't used `rust-analyzer` (in a while) but I know Clion (with the rust extension) gives quick fixes so I would assume RA does as well

> I'm reluctant to add something like this for a few reasons:

Given the number of reasons, and the number of problems with `cargo fix` (which appear to be major blockers), it might be a good idea to close this and continue the discussion in #10976. I could see waiting on this until `cargo fix` has some issues resolved, or there is a new error/warning variant within `rustc` that would always be "fixable".

**Comment by epage** [comment]
Let's leave this open but move this to the Issue

**Comment by Muscraft** [comment]
I've updated this with feedback from #10976.
Changes:
- The note is added to the summary line as [suggested here](https://github.com/rust-lang/cargo/issues/10976#issuecomment-1215921821)
- The command to run now includes the exact command to run i.e. 
  ```
  warning: `foo` (example "ex1") generated 1 warning (run `cargo fix --example "ex1"` to apply suggestions)
  warning: `foo` (bench "bench") generated 1 warning (run `cargo fix --bench "bench" --tests` to apply suggestions)
  warning: `foo` (bin "foo" test) generated 2 warnings (run `cargo fix --bin "foo" --tests` to apply suggestions)
  ```

Concerns:
- Will adding this suggestion cause there to be too many issues filed and lots of work to fix things?
- Is the output message too verbose/specific  
- Should the message only be shown once?

**Comment by weihanglo** [comment]
> * Is the output message too verbose/specific

Looks fine to me, since Cargo already emits such note. 

I am uncertain whether we need to make sure the suggested command is always runnable. A bad suggestion could be worse than no suggestion.

> * Should the message only be shown once?

I don't get it. Could you expand a bit?

**Comment by Muscraft** [comment]
> I am uncertain whether we need to make sure the suggested command is always runnable. A bad suggestion could be worse than no suggestion.

I agree that a bad suggestion is much worse than no suggestion and it's something that I tried to make sure wouldn't happen. That being said, I think having a specific command to run is much better. 
Pros:
- It ensures that `cargo fix` is only being run on exactly what is giving the warning
- It makes sure that `cargo fix` is not being run on anything with an error
- Reduces unintended code churn
- Can clearly see what target/package the command is for
- Fixes applied target by target

Cons:
- The lines are very long
- Lots of new output
- Chance to give the wrong command
- Each command would need to be run separately (lots of `cargo fix` runs)
- Doesn't suggest `--allow-dirty` so the command would probably always be "wrong"

> > * Should the message only be shown once?
> 
> I don't get it. Could you expand a bit?

There is a chance that the long lines on potentially every summary line could be overwhelming. Having it output once per package(compared to target) would reduce this and make the command less specific. Going further and having it only be suggested once could make it so there is one place command is suggested and not affect every summary line. Having it be on its own line comes with its own problems but might make it easier to suggest a hyper-specific command (check version control status).

File: tests/testsuite/check.rs [hunk 1]
```diff
@@ -1176,3 +1176,270 @@ fn git_manifest_with_project() {
...
+                version = "0.0.1"
+                authors = []
+            "#,
+        )
+        .file("src/lib.rs", "use std::io;")
+        .build();
+
+    foo.cargo("check")
+        .masquerade_as_nightly_cargo(&["auto-fix note"])
+        .with_status(0)
```
Comment (weihanglo) [inline tests/testsuite/check.rs:1197]: 0 is the default.

```suggestion
```

File: tests/testsuite/check.rs [hunk 2]
```diff
@@ -1176,3 +1176,270 @@ fn git_manifest_with_project() {
...
+                version = "0.0.1"
+                authors = []
+            "#,
+        )
+        .file("src/lib.rs", "use std::io;")
+        .build();
+
+    foo.cargo("check")
+        .with_status(0)
+        .with_stderr_does_not_contain("[..] (run `cargo fix --lib -p foo` to apply 1 suggestion)")
```
Comment (weihanglo) [inline tests/testsuite/check.rs:1219]: I have a bit concern of overmatching the string here. We might forget to update this "not_contain" when changing the error message. Then it will become always true. Maybe matching less or just matching the entire stderr? 
(it might be overkill tho)

File: tests/testsuite/check.rs [hunk 3]
```diff
@@ -1176,3 +1176,270 @@ fn git_manifest_with_project() {
...
+#[cargo_test]
+fn check_fixable_warning() {
+    let foo = project()
+        .file(
+            "Cargo.toml",
+            r#"
+                [package]
+                name = "foo"
+                version = "0.0.1"
+                authors = []
```
Comment (weihanglo) [inline tests/testsuite/check.rs:1189]: I feel like `authors` field is not necessary for tests anymore.

**Review by weihanglo — COMMENTED** [review]
Looks fine! Thank you for the pull request.

File: src/cargo/core/compiler/mod.rs [hunk 4]
```diff
@@ -1443,8 +1446,19 @@ fn on_stderr_line_inner(
                         .expect("strip should never fail")
                 };
                 if options.show_diagnostics {
+                    let machine_applicable: bool = msg
+                        .children
+                        .iter()
+                        .map(|child| {
+                            child
```
[the remark this answers is not in the document]
Comment (Muscraft) [reply src/cargo/core/compiler/mod.rs:1453]: I believe so. I do not think there is access to the `Applicability` without looking at each child and each `DiagnosticSpan` of the child

File: src/cargo/core/compiler/job_queue.rs [hunk 5]
```diff
@@ -131,10 +131,11 @@ struct DrainState<'cfg> {
...
     /// Count of warnings, used to print a summary after the job succeeds.
     ///
-    /// First value is the total number of warnings, and the second value is
+    /// First value is the total number of warnings, the second value is
     /// the number that were suppressed because they were duplicates of a
-    /// previous warning.
-    warning_count: HashMap<JobId, (usize, usize)>,
+    /// previous warning, and the third value is for the number of fixable
+    /// warnings (set to -1 if there are any errors).
+    warning_count: HashMap<JobId, (usize, usize, isize)>,
```
[the remark this answers is not in the document]
Comment (Muscraft) [reply src/cargo/core/compiler/job_queue.rs]: I may have gone a bit overboard on turning this into a struct but it does make it much clearer what is going on. I Can revert it or change it if needed

File: src/cargo/core/compiler/mod.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (weihanglo) [reply src/cargo/core/compiler/mod.rs:1453]: I mean the recursive `child.children.children.children…`. Do we need to check that as well?

File: src/cargo/core/compiler/job_queue.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (weihanglo) [reply src/cargo/core/compiler/job_queue.rs]: Thank you for teh update. I also feel it clearer. Either of this and previous is good to me. I'll leave it for you to choose :)

Just a reminder. Some doc comments still mention `-1`, which should be removed or updated.

File: src/cargo/core/compiler/mod.rs [hunk 6]
```diff
@@ -1420,7 +1421,9 @@ fn on_stderr_line_inner(
                 rendered: String,
                 message: String,
                 level: String,
+                children: Vec<Diagnostic>,
             }
+
```
Comment (weihanglo) [inline src/cargo/core/compiler/mod.rs:1426]: Should we hand-pick field to deserialize? I see other places doing so.

```suggestion
                children: Vec<Diagnostic>,
            }
            #[derive(serde::Deserialize)]
            struct Diagnostic {
                spans: Vec<Span>,
                // `children: Vec<Diagnostic>` if we need to check them recursively
            }
            #[derive(serde::Deserialize)]
            struct Span {
                suggestion_applicability: Option<Applicability>,
            }
```

BTW, I feel like every existing ad-hoc deserialization should have a comment telling which struct it refers to.

File: src/cargo/core/compiler/job_queue.rs [hunk 7]
```diff
@@ -1151,15 +1223,47 @@ impl<'cfg> DrainState<'cfg> {
...
+        // Only show the `cargo fix` message if its a local `Unit`
+        if unit.is_local() && config.nightly_features_allowed {
+            // Do not show this if there are any errors or no fixable warnings
+            if let FixableWarnings::Positive(fixable) = count.fixable {
+                // `cargo fix` doesnt have an option for custom builds
+                if !unit.target.is_custom_build() {
+                    let mut command = {
+                        let named = unit.target.description_named();
+                        // if its a lib we need to add the package to fix
+                        if named == "lib" {
```
Comment (weihanglo) [inline src/cargo/core/compiler/job_queue.rs:1244]: More robust?

```suggestion
                        if unit.target.is_lib() {
```

File: src/cargo/core/compiler/mod.rs (hunk 6 above)
Comment (Muscraft) [reply src/cargo/core/compiler/mod.rs:1426]: > Should we hand-pick field to deserialize? I see other places doing so.

I'm not sure what you mean by this

File: src/cargo/core/compiler/mod.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (Muscraft) [reply src/cargo/core/compiler/mod.rs:1453]: I'm not sure but I don't think so from what I remember. It has been a while since I looked at it originally.

File: src/cargo/core/compiler/job_queue.rs [hunk 8]
```diff
@@ -170,6 +166,49 @@ struct DrainState<'cfg> {
...
+}
+
+/// Used to keep track of how many fixable warnings there are
+/// and if fixable warnings are allowed
+#[derive(Default)]
+pub enum FixableWarnings {
+    NowAllowed,
+    #[default]
+    Zero,
+    Positive(usize),
```
[the remark this answers is not in the document]
Comment (Muscraft) [reply src/cargo/core/compiler/job_queue.rs:209]: It's the convenience of deriving default, but also that it makes it easier to know when to show the message. You can just `if let FixableWarnings::Positive(fixable) = count.fixable`

File: src/cargo/core/compiler/mod.rs (hunk 6 above)
Comment (weihanglo) [reply src/cargo/core/compiler/mod.rs:1426]: I mean deserializing only those fields we need instead of the whole Diagnostic struct

Comment (Muscraft) [reply src/cargo/core/compiler/mod.rs:1426]: We could do that but I was trying to use the available types from `rustfix`. I figured that since it had the ability to tell what things were it would be kept updated, instead of updating multiple places.

Comment (weihanglo) [reply src/cargo/core/compiler/mod.rs:1426]: If there is an update of types in `rustfix` crate, either reuse or not we still need to update to some extent. 

I was asking because other places deserialize fields-of-interest. Besides, there might be a performance hit if a package start emitting thousands of warnings with full struct fields, though I guess it is rare.

Anyway, I am good with reuse types from `rustfix`. Let's move on :)

File: src/cargo/core/compiler/mod.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (weihanglo) [reply src/cargo/core/compiler/mod.rs:1454]: You're correct. I guess these lines telling the story. Thank you!
https://github.com/rust-lang/rustfix/blob/d67672b282413b462d8a9e752dffb655e775db9c/src/lib.rs#L187-L215

**Review by weihanglo — APPROVED** [review]
This looks good to me. 

According to the conclusion of the recent Cargo meeting, we decide to enable rustfix suggestions on nightly to collect feedback.  I am going to merge it soon to proceed.

Just note that, one little concern I have is that Cargo now does [full deserialization on `Diagnostic` struct](https://github.com/rust-lang/cargo/pull/10989#discussion_r1006437792). Not sure how it impacts the real world performance but I assume it is rare.
