### PR TITLE
Gracefully handle errors during a build.

### LINKED ISSUE #8245: Hangs if procedural macro prints output when stdout is closed
## Problem

Running `cargo check | false` (or more realistically `cargo check | head`) hangs if a macro prints more than a small number of lines to stdout.

Expected: same behavior as if the macro only prints a small number of lines to stdout, which is to not hang.

#### Cargo.toml

```toml
[package]
name = "repro"
version = "0.0.0"
edition = "2018"

[lib]
proc-macro = true
```

#### src/lib.rs

```rust
use proc_macro::TokenStream;

#[proc_macro]
pub fn repro(_input: TokenStream) -> TokenStream {
    // On my machine <202 lines terminates successfully.
    // >=202 lines hangs.
    for i in 0..1000 {
        println!("{}", i);
    }
    TokenStream::new()
}
```

#### src/main.rs

```rust
repro::repro!();

fn main() {}
```

## Notes

- Tested with current master branch of cargo (13bded9a335a855a15b95f54779d7f8a889404dd) and nightly rustc 1.45.0-nightly (a74d1862d 2020-05-14) on linux. `/path/to/cargo/target/release/cargo check | head`

- Mentioning @ehuss because #8236 looks relevant.

- Nightly cargo panicks *and* hangs, so this is not a regression from #8236 which does eliminate the panic.

- I think the hang is cargo not rustc but I can't be sure. Reasoning: I ran `cargo check --verbose` to grab the last rustc invocation before the hang, and ran that rustc invocation piped to `head`, and that did not hang.

### PR DESCRIPTION
**Pull request by ehuss**
If there are certain errors like EPIPE during a build, Cargo runs the risk of hanging if the compiler emits too many messages. This happens because Cargo now uses a bounded queue for compiler messages. However, if the main loop exits while the threads are running, there is nothing to drain the queue, and thus the threads will block indefinitely.

The solution here is to be extra careful of how errors are handled in the main loop. All errors are now treated roughly the same (report the error, allow the queue to continue to drain).  

I've also tweaked things so the *first* error is reported, not the last.

Closes #8245

### CODE REVIEW

**Comment by Eh2406** [comment]
Seams reasonable to me.

File: src/cargo/core/compiler/job_queue.rs [hunk 1]
```diff
@@ -651,25 +635,33 @@ impl<'cfg> DrainState<'cfg> {
         // successful and otherwise wait for pending work to finish if it failed
         // and then immediately return.
         let mut error = None;
+        // CAUTION! From here on out, do not use `?`. Every error must be handled
```
Comment (alexcrichton) [inline src/cargo/core/compiler/job_queue.rs:638]: Could this loop get factored into a function that doesn't return `Result` to statically prevent usage of `?`?

Comment (ehuss) [reply src/cargo/core/compiler/job_queue.rs]: Updated, WDYT?  I assume `Result` will never be changed to implement `Try` such that it calls `result.ok()` to convert a Result to Option automatically?

**Comment by alexcrichton** [comment]
@bors: r+

Looks great to me!

I highly doubt that auto-conversion will ever be added, but even so we've got a nice comment explaining to be vigilant anyway
