### PR TITLE
fix: update `resolve_all_features()` to filter pkg deps

### LINKED ISSUE #15399: `cargo test` requires windows-only dependency on linux
### Problem

I am trying to test a crate that has a windows-only dependency using the `--frozen` flag. The windows-only dependency in question is `ipconfig`, locked to 0.3.0. However, cargo gives me this unexpected error instead of running tests, which is problematic (a) because it is not a dependency on my platform, and (b) ignores the version lock:

```
thread 'main' panicked at src/tools/cargo/src/cargo/ops/cargo_compile/mod.rs:950:14:
packages downloaded: failed to download `ipconfig v0.3.2`

Caused by:
    attempting to make an HTTP request, but --frozen was specified

Stack backtrace:
   0: <anyhow::Error>::msg::<&str>
   1: cargo::util::network::http::http_handle_and_timeout
   2: <cargo::core::package::Downloads>::start_inner
   3: <cargo::core::package::Downloads>::start
   4: <cargo::core::package::PackageSet>::get_one
   5: cargo::ops::cargo_compile::resolve_all_features
   6: <cargo::ops::cargo_compile::unit_generator::UnitGenerator>::proposals_to_units
   7: <cargo::ops::cargo_compile::unit_generator::UnitGenerator>::generate_root_units
   8: cargo::ops::cargo_compile::create_bcx
   9: cargo::ops::cargo_compile::compile_ws
  10: cargo::ops::cargo_compile::compile_with_exec
  11: cargo::ops::cargo_compile::compile
  12: cargo::ops::cargo_test::compile_tests
  13: cargo::ops::cargo_test::run_tests
  14: cargo::commands::test::exec
  15: <cargo::cli::Exec>::exec
  16: cargo::main
  17: std::sys::backtrace::__rust_begin_short_backtrace::<fn(), ()>
  18: std::rt::lang_start::<()>::{closure#0}
  19: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/ops/function.rs:284:13
  20: std::panicking::try::do_call
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:584:40
  21: std::panicking::try
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:547:19
  22: std::panic::catch_unwind
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panic.rs:358:14
  23: std::rt::lang_start_internal::{{closure}}
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/rt.rs:174:48
  24: std::panicking::try::do_call
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:584:40
  25: std::panicking::try
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:547:19
  26: std::panic::catch_unwind
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panic.rs:358:14
  27: std::rt::lang_start_internal
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/rt.rs:174:20
  28: main
  29: <unknown>
  30: __libc_start_main
  31: <unknown>
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:692:5
   1: core::panicking::panic_fmt
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/result.rs:1704:5
   3: cargo::ops::cargo_compile::resolve_all_features
   4: <cargo::ops::cargo_compile::unit_generator::UnitGenerator>::proposals_to_units
   5: <cargo::ops::cargo_compile::unit_generator::UnitGenerator>::generate_root_units
   6: cargo::ops::cargo_compile::create_bcx
   7: cargo::ops::cargo_compile::compile_ws
   8: cargo::ops::cargo_compile::compile_with_exec
   9: cargo::ops::cargo_compile::compile
  10: cargo::ops::cargo_test::compile_tests
  11: cargo::ops::cargo_test::run_tests
  12: cargo::commands::test::exec
  13: <cargo::cli::Exec>::exec
  14: cargo::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Steps

On a linux computer, run

```bash
git clone https://github.com/hickory-dns/hickory-dns
cd hickory-dns
git checkout v0.25.1
mkdir .cargo_home
CARGO_HOME=.cargo_home cargo fetch --locked --target=x86_64-unknown-linux-gnu
CARGO_HOME=.cargo_home cargo test --frozen -p hickory-resolver
```

### Possible Solution(s)

- Don't download unnecessary dependencies
- As a workaround, make `cargo fetch` download the dependency

### Notes

_No response_

### Version

```text

```

### PR DESCRIPTION
**Pull request by Saplyn**
### What does this PR try to resolve?

Before, [`resolve_all_features()`](https://github.com/rust-lang/cargo/blob/13695497cd3060ba2700a5552b3397c451456a89/src/cargo/ops/cargo_compile/mod.rs#L1001-L1032) isn't filtering dependencies, as it uses the set returned by [`Resolve::deps()`](https://github.com/rust-lang/cargo/blob/0f14d9d2fa4ca7ebee982e6015e98b0d28495390/src/cargo/core/resolver/resolve.rs#L327-L330) directly which is mostly unfiltered. This PR fixes it by having the set goes through [`PackageSet::filter_deps()`](https://github.com/rust-lang/cargo/blob/0f14d9d2fa4ca7ebee982e6015e98b0d28495390/src/cargo/core/package.rs#L632-L660)'s filter.

Note that this patch changed `resolve_all_features()`'s function signature as well as made `PackageSet::filter_deps()` public.

Close #15399 

### How to test and review this PR?

As described in #15399, `cargo test --frozen` should not panic (doesn't try to download unneeded deps) when does the following:

```sh
git clone https://github.com/hickory-dns/hickory-dns
cd hickory-dns
git checkout v0.25.1
mkdir .cargo_home
CARGO_HOME=.cargo_home cargo fetch --locked --target=x86_64-unknown-linux-gnu
CARGO_HOME=.cargo_home cargo test --frozen -p hickory-resolver
```

More discussion on [Zulip chat](https://rust-lang.zulipchat.com/#narrow/channel/246057-t-cargo/topic/Issue.20.2315399.3A.20.20.60cargo.20test.60.20trys.20to.20fetch.20not.20required.20deps/with/553899270).

### CODE REVIEW

**Comment by epage** [comment]
Not sure I'm in a good place to give feedback on the change itself at this time but wanted to highlight PR expectations (https://doc.crates.io/contrib/process/working-on-cargo.html#submitting-a-pull-request)
- A test will be needed for this
- It is really helpful if you create a test in its own commit that shows the panic and then put this commit on top that removes the panic.  Then the diff between these two commits shows how behavior changed.  This allows you to verify the test is testing the right thing and gives a good demonstration of the fix

**Comment by Saplyn** [comment]
Thanks! I'll look into how to write a test for this pr and try implementing it before making it ready for review

File: tests/testsuite/resolve_optional_dependency.rs [hunk 1]
```diff
@@ -0,0 +1,50 @@
+use crate::prelude::*;
+use cargo_test_support::project;
+
+#[cargo_test(ignore_windows = "test windows only dependency on unix systems")]
+fn cargo_test_should_not_demand_not_required_dep() {
```
Comment (ehuss) [inline tests/testsuite/resolve_optional_dependency.rs]: Just some quick feedback on this test:

- Tests should not access the network or crates.io. Registries must be defined locally. See the calls to `Package::new` as examples.
- Tests should not hard-code target names. If possible try to model this without things that depend on the target (like maybe `cfg(false)`). See also the `rustc_host()` function if you need a target for `cargo fetch`.
- The first commit adding a test should show the failing behavior. That way we can see and verify what the change in behavior is in the second commit.
- Generally we don't create new modules to house a single test. Since this is essentially checking the behavior of dealing with features, I would probably just put it in the features module.
- For performance reasons, we tend to prefer using `cargo check` instead of other commands (`--examples` would be needed in this case).

Comment (Saplyn) [reply tests/testsuite/resolve_optional_dependency.rs]: 1. I've changed to `Package::new()` and it now uses dumb-registery
2. It's now using `rust_host()` to detect host and the test ignores windows
3. I could confirm the test fails before the second commit and passes after, both privously and now
4. It's now moved into `features` (`features::dont_demand_not_required_dep`)
5. I've now changed to `cargo check --examples`

Sorry for force pushing into my own repo. I don't know how to keep all history there while keeping 2 commits (test, then fix) in order.

Comment (Saplyn) [reply tests/testsuite/resolve_optional_dependency.rs]: (I guess I should also @epage)

File: tests/testsuite/features.rs [hunk 2]
```diff
@@ -2368,3 +2368,38 @@ fn invalid_feature_name_slash_error() {
...
+[package]
+name = "sample"
+version = "0.1.0"
+edition = "2024"
+
+[features]
+default = ["feat"]
+feat = ["dep:win-only"]
+
+[target.'cfg(windows)'.dependencies]
```
Comment (ehuss) [inline tests/testsuite/features.rs]: This test can be made to run on any target by using `cfg(false)` here instead of windows.

**Review by ehuss — COMMENTED** [review]
Thanks! Small request for the test, but otherwise I think this should be fine.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16221/4d0eff0dad0d717ce4df51e0f536cc6f403cb984..7232f37104a1075563cb0762998d0591ee817fbd)*

File: tests/testsuite/features.rs (hunk 2 above)
Comment (Saplyn) [reply tests/testsuite/features.rs]: Thanks, I shall fix this right now

**Comment by Saplyn** [comment]
Hi @ehuss, I've changed my solution as requested (from `cfg(windows)` to `cfg(false)`).

**Review by ehuss — APPROVED** [review]
Thanks!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16221/a793cd1d0262226139819100df4d8f23c2cc7294..a120d528f3220e1bd2f3b00be84ae41fe06dc406)*

File: tests/testsuite/features.rs [hunk 3]
```diff
@@ -2419,3 +2368,38 @@ fn invalid_feature_name_slash_error() {
...
+required-features = ["feat"]
+"#,
+        )
+        .file("src/main.rs", "fn main() {}")
+        .file("examples/demo.rs", "fn main() {}")
+        .build();
+
+    let host = rustc_host();
+    p.cargo(&format!("fetch --target={host}")).run();
+    p.cargo(&format!("check --target={host} --examples --frozen"))
```
Comment (weihanglo) [inline tests/testsuite/features.rs:2403]: Nit: can use `--target host-tuple` maybe?
