### PR TITLE
Auth with more usernames and improve errors

### LINKED ISSUE #2399: default username used for git clones over ssh is not generally correct
This might be a duplicate of #1851 or #2078 but I can't quite tell.  My understanding is that cargo is supposed to use ssh-agent for authentication, but I can't get this to work.

I have a dependency with a git-over-ssh path:

```toml
[dependencies.sma_utils]
git = "ssh://gitsrvsim/usr/abaqus60/GITrepo/sma_rust.git"
```

SSH to this machine is password-less (due to ssh-agent, and not due a `.ssh/config` file):

```
$ ssh -o BatchMode=yes gitsrvsim hostname
Permission denied (publickey,gssapi-with-mic,password).
$ ssh-add ~/.ssh/sim_internal
Identity added: /u/users/lxd/.ssh/sim_internal (/u/users/lxd/.ssh/sim_internal)
$ ssh -o BatchMode=yes gitsrvsim hostname
gitsrvsim
```

But cargo build still fails:

```
cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `ssh://gitsrvsim/usr/abaqus60/GITrepo/sma_rust.git`
Unable to update ssh://gitsrvsim/usr/abaqus60/GITrepo/sma_rust.git

Caused by:
  failed to fetch into /rd/gen/lxd/do_not_delete/multirust/.cargo/git/db/sma_rust-0fec95efab468a0c

Caused by:
  failed to authenticate when downloading repository

Caused by:
  [7/-1] Config value 'credential.helper' was not found
```

My quick googling suggests that git's credential-helper is primarily used for HTTPS authentication.  No one seems to use it for ssh (likely because git can use `~/.ssh/config`).  My git is not new enough to have the credential-helper subsystem.

So I can't really tell where the problem lies.  Currently running `cargo 0.9.0-nightly (4739ba1 2016-02-16)

Thanks!

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit is an attempt to improve the error message from failed
authentication attempts as well as attempting more usernames. Right now we only
attempt one username, but there are four different possible choices we could
select (including $USER which we weren't previously trying).

This commit tweaks a bunch of this logic and just in general refactors the
with_authentication function.

Closes #2399

### CODE REVIEW

File: src/cargo/sources/git/utils.rs [hunk 1]
```diff
@@ -358,66 +359,169 @@ impl<'a> GitCheckout<'a> {
...
+                        username_attempt = UsernameAttempt::CredHelper;
+                        username.map(|s| s.to_string())
+                    }
+                    UsernameAttempt::CredHelper => {
+                        username_attempt = UsernameAttempt::Local;
+                        cred_helper.username.clone()
+                    }
+                    UsernameAttempt::Local => {
+                        username_attempt = UsernameAttempt::Git;
+                        env::var("USER").ok()
```
Comment (eminence) [inline src/cargo/sources/git/utils.rs]: On Windows, the local username is stored in the `%USERNAME%` environment variable.  `%USER%` is not generally set.
