### PR TITLE
Handle "jobs = 0" case in cargo config files

### LINKED ISSUE #9219: Specifying jobs = 0 in .cargo/config hangs cargo forever without output
If you specify `jobs = 0` in `.cargo/config`, your `cargo build` invocations will hang forever without output. Note that if you try to invoke `cargo build -j 0` it will warn you:

```
$ cargo build -j 0
error: jobs must be at least 1
```

**Steps**

1. Place a `.cargo/config` in any valid location with the following content:

        [build]
        jobs = 0

2. Run `cargo build`.
3. You will never reach step 3.

**Possible Solution(s)**

Check for `jobs` being 0 when reading the config file.

**Notes**

Output of `cargo version`: latest `master` commit, https://github.com/rust-lang/cargo/commit/0b2059e9811caa238a603f0300d9c5fb485000a6.

### PR DESCRIPTION
**Pull request by henrifrancois**
Cargo hangs without output if the jobs argument under build in a cargo/config file is set to 0. This PR handles this case by providing an appropriate error.

Closes #9219

### CODE REVIEW

**Comment by Eh2406** [comment]
This looks good. Can we have a test in `tests/testsuite/build.rs`?

**Comment by henrifrancois** [comment]
> 
> 
> This looks good. Can we have a test in `tests/testsuite/build.rs`?

Just added one!

**Comment by Eh2406** [comment]
@bors r+
Thank you!

**Comment by ehuss** [comment]
I'm checking on the test failure...

File: src/cargo/core/compiler/build_config.rs [hunk 1]
```diff
@@ -68,7 +68,11 @@ impl BuildConfig {
                  its environment, ignoring the `-j` parameter",
             )?;
         }
-        let jobs = jobs.or(cfg.jobs).unwrap_or(::num_cpus::get() as u32);
+        let jobs = match jobs.or(cfg.jobs) {
+            None => ::num_cpus::get() as u32,
+            Some(j) if j != 0 => (::num_cpus::get() as u32).max(j),
```
Comment (ehuss) [inline src/cargo/core/compiler/build_config.rs:73]: Why does it call `num_cpus` with `max` here?  This effectively prevents `-j` from working.

Comment (henrifrancois) [reply src/cargo/core/compiler/build_config.rs:73]: That's a logic error on my part. Would the correct behavior be accepting the `-j` parameter regardless of its value as long as it's greater than 0?

Comment (ehuss) [reply src/cargo/core/compiler/build_config.rs:73]: Yea, I think so.

Comment (henrifrancois) [reply src/cargo/core/compiler/build_config.rs]: Ok hopefully that's taken care of by this latest commit

File: src/cargo/core/compiler/build_config.rs [hunk 2]
```diff
@@ -68,7 +68,12 @@ impl BuildConfig {
                  its environment, ignoring the `-j` parameter",
             )?;
         }
-        let jobs = jobs.or(cfg.jobs).unwrap_or(::num_cpus::get() as u32);
+        let jobs = match jobs.or(cfg.jobs) {
+            None => ::num_cpus::get() as u32,
+            Some(j) if j > 0 => j,
+            Some(j) if j == 0 => anyhow::bail!("jobs may not be 0"),
+            Some(_) => anyhow::bail!("jobs may not have a negative value"),
```
Comment (ehuss) [inline src/cargo/core/compiler/build_config.rs:75]: This case isn't possible, since it is an unsigned integer, is it?  Perhaps this could be restructured to be a simple `let` statement as before, and then a conditional `if jobs == 0 {bail!("...")}`?

Comment (henrifrancois) [reply src/cargo/core/compiler/build_config.rs:75]: Sure, that makes sense. I will review and edit.

**Comment by ehuss** [comment]
Thanks!

@bors r+
