### PR TITLE
Fully capture rustc and rustdoc output when -Zcompile-progress is passed

### LINKED ISSUE #5764: UI nit: Progress bar partially overwritten by errors
cc #3448, #2536

When compilation terminates with an error, the progress bar is partially overwritten. Perhaps there is a missing `\n` that needs to be output before the first error?

Sample error:
```console
$ cargo +nightly check
    Checking x86_64 v0.2.4 (file:///home/mark/Documents/home/x86_64)                                                                                                                                                
error[E0573]: expected type, found module `self`==============>          ] 5/6: x86_64                                                                                                                              
   --> src/structures/paging/recursive.rs:354:14
    |
354 |         &mut self,
    |              ^^^^ did you mean `Self`?
```

Notice this part: `==============>          ] 5/6: x86_64`. This is the progress bar (I'm compiling the x86_64 crate), which is overwritten by the first error.

```console
$ cargo --version
cargo 1.27.0 (1e95190e5 2018-05-27)
```

### PR DESCRIPTION
**Pull request by kennytm**
Fixes #5764 and #5695.

On Windows, we will parse the ANSI escape code into console commands via my `fwdansi` package, based on @ishitatsuyuki's idea in https://github.com/rust-lang/cargo/issues/5695#issuecomment-406300234. Outside of Windows the content is forwarded as-is.

### CODE REVIEW

**Comment by dwijnand** [comment]
> Fixes #5764 and #5695.

Needs to be...

Fixes #5764 
Fixes #5695 

.. for GitHub to auto-close them both.

**Comment by ishitatsuyuki** [comment]
Great work.

I'm not sure we should special case Windows here - at a little sacrifice of efficiency, we can just:
- pass `--color=always` to downstream processes.
- parse it with `fwdansi` and then let it handle all output cases with termcolor: Windows console, ANSI, no color.

**Comment by kennytm** [comment]
@dwijnand they are already closed so I choose the human syntax instead 😄.

**Comment by kennytm** [comment]
(rust-lang/rust#53003 has been merged so this is unblocked.)

**Comment by ishitatsuyuki** [comment]
@kennytm Do you have some opinions on https://github.com/rust-lang/cargo/pull/5862#issuecomment-410411121?

**Comment by kennytm** [comment]
@ishitatsuyuki I don't see any advantage doing that. I'll let the reviewers decide.

File: src/cargo/core/compiler/mod.rs [hunk 1]
```diff
@@ -672,6 +709,15 @@ fn add_cap_lints(bcx: &BuildContext, unit: &Unit, cmd: &mut ProcessBuilder) {
     }
 }
 
+fn add_color(bcx: &BuildContext, cmd: &mut ProcessBuilder) {
+    let capture_output = bcx.config.cli_unstable().compile_progress;
+    let shell = bcx.config.shell();
+    if capture_output || shell.color_choice() != ColorChoice::CargoAuto {
+        let color = if shell.supports_color() { "always" } else { "never" };
+        cmd.args(&["--color", color]);
```
Comment (alexcrichton) [inline src/cargo/core/compiler/mod.rs]: This is slightly different than the previous invocation that was moved up from below, but I think it's equivalent, right?

Previously if I pass `--color never` to Cargo it'll forward that to rustc unconditionally. I think that'll happen here because `stream.supports_color()` is already set to return `false` unconditionally inside of `termcolor`, I think?

(and I believe the reverse is true for `--color always`)

Just wanted to make sure!

**Comment by kennytm** [comment]
> when `--color` always is passed to rustc on windows when stderr is a pipe, that means that `termcolor`, the compiler's currently terminal coloring library (I think?), will turn on ANSI unconditionally, despite being on Windows?

Yes. The behavior is the same with or without this PR.

screenshot_2018-08-06 21 35 44_gmqq9p-fs8

**Comment by alexcrichton** [comment]
@bors: r+

Ok this looks great to me, thanks again @kennytm!

I think after this we're probably ready to turn this on by default, right?

**Comment by kennytm** [comment]
@alexcrichton Yes :)

**Comment by alexcrichton** [comment]
@kennytm I'd say this is probably ready to stabilize, but curious what you think?

**Comment by kennytm** [comment]
SGTM, I'll prepare a PR.
