### PR TITLE
Fix renaming a project using build scripts

### LINKED ISSUE #4053: `cargo:rustc-link-search` becomes invalid when you move a Cargo project
### STR

```
# create a dependency that uses cargo:rustc-link-search
$ cargo new --lib foo && cd $_
$ edit build.rs && cat $_
```

``` rust
use std::{env, fs};
use std::path::PathBuf;

fn main() {
    let src_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());

    fs::copy(src_dir.join("link.x"), out_dir.join("link.x")).unwrap();
    println!("cargo:rustc-link-search={}", out_dir.display());
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=link.x");
}
```

```
# create an empty linker script
$ touch link.x

# create an application that depends on `foo`
$ cd ..
$ cargo new --bin hello && cd $_
$ cargo add foo --path ../../foo

# this won't link because the linker script is empty. that's OK; that's not the issue
$ cargo rustc -- -C link-arg=-Tlink.x
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" (..) "-L" "/home/japaric/tmp/a/hello/target/debug/build/foo-4cfaa457c325b81c/out" (..)

# note the -L path in the linker error; the linker script *is* in that folder
# so the linker finds the linker script
$ find -name link.x
/home/japaric/tmp/a/hello/target/debug/build/foo-4cfaa457c325b81c/out/link.x
```

```
# now move the Cargo project
$ cd ../..
$ mkdir b && cd $_
$ mv ../a/hello .
$ cd hello

# re-run the `cargo rustc` command
# the linker error is different; the linker can't find `link.x` this time
$ cargo rustc -- -C link-arg=-Tlink.x
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" (..) "-L" "/home/japaric/tmp/a/hello/target/debug/build/foo-4cfaa457c325b81c/out" (..)
  = note: /usr/bin/ld: cannot open linker script file link.x: No such file or directory
```

Note the linker invocation; the `foo` search path is the *same* as before. By moving the `hello` crate the search path generated by the `foo` dependency becomes invalidated.

### Meta

```
$ cargo -V
cargo 0.20.0-nightly (cf17c9f71 2017-05-09)
```

Possible solution: Re-run all build scripts when the Cargo project is moved.

cc @alexcrichton @dpc
Originally reported in japaric/cortex-m#31

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit fixes an issue in Cargo where if a project's folder was
renamed but it also contained a build script the project could break.
Cargo would continue to use the previous `rustc-link-search` arguments
to configure env vars like `LD_LIBRARY_PATH` but the literal values from
the previous compilation would be stale as the directories would no
longer be there.

To fix this when parsing the build script output we now retain a log of
the previous output directory of a build script invocation as well as
the current output, tweaking paths as appropriate if they were contained
in the output folder.

Closes #4053

### CODE REVIEW

**Comment by matklad** [comment]
Am I correct that currently we don't set cwd for build scripts? If so, let's lock cwd here as well?

**Comment by matklad** [comment]
Nevermind, we do set cwd in `fill_env`

File: src/cargo/ops/cargo_rustc/custom_build.rs [hunk 1]
```diff
@@ -364,6 +391,13 @@ impl BuildOutput {
                 _ => bail!("Wrong output in {}: `{}`", whence, line),
             };
 
+            let path = |val: &str| {
```
Comment (matklad) [inline src/cargo/ops/cargo_rustc/custom_build.rs]: Could we, instead of post-processing after reading, do some pre-processing before writing, so as not to store absolute paths at the moment of generation at all?

Comment (alexcrichton) [reply src/cargo/ops/cargo_rustc/custom_build.rs]: Hm yeah I wasn't sure what was the best option here, we don't have a serialized format for Cargo's parsed data structures for the output file so it'd have to be added, it just wasn't clear to me how much of a benefit we'd get from it.

Do you think that the preprocessed version would be less buggy though?

Comment (matklad) [reply src/cargo/ops/cargo_rustc/custom_build.rs]: I don't think there are any tangible benefits one way or the other, but not having absolute paths feels slightly cleaner. But I am fine either way!
