### PR TITLE
fix(host-config): fix panic when cross-compiling with host-config

### LINKED ISSUE #16664: Cargo crashed on cargo 1.95.0-nightly (8cc0cb136 2026-02-17)
cargo always crashed on almost all targets when using `--target <triple>` cross-compiling, detail like below:
```
thread 'main' (58478) panicked at src/tools/cargo/src/cargo/core/compiler/build_context/target_info.rs:1103:58:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Rust: rustc 1.95.0-nightly (5fb2ff861 2026-02-21)

### PR DESCRIPTION
**Pull request by arlosi**
### What does this PR try to resolve?

When cross compiling (with `--target`), cargo panics with -Zhost-config.

This changes the explicit addition of the host target to only occur if the `requested_kinds` includes the host.

Otherwise, looking up the target_runner for the explicit_host_kind attempts to look up an entry in the target_config map that does not exist.

### How to test and review this PR?

Validate that new test passes and does not panic.

Fixes #16664

### CODE REVIEW

File: tests/testsuite/cross_compile.rs [hunk 1]
```diff
@@ -1352,3 +1353,20 @@ fn host_linker_does_not_apply_to_binary_build() {
 "#]])
         .run();
 }
+
+#[cargo_test]
+fn cross_with_host_config() {
```
Comment (epage) [inline tests/testsuite/cross_compile.rs:1358]: Could you add this in a prior commit, with it passing?  That makes it easier to see how the behavior evolved with this change.

**Comment by arlosi** [comment]
Note that I'm not very familiar with this area of cargo, and there have been a chain of regressions and fixes here.

File: tests/testsuite/cross_compile.rs (hunk 1 above)
Comment (arlosi) [reply tests/testsuite/cross_compile.rs:1358]: I can. Cargo will panic.

File: tests/testsuite/cross_compile.rs [hunk 2]
```diff
@@ -1339,6 +1339,7 @@ fn host_linker_does_not_apply_to_binary_build() {
     // host.linker should not be applied but target.linker
     p.cargo("build -Z target-applies-to-host -Z host-config")
         .masquerade_as_nightly_cargo(&["target-applies-to-host", "host-config"])
+        .env("CARGO_TARGET_APPLIES_TO_HOST", "false")
```
Comment (epage) [inline tests/testsuite/cross_compile.rs]: Looks like this was forgotten when the test was added?

Does it make the test fail without this?  Or can it be split out?

Comment (arlosi) [reply tests/testsuite/cross_compile.rs]: The test passes either way. I can split it out into a separate PR.

Comment (epage) [reply tests/testsuite/cross_compile.rs]: Separate commit before this also works

Comment (arlosi) [reply tests/testsuite/cross_compile.rs]: I've added as separate commit

**Comment by weihanglo** [comment]
While this is nightly feature fix, it would be great if we can do a cargo submodule bump before beta branches off. 

I am not available to do that this week though
