### PR TITLE
fix(config): Fallback to non-canonical path for workspace-path-hash

### LINKED ISSUE #16110: cargo -Zscript doesn't work for memfd created files anymore
When the script file is created through [memfd_create](<https://man7.org/linux/man-pages/man2/memfd_create.2.html>), cargo panics when trying to run the script.

Repro:
```Rust
use std::os::fd::FromRawFd;
use std::io::Write;
use std::os::unix::process::CommandExt;

unsafe extern "C" {
    fn memfd_create(name: *const std::ffi::c_char, flags: std::ffi::c_uint) -> std::ffi::c_int;
}

fn main() {
    let fd = unsafe { memfd_create(c"otkeep-script".as_ptr(), 0) };
    if fd == -1 {
        panic!("memfd_create failed when trying to create script file");
    }
    let mut f = unsafe { std::fs::File::from_raw_fd(fd) };
    f.write_all(SCRIPT.as_bytes()).unwrap();
    f.flush().unwrap();
    dbg!(std::process::Command::new(format!("/proc/self/fd/{fd}")).exec());
}

const SCRIPT: &str = r#"#!/usr/bin/env -S cargo +nightly -Zscript

fn main() {
    println!("Hello World");
}
"#;
```

Cargo output (as of `1.92.0-nightly (81c3f77a4 2025-10-10)`):
```
thread 'main' (26272) panicked at src/tools/cargo/src/cargo/core/workspace.rs:454:18:
template is correct: No such file or directory (os error 2)
```

My use case is that I'm running cargo scripts through my script runner called [OtKeep](<https://github.com/crumblingstatue/OtKeep/>), which stores scripts in a database and uses memfd_create to create temporary files when executing the scripts.

This used to work, but doesn't anymore. The regression seems to be caused by #16073.

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

Fixes #16110

### CODE REVIEW

File: tests/testsuite/script/cargo.rs [hunk 1]
```diff
@@ -2174,3 +2175,37 @@ args: []
...
+
+#[cargo_test(nightly, reason = "-Zscript is unstable")]
+#[cfg(target_os = "linux")]
+fn memfd_script() {
+    use std::os::fd::AsRawFd;
+
+    let fd = memfd::MemfdOptions::new()
+        .close_on_exec(false)
+        .create("otkeep-script")
+        .unwrap();
```
Comment (weihanglo) [inline tests/testsuite/script/cargo.rs:2187]: Should we instead use `libc::memfd_create` so we don't need to pull in another dependency (it is lightweight I agree). Something like

```rust
let ret  = unsafe { libc::memfd_create(0) };
if ret < 0 {
    panic!("failed to created memfd: {}", std::io::Error::last_os_error());
}
let raw_fd = ret;
let file = std::fs::File::from_raw_fd(raw_fd);
...
```

Or do we have any more plans on memfd support?

Comment (epage) [reply tests/testsuite/script/cargo.rs:2187]: I just didn't want to be responsible for unsafe code for APIs I'm unfamiliar with. If you think it  is worth it, I'll change it.

Comment (weihanglo) [reply tests/testsuite/script/cargo.rs:2187]: Or <https://docs.rs/rustix/1.1.2/rustix/fs/fn.memfd_create.html> since we already depend on rustix anyway?

Regardless, feel free to proceed with whatever you feel comfortable :)
