### PR TITLE
Check for duplicate output filenames.

### LINKED ISSUE #5524: Warn on duplicate artifact creation
With a workspace such as in this repository: https://github.com/Mark-Simulacrum/cargo-issue-5524, running Cargo check on stable results in the following metadata being generated.

I believe that Cargo should try to detect the situation where duplicate artifacts will be generated and stop compilation; however, I'm not sure it's possible to do this well. I think even a heuristic that checks for lib/bin entries with the same `name` across the workspace would be sufficient for most of the benefits, though.

It's worth noting that I think this has only become an issue (at least for cargo check) since https://github.com/rust-lang/rust/pull/49289, which made `rustc --emit=metadata` emit metadata for bin targets. It might be enough to make change to rustc to disambiguate binary and lib metadata in the filename. In a way, this might be a regression, but I'm not sure.

```
$ find target -type f -name '*rmeta' | xargs ls -trl # stable 1.26
-rw-r--r-- 2 mark mark 1058 May 11 21:35 target/debug/libfoo.rmeta
-rw-r--r-- 2 mark mark 1058 May 11 21:35 target/debug/deps/libfoo-a9f370a27c2df2eb.rmeta
```

However, on beta, the following occurs:
```
$ find target -type f -name '*rmeta' | xargs ls -trl # beta 1.27
-rw-r--r-- 1 mark mark 1221 May 11 21:36 target/debug/deps/libfoo-11803c32bdc69a09.rmeta
-rw-r--r-- 2 mark mark    0 May 11 21:36 target/debug/libfoo.rmeta
-rw-r--r-- 2 mark mark    0 May 11 21:36 target/debug/deps/libfoo-f0bc89da5bcecba3.rmeta

```

cc @alexcrichton -- do you think this ought to be marked as a regression? It's confusing behavior that has only become a problem since 1.27, but I don't know whether it really warrants regression-like tracking.

### LINKED ISSUE #6293: What to do about duplicate targets in a workspace?
Currently a workspace can have multiple packages with the same target names. This causes a problem if you attempt to build both targets at the same time.  One will overwrite the other when it is hardlinked in the target dir, and the result is somewhat random.

This affects binaries, examples, and libraries. Tests and benchmarks have unique hashes in their names.

I'm unsure of the best way to deal with this. One option is to issue a warning if this happens (at workspace validation phase), and turn that warning into a hard error after a sufficiently long time.

Another option is to detect if you attempt to build conflicting targets and return an error explaining you can only build one at a time (with some explanation about the naming conflict).

### PR DESCRIPTION
**Pull request by ehuss**
This generates an error if it detects that different units would output the same file name. This can happen in a few situations:
- Multiple targets in a workspace use the same name.
- `--out-dir` in some cases (like `examples` because it does not include the directory).
- Bugs in cargo (like #5524, #5444)

This includes a few cleanups/consolidations:
- `export_path` added to `OutputFile` so there is one place where the `--out-dir` filename logic is located.
- `TargetKind::description()` added for a simple way to get a human-readable name of a target kind.
- The `PartialOrd` changes are a slight performance improvement (overall things are now slightly faster even though it is doing more work).

Closes #5524, closes #6293.

### CODE REVIEW

**Comment by ehuss** [comment]
@alexcrichton I didn't fully follow your [last comment](https://github.com/rust-lang/cargo/issues/6293#issuecomment-437553662), because it kinda sounded like you were saying two different things. I think generating an error if the current command would generate duplicates is the right thing to do, because almost certainly that is the wrong behavior. These can be converted to warnings if needed, though.

I might follow up with a separate PR sometime later to clean up the `OutputFile` calculation. It currently does not generate *all* outputs correctly. In particular, some debug files are missing because `file_types` is making hardlinking decisions which should be deferred. Also, doc and doctests both create wrong paths (and handling doc units correctly could simplify some special cases).

File: src/cargo/core/compiler/context/mod.rs [hunk 1]
```diff
@@ -72,18 +72,6 @@ impl<'a> Unit<'a> {
 	}
 }
 
-impl<'a> Ord for Unit<'a> {
```
Comment (alexcrichton) [inline src/cargo/core/compiler/context/mod.rs]: Out of curiosity, was this done for performance reasons or for correctness reasons?

Comment (ehuss) [reply src/cargo/core/compiler/context/mod.rs]: Yes, it is only for performance. The old code was rehashing every field for every comparison.

**Comment by ehuss** [comment]
> Do you think it's feasible to tweak the output here to say that it will soon become a hard error (perhaps with an issue URL as well) and leave it as a warning for now?

Yea, sounds good!  Updated with a corresponding tracking issue.

**Comment by alexcrichton** [comment]
@bors: r+

💯

**Comment by ehuss** [comment]
🤔 forgot to check windows after switching to a warning.  Looks like it's a little more sensitive to concurrent writers to the same library.  I think the other tests should be safe.

**Comment by alexcrichton** [comment]
Looks like one of our old friends [may be sneaking back](https://travis-ci.org/rust-lang/cargo/jobs/454769394)...

@bors: r+
