### PR TITLE
fix(run): Override arg0 for cargo scripts 

### LINKED ISSUE #12870: Cargo Scripts with `-Zscript` should override `current_exe`
### Problem

`std::env::args` and `std::env::current_exe` return potentially confusing results when running cargo scripts with the `-Zscript` unstable feature. While ostensibly correct, returning the actual built executable path is generally less useful to scripts than returning the path to the cargo script file, and leads to antipatterns like using `current_dir().join(SCRIPT_NAME)` to find the script file.

```rust
#!/usr/bin/env -S cargo +nightly -Z script

use std::env::{args, current_dir, current_exe};

fn main() {
    println!("args: {:?}", args());
    println!("current_dir: {}", current_dir().unwrap().display());
    println!("current_exe: {}", current_exe().unwrap().display());
}

```

```text
/tmp/test $ ./test.rs
warning: `package.edition` is unspecified, defaulting to `2021`
   Compiling test- v0.0.0 (/tmp/test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `/home/rhart/.cargo/target/8c/d68b704094916b/debug/test-`
args: Args { inner: ["/home/rhart/.cargo/target/8c/d68b704094916b/debug/test-"] }
current_dir: /tmp/test
current_exe: /home/rhart/.cargo/target/8c/d68b704094916b/debug/test-
```

### Proposed Solution

It seems there are ~3 possible ways to go about this:

- Leave it as is -- it is correct, despite being a little confusing compared to the typical bash "SCRIPT_DIR" one-liner.
- Override the behavior of these functions somehow to return the path to the script. `std::env::current_exe` has a [note](https://doc.rust-lang.org/std/env/fn.current_exe.html) that it may return the path of a symbolic link instead of a target of a symbolic link, or other platform specific behavior. Treating the script file as a symbolic link-equivalent whose path is returned instead of the actual executable using this escape hatch is the route I'd personally like best.
- Provide a way of accessing the script environment separately from the executable environment.

### Notes

Related to #3502 and #12207.

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

Fixes #12870

### CODE REVIEW

File: crates/cargo-util/src/process_builder.rs [hunk 1]
```diff
@@ -92,6 +95,12 @@ impl ProcessBuilder {
         self
     }
 
+    /// (chainable) Adds `arg` to the args list.
```
Comment (weihanglo) [inline crates/cargo-util/src/process_builder.rs]:
```suggestion
    /// (chainable) Overrides `arg0` for this program.
```

File: crates/cargo-util/src/process_builder.rs [hunk 2]
```diff
@@ -483,6 +497,11 @@ impl ProcessBuilder {
             cmd.args(iter);
             cmd
         };
+        #[cfg(unix)]
+        if let Some(arg0) = self.get_arg0() {
```
Comment (weihanglo) [inline crates/cargo-util/src/process_builder.rs:501]: https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw


> If both lpApplicationName and lpCommandLine are non-**NULL**, the null-terminated string pointed to by lpApplicationName specifies the module to execute, and the null-terminated string pointed to by lpCommandLine specifies the command line. The new process can use [GetCommandLine](https://learn.microsoft.com/en-us/windows/desktop/api/processenv/nf-processenv-getcommandlinea) to retrieve the entire command line. Console processes written in C can use the argc and argv arguments to parse the command line. Because argv[0] is the module name, C programmers generally repeat the module name as the first token in the command line.

Not sure if this means that we can override the first token in `lpCommandLine` as arg0 overrideen.

**Review by weihanglo — COMMENTED** [review]
Trying to think through cases of [the detection of the `CARGO` env](https://github.com/rust-lang/cargo/blob/da81ca317ef0223a28c37a9de8e5220fd5870a17/src/cargo/util/context/mod.rs#L465-L526), but probably doesn't really matter if they really want to access `CARGO` and know which Cargo they are using?
