### PR TITLE
Fix dep/feat syntax with hidden implicit optional dependencies

### LINKED ISSUE #10788: Using `dep:` syntax in Cargo.toml makes it impossible to enable features for dependencies unless you also have a feature by that name
Any crate with this Cargo.toml, or any one like it:

```toml
[package]
name = 'whatever'
version = '0.1.0'
edition = '2021'

[features]
default = ['font', 'allsorts/flate2_rust']
font = ['dep:allsorts']

[dependencies]
allsorts = { version = '~0.10.0', optional = true, default-features = false }
```

fails to compile because of the `allsorts/flate2_rust`, even though it shouldn't (`allsorts` is a dependency, not a feature name).

Adding an `allsorts` feature, even a completely empty one, fixes the error:

```toml
[package]
name = 'whatever'
version = '0.1.0'
edition = '2021'

[features]
default = ['font', 'allsorts/flate2_rust']
font = ['dep:allsorts']
allsorts = []

[dependencies]
allsorts = { version = '~0.10.0', optional = true, default-features = false }
```

so this is probably a misbehaving lint. I don't want an extra `allsorts` feature (in my real crate, `font` is more than just `allsorts`, and enabling `allsorts` on its own makes 0 sense).

If this lint exists for encapsulation purposes, I would like to be able to do `dep:allsorts/flate2_rust` at least, if there is no outer-facing `allsorts` feature (although I'd add one in that case so that downstream crates can configure which flate2 backend they want).

Active toolchain:

```
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.63.0-nightly (dc80ca78b 2022-06-21)
```

I have made a minimum effort to search for duplicate issues, but "dep cargo feature" is such a generic search term that it gives thousands of results.

### PR DESCRIPTION
**Pull request by ehuss**
This fixes an issue with `dep/feat` syntax in the `[features]` table where it wouldn't work if the optional dependency had its implicit feature removed via the `dep:` syntax.

The problem is that both resolvers were expecting that `dep/feat` would be able to activate a feature named "dep". But if that implicit feature wasn't created, then it would fail with an error.

This was just an oversight (which probably happened in #9574).

Fixes #10788

### CODE REVIEW

File: tests/testsuite/features_namespaced.rs [hunk 1]
```diff
@@ -1216,3 +1216,81 @@ Caused by:
...
+                [package]
+                name = "foo"
+                version = "0.1.0"
+
+                [dependencies]
+                bar = { path = "bar", optional = true }
+
+                [features]
+                f1 = ["dep:bar"]
+                f2 = ["bar/bar_feat"]
```
Comment (epage) [inline tests/testsuite/features_namespaced.rs:1237]: I think I would have preferred for this to be `dep:bar/bar_feat` for improved consistency but that is already out the window because `bar?/bar_feat` already works.

**Review by epage — APPROVED** [review]
Based on the tests this seems fine but I don't feel the resolver changes are clear enough without digging a lot more into the implementation for me to feel comfortable merging this.  The change causes us to skip some parts but its not obvious from this that this allows the rest to work

File: src/cargo/core/resolver/features.rs [hunk 2]
```diff
@@ -717,7 +717,14 @@ impl<'a, 'cfg> FeatureResolver<'a, 'cfg> {
                         // The old behavior before weak dependencies were
                         // added is to also enables a feature of the same
                         // name.
-                        self.activate_rec(pkg_id, fk, dep_name)?;
+                        //
+                        // Don't enable if the implicit optional dependency
+                        // feature wasn't created due to `dep:` hiding.
```
Comment (weihanglo) [inline src/cargo/core/resolver/features.rs:722]: Feel like it's a bit too concise. Perhaps add some links as references?

```suggestion
                        // Don't enable if the implicit optional dependency
                        // feature wasn't created due to `dep:` hiding.
                        // See rust-lang/cargo#10788 and rust-lang/cargo#12130
```

**Review by weihanglo — APPROVED** [review]
The change is good. `r=weihanglo` when you're ready.
