### PR TITLE
fix: fetch nested git submodules

### LINKED ISSUE #12151: Relative git submodules did not resolve correctly
### Problem

I'm trying to add dependency from git repo that have submodule from different git org/user. That submodule also have submodule as dependency. It looks something like this:
```
https://github.com/messense/mupdf-rs.git
└── https://github.com/ArtifexSoftware/mupdf.git
    ├── https://github.com/ArtifexSoftware/jbig2dec.git
    ├── ...
    ├── https://github.com/ArtifexSoftware/thirdparty-curl.git
    └── ...
```

When cargo fetch the submodule, it's using the wrong url, instead of fetching from `https://github.com/ArtifexSoftware/thirdparty-curl.git`, it's fetching from `https://github.com/messense/thirdparty-curl.git`. When I check the [`.gitmodules`](https://github.com/ArtifexSoftware/mupdf/blob/master/.gitmodules) in the repo, it has relative url.

the `.gitmodules` looks like this:
```
[submodule "thirdparty/jbig2dec"]
	path = thirdparty/jbig2dec
	url = ../jbig2dec.git
...
[submodule "thirdparty/curl"]
	path = thirdparty/curl
	url = ../thirdparty-curl.git
...
```

### Steps

1. Add `mupdf = {git="https://github.com/messense/mupdf-rs.git", rev="77f17e2b52beeeb108927f65471f122dc572740e"}` as dependency in `cargo.toml`
2. Run `cargo build`

### Possible Solution(s)

_No response_

### Notes

log:
```
PS C:\Users\LazyGeniusMan\Downloads\mupdf\test-toc> cargo run
    Updating git repository `https://github.com/messense/mupdf-rs.git`
    Updating git submodule `https://github.com/messense/thirdparty-curl.git`
error: failed to get `mupdf` as a dependency of package `test-toc v0.1.0 (C:\Users\LazyGeniusMan\Downloads\mupdf\test-toc)`

Caused by:
  failed to load source for dependency `mupdf`

Caused by:
  Unable to update https://github.com/messense/mupdf-rs.git?rev=77f17e2b52beeeb108927f65471f122dc572740e

Caused by:
  failed to update submodule `mupdf-sys/mupdf`

Caused by:
  failed to update submodule `thirdparty/curl`

Caused by:
  failed to fetch submodule `thirdparty/curl` from https://github.com/messense/thirdparty-curl.git

Caused by:
  failed to authenticate when downloading repository

  * attempted to find username/password via git's `credential.helper` support, but failed

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  failed to acquire username/password from local configuration
```

### Version

```text
cargo 1.68.2 (6feb7c9cf 2023-03-26)
release: 1.68.2
commit-hash: 6feb7c9cfc0c5604732dba75e4c3b2dbea38e8d8
commit-date: 2023-03-26
host: x86_64-pc-windows-msvc
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:Schannel)
os: Windows 10.0.19044 (Windows 10 Pro) [64-bit]
```

### PR DESCRIPTION
**Pull request by krs98**
### What does this PR try to resolve?

Fixes #12151.

When recursing submodules, the url of the parent remote was being passed to `update_submodules` instead of the child remote url. This caused Cargo to try to add the wrong submodule. 

### How should we test and review this PR?

A test case is added in the first commit. The second one renames the `url` variable as suggested in the issue. The third includes the changes to fix the issue. The last one includes a minor refactor where a redundant `match` expr is removed.

### CODE REVIEW

File: src/cargo/sources/git/utils.rs [hunk 1]
```diff
@@ -453,17 +455,14 @@ impl<'a> GitCheckout<'a> {
...
-                        format!(
-                            "failed to parse relative child submodule url `{}` using parent base url `{}`",
-                            child_url_str, new_parent_remote_url
-                        )
-                    })?,
-                }
+                new_parent_remote_url.join(child_url_str).with_context(|| {
+                    format!(
+                        "failed to parse relative child submodule url `{}` using parent base url `{}`",
+                        child_url_str, new_parent_remote_url
```
Comment (weihanglo) [inline src/cargo/sources/git/utils.rs:461]: Not blockers

* use implicit arg capture maybe?
* perhaps wrap the line for readability in source code level

```suggestion
                        "failed to parse relative child submodule url `{child_url_str}` \
                        using parent base url `{new_parent_remote_url}`"
```

File: src/cargo/sources/git/utils.rs [hunk 2]
```diff
@@ -453,17 +455,14 @@ impl<'a> GitCheckout<'a> {
...
+                    )
+                })?
             } else {
-                child_url_str.to_string()
+                Url::parse(child_url_str)?
```
Comment (weihanglo) [inline src/cargo/sources/git/utils.rs:465]: I know it is pretty unlikely to happen but maybe it still worth having a decent error message for this. What do you think about something like:
```
failed to parse url for submodule `{child_module_name}`: `{child_url_str}`
```

File: tests/testsuite/git.rs [hunk 3]
```diff
@@ -3619,3 +3619,69 @@ fn cleans_temp_pack_files() {
...
+            "[UPDATING] git repository `{}`\n\
+             [UPDATING] git submodule `{}`\n\
+             [UPDATING] git submodule `{}`\n\
+             [COMPILING] dep1 v0.5.0 ({}#[..])\n\
+             [COMPILING] foo v0.5.0 ([CWD])\n\
+             [FINISHED] dev [unoptimized + debuginfo] target(s) in [..]\n",
+            path2url(&user1_git_project.root()),
+            path2url(&user2_git_project.root()),
+            path2url(&user2_git_project2.root()),
+            path2url(&user1_git_project.root()),
```
Comment (weihanglo) [inline tests/testsuite/git.rs:3682]: Could we follow how the string matches have been done in other test cases? Like the following, we don't want to many escapes and leading whitespaces.

https://github.com/rust-lang/cargo/blob/9e33d3124165bd605225fa30d6f5a1762e1c6ec1/tests/testsuite/git.rs#L2347-L2354

**Review by weihanglo — APPROVED** [review]
Thanks. That's pretty much of it!
