### PR TITLE
fix: reset $CARGO if the running program is real `cargo[.exe]` 

### LINKED ISSUE #15099: `$CARGO` passed to external subcommands can point to the wrong `cargo` if already set
### Problem

Observed in https://github.com/rust-lang/rust-clippy/issues/14045, if `cargo +nightly clippy` is ran by a process with `CARGO` pointing to the stable `cargo` then nightly `clippy-driver` will be ran by stable `cargo`

In this case that resulted in a confusing warning

### Steps

1. Put the following into your `PATH` as `cargo-foo`

   ```bash
   #!/usr/bin/env bash

   echo "$CARGO"
   ```
2. With stable cargo use `cargo run` on

   ```rust
   use std::process::Command;
   
   fn main() {
       Command::new("cargo")
           .args(["+nightly", "foo"])
           .status()
           .unwrap();
   }
   ```

3. The output will be `.../.rustup/toolchains/stable-.../bin/cargo`

### Possible Solution(s)

Looks to be due to https://github.com/rust-lang/cargo/pull/11285, perhaps there could be an exception for when the current exe really is `cargo`

### Notes

_No response_

### Version

```text
cargo 1.84.0 (66221abde 2024-11-19)
```

### PR DESCRIPTION
**Pull request by smoelius**
Overwrite `$CARGO` when the current exe is detected to be a cargo binary.

From https://github.com/rust-lang/cargo/issues/15099#issuecomment-2666737150:
> opt-in behavior (set by cargo-the-bin):
> 
> 1. `from_current_exe` if its `cargo[EXE_SUFFIX]`
> 2. `from_argv` if its `cargo[EXE_SUFFIX]`
> 3. `from_env`
> 4. `from_current_exe`
> 5. `from_argv`

r? @epage

### CODE REVIEW

**Comment by smoelius** [comment]
I'll fix the errors shortly.

File: src/cargo/util/context/mod.rs [hunk 1]
```diff
@@ -493,9 +493,23 @@ impl GlobalContext {
                     paths::resolve_executable(&argv0)
                 }
 
+                fn is_cargo(path: &Path) -> bool {
```
Comment (weihanglo) [inline src/cargo/util/context/mod.rs:496]: We might want to write down a comment for why checking `cargo[.exe]` is needed.

**Review by weihanglo — COMMENTED** [review]
Thanks for the patch!

Please allow me time to test against the dynamic linker use case.

File: src/cargo/util/context/mod.rs [hunk 2]
```diff
@@ -493,9 +493,23 @@ impl GlobalContext {
...
+                    path.file_stem() == Some(OsStr::new("cargo"))
+                }
+
+                let from_current_exe_result = from_current_exe();
```
[the remark this answers is not in the document]
Comment (smoelius) [reply src/cargo/util/context/mod.rs]: I don't object, but just to be clear, that means that `from_current_exe` and `from_argv` shadow declarations from above.

**Comment by smoelius** [comment]
Just because I am curious, is the reason for the recent CI failures known?

**Comment by epage** [comment]
They were fixed in #15211
- One was because of a short term hack until 1.85 was released which then needed to be removed
- We're experimenting with automating the fix for the other one in #15212.

**Comment by smoelius** [comment]
> * We're experimenting with automating the fix for the other one in [chore(ci): Auto-update cargo-semver-checks #15212](https://github.com/rust-lang/cargo/pull/15212).

Oh, interesting! Thank you for explaining!

**Comment by smoelius** [comment]
If I'm interpreting the results right, path normalization is applied to sterr but not stdout?

Anyway, the PR should be ready for review.

**Review by weihanglo — COMMENTED** [review]
Did manual tests for ld wrapper from what Joo's has described in #10113. This seems working!

One thing I am not sure is this characteristic:

> * We don't fix this issue for when users have an alternative name for the Cargo binary (or on some platforms, an alternative symlink name)

Should we document our heuristic rule in the CARGO env doc? I feel like it might be excessive and don't want to wait for a perfect doc to merge this fix.

File: tests/testsuite/freshness.rs
Comment (weihanglo) [inline tests/testsuite/freshness.rs:1]: Feel like this should be moved to either `test/testsuite/cargo_command.rs` or `test/testsuite/run.rs` (perhaps the former is better?).

File: tests/testsuite/cargo_command.rs [hunk 3]
```diff
@@ -391,10 +391,13 @@ fn cargo_subcommand_env() {
         .canonicalize()
         .unwrap();
     let envtest_bin = envtest_bin.to_str().unwrap();
+    // Previously, `$CARGO` would be left at `envtest_bin`. However, with the
```
Comment (weihanglo) [inline tests/testsuite/cargo_command.rs:394]: Seeing this test change and I wonder if using `$CARGO` as a Cargo wrapper is a supported use case, and we don't want to reset it. 

Maybe we can detect iff the current `$CARGO` is `cargo[.exe]` and then we reset?

Comment (weihanglo) [reply tests/testsuite/cargo_command.rs:394]: cc @epage as you proposed the current solution

**Comment by smoelius** [comment]
> One thing I am not sure is this characteristic:
> 
> > * We don't fix this issue for when users have an alternative name for the Cargo binary (or on some platforms, an alternative symlink name)
> 
> Should we document our heuristic rule in the CARGO env doc? I feel like it might be excessive and don't want to wait for a perfect doc to merge this fix.

I would just point out that the current description of each variable is light on details: https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates

I think there some benefit to this, as it makes the list easy to scan.

File: tests/testsuite/cargo_command.rs (hunk 3 above)
Comment (smoelius) [reply tests/testsuite/cargo_command.rs:394]: I have no problem with implementing this is @epage agrees.

Comment (epage) [reply tests/testsuite/cargo_command.rs:394]: `CARGO` was originally not intended for purposes of being a wrapper.  That people could do it was a byproduct of the implementation that was done but it wasn't intentional.  I wouldn't worry too much about it.

Comment (weihanglo) [reply tests/testsuite/cargo_command.rs:394]: That is fair. Thanks Ed.

**Review by weihanglo — APPROVED** [review]
Thanks for working with us for this fix!
