### PR TITLE
fix(check): Fix suggested command for bin package

### LINKED ISSUE #15982: Suggested `cargo fix` command fails for workspace packages not in `default-members`
### Problem

With the following root `Cargo.toml`:

```toml
[workspace]
members = ["a"]
default-members = []
resolver = "3"
```

If the workspace member `a` emits a fixable diagnostic, e.g.

```
% cargo check -p a
    Checking a v0.1.0 (/home/gh-Alexendoo/temp/a)
warning: unnecessary parentheses around assigned value
 --> a/src/main.rs:2:13
  |
2 |     let _ = (1);
  |             ^ ^
  |
  = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
  |
2 -     let _ = (1);
2 +     let _ = 1;
  |

warning: `a` (bin "a") generated 1 warning (run `cargo fix --bin "a"` to apply 1 suggestion)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
```

Running the suggested command results in an error:

```
% cargo fix --bin "a"
error: manifest path `/home/gh-Alexendoo/temp` contains no package: The manifest is virtual, and the workspace has no members.
```

### Steps

_No response_

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
cargo 1.90.0 (840b83a10 2025-07-30)
release: 1.90.0
commit-hash: 840b83a10fb0e039a83f4d70ad032892c287570a
commit-date: 2025-07-30
host: aarch64-unknown-linux-gnu
libgit2: 1.9.1 (sys:0.20.2 vendored)
libcurl: 8.14.1-DEV (sys:0.4.82+curl-8.14.1 vendored ssl:OpenSSL/3.5.0)
ssl: OpenSSL 3.5.0 8 Apr 2025
os: Ubuntu 24.4.0 (noble) [64-bit]
```

### PR DESCRIPTION
**Pull request by dawedawe**
fixes #15982 

This PR fixes the suggested command for a bin package and fixes a comment while in the area.

### CODE REVIEW

File: src/cargo/core/compiler/job_queue/mod.rs [hunk 1]
```diff
@@ -1087,9 +1087,12 @@ impl<'gctx> DrainState<'gctx> {
                     };
                     let mut args = {
                         let named = unit.target.description_named();
-                        // if its a lib we need to add the package to fix
+                        // if it's a lib we need to add the package to fix
                         if unit.target.is_lib() {
                             format!("{} -p {}", named, unit.pkg.name())
+                        // if it's a bin we need to add --package but not --bin
+                        } else if unit.target.is_bin() {
+                            format!("package \"{}\"", unit.pkg.name())
```
Comment (weihanglo) [inline src/cargo/core/compiler/job_queue/mod.rs]: Thanks, though isn't this means we actually test more Cargo targets than the actual failed one?
My initial thought were just always append `-p`. That also cover all Cargo target failing cases, not just lib or bin.

Comment (dawedawe) [reply src/cargo/core/compiler/job_queue/mod.rs]: Ah sorry, I had a temporary glitch here locally that made me think it wouldn't work with `--bin`.
But it seems it's all good now with always using `-p`.

File: src/cargo/core/compiler/job_queue/mod.rs [hunk 2]
```diff
@@ -1085,15 +1085,8 @@ impl<'gctx> DrainState<'gctx> {
...
-                        let named = unit.target.description_named();
-                        // if its a lib we need to add the package to fix
-                        if unit.target.is_lib() {
-                            format!("{} -p {}", named, unit.pkg.name())
-                        } else {
-                            named
-                        }
-                    };
+                    let mut args =
+                        format!("{} -p {}", unit.target.description_named(), unit.pkg.name());
```
Comment (dawedawe) [inline src/cargo/core/compiler/job_queue/mod.rs:1089]: Should we also wrap the package name after `-p` in double quotes?
As it is, it looks a bit inconsistant to me

Comment (weihanglo) [reply src/cargo/core/compiler/job_queue/mod.rs:1089]: pkgid / package name should be a valid string in most shells, comparing to final artifact especially `[[bin]]` can be arbitrary. We can revisit if hitting issues

Comment (weihanglo) [reply src/cargo/core/compiler/job_queue/mod.rs:1089]: I am fine with either actually.

Comment (dawedawe) [reply src/cargo/core/compiler/job_queue/mod.rs:1089]: Thanks, then let's keep the PR scope as it is for now.

Comment (weihanglo) [reply src/cargo/core/compiler/job_queue/mod.rs:1089]: Somehow I remembered it wrongly.

https://doc.rust-lang.org/cargo/reference/unstable.html#different-binary-name

you can have a binary target file name arbitrary but not binary target name. So probably quotes around target names are overly defensive
