### PR TITLE
Do not ignore `--features` when `--all-features` is present

### LINKED ISSUE #10333: `--features` is silently ignored when `--all-features` is present
### Problem

When `--all-features` flag is present, any `--features` flags are **silently** ignored.

At first glance that may not seem as a problem, since all features are enabled anyway. But there is a corner case: an `[[example]]` can depend on a feature of a dependency (`required-features = ["dep/something"]`). Dependency features are not enabled with `--all-features` and `--features` flags are ignored, so it's impossible to build such example with `--all-features`.

This is especially troublesome when using some external tools (like rust-analyzer) that pass `--all-features` to cargo.

### Steps

1. Clone the example repository: https://github.com/WaffleLapkin/cargo_all_some_features
2. try running `cargo run --example example --all-features --features "tracing/log"`
3. notice that cargo suggests using `--features="aaaaaaaa bbbbbbbb cccccccc dddddddd eeeeeeee ffffffff gggggggg tracing/log"`
4. try running `cargo run --example example --all-features --features="aaaaaaaa bbbbbbbb cccccccc dddddddd eeeeeeee ffffffff gggggggg tracing/log"`
5. notice that it doesn't work either (the suggestion is still the same)

### Possible Solution(s)

1. Do not ignore `--features` in the presence of  `--all-features`.
   This seems to be the right & easy way to resolve this issue. I'll try to come up with a PR later.
2. Add a warning or an error when `--all-features` is used with `--features`.
    This does not solve my issue, but at least it improves diagnostics.

### Notes

With `edition = 2021` (instead of `edition = 2018`) the behaviour is even weirder:

```
; sed -i 's/2018/2021/g' ./Cargo.toml           
; cargo run --example example --all-features --features="tracing/log" 
error: none of the selected packages contains these features: tracing/log
; cargo run --example example --all-features --features="aaaaaaaa bbbbbbbb cccccccc dddddddd eeeeeeee ffffffff gggggggg tracing/log"
error: none of the selected packages contains these features: aaaaaaaa, bbbbbbbb, cccccccc, dddddddd, eeeeeeee, ffffffff, gggggggg, tracing/log
; cargo run --example example --features="aaaaaaaa bbbbbbbb cccccccc dddddddd eeeeeeee ffffffff gggggggg tracing/log"               
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/example`
```
Cargo says that all of the features do not exist, even though they clearly exist.

---

`edition = 2018` though has the oposite problem of allowing clearly non-existing features (by ignoring all of them):
```
; cargo b --all-features --features "anahsddhjdhjdh definetly_non_existing_feature dep/aaaa"                         
   Compiling tracing v0.1.29
   Compiling cargo_all_some_features v0.1.0 (/home/waffle/projects/repos/cargo_all_some_features)
    Finished dev [unoptimized + debuginfo] target(s) in 0.94s
```
----

See also: #10332

### Version

```text
cargo 1.60.0-nightly (95bb3c92b 2022-01-18)
```

### PR DESCRIPTION
**Pull request by WaffleLapkin**
This allows to specify dependency features when using `--all-features`, for example:
```shell
$ cargo run --example example --all-features --features="tracing/log"
```
You can test this in this repository: https://github.com/WaffleLapkin/cargo_all_some_features, it contains an example with ``required-features = [..., "tracing/log"]`` that is impossible to run with `--all-features` without this patch.

An attempt to fix #10333

### CODE REVIEW

**Comment by WaffleLapkin** [comment]
CI seems to fail due to changes in cli help formatting, but I didn't change anything there 🤔

**Comment by weihanglo** [comment]
for fixing broken tests on CI, rebase to master 😄

ref: https://github.com/rust-lang/cargo/pull/10336

**Comment by WaffleLapkin** [comment]
@weihanglo thanks!

File: tests/testsuite/features_namespaced.rs [hunk 1]
```diff
@@ -849,7 +849,8 @@ foo v0.1.0 ([ROOT]/foo)
 bar v1.0.0
 └── bar feature \"default\"
     └── foo v0.1.0 ([ROOT]/foo)
-        └── foo feature \"a\" (command-line)
+        ├── foo feature \"a\" (command-line)
+        └── foo feature \"default\" (command-line)
```
Comment (alexcrichton) [inline tests/testsuite/features_namespaced.rs:853]: While I don't think that this is a bug with this PR per-se I think that this is a bug because neither of the packages here actually have a feature called `default`, so I don't think that this should be printed. I think this could probably be fixed by conditionally inserting the feature `"default"` in `cargo tree` depending on whether the package actually has that feature.

**Review by alexcrichton — COMMENTED** [review]
Looks reasonable to me! Can you add a test for this feature as well?

File: tests/testsuite/features_namespaced.rs (hunk 1 above)
Comment (WaffleLapkin) [reply tests/testsuite/features_namespaced.rs:853]: Should I open an issue about this?

**Comment by WaffleLapkin** [comment]
@alexcrichton I've added a test

File: tests/testsuite/features_namespaced.rs (hunk 1 above)
Comment (alexcrichton) [reply tests/testsuite/features_namespaced.rs:853]: Hm yeah I think it's probably orthogonal-enough from this PR it's best to fix later, and yeah if you wouldn't mind opening an issue that'd be great!

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

File: tests/testsuite/features_namespaced.rs (hunk 1 above)
Comment (WaffleLapkin) [reply tests/testsuite/features_namespaced.rs:853]: Opened #10351
