### PR TITLE
fix: Fix unusual errors with `RUSTC_WRAPPER`

### LINKED ISSUE #5981: cargo fix doesn't work with RUSTC_WRAPPER=sccache
Before:

```bash
$ cargo +nightly new --lib foo && command cd foo && cargo +nightly fix --lib
     Created library `foo` project
    Checking foo v0.1.0 (file:///Users/dnw/Desktop/foo)
error: failed to execute compile
caused by: Bad relative path
error: Could not compile `foo`.
```

After:

```bash
$ unset RUSTC_WRAPPER; cargo +nightly new --lib foo && command cd foo && cargo +nightly fix --lib
     Created library `foo` project
    Checking foo v0.1.0 (file:///Users/dnw/Desktop/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.82s
```

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit fixes the interaction of `cargo fix` and `RUSTC_WRAPPER`, ensuring
that Cargo at least doesn't die internally. For now `RUSTC_WRAPPER` is
overridden for normal execution but we can eventually one day probably support
`RUSTC_WRAPPER`!

Closes #5981

### CODE REVIEW

File: src/cargo/core/compiler/compilation.rs [hunk 1]
```diff
@@ -82,18 +82,26 @@ pub struct Compilation<'cfg> {
 
 impl<'cfg> Compilation<'cfg> {
     pub fn new<'a>(bcx: &BuildContext<'a, 'cfg>) -> CargoResult<Compilation<'cfg>> {
-        let mut rustc = bcx.rustc.process();
+        // If we're using cargo as a rustc wrapper then we're in a situation
+        // like `cargo fix`. For now just disregard the `RUSTC_WRAPPER` env var
+        // (which is typically set to `sccache` for now). Eventually we'll
+        // probably want to implement `RUSTC_WRAPPER` for `cargo fix`, but we'll
+        // leave that open as a bug for now.
+        let mut rustc = if bcx.build_config.cargo_as_rustc_wrapper {
```
Comment (dwijnand) [inline src/cargo/core/compiler/compilation.rs]: This option sounds more generic than it actually is. Before looking it up I would've assumed it was also used for at least `cargo rustc`, maybe `cargo rustdoc` too (given the chat in #5958).

But, no, it's just set `ops::fix`.

File: tests/testsuite/fix.rs [hunk 2]
```diff
@@ -1117,3 +1117,26 @@ fn doesnt_rebuild_dependencies() {
 ")
         .run();
 }
+
+#[test]
+fn does_not_crash_with_rustc_wrapper() {
+    // We don't have /usr/bin/env on Windows.
```
Comment (dwijnand) [inline tests/testsuite/fix.rs]: So? It's expressly ignored, so whatever you set `RUSTC_WRAPPER` doesn't even need to exist on non-windows, no?

**Comment by dwijnand** [comment]
I also manually tested this fixes my case in #5981:

```bash
23:53:40 $ type dcargo
dcargo is a function
dcargo ()
{
    /d/cargo/target/debug/cargo "$@"
}

23:53:42 $ dcargo new --lib foo && command cd foo && dcargo fix --lib
     Created library `foo` project
    Checking foo v0.1.0 (file:///Users/dnw/Desktop/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.55s
```

🎉

File: tests/testsuite/fix.rs [hunk 3]
```diff
@@ -1117,3 +1117,26 @@ fn doesnt_rebuild_dependencies() {
...
+    if cfg!(windows) {
+        return;
+    }
+    let p = project()
+        .file(
+            "Cargo.toml",
+            r#"
+                [package]
+                name = "foo"
+                version = "0.1.0"
```
Comment (dwijnand) [inline tests/testsuite/fix.rs]: Old habits die hard 😉

**Comment by dwijnand** [comment]
```
---- build_script::switch_features_rerun stdout ----
running `C:\projects\cargo\target\debug\cargo.exe run -v --features=foo`
running `C:\projects\cargo\target\debug\cargo.exe run -v`
running `C:\projects\cargo\target\debug\cargo.exe run -v --features=foo`
thread 'build_script::switch_features_rerun' panicked at '
Expected: execs
    but: exited with exit code: 101
--- stdout
--- stderr
       Fresh foo v0.0.1 (file:///C:/projects/cargo/target/cit/t353/foo)
error: failed to link or copy `C:\projects\cargo\target\cit\t353\foo\target\debug\deps\foo-5dfa908d8c0c3515.exe` to `C:\projects\cargo\target\cit\t353\foo\target\debug\foo.exe`
Caused by:
  Access is denied. (os error 5)
', tests\testsuite\support\mod.rs:731:13
```

@bors: retry
