### PR TITLE
Stabilize Alternative Registries

### LINKED ISSUE #4688: Areas requiring agreement for stabilization of alternative registries
Below are a list of current concerns that @alexcrichton raised as wanting resolution before alternative registries becomes stable:

- [ ] --registry command for publish
  * currently `login`, `owner`, `publish`, `search`, and `yank` have `--registry` as an argument, taking a registry identifier
- [x] format of the registry name, including validation of the format
  * should we accept `foo.bar.baz`? Just `foo-bar`? What about `foo-💖`?
- [ ] what should be the format of the credentials file for alternative registries
  * Currently it's:
  ```toml
  token = ".." # crates.io token
  [custom-registry-name]
  token = ".." # custom registry token
  ```
- [ ] have we got the correct syntax for the .cargo/config file
  * Currently it's:
  ```toml
  [registries.custom-registry-name]
  index = "..."
  ```
- [ ] specification of index format (#4574)
- [ ] verification that the current index follows the specification (https://github.com/rust-lang/crates.io/issues/1168)
- [ ] specification in Cargo.toml
  * Currently it's:
  ```toml
  [dependencies]
  foo = { version = "0.1", registry = "custom-registry-name" }
  ```
- [x] `cargo login` doesn't work without a token for a custom registry, it just returns an error instead of printing a URL to visit and reading the token from a prompt
- [ ] credentials per project #4645
- [ ] registry subcommand #4690

Please add to the list to include any other concerns.

### LINKED ISSUE #6589: Alternative Registries Stabilization Proposal
@rfcbot fcp merge

This issue is to track the proposal to stabilize alternative registries.

RFC: [2141](https://github.com/rust-lang/rfcs/blob/master/text/2141-alternative-registries.md)
Tracking Issue: rust-lang/rust#44931
Stabilization Target: 1.34 — Release date Apr 11 2019

## What is being stabilized

Alternate registries allows Cargo to use registries other than crates.io. The following is an overview of the surface changes:

- Alternate registries are defined in `.cargo/config` under the `registries` table, example:

    ```toml
    [registries]
    my-registry = { index = "https://my-intranet:8080/git/index" }
    ```

- Dependencies in `Cargo.toml` can reference other registries with the `registry` key, example:

    ```toml
    [dependencies]
    other-crate = { version = "1.0", registry = "my-registry"}
    ```

- Commands may take the `--registry` flag to specify the server to interact with. This includes `install`, `login`, `owner`, `publish`, `search`, and `yank`. `new` and `init` also take the same flag to initialize the `publish` field. Example:

    ```bash
    cargo publish --registry my-registry
    ```

    - The default for `--registry` may be specified in `.cargo/config` with the `registry.default` key (except `new` and `init`, see #6153). Example:

    ```toml
    [registry]
    default = "my-registry"
    ```

- Manifests may restrict which registry they may interact with the `publish` key, example:

    ```toml
    [package]
    publish = ["my-registry"]
    ```

- Authentication information saved by `cargo login` is stored in `.cargo/credentials` under the registries table:

    ```toml
    [registries.my-registry]
    token = "854DvwSlUwEHtIo3kWy6x7UCPKHfzCmy"
    ```

- Ancillary feature support:
    - `cargo metadata` exposes the `registry` field for dependency declarations. `source` and PackageID fields also point to the registry.
    - `[patch]` tables can be a registry name or index URL.
    - Registries may opt-out of Web API support, in which case commands like `publish` display an appropriate error message.

- Misc post-RFC decisions:
    - Registries as URLs in `Cargo.toml` are currently not allowed.
    - Registry names are restricted to the same format as package names (alphanumeric characters, dash, and underscore only).
    - Registry URLs in `[registries]` may contain usernames, but not passwords.
    - The crates.io codebase won't currently cater towards being used for alternative registries. Cargo refuses to publish alternative dependencies to crates.io, and crates.io double-checks to prevent it.
    - `generate-index-metadata` will currently not be implemented directly in Cargo. [cargo-index](https://crates.io/crates/cargo-index) is a demonstration of how it can be implemented using `cargo metadata`.
    - [cargo-reg](https://crates.io/crates/cargo-reg) is a third-party util to assist adding registries to `.cargo/config`.

- Documentation: I have written a new chapter for the Cargo Reference that goes into depth about registries. This includes how to use them, how to run one, the index format, and the minimum required Web API. I will be posting this soon.

### PR DESCRIPTION
**Pull request by ehuss**
This includes a few minor changes besides stabilizing:
- `cargo search` won't display `crates.io` search URL for extra results for non-crates.io registries.
- Document using environment variables for API tokens.
- Explicit section in `config.md` for documenting the credentials file.

Closes rust-lang/rust#44931
Closes rust-lang/crates-io-cargo-teams#21
Closes #6589
Closes #4688

### CODE REVIEW

File: src/cargo/util/toml/mod.rs [hunk 1]
```diff
@@ -1410,12 +1403,10 @@ impl DetailedTomlDependency {
             .set_optional(self.optional.unwrap_or(false))
             .set_platform(cx.platform.clone());
         if let Some(registry) = &self.registry {
-            cx.features.require(Feature::alternative_registries())?;
             let registry_id = SourceId::alt_registry(cx.config, registry)?;
             dep.set_registry_id(registry_id);
         }
         if let Some(registry_index) = &self.registry_index {
-            cx.features.require(Feature::alternative_registries())?;
```
Comment (alexcrichton) [inline src/cargo/util/toml/mod.rs]: *technically speaking* we don't have to delete this code, but also technically speaking there's no reason to keep the code around!

File: src/doc/man/options-token.adoc [hunk 2]
```diff
@@ -1,2 +1,8 @@
 *--token* _TOKEN_::
-    API token to use when authenticating.
+    API token to use when authenticating. This overrides the token stored in
+    the credentials file (which is created by man:cargo-login[1]).
++
+The token for crates.io may be specified with the `CARGO_REGISTRY_TOKEN`
+environment variable. Tokens for other registries may be specified with
+environment variables of the form `CARGO_REGISTRIES_NAME_TOKEN` where `NAME`
+is the name of the registry in all capital letters.
```
Comment (alexcrichton) [inline src/doc/man/options-token.adoc]: I wonder if this could perhaps mention that the env vars are derived from the `.cargo/config` configuration to ensure both mechanisms are mentioned here?

File: src/doc/src/reference/registries.md [hunk 3]
```diff
@@ -0,0 +1,586 @@
...
+The authentication information saved by [`cargo login`] is stored in the
+`credentials` file in the Cargo home directory (default `$HOME/.cargo`). It
+has a separate table for each registry, for example:
+
+```toml
+[registries.my-registry]
+token = "854DvwSlUwEHtIo3kWy6x7UCPKHfzCmy"
+```
+
+### Running a Registry
```
Comment (alexcrichton) [inline src/doc/src/reference/registries.md]: Could some text be added to this section along the lines of:

* There's no widely used piece of software used to run your own registry
* We are, however, very interested in documenting those which crop up
* We're also interested in documenting integration with existing package caches once they have crates.io support

**Comment by ninrod** [comment]
this seems great. So can I use rust with artifactory now?

**Comment by nbigaouette-eai** [comment]
For artifactory support, please vote for the feature request here: https://www.jfrog.com/jira/browse/RTFACT-13469

**Comment by przygienda** [comment]
yeah ! ;-)
