### PR TITLE
fix(fix): Address problems with implicit -> explicit feature migration

### LINKED ISSUE #14010: 2024 implicit feature migration deletes dependency features
### Problem

Migrating to 2024 causes `foo/feature_name` features to get removed for optional dependencies. Those need to be preserved.

### Steps

Example manifest:

```toml
cargo-features = ["edition2024"]
[package]
name = "foo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", optional = true }

[features]
serde = ["serde/derive"]
```

Running `cargo fix --edition` on this will result in:

```toml
serde = ["dep:serde"]
```

Note that the `/derive` feature got removed.

### Possible Solution(s)

When there is a `["foo/feature_name"]` syntax in the `[features]` table, and `dep:foo` isn't found anywhere in the `[features]` table, it should be rewritten to be `["dep:foo", "foo/feature_name"]`. Some things to be careful of:

* Adjust all places that `foo/xxx` is found (such as `x = ["foo/a"]` and `y = ["foo/b"]`, both x and y need a "`dep:foo`")
* Should not disturb any other features (like `["foo/feature_name", "bar"] would be rewritten to ["dep:foo", "foo/feature_name", "bar"]`)
* Should avoid duplicates (`["foo/a", "foo/b"]` should not have two `dep:foo` entries added).

### Notes

_No response_

### Version

```text
cargo 1.80.0-nightly (7a6fad098 2024-05-31)
release: 1.80.0-nightly
commit-hash: 7a6fad0984d28c8330974636972aa296b67c4513
commit-date: 2024-05-31
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0 (sys:0.4.72+curl-8.6.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 14.5.0 [64-bit]
```

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

Within the scope of `cargo fix` there  are two problems
- We wipe out existing feature activations if it has the same name as an optional dependency
- The `Cargo.toml` isn't parseable because the unused optional dependency won't "exist" if just `dep_name/feature_name` is used

Fixes #14010

### How should we test and review this PR?

As for the unused optional dependency not "existing" error,
- #14015 is for improving the message for weak dep features
- #14016 is for re-evaluating how we handle this for strong dep features

Depending on what solution we go with for #14016, we might want to revisit the second migration within this PR.  This is one reason I made the commit separate (in addition to just making it clearer whats happening as this gets into some finer details of features).

### CODE REVIEW

File: src/cargo/ops/fix.rs [hunk 1]
```diff
@@ -461,14 +465,43 @@ fn add_feature_for_unused_deps(pkg: &Package, parent: &mut dyn toml_edit::TableL
...
+                // Ensure `dep:dep_name` is present for `dep_name/feature_name` since `dep:` is the
+                // only way to guarantee an optional dependency is available for use.
+                //
+                // The way we avoid implicitly creating features in Edition2024 is we remove the
+                // dependency from `resolved_toml` if there is no `dep:` syntax as that is the only
+                // syntax that suppresses the creation of the implicit feature.
+                for (feature_name, activations) in features.iter_mut() {
+                    let Some(activations) = activations.as_array_mut() else {
+                        let _ = gctx.shell().warn(format_args!("skipping fix of feature `{feature_name}` in package `{}`: unsupported feature schema", pkg.name()));
+                        continue;
```
Comment (epage) [inline src/cargo/ops/fix.rs:487]: This check was written with rust-lang/rfcs#3416 in mind

That syntax is likely to work on any Edition and if we forget to touch this code, I'd prefer to make that known so people can report it to us and we can fix it rather than silently ignoring it.

The question that remains is to warn or error.  I figured we shouldn't block the user from getting other fixes for something they can't workaround in a reasonable way.

**Comment by ehuss** [comment]
Thanks!

@bors r+
