### PR TITLE
fix(vendor): recursively filter git files in subdirectories

### LINKED ISSUE #13607: Vendored crate with git submodule may have something wrong with gitignore
### Problem

When one crate (lib) uses `jemalloc` as a submodule and another crate (binary) uses that library, `cargo vendor` for the binary works, but some files with checksums are ignored by `git`.

If I run `git clean -dfqx` or push the repository and clone it to another location, the build fails.

I tried to reproduce it with my handwritten `.gitignore` but failed. Only `jemalloc` (with its `gitignore`) can reproduce the problem.

### Steps

I've created repositories for reproducing it:

- (lib): https://github.com/wfly1998/vendor-issue-reproduce-crate
- (bin): https://github.com/wfly1998/vendor-issue-reproduce

There is `jemalloc` as submodule in the lib.

To reproduce the problem, you can use the above binary crate:

```bash
git clone https://github.com/wfly1998/vendor-issue-reproduce.git
cd vendor-issue-reproduce
cargo vendor > .cargo/config
git add .
git commit -m "test"
git clean -dfqx # or try `git clean -dfnx` to show the ignored files
cargo build --offline # fails
```

My outputs:

```
$ git clean -dfnx
Would remove target/
Would remove vendor/is_odd/jemalloc/test/stress/cpp/

$ git clean -dfqx

$ cargo build --offline
error: failed to calculate checksum of: vendor-issue-reproduce/vendor/is_odd/jemalloc/test/stress/cpp/microbench.cpp

Caused by:
  failed to open file `vendor-issue-reproduce/vendor/is_odd/jemalloc/test/stress/cpp/microbench.cpp`

Caused by:
  No such file or directory (os error 2)
```

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
$ cargo version --verbose
cargo 1.79.0-nightly (2fe739fcf 2024-03-15)
release: 1.79.0-nightly
commit-hash: 2fe739fcf16c5bf8c2064ab9d357f4a0e6c8539b
commit-date: 2024-03-15
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Debian 10 (buster) [64-bit]
```
```

### LINKED ISSUE #16148: .gitattributes in subdirectories
### Code

```
# From file `vendor/libssh2-sys-0.3.1/libssh2/tests/openssh_server/.gitattributes`
# Copyright (C) The libssh2 project and its contributors.
#
# SPDX-License-Identifier: BSD-3-Clause

# OpenSSH requires LF EOLs in key files, even on Windows, where
# a git checkout may set CRLF EOLs by default.
* text eol=lf
```

### Meta

In Rust v1.89.0 the version of libssh2-sys-0.3.1 includes `.gitattributes` which specifies line endings.

`vendor/libssh2-sys-0.3.1/libssh2/tests/openssh_server/.gitattributes`

### Error output

When a fetch the rust repo and get the checksum it matches the one in `vendor/libssh2-sys-0.3.1/.cargo-checksum.json`

`$ sha256sum ca_rsa 
52baa93a5f6915bb2d66eef7b9c7f7eec400d5fe5bc969015f46ab05b7e0238f  ca_rsa`

However, once the file is added and uploaded the file changes. We get a checksum error. If I checkout the commit and then measure it again the checksum changes.

`
$ sha256sum ca_rsa
7297a4c658d398564d75964e503da94e845a0d709f64b393e3017e66dee0fb4b  ca_rsa`

Note if I try to add a file I get this: 

```
git add vendor/libssh2-sys-0.3.1/libssh2/tests/openssh_server/ca_rsa 
warning: in the working copy of 'vendor/libssh2-sys-0.3.1/libssh2/tests/openssh_server/ca_rsa', CRLF will be replaced by LF the next time Git touches it
```

### More thoughts
 It looks like Cargo ignores .gitattributes at the root level. Perhaps that can be extended to the subdirectories. [cargo
](https://github.com/rust-lang/cargo/blob/6b4044641a48616fa4a1005979f8e6debb4bbcfe/src/cargo/ops/vendor.rs#L624)
@pirama-arumuga-nainar  @jfgoog 
</p>
</details>

### PR DESCRIPTION
**Pull request by vishalmudhirajpokala**
### What does this PR try to resolve?

Fixes #16148
Fixes #13607

Right now cargo vendor only filters .gitattributes, .gitignore, and .git at the top level of each package. If these files exist in subdirectories, they don't get filtered. This causes problems when the vendored code gets checked into a git repo - git processes those files and modifies them, which breaks checksums.

I ran into this when trying to vendor libssh2-sys. The .gitattributes file in libgit2/src/util/ was getting its line endings changed by git, causing checksum failures.

### How should we test and review this PR?

This follows the atomic commit pattern:
- First commit adds a test showing the current buggy behavior (test passes)
- Second commit implements the fix and updates test assertions (test still passes)

The fix uses components() to recursively check for .git directories (since they can appear at any path level like deep/nested/.git/config), while using file_name() for .gitattributes and .gitignore files.

### Additional context

This should also help with #13607 since it filters .gitignore and .git recursively too.

If people actually need git functionality in their vendored deps, they can add rules to their own .gitattributes at the root level.

### CODE REVIEW

**Comment by vishalmudhirajpokala** [comment]
Hey @weihanglo 
Thanks for the detailed feedback on the previous PR! I've cleaned things up:

I restructured the commits like you suggested - now there's just two. The first one adds the test (which passes because it expects the current buggy behavior), and the second one has the fix plus the updated test expectations. Much cleaner this way.

For the code itself, I kept your suggestions about the comments and only filtering .cargo-ok at the root level. 

For the git file filtering, I ended up using a mix - components() for .git directories and file_name() for the other files. The reason is that .git is actually a directory, so when you have something like deep/nested/.git/config, file_name() just returns "config" and misses the .git part. But for .gitattributes and .gitignore (which are files), file_name() works perfectly. Seemed like a reasonable middle ground?

Also dropped that second libssh2 test since the first one covers everything we need.

Let me know if anything needs tweaking!

File: tests/testsuite/vendor.rs [hunk 1]
```diff
@@ -2122,100 +2122,70 @@ fn vendor_rename_fallback() {
...
-    assert_e2e().eq(
-        p.read_file("vendor/bar/src/lib.rs"),
-        str!["pub fn bar() {}"],
-    );
-}
+    // Generated files should have deterministic mtime after unpacking.
+    assert_deterministic_mtime(p.root().join("vendor/foo/Cargo.lock"));
+    assert_deterministic_mtime(p.root().join("vendor/foo/Cargo.toml"));
+    assert_deterministic_mtime(p.root().join("vendor/foo/.cargo_vcs_info.json"));
+} // <- ADD THIS CLOSING BRACE!
```
Comment (weihanglo) [inline tests/testsuite/vendor.rs]: What is this?

File: src/cargo/ops/vendor.rs [hunk 2]
```diff
@@ -638,17 +638,32 @@ fn copy_and_checksum<T: Read>(
...
-        // the time and if we respect them (e.g.  in git) then it'll
-        // probably mess with the checksums when a vendor dir is checked
-        // into someone else's source control
-        Some(".gitattributes" | ".gitignore" | ".git") => false,
+    // Skip git config files as they're not relevant to builds most of
+    // the time and if we respect them (e.g. in git) then it'll
+    // probably mess with the checksums when a vendor dir is checked
+    // into someone else's source control
+
+    // Check if any component in the path is .git (for directories like deep/nested/.git)
```
Comment (weihanglo) [inline src/cargo/ops/vendor.rs]: Please avoid explaining how in comments unless the approach itself is complex. If you want, please explain why

File: src/cargo/ops/vendor.rs [hunk 3]
```diff
@@ -638,17 +638,32 @@ fn copy_and_checksum<T: Read>(
...
+        if let Some(name) = component.as_os_str().to_str() {
+            if name == ".git" {
+                return false;
+            }
+        }
+    }
 
-        // Temporary Cargo files
-        Some(".cargo-ok") => false,
+    // Check file name for .gitattributes and .gitignore
```
Comment (weihanglo) [inline src/cargo/ops/vendor.rs]: Please avoid explaining how in comments unless the approach itself is complex.

**Review by weihanglo — COMMENTED** [review]
Besides nits around comments, looks good!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16439/94c368ad2b9db0f0da5bdd8421cea13786ce4412..8f34e75d69fdb9182d5bf5652ed5da5492534dfc)*

File: tests/testsuite/vendor.rs (hunk 1 above)
Comment (vishalmudhirajpokala) [reply tests/testsuite/vendor.rs]: to make sure I don't repeat the same mistake again and again I placed comments for myself I had to remove them which I forgot I will clean it My apologies

**Comment by vishalmudhirajpokala** [comment]
Fixed , Removed the "how" comments and that stray brace comment. Thanks for catching those! @weihanglo

**Review by weihanglo — APPROVED** [review]
Thanks for working with us!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16439/94c368ad2b9db0f0da5bdd8421cea13786ce4412..4c6f5a61ab4b5ee93fb792a63e0815eb49b92bf6)*

**Comment by vishalmudhirajpokala** [comment]
Thanks @weihanglo  for the thorough review and guidance! Learned a lot through this process.
