### PR TITLE
Provide better error messages for a bad `patch`.

### LINKED ISSUE #4678: Improve the error message for when a patched dependency doesn't resolve to anything
**If you were brought here from an error message:** It may be that the version of a dependency in your Cargo.lock file does not match the version of your patched dependency. You can often fix this by running `cargo update -p <your package name>`. We're working on improving this error message to provide better, more detailed suggestions.

If you ran into this error message because of a different reason with a different solution, please let us know in the comments so we can address it. :)

---

This issue is meant to be a more long term fix than the error message updated in https://github.com/rust-lang/cargo/pull/4607.

From @alexcrichton:
> Ideally what we'd do is upon failure do a query again for a more relaxed version constraint, seeing if you just got the wrong version. If that fails we could say that the package doesn't even exist in the source.

### More details from @sunjay in the original PR (#4607)

The specific problem that I ran into occurred when I was trying to upgrade the `rustfmt` submodule in the rust codebase. The `rustfmt-nightly` dependency changed version numbers and this conflicted with what was in the `Cargo.lock` file. After some detective work I was able to find the [documentation on `[patch]`](http://doc.crates.io/manifest.html#the-patch-section) which I had never read before and the following relevant paragraphs from [some other documentation](http://doc.crates.io/specifying-dependencies.html#testing-a-bugfix):

> Next up we need to ensure that our lock file is updated to use this new version of uuid so our project uses the locally checked out copy instead of one from crates.io. The way [patch] works is that it'll load the dependency at ../path/to/uuid and then whenever crates.io is queried for versions of uuid it'll also return the local version.
> 
> This means that the version number of the local checkout is significant and will affect whether the patch is used. Our manifest declared uuid = "1.0" which means we'll only resolve to >= 1.0.0, < 2.0.0, and Cargo's greedy resolution algorithm also means that we'll resolve to the maximum version within that range. Typically this doesn't matter as the version of the git repository will already be greater or match the maximum version published on crates.io, but it's important to keep this in mind!

If it was not for the person who wrote those docs, I would not have known what to do here!

### PR DESCRIPTION
**Pull request by ehuss**
This attempts to provide more user-friendly error messages for some situations with a bad `patch`.  This is a follow-up to #8243.

I think this more or less covers all the issues from #4678.  I imagine there are other corner cases, but those will need to wait for another day. The main one I can think of is when the patch location is missing required features.  Today you get a "blah was not used in the crate graph." warning, with some suggestions added in #6470, but it doesn't actually check if there is a feature mismatch.

Closes #4678

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for working on this!

I think this is good to give some more useful information here regardless, but I don't think this is the final state we want to end up at. Ideally Cargo would automatically update/manage the lock file, even in the face of stale lock files and updated patches, avoiding the need to print an error asking the user to update.

One of the things I run into is when I've got a `[patch]` pointing to the local repository (for unrelated reasons). If the crates are all bumped then nothing works afterwards. For example the [wasm-bindgen repository](https://github.com/rustwasm/wasm-bindgen) you can run `rustc publish.rs && ./publish bump`, after which `cargo build `gives you weird #4678 error messages. Cargo still gives an error (a better one) with this PR, but ideally the lock file would simply automatically get updated.

I think though it may be a small enough change to, if there's one candidate, treat it as if there's no locked version if the previously locked version doesn't match?

**Comment by ehuss** [comment]
Yea, I agree it would be better to be automatic. I'm uncertain how to do that.

The issue is that the old version is "locked" in the `PackageRegistry`, so adding a patch to a new version won't work (it will still ultimately want to use the old version).  If the `patch` function just returns the new patch, it ends up in the "unused" section, and Cargo remains locked to the old version.

Do you have any advice or ideas how to handle that?  "Unlocking" the original entry doesn't sound like the right way to go, so maybe making it part of the "avoid" list early on might work? [`register_previous_locks`](https://github.com/rust-lang/cargo/blob/500b2bd01c958f5a33b6aa3f080bea015877b83c/src/cargo/ops/resolve.rs#L412-L581) is pretty gnarly, and I haven't yet understood everything it does. It may need to register patches before the call to `register_previous_locks`, and I'm uncertain if that's possible.  If you don't have any ideas, I'll try to spend some time untangling it.

**Comment by alexcrichton** [comment]
Hm I'll try to dig in for a bit and see what I can come up with.

**Comment by alexcrichton** [comment]
Ok so I think the general problem is that [the `keep` filter used here](https://github.com/rust-lang/cargo/blob/500b2bd01c958f5a33b6aa3f080bea015877b83c/src/cargo/ops/resolve.rs#L265) is not aggressive enough and fails to account for [this comment](https://github.com/rust-lang/cargo/blob/500b2bd01c958f5a33b6aa3f080bea015877b83c/src/cargo/ops/resolve.rs#L472-L502). We can't `keep` a `[patch]` to a path dependency if the path dependency has changed on the filesystem. I think we can fix the issue I've run into historically with using the [updated `keep` function](https://github.com/rust-lang/cargo/blob/500b2bd01c958f5a33b6aa3f080bea015877b83c/src/cargo/ops/resolve.rs#L560).

I've got an [ugly patch](https://gist.github.com/alexcrichton/76b358ad212520da70a99d6d13c412c5) which I believe handles the case I run into with wasm-bindgen at least.

I think this should work in general to hook into the `register_previous_locks` function a bit more. That could perhaps return the "keep" set or maybe even a new closure to keep things with. I haven't looked too much into this though. I'd always left #4678 as a "I should investigate this one day" issue where I wanted to dig into cc'd issues, reproduce, and verify the fix. Ideally that #4678 never shows up in error messages at all and we shouldn't need this PR beyond the better error messages it returns in the default case.

WDYT about trying to hook into `register_previous_locks` a bit more, updating the error message to indicate a new Cargo issue should be opened if it seems suspicious, and landing these improvements as well?

**Comment by ehuss** [comment]
OK, I took a stab at making patches update automatically.  In the process, I changed it so that if there are multiple possible patches, it picks the one with the greatest version. That might be dangerous, but seems to be decent behavior when patching with an alt registry.

There are a million edge cases, and I'm a bit tired of chasing them.  I imagine there are still a lot of rough spots. At this point, my hope is that user reports will help guide anything that needs to be fixed. However, if you can think of some other tests to try, I'll give them a shot.  One area that I'm uncomfortable with is transitive dependency updates.  Somehow they seem to work, but the fact that I didn't make changes to `register_previous_locks` makes me uneasy.

From a high level, the main change is to update the filter ("avoid" set) to include patches when the patch is locked, but the locked value is no longer found.  This should make it so that `cargo build` will automatically update `Cargo.lock` to the new value. There are two things that are added to the avoid set: the patch itself, and the thing the patch is patching.

File: src/cargo/core/registry.rs [hunk 1]
```diff
@@ -718,3 +743,114 @@ fn lock(
...
+) -> CargoResult<(Summary, Option<PackageId>)> {
+    if summaries.len() == 1 {
+        return Ok((summaries.pop().unwrap(), None));
+    }
+    let best_summary = |summaries: &mut Vec<Summary>| -> Summary {
+        // TODO: This could maybe honor -Zminimal-versions?
+        summaries.sort_by(|a, b| a.version().cmp(b.version()));
+        summaries.pop().unwrap()
+    };
+    if summaries.len() > 1 {
```
Comment (alexcrichton) [inline src/cargo/core/registry.rs:762]: This makes me a bit hesitant here trying to handle multiple candidates being returned. When `[patch]` was originally implemented we didn't have custom registries yet, so the only real usage of `[patch]` was pointing to `git` and `path`, neither of which can possibly have multiple versions of a package. With custom registries, though, that's now possible!

My main worry is that the candidates here don't participate in the normal version resolution of everything else. The biggest version may not always be the right one to pick (with other constraints like `links` and such).

Could this continue to restrict to only one package? I think it's fine to allow more candidates, but I think what should be done is to add all the candidates to "these can be searched through with version resolution". Version resolution would then do its normal thing to pick which is the best.

File: src/cargo/core/registry.rs [hunk 2]
```diff
@@ -718,3 +743,114 @@ fn lock(
...
+                Vec::new()
+            }
+        };
+        if orig_matches.is_empty() {
+            // This should be relatively unusual. For example, a patch of
+            // {version="0.1.2", ...} and the patch location no longer contains a
+            // version that matches "0.1.2". It is unusual to explicitly write a
+            // version in the patch.
+            anyhow::bail!(
+                "The patch is locked to {} in Cargo.lock, but the version in the \
```
Comment (alexcrichton) [inline src/cargo/core/registry.rs:794]: I think technically the mention of Cargo.lock here may be superfluous? While true it may not necessarily help that previously you had a successful build and have since modified the `version` to be too restrictive.

Comment (alexcrichton) [reply src/cargo/core/registry.rs:794]: I also think it'd be nice, if we're specifically calling out versions, to list the versions in play here. 

Could this error case fall-through to the error handling code below to get a similar error message? It'd be nice if the existence of a lock file only guided which packages remained unlocked afterwards.

File: src/cargo/core/registry.rs [hunk 3]
```diff
@@ -718,3 +743,114 @@ fn lock(
...
+                patch location does not match any packages in the patch location.\n\
+                Make sure the patch points to the correct version.",
+                locked_patch.version_req(),
+            );
+        }
+        let summary = best_summary(&mut orig_matches);
```
Comment (alexcrichton) [inline src/cargo/core/registry.rs:800]: It might be best to restructure this so it's maybe recursive or otherwise shares logic with the above. I'm a bit wary of having two instances of "pick the summary out of this list of summaries" which differ slightly

File: src/cargo/core/registry.rs [hunk 4]
```diff
@@ -718,3 +743,114 @@ fn lock(
...
+                    }
+                }
+            }
+            Err(e) => {
+                log::warn!(
+                    "failed to do name-only summary query for {:?}: {:?}",
+                    name_only_dep,
+                    e
+                );
+                "".to_string()
```
Comment (alexcrichton) [inline src/cargo/core/registry.rs:835]: This might be a bit simpler to explicitly ignore it with:

```rust
let found = source.query_vec(...).unwrap_or_else(|| {
    warn!(...); 
    Vec::new()
});
```

File: src/cargo/core/registry.rs [hunk 5]
```diff
@@ -718,3 +743,114 @@ fn lock(
...
+            }
+        };
+        if found.is_empty() {
+            anyhow::bail!(
+                "The patch location does not appear to contain any packages \
```
Comment (alexcrichton) [inline src/cargo/core/registry.rs:840]: Could the patch location be mentioned here and below? (e.g. rendering in `source_id()` and such)

File: src/cargo/core/registry.rs (hunk 1 above)
Comment (ehuss) [reply src/cargo/core/registry.rs:762]: I'm not sure if I'm understanding correctly.  If you're saying that this function should return multiple summaries, the problem is that any of the entries that aren't selected during version resolution end up in the unused patch list which triggers a warning.

I guess it could group related summaries together, so that the "unused patch" logic could only mark them unused if none in the group were used.  However, that would require changes in lots of places (which I'd rather not do right now).

Unless you meant something else, should I just switch it back to an error (maybe with a suggestion to use an `=` version requirement)?

Comment (alexcrichton) [reply src/cargo/core/registry.rs:762]: Oh sorry, let me clarify. Primarily this is a change in behavior from today which I'm worried about, so I would prefer to switch it back to make multiple candidates an error.

Other than that I was thinking that we probably *could* support this, but not by picking a version here and instead letting version resolution later pick a version. The theoretical idea behind `[patch]` was "take this crate and assume it comes from that source". That same idea works for "take this set of crates and assume they all come from that source", but the code here just isn't structured to do that. Ideally what we should do here is that when there's an unlocked (the only way to return multiple versions) dependency we make all matching candidates available for version resolution from the resolver, and the resolver picks one we'd then lock. If it ends up being entirely unused then we could pick the biggest one to lock and it wouldn't be an issue.

Does that make sense?

**Comment by ehuss** [comment]
I think I covered most of your feedback.

**Comment by alexcrichton** [comment]
@bors: r+

👍
