### PR TITLE
Don't require dev-dependencies when not needed in certain cases

### LINKED ISSUE #4988: cargo shouldn't check for dev-dependencies when running `cargo build` or `cargo install`
In the [docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html), dev-dependencies are advertised as "not used when compiling a package for building, but are used for compiling tests, examples, and benchmarks."

However, cargo fails if dev-dependencies are not available in a local registry. For example:

~~~~
$ basename $PWD
aho-corasick
$ git describe
0.6.4
$ ls -1 ../registry/
libc-0.2.36/
memchr-2.0.1/
$ # ^^^ this is all the dependencies, but none of the dev-dependencies like csv
$ cat config 
[source.crates-io]
replace-with = "dh-cargo-registry"

[source.dh-cargo-registry]
directory = "./registry"
$ CARGO_HOME=$PWD cargo build
warning: path `$PWD/src/main.rs` was erroneously implicitly accepted for binary `aho-corasick-dot`,
please set bin.path in Cargo.toml
error: no matching package named `csv` found (required by `aho-corasick`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: = 0.15.0
exit code 101
~~~~

This makes it awkward to package crates for distros, since we need to set up a local registry - we would have to add dev-dependencies in here as well, even though they're not actually used by `build` or `install`.

### PR DESCRIPTION
**Pull request by infinity0**
Specifically, when running `cargo install` and add a flag for this behaviour in `cargo build`.

This closes #4988.

### CODE REVIEW

File: src/bin/build.rs [hunk 1]
```diff
@@ -63,6 +64,7 @@ Options:
     --features FEATURES          Space-separated list of features to also build
     --all-features               Build all available features
     --no-default-features        Do not build the `default` feature
+    --avoid-dev-deps             Avoid installing dev-dependencies if possible
```
Comment (alexcrichton) [inline src/bin/build.rs]: Could this start out as a `-Z` flag to be unstable by default?

File: src/cargo/ops/cargo_compile.rs [hunk 2]
```diff
@@ -413,9 +419,21 @@ impl<'a> CompileFilter<'a> {
...
+    }
+
     pub fn matches(&self, target: &Target) -> bool {
         match *self {
-            CompileFilter::Default { .. } => true,
+            CompileFilter::Default { .. } => match *target.kind() {
+                TargetKind::Bin => true,
+                TargetKind::Lib(..) => true,
+                _ => false,
+            },
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_compile.rs]: How come this needed changing?

File: src/cargo/ops/cargo_install.rs [hunk 3]
```diff
@@ -175,7 +175,11 @@ fn install_one(root: &Filesystem,
 
     let ws = match overidden_target_dir {
         Some(dir) => Workspace::ephemeral(pkg, config, Some(dir), false)?,
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_install.rs]: Shouldn't the optional deps flag be set for this as well?

File: src/cargo/ops/cargo_compile.rs [hunk 4]
```diff
@@ -226,12 +226,18 @@ pub fn compile_ws<'a>(ws: &Workspace<'a>,
...
     let specs = spec.into_package_id_specs(ws)?;
-    let resolve = ops::resolve_ws_precisely(ws,
-                                            source,
-                                            features,
-                                            all_features,
-                                            no_default_features,
-                                            &specs)?;
+    let features = Method::split_features(features);
+    let method = Method::Required {
+        dev_deps: ws.require_optional_deps() || filter.need_dev_deps(),
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_compile.rs]: Perhaps the name `optional_deps` could change since it's affecting dev-dependencies?

Additionally, I think that we'd want this flag to affect target-specific dependencies, right? If this is a sort of "one shot" compilation there should also be no need to resolve and require windows-specific dependencies when on Linux, right?

File: src/cargo/ops/cargo_install.rs (hunk 3 above)
Comment (infinity0) [reply src/cargo/ops/cargo_install.rs]: ephemeral() already sets that internally

File: src/cargo/ops/cargo_compile.rs (hunk 2 above)
Comment (infinity0) [reply src/cargo/ops/cargo_compile.rs]: It's not necessary and could be dropped from this PR. But without it, the current situation means I have to give extra flags to `cargo build`, it contradicts the documentation, and it also means the `all-targets` flag is redundant.

File: src/cargo/ops/cargo_compile.rs (hunk 4 above)
Comment (infinity0) [reply src/cargo/ops/cargo_compile.rs]: Would you mind if we leave that as a TODO for the future? What you say makes sense but it is not actually needed in Debian right now, because we union over all targets when translating dependencies - so e.g. winapi etc are all pulled in regardless of what target you're building for. This means we have to have less special-cases in the packaging, and also supports cross-compilation later.

If I understood correctly, on Fedora they are patching out windows dependencies so they don't appear in Cargo.toml, so this functionality wouldn't be needed either. (Perhaps @ignatenkobrain can confirm).

**Comment by infinity0** [comment]
Thanks for the comments, I'll soon find some time to write tests and switch to `-Z` for the new flag.

File: src/cargo/ops/cargo_compile.rs (hunk 4 above)
Comment (alexcrichton) [reply src/cargo/ops/cargo_compile.rs]: Ok sure yeah, I think a TODO should suffice!

**Comment by infinity0** [comment]
Hey, I've added some tests and changed `avoid-dev-deps` to be a `-Z` unstable flag.

I wasn't quite sure what to rename `require_optional_deps` to, and it's a public struct so switching would carry some extra cost. I did add a comment to it, describing the new behaviour. I could change it if you want though, like `require_extra_deps` or `require_unneeded_deps`, let me know which you prefer.

File: src/cargo/ops/cargo_compile.rs (hunk 4 above)
Comment (infinity0) [reply src/cargo/ops/cargo_compile.rs]: I'm unsure if it's appropriate to mention "targets" in the sense of "platform" here on this line. The term "target" in the context of CompileFilter and `core::Target` and `cargo build` options, seems rather to mean "lib/bin/examples/tests" etc and not platform.

OTOH the functionality you mention does seem to be missing - if I add `[target."XXXX".dependencies] YYY = "999"` to Cargo.toml then `cargo install` still fails with this PR, despite the fact that "XXXX" does not match the current platform. I'm just unsure of the appropriate place to add this TODO, please advise. Perhaps on `struct Method`?

Comment (alexcrichton) [reply src/cargo/ops/cargo_compile.rs]: Hm ok, perhaps an issue can be filed? I think the `-Z avoid-dev-deps` flag added here may in the long run want to be something like `--minimal-cargo-lock` which prunes all non-relevant dependencies like platform-specific dependencies that don't apply, dev-deps if you're not building tests, etc. In that sense I think the feature/TODO here is slightly broader than a comment in the code. Would you be ok filing that?

File: src/cargo/ops/cargo_compile.rs (hunk 2 above)
Comment (alexcrichton) [reply src/cargo/ops/cargo_compile.rs]: Hm sorry I missed this earlier, but I'm not sure I quite understand this. Could this perhaps be left out for a future PR?

Comment (alexcrichton) [reply src/cargo/ops/cargo_compile.rs]: (or maybe a test could be added?)

**Comment by alexcrichton** [comment]
Thanks for the update, tests look good to me! It's also ok to not worry much about naming, despite being public we bump the major version for Cargo regularly so it's not too critical to think too hard about APIs

File: src/cargo/ops/cargo_compile.rs (hunk 2 above)
Comment (infinity0) [reply src/cargo/ops/cargo_compile.rs]: This actually opened up a whole new can of worms, so I've reverted it from this PR and opened up a new issue #5134 which I'll file a PR for as soon as this PR is merged (I have a fix, but it builds on top of this PR).

File: src/cargo/ops/cargo_compile.rs (hunk 4 above)
Comment (infinity0) [reply src/cargo/ops/cargo_compile.rs]: Filed as #5133

**Comment by infinity0** [comment]
I've resolved the merge conflict and dealt with all the remaining issues I think, please take a look and merge if good.

**Comment by alexcrichton** [comment]
Ah looks like some tests may be failing?

**Comment by infinity0** [comment]
Turns out the tests were also dependent on the fix for #5134, I've pushed a commit to work around it. Should be all good now.
