### PR TITLE
artifact deps shoud works when target field specified coexists with `optional = true`

### LINKED ISSUE #10526: Binary dependency is never built if specified with both `optional` and `target` keys
### Problem

For convenience I have also uploaded the failing code here: https://github.com/bstrie/bindeperror2 

For the following code:

```
# Cargo.toml
[package]
name = "mycrate"
version = "0.0.0"
edition = "2021"

[dependencies]
mybindep = { path = "mybindep", artifact = "bin", optional = true, target = "x86_64-unknown-linux-gnu" }

[features]
default = ["mybindep"]
```

```rust
// src/main.rs
fn main() {
    env!("CARGO_BIN_FILE_MYBINDEP");
}
```

```
# mybindep/Cargo.toml
[package]
name = "mybindep"
version = "0.0.0"
edition = "2021"
```

```rust
// mybindep/src/main.rs
fn main() {}
```

I expected this code to build. However, `cargo build` produces the following:

```
 > cargo build
   Compiling mycrate v0.0.0 (/home/ben/code/scrap/bindeperror2)
error: environment variable `CARGO_BIN_FILE_MYBINDEP` not defined
 --> src/main.rs:2:5
  |
2 |     env!("CARGO_BIN_FILE_MYBINDEP");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `mycrate` due to previous error
```

As we can see from the output, it is not merely that the environment variable is missing; only mycrate is ever built, and mybindep is skipped.

Note that mybindep is an optional dependency, but is specified as a default feature.

In addition, neither `cargo build --features mybindep` nor `cargo build --all-features` will result in mybindep being built.

The following causes the code to compile:

```diff
- mybindep = { path = "mybindep", artifact = "bin", optional = true, target = "x86_64-unknown-linux-gnu" 
+ mybindep = { path = "mybindep", artifact = "bin", optional = true }
```

Furthermore, with this (along with removing the default feature) we can observe that `cargo build --features mybindep` and `cargo build --all-features` now functions as expected. Leaving the `target` key and removing the `optional` key also causes the code to build. It is the presence of both these keys simultaneously that results in the issue.

cc @Byron 

### Version

```text
cargo 1.61.0-nightly (109bfbd 2022-03-17)
release: 1.61.0-nightly
commit-hash: 109bfbd055325ef87a6e7f63d67da7e838f8300b
commit-date: 2022-03-17
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Pop!_OS 21.10 (impish) [64-bit]
```

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

fixes #10526

Previously, `is_dep_activated` depends on `activated_dependencies`,
which is a map of `PackageFeaturesKey` to its own activated `DepFeature`s.
`PackageFeaturesKey` in feature resolver is always comprised of

* A `PackageId` of a given dependency, and
* A enum value that helps decoupling activated features for that dependency.
  Currently depending on the type of given dependency.

Looking into issue 10526, it has an `activated_dependencies` of

```
{
    (mycrate, NormalOrDevOrArtifactTarget(None)) -> [dep:mybindep]
}
```

However, this [line][1] accidentally use a parent's `pkgid`
and a dependency's `FeaturesFor` to compose a key:

```
(mycrate, NormalOrDevOrArtifactTarget("x86_64-unknown-linux-gnu"))
```

That is never a valid key to query features for artifacts dependency.
A valid key should be comprised of components both from the parent:

```
(mycrate, NormalOrDevOrArtifactTarget(None))
```

Or both from the dependency itself:

```
(mybindep, NormalOrDevOrArtifactTarget("x86_64-unknown-linux-gnu"))
```

As aforementioned `activated_dependencies` only stores parent packages
and their activated features. Those informations are included in
`activated_features` as well, so this commit goes with the route that
removes `activated_dependencies` and uses only dependency's infomation
to query if itself is activated.

[1]: https://github.com/rust-lang/cargo/blob/0b84a35c2c7d70df4875a03eb19084b0e7a543ef/src/cargo/core/compiler/unit_dependencies.rs#L1097-L1098

### How should we test and review this PR?

This first commit logs the current "incorrect" behaviour.
The second commit contain the fix.
The last commit update some docs.

### Additional information

There could be some other refactors to make the interaction between `-Zbindeps` and feature resolver a bit better. I'll try to send more follow-ups if life don't bite me again.

### CODE REVIEW

**Comment by ehuss** [comment]
If my understanding of this is correct, the removal of `activated_dependencies` is depending on [this](https://github.com/rust-lang/cargo/blob/9210810d1fd7b51ae0439a0a363cc50e36963455/src/cargo/core/resolver/features.rs#L521-L526) in order to know whether or not a dependency is activated. That is, the presence of the set determines whether or not something is activated. Is that correct?

If so, I'm slightly uncomfortable with relying on that. The idea was that in the future there would not be an empty set used for things that don't have any features set. Then, the call to `expect` in `activated_features` could be removed, and instead be something like `unwrap_or_default()`.

However, there isn't really a strong need for that (I just kind wanted to get rid of the `expect()` call).  I *think* it should be fine, but can you update the comment linked above? Essentially just remove it and write something to explain the importance of inserting an empty set (that the presence of set also means the dependency is activated). How does that sound to you?

**Comment by weihanglo** [comment]
Thank you for the review! Of course I will update that comment! And maybe explain more on the purpose of `activated_features` and `activated_dependencies` as well.

Just curious, besides removing `expect`, is there any concern/extension/ambiguity I am not aware of when we start depending on `activated_features` for checking activation of a dependency? Maybe I miss some contexts, but it seems that we can switch to `unwrap_or_default` nowadays even if we stop inserting empty set from now on.

**Comment by weihanglo** [comment]
Rebased and added comments per discussion.

File: src/cargo/core/resolver/features.rs [hunk 1]
```diff
@@ -520,7 +519,8 @@ impl<'a, 'cfg> FeatureResolver<'a, 'cfg> {
         log::trace!("activate_pkg {} {}", pkg_id.name(), fk);
         // Add an empty entry to ensure everything is covered. This is intended for
         // finding bugs where the resolver missed something it should have visited.
-        // Remove this in the future if `activated_features` uses an empty default.
+        // The presence of an (empty) set also means that the dependency is activated,
+        // The presence of an (empty) set also means that the dependency is activated.
```
Comment (ehuss) [inline src/cargo/core/resolver/features.rs:523]: Looks like these lines are duplicated.

**Comment by ehuss** [comment]
> Just curious, besides removing expect, is there any concern/extension/ambiguity I am not aware of when we start depending on activated_features for checking activation of a dependency?

I'm not sure. I recall having separate maps seemed important at the time, but I don't remember.

> Maybe I miss some contexts, but it seems that we can switch to unwrap_or_default nowadays even if we stop inserting empty set from now on.

I'm not sure I follow.  With this change, it must insert an empty set, so skipping that step is no longer an option?

File: src/cargo/core/resolver/features.rs (hunk 1 above)
Comment (weihanglo) [reply src/cargo/core/resolver/features.rs]: Just tweak the comment a bit further.

File: src/cargo/core/resolver/features.rs [hunk 2]
```diff
@@ -321,21 +322,14 @@ impl ResolvedFeatures {
             .expect("activated_features for invalid package")
```
Comment (weihanglo) [inline src/cargo/core/resolver/features.rs:322]: I feel like we are not on the same page, @ehuss 😆 

> > Maybe I miss some contexts, but it seems that we can switch to unwrap_or_default nowadays even if we stop inserting empty set from now on.
> 
> I'm not sure I follow. With this change, it must insert an empty set, so skipping that step is no longer an option?


`activated_features_int` returns a `Result` so `unwrap_or_default` can easily recover from it with a default. There is no need of the presence of an empty set, no?

https://github.com/rust-lang/cargo/blob/1945b44853c87bc8a600ced428e1292a5350e814/src/cargo/core/resolver/features.rs#L352-L363

Comment (ehuss) [reply src/cargo/core/resolver/features.rs:322]: Ah, I was conflating "switch to unwrap_or_default" and "remove inserting the empty set", as I was thinking of them as a single action that would be done together. I suppose it could switch to unwrap_or_default, but I like the validation that `expect` has been giving.

**Comment by ehuss** [comment]
Thanks! 

@bors r+
