### PR TITLE
fix: unsupported protocol error on old macos version

### LINKED ISSUE #11726: `Unsupported protocol` with sparse registry
### Problem

When using sparse registry, cargo reports `Unsupported protocol` error.

HTTP multiplexing defaults to true at https://github.com/rust-lang/cargo/blob/39c13e67a5962466cc7253d41bc1099bbcb224c3/src/cargo/sources/registry/http_remote.rs#L223-L225 and this error is produced at https://github.com/rust-lang/cargo/blob/39c13e67a5962466cc7253d41bc1099bbcb224c3/src/cargo/sources/registry/http_remote.rs#L555-L556
cargo is dynamic linked to `libcurl`, however `libcurl` from Apple in macOS 10.12.6 has no `HTTP2`:flushed:

### Steps

```
$ env CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse rustup run nightly cargo install oris
    Updating crates.io index
error: failed to query replaced source registry `crates-io`

Caused by:
  [1] Unsupported protocol
```

### Possible Solution(s)

- fallback to `HTTP/1.1`
- replace the ambiguous error message
  - maybe add suggestion: set `CARGO_HTTP_MULTIPLEXING` to `false` if `libcurl` doesn't support `HTTP/2`
- static link to `libcurl`

### Notes

_No response_

### Version

```text
$ rustup run nightly cargo version --verbose
cargo 1.69.0-nightly (39c13e67a 2023-02-12)
release: 1.69.0-nightly
commit-hash: 39c13e67a5962466cc7253d41bc1099bbcb224c3
commit-date: 2023-02-12
host: x86_64-apple-darwin
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.54.0 (sys:0.4.59+curl-7.86.0 system ssl:SecureTransport)
os: Mac OS 10.12.6 [64-bit]

$ otool -L (rustup which --toolchain nightly cargo)
/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo:
    /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
    /System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60158.100.133)
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
    /usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)

$ /usr/bin/curl-config --version
libcurl 7.54.0

$ /usr/bin/curl-config --feature 
SSL
IPv6
UnixSockets
libz
AsynchDNS
GSS-API
SPNEGO
Kerberos
NTLM
NTLM_WB
```

### PR DESCRIPTION
**Pull request by bebecue**
fix #11726

### CODE REVIEW

File: src/cargo/sources/registry/http_remote.rs [hunk 1]
```diff
@@ -391,6 +391,25 @@ impl<'cfg> HttpRegistry<'cfg> {
     }
 }
 
+// copied from src/cargo/core/package.rs to keep change minimal
```
Comment (ehuss) [inline src/cargo/sources/registry/http_remote.rs:394]: I think we should avoid copying the macro.  I think it would be fine to just move it somewhere, like `cargo::util::network` or something like that.

**Review by ehuss — COMMENTED** [review]
Also, it looks like the `pipewait` call needs to check for old curl too.

File: src/cargo/sources/registry/http_remote.rs (hunk 1 above)
Comment (bebecue) [reply src/cargo/sources/registry/http_remote.rs]: fixed in https://github.com/rust-lang/cargo/pull/11733/commits/6dbfde37e13c1e899300351d18edd98894d7b627

**Comment by bebecue** [comment]
> Also, it looks like the `pipewait` call needs to check for old curl too.

added in https://github.com/rust-lang/cargo/pull/11733/commits/9e2933ee5493a871ebf8220f4cba2ee22324e011

**Review by weihanglo — APPROVED** [review]
Looks good. Thanks!

Would you like to submit backport as well? I could help that if that sounds a bit too boring to you.

**Comment by bebecue** [comment]
> Would you like to submit backport as well? I could help that if that sounds a bit too boring to you.

Just submitted as #11735
