### PR TITLE
Fix overriding mixing with default features

### LINKED ISSUE #3812: Cargo sometimes chooses incorrect features
I've been experiencing “random rebuilds”: sometimes when running `cargo build` twice in a row, the second time it rebuilds some crates even though nothing changed.

I've spent some time debugging this issue and it seems to be caused by a low but non-negligible probability of incorrect feature selection for one of the crates in my dependency graph. This will then lead to a different fingerprint being computed and a rebuild happening.

When I run `RUST_LOG=cargo::core::resolver=trace cargo build --lib --verbose|&egrep 'activating (tempdir|rand)'`, most of the time I get output like this:
```
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
TRACE:cargo::core::resolver: activating tempdir v0.3.5
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
TRACE:cargo::core::resolver: activating tempdir v0.3.5
```
or this:
```
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
TRACE:cargo::core::resolver: activating tempdir v0.3.5
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
TRACE:cargo::core::resolver: activating tempdir v0.3.5
```

But sometimes, I get this:
```
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
TRACE:cargo::core::resolver: activating tempdir v0.3.5
TRACE:cargo::core::resolver: activating tempdir v0.3.5
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
```
or this:
```
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
TRACE:cargo::core::resolver: activating tempdir v0.3.5
TRACE:cargo::core::resolver: activating tempdir v0.3.5
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
TRACE:cargo::core::resolver: activating rand v0.3.14 (https://github.com/jethrogb/rand?branch=rdrand#b052c179) (replacing rand v0.3.14)
```

When that happens, the incorrect features are selected for the rand crate. As far as I can tell, the resolver logic in cargo is run twice. If during the first time tempdir was activated *after* rand but during the second time tempdir is activated *before* rand, *then* the features that tempdir specifies for the rand crate are being used.

Note that tempdir is not actually ever built since it is a build-dependency of a crate that is a dependency of another crate, but not on my platform.

I suspect the non-determinism is coming from HashMaps or ReadDir. I have no clue where to go from here and could use some debugging help. I unfortunately can't share my Cargo.toml and have not been able to reproduce the issue in a smaller test case. My dependency graph includes about 400 crates and I'm using crates.io, git, and path dependencies as well as a `[replace]` section.

You may ignore the following, putting it here for my records:
```
Useful breakpoints:
1       breakpoint     keep y   0x0000561ecd6d04a7 in cargo::ops::cargo_rustc::fingerprint::calculate at /tmp/cargo/src/cargo/ops/cargo_rustc/fingerprint.rs:365
	stop only if unit->pkg->manifest.summary.package_id.inner.ptr.pointer.__0->data.name.vec.buf.ptr.pointer.__0[0] == 'r' && unit->pkg->manifest.summary.package_id.inner.ptr.pointer.__0->data.name.vec.buf.ptr.pointer.__0[1] == 'a' && unit->pkg->manifest.summary.package_id.inner.ptr.pointer.__0->data.name.vec.buf.ptr.pointer.__0[2] == 'n' && unit->pkg->manifest.summary.package_id.inner.ptr.pointer.__0->data.name.vec.buf.ptr.pointer.__0[3] == 'd' && fingerprint.ptr.pointer.__0->data.features.vec.buf.ptr.pointer.__0[13] != 'r'
2       breakpoint     keep y   0x0000561ecd6ea51a in cargo::ops::cargo_rustc::compile at /tmp/cargo/src/cargo/ops/cargo_rustc/mod.rs:226
3       breakpoint     keep y   0x0000561ecd642034 in cargo::core::resolver::{{impl}}::resolve_features at /tmp/cargo/src/cargo/core/resolver/mod.rs:972
	stop only if candidate->package_id.inner.ptr.pointer.__0->data.name.vec.buf.ptr.pointer.__0[0] == 'r' && candidate->package_id.inner.ptr.pointer.__0->data.name.vec.buf.ptr.pointer.__0[1] == 'a' && candidate->package_id.inner.ptr.pointer.__0->data.name.vec.buf.ptr.pointer.__0[2] == 'n' && candidate->package_id.inner.ptr.pointer.__0->data.name.vec.buf.ptr.pointer.__0[3] == 'd'
4       breakpoint     keep y   0x0000561ecd635868 in cargo::core::resolver::activate at /tmp/cargo/src/cargo/core/resolver/mod.rs:308
	stop only if candidate->summary.ptr.pointer.__0->value.package_id.inner.ptr.pointer.__0->data.name.vec.buf.ptr.pointer.__0[0] == 'r' && candidate->summary.ptr.pointer.__0->value.package_id.inner.ptr.pointer.__0->data.name.vec.buf.ptr.pointer.__0[1] == 'a' && candidate->summary.ptr.pointer.__0->value.package_id.inner.ptr.pointer.__0->data.name.vec.buf.ptr.pointer.__0[2] == 'n' && candidate->summary.ptr.pointer.__0->value.package_id.inner.ptr.pointer.__0->data.name.vec.buf.ptr.pointer.__0[3] == 'd'

Useful displays:
1:   y  unit->pkg->manifest.summary.package_id.inner.ptr.pointer.__0->data.name
2:   y  fingerprint.ptr.pointer.__0->data.features
3:   y  used_features.map.table.size
4:   y  *method
5:   y  parent->RUST$ENCODED$ENUM$0$None.__0->ptr.pointer.__0->value.package_id.inner.ptr.pointer.__0->data.name
```

### PR DESCRIPTION
**Pull request by alexcrichton**
Previously Cargo had a bug where if a crate *without* a default feature was
overridden with one that did indeed have a default feature then the default may
not end up getting activated by accident. The fix was to avoid returning too
quickly hen activating dependencies until after we've inspected and learned
about replacements.

Closes #3812

### CODE REVIEW

**Comment by jethrogb** [comment]
Whew this must have been a pain to figure out! Thanks a lot.

If you run the test in this PR on the old code, will it sometimes pass non-deterministically?

I think this works... sort-of. Since the failure mode of this bug was that most of the time, the default feature would *not* be selected, this might be considered a breaking change since the default feature will now always be selected.

**Comment by alexcrichton** [comment]
Yeah the test would fail nondeterministically, that's how I figured this fixed it :). A thousand or so runs with no failures makes me think this is confirmed as the right fix.

Yeah features across build deps and across actual deps are kinda hairy unfortunately :(

File: src/cargo/core/resolver/mod.rs [hunk 1]
```diff
@@ -316,22 +316,23 @@ fn activate(cx: &mut Context,
...
-        return Ok(None);
-    }
+    let activated = cx.flag_activated(&candidate.summary, method);
 
     let candidate = match candidate.replace {
         Some(replace) => {
             cx.resolve_replacements.insert(candidate.summary.package_id().clone(),
                                            replace.package_id().clone());
-            if cx.flag_activated(&replace, method) {
+            if cx.flag_activated(&replace, method) && activated {
```
Comment (matklad) [inline src/cargo/core/resolver/mod.rs]: I am not sure about this `&& activated`. Can it cause the same replacement to be activated twice? Is it bad?

If I remove `&& activated`, the tests pass just as well. So we either don't need it, or don't have some test?

Comment (matklad) [inline src/cargo/core/resolver/mod.rs]: That is, we can move perhaps all ifs after replacement:

```Rust
let candidate = match candidate.replace {
    Some(replace) => {
        cx.resolve_replacements.insert(candidate.summary.package_id().clone(),
                                       replace.package_id().clone());
        trace!("replacing {} with {}", candidate.summary.package_id(),
                replace.package_id());
        replace
    }
    None => candidate.summary,
};

if cx.flag_activated(&candidate, method) {
    return Ok(None)
}
trace!("activating {}", candidate.package_id());
```

Comment (matklad) [inline src/cargo/core/resolver/mod.rs]: Ah, looks like moving if forward won't work because during replacement we need to activate both the original and the replacement.

**Comment by matklad** [comment]
@bors: r+

Okey, I am still not sure if `&& activated` bit is right, but this PR definitely should fix the issue.

**Comment by alexcrichton** [comment]
Ah yeah so we definitely need to activate both the original and the replacement, but to answer your original question:

In general Cargo's resolution algorithm is just a brute force search with some heuristics thrown in. We then pick the first successful resolution reached, or we try every possible resolution and determine they're all errors and return an error. (I don't actually know which error...)

In that sense what this `flag_activated` function is doing is activating a specific version for a crate. This involves registering it in the dependency graph. The check here (`return Ok(None)`) is purely an optimization saying that if we've already activated this component there's no need to keep activating and traversing the graph here (reducing duplicate work). In that sense I think the `&& activated` is ok because it's not harmful to re-activate something it'll just end up in extra work being done which would otherwise be avoided.

Note that the crux of this bug was that we were returning too soon! When activating a crate you have to follow through with dependency traversal if any new features were activated, but if you've already activated all relevant features then you don't have to go further. The bug here was that we *thought* that we had already activated a crate when in fact we had forgotten to activate the replacement's default feature.
