### PR TITLE
Fix overwriting alternate registry token

### LINKED ISSUE #7701: `cargo login` with 2nd alternate registry overwrites 1st alternate registry's token in ~/.cargo/credentials
**Problem**

When working on crates.io, I often run an instance locally and interact with it through cargo. We also have a staging instance where I test things out. So this is 2 alternate registries in addition to the main crates.io.

My `~/.cargo/config` looks like this:

```
[registries]
staging = { index = "https://github.com/rust-lang/staging.crates.io-index" }
local = { index = "file:///Users/carolnichols/rust/crates.io/tmp/index-bare" }
```

If I run `cargo login --registry staging [token]` then run `cargo login --registry local [other-token]`, `~/.cargo/credentials` only contains the credentials for the local registry.

**Steps**

1. Using rustc 1.39.0 (4560ea788 2019-11-04)/cargo 1.39.0 (1c6ec66d5 2019-09-30), create a `~/.cargo/config` containing 2 alternate registries as shown above.

2. Move your existing `~/.cargo/credentials` file elsewhere if you don't want to mess it up reproducing this.

2. Run `cargo login abcde` to set your token for the main crates.io registry.

3. Observe that `~/.cargo/credentials` contains these contents, as expected:

```
[registry]
token = "abcde"
```

4. Run `cargo login --registry staging fghij`.
5. Observe that `~/.cargo/credentials` contains these contents, as expected:

```
[registries.staging]
token = "fghij"

[registry]
token = "abcde"
```

6. Run `cargo login --registry local klmno`.
7. Observe that `~/.cargo/credentials` contains these contents, with `local` and the main registry present as expected, but with `staging` gone:

```
[registries.local]
token = "klmno"

[registry]
token = "abcde"
```

The contents I expected to have would contain tokens for all 3 registries, like:

```
[registries.local]
token = "klmno"

[registries.staging]
token = "fghij"

[registry]
token = "abcde"
```

**Possible Solution(s)**

Unclear, I was going to go poking around after filing this.

**Notes**

Output of `cargo version`: `cargo 1.39.0 (1c6ec66d5 2019-09-30)`, current stable on macOS. 

I was also able to reproduce with `rustc 1.41.0-nightly (27d6f55f4 2019-12-11)`/`cargo 1.41.0-nightly (626f0f40e 2019-12-03)`.

### PR DESCRIPTION
**Pull request by giraffate**
When executing `cargo login`, 2nd alternate registry token overwrites
1st alternate registry token.

Fixes #7701.

### CODE REVIEW

**Comment by giraffate** [comment]
Thank you for reviewing!

As you say, it seems better to avoid creating a second registry in the other tests, so I fix it. Could you review this again? 

I will squashed these commits at the end.

File: crates/cargo-test-support/src/registry.rs [hunk 1]
```diff
@@ -60,6 +60,17 @@ pub fn alt_api_url() -> Url {
...
+fn generate_path(name: &str) -> PathBuf {
+    paths::root().join(name)
+}
+fn generate_url(name: &str) -> Url {
+    Url::from_file_path(generate_path(name)).ok().unwrap()
+}
+fn generate_dl_url(name: &str) -> String {
+    let base = Url::from_file_path(generate_path(name)).ok().unwrap();
+    format!("{}/{{crate}}/{{version}}/{{crate}}-{{version}}.crate", base)
+}
```
Comment (ehuss) [inline crates/cargo-test-support/src/registry.rs]: Can all the other functions (the `alt_*` functions) be changed to call these new functions instead of duplicating the code?

File: crates/cargo-test-support/src/registry.rs [hunk 2]
```diff
@@ -166,9 +177,13 @@ pub fn init() {
 
         [registries.alternative]
         index = '{alt}'
+
+        [registries.alternative2]
+        index = '{alt2}'
```
Comment (ehuss) [inline crates/cargo-test-support/src/registry.rs]: I think it would be best to not set this here, and only set it in the `registry_credentials` test.  Can probably just append to the config file.

File: crates/cargo-test-support/src/registry.rs [hunk 3]
```diff
@@ -214,6 +229,23 @@ pub fn init() {
     fs::create_dir_all(alt_api_path().join("api/v1/crates")).unwrap();
 }
 
+pub fn init_alt2_registry() {
```
Comment (ehuss) [inline crates/cargo-test-support/src/registry.rs]: Can this be written so that the other two registries reuse the same code instead of duplicating it?

File: tests/testsuite/login.rs [hunk 4]
```diff
@@ -185,4 +187,18 @@ fn registry_credentials() {
 
     // Also ensure that we get the new token for the registry
     assert!(check_token(TOKEN, Some(reg)));
+
+    let reg2 = "alternative2";
+    cargo_process("login --registry")
+        .arg(reg2)
+        .arg(TOKEN2)
+        .arg("-Zunstable-options")
+        .masquerade_as_nightly_cargo()
```
Comment (ehuss) [inline tests/testsuite/login.rs]: These two lines can be removed, I think we just forgot to remove them when stabilized. And remove the same 2 lines in the call above.

File: crates/cargo-test-support/src/registry.rs (hunk 3 above)
Comment (giraffate) [reply crates/cargo-test-support/src/registry.rs]: I replaced this with a new function `init_registry` and the existing codes for creating registry call the new function. I am a little worried that there are many arguments for this new function, but I couldn't come up with another good way to write it.

File: crates/cargo-test-support/src/registry.rs (hunk 1 above)
Comment (giraffate) [reply crates/cargo-test-support/src/registry.rs]: Yes, I fixed it like that. I also corrected `registry_path` function etc., but is this OK?

**Comment by ehuss** [comment]
Looks good to me, thanks!

@bors r+
