### PR TITLE
Fix fingerprint for canceled build script.

### LINKED ISSUE #6770: Failed build script is not tracked in fingerprint.
There is a scenario where cargo fails to rebuild when the execution of a build script is interrupted (such as hitting ctrl-c).  There are a variety of ways this can happen, the test below illustrates one way.

The fundamental problem is that the fingerprint does not track enough information about the execution of a build script as a dependency.  #6720 added tracking the `invoked.timestamp` file, but that is not sufficient.  

I've been pondering various ways to fix this, but not loving the options. I would be interested if anyone has any more ideas. Bonus points if both this and #6733 can be fixed. Some options:

* #6733 mentions adding the info from  `build_script_local_fingerprints`, but there are some complications with updating that after the build is done (it would need to do everything that `prepare_build_cmd` does, too).  
* Add another file that is written in the fingerprint dir that tracks the *completion* of running the build script, perhaps with a sequence number bumped each time it is run.
* When the build script starts, write `invoked.timestamp.start` (and delete `invoked.timestamp`) and then when the build script succeeds, rename it to `invoked.timestamp`.  I think this should work, but I'm not sure.
* (Crazy) Switch to a database for fingerprint tracking to make it easier to track dependencies.

### Example
(This currently fails on the last line where the build succeeds when it should fail.)
```rust
#[test]
fn script_fails_stay_dirty() {
    let p = project()
        .file(
            "build.rs",
            r#"
                mod helper;
                fn main() {
                    println!("cargo:rerun-if-changed=build.rs");
                    helper::doit();
                }
            "#,
        )
        .file("helper.rs", "pub fn doit() {}")
        .file("src/lib.rs", "")
        .build();

    p.cargo("build").run();
    p.change_file("helper.rs", r#"pub fn doit() {panic!("Crash!");}"#);
    p.cargo("build")
        .with_stderr_contains("[..]Crash![..]")
        .with_status(101)
        .run();
    // There was a bug where this second call would be "fresh".
    p.cargo("build")
        .with_stderr_contains("[..]Crash![..]")
        .with_status(101)
        .run();
}
```

### PR DESCRIPTION
**Pull request by ehuss**
Fixes #6770. See that issue for a description.

The fix is to include the compilation of the build script itself in the fingerprint of the `RunCustomBuild` Unit.

This also includes some documentation for how fingerprints work.

Also includes a test for docker-style caching of dependencies where timestamps get truncated to the nearest second.

### CODE REVIEW

File: src/cargo/core/compiler/fingerprint.rs [hunk 1]
```diff
@@ -1,10 +1,174 @@
...
+//!   output files will be missing, and the Unit will be dirty (missing
+//!   outputs are considered "dirty").
+//! - The `Fingerprint` is another hash, saved to the filesystem in the
+//!   `.fingerprint` directory, that tracks information about the inputs to a
+//!   Unit. If any of the inputs changes from the last compilation, then the
+//!   Unit is considered dirty. A missing fingerprint (such as during the
+//!   first build) is also considered dirty.
+//! - Dirty propagation is done in the `JobQueue`. When a Unit is dirty, the
+//!   `JobQueue` automatically treats anything that depends on it as dirty.
+//!   Anything that relies on this is probably a bug. The fingerprint should
```
Comment (alexcrichton) [inline src/cargo/core/compiler/fingerprint.rs]: This is definitely something we slowly realized over time, and I think at this point we should probably remove this logic in `JobQueue` perhaps? (fine to leave to a separate PR). 

It may uncover a bug or two either in the test suite or in the wild, but it's all stuff we'd have to fix eventually anyway.

File: src/cargo/core/compiler/fingerprint.rs [hunk 2]
```diff
@@ -1,10 +1,174 @@
...
+//! separate directory. Each Unit directory contains:
+//!
+//! - A file with a 16 hex-digit hash. This is the Fingerprint hash, used for
+//!   quick loading and comparison.
+//! - A `.json` file that contains details about the Fingerprint. This is only
+//!   used to log details about *why* a fingerprint is considered dirty.
+//!   `RUST_LOG=cargo::core::compiler::fingerprint=trace cargo build` can be
+//!   used to display this log information.
+//! - A "dep-info" file which contains a list of source filenames for the
+//!   target. This is produced by `rustc`'s `--emit=dep-info` flag. Cargo uses
```
Comment (alexcrichton) [inline src/cargo/core/compiler/fingerprint.rs]: I think technically we actually rewrite the output of the compiler, right? IIRC we have a binary-encoding (ish) which puts the cwd at the top and then all the paths are rewritten as relative to that (or something like that)

File: src/cargo/core/compiler/fingerprint.rs [hunk 3]
```diff
@@ -617,6 +796,10 @@ pub fn prepare_build_cmd<'a, 'cfg>(
                 fingerprint.local = local_fingerprints_deps(&deps, &target_root, &pkg_root);
                 fingerprint.update_local(&target_root)?;
             }
+            // Note: If a build script switches from new style to old style,
```
Comment (alexcrichton) [inline src/cargo/core/compiler/fingerprint.rs]: s/Note/FIXME/ perhaps?

File: src/cargo/core/compiler/fingerprint.rs [hunk 4]
```diff
@@ -585,9 +729,44 @@ pub fn prepare_build_cmd<'a, 'cfg>(
...
+    // (if it is overridden).
+    //
+    // Note that this filters out `RunCustomBuild` units. These are `links`
+    // build scripts. Unfortunately, for many reasons, those would be very
+    // difficult to include, so for now this is slightly wrong. Reasons:
+    // Fingerprint::locals has to be rebuilt in the closure, LocalFingerprint
+    // isn't cloneable, Context is required to recompute them, build script
+    // fingerprints aren't shared in Context::fingerprints, etc.
+    // Ideally this would call local_fingerprint_run_custom_build_deps.
+    // See https://github.com/rust-lang/cargo/issues/6780
```
Comment (alexcrichton) [inline src/cargo/core/compiler/fingerprint.rs]: s/See/FIXME/ ?

File: src/cargo/core/compiler/fingerprint.rs (hunk 2 above)
Comment (ehuss) [reply src/cargo/core/compiler/fingerprint.rs]: Correct, I have tried to clarify it.

File: src/cargo/core/compiler/fingerprint.rs (hunk 1 above)
Comment (ehuss) [reply src/cargo/core/compiler/fingerprint.rs]: That might be a worthwhile experiment, at least to see where things break in the testsuite.

**Comment by ehuss** [comment]
> by passing `&Context` to all of the child work tasks?

That sounds like it would be difficult.  `Context` is mutable while the queue is draining (and when the closures are created).

At this point, I think I'm going to leave things as-is for now.  The issues I filed are somewhat difficult to hit, and any solution to fix them will require a lot of code changes.  If at some point in the future that someone wants to do a major overhaul of fingerprinting, that would be a good opportunity to make sure all these edge cases are covered.  I don't think these edge cases justify that much code churn right now.  

While working on this, it's been interesting to look at how other projects deal with it.  Ninja for example has some of the same bugs with mtime handling.  One thought is to add filesize (and maybe other metadata) to the fingerprint to reduce the chances of mtime errors.  It wouldn't guard against modifications that do not change the size, but might help.  I do see complaints about tools that rely heavily on hashing being too slow.

**Comment by alexcrichton** [comment]
> That sounds like it would be difficult. Context is mutable while the queue is draining (and when the closures are created).

Ah yep, definitely sounds too difficult for this PR

>  One thought is to add filesize (and maybe other metadata) to the fingerprint to reduce the chances of mtime errors. It wouldn't guard against modifications that do not change the size, but might help. I do see complaints about tools that rely heavily on hashing being too slow.

Seems like not a bad idea!
