### PR TITLE
Error message for transitive artifact dependencies with targets the package doesn't directly interact with

### LINKED ISSUE #11260: Panic when depending on a package with artifact dependencies
### Problem

We hit a `thread 'main' panicked at 'no entry found for key'` error in our project. We're testing the use of various build artifacts (wasm/staticlib) in our setup. We have a project-wide `config.toml` with `bindeps = true`.

<details>
<summary>error from cargo check</summary>

```
thread 'main' panicked at 'no entry found for key', src/tools/cargo/src/cargo/core/compiler/build_context/target_info.rs:901:40
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::panicking::panic_str
   4: core::option::expect_failed
   5: <cargo::core::compiler::build_context::target_info::RustcTargetData>::info
   6: <core::iter::adapters::map::Map<std::collections::hash::set::Iter<cargo::core::compiler::compile_kind::CompileKind>, <cargo::core::compiler::compilation::Compilation>::new::{closure#0}> as core::iter::traits::iterator::Iterator>::fold::<(), core::iter::traits::iterator::Iterator::for_each::call<(cargo::core::compiler::compile_kind::CompileKind, std::path::PathBuf), <hashbrown::map::HashMap<cargo::core::compiler::compile_kind::CompileKind, std::path::PathBuf, std::collections::hash::map::RandomState> as core::iter::traits::collect::Extend<(cargo::core::compiler::compile_kind::CompileKind, std::path::PathBuf)>>::extend<core::iter::adapters::map::Map<std::collections::hash::set::Iter<cargo::core::compiler::compile_kind::CompileKind>, <cargo::core::compiler::compilation::Compilation>::new::{closure#0}>>::{closure#0}>::{closure#0}>
   7: <std::collections::hash::map::HashMap<cargo::core::compiler::compile_kind::CompileKind, std::path::PathBuf> as core::iter::traits::collect::FromIterator<(cargo::core::compiler::compile_kind::CompileKind, std::path::PathBuf)>>::from_iter::<core::iter::adapters::map::Map<std::collections::hash::set::Iter<cargo::core::compiler::compile_kind::CompileKind>, <cargo::core::compiler::compilation::Compilation>::new::{closure#0}>>
   8: <cargo::core::compiler::compilation::Compilation>::new
   9: <cargo::core::compiler::context::Context>::new
  10: cargo::ops::cargo_compile::compile_ws
  11: cargo::ops::cargo_compile::compile
  12: cargo::commands::check::exec
  13: cargo::cli::main
  14: cargo::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

### Notes

possibly related to #10444

### Version

```text
cargo 1.66.0-nightly (b332991a5 2022-10-13)
release: 1.66.0-nightly
commit-hash: b332991a57c9d055f1864de1eed93e2178d49440
commit-date: 2022-10-13
host: aarch64-apple-darwin
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.79.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.6.0 [64-bit]
```

### PR DESCRIPTION
**Pull request by jofas**
Address #11260. Produces an error message like described by @weihanglo [here](https://github.com/rust-lang/cargo/issues/11260#issuecomment-1400455203): 

```
error: could not find specification for target "x86_64-windows-msvc"
  Dependency `bar v0.1.0` requires to build for target "x86_64-windows-msvc".
```

Note that this is not a complete fix for #11260.

### CODE REVIEW

File: tests/testsuite/artifact_dep.rs [hunk 1]
```diff
@@ -20,7 +20,7 @@ fn check_with_invalid_artifact_dependency() {
                 version = "0.0.0"
                 authors = []
                 resolver = "2"
-
```
Comment (jofas) [inline tests/testsuite/artifact_dep.rs:23]: my text editor automatically removes trailing whitespaces, hope that is okay... I actually think this would be a good idea to add to `rustfmt` :slightly_smiling_face:

File: src/cargo/core/compiler/compilation.rs [hunk 2]
```diff
@@ -384,6 +375,48 @@ fn fill_rustc_tool_env(mut cmd: ProcessBuilder, unit: &Unit) -> ProcessBuilder {
...
+                            .iter()
+                            .find_map(|(k, _)| {
+                                if k.kind == kind {
+                                    let summary = k.pkg.manifest().summary();
+
+                                    Some(format!("{} v{}", summary.name(), summary.version()))
+                                } else {
+                                    None
+                                }
+                            })
```
Comment (weihanglo) [inline src/cargo/core/compiler/compilation.rs:405]: (nit: styling)

```suggestion
                            .find_map(|(u, _)| (unit.kind == kind).then_some(unit.pkg.summary().package_id()))
```

BTW, it might be overkill but by reusing `Display` impl for `PackageId` one can get more useful info when developing a local artifact dep. (And DRY rule applied 😆)


https://github.com/rust-lang/cargo/blob/b862c6df16bfe6f29da2237c7d1a86159dc85d19/src/cargo/core/package_id.rs#L210-L220

File: src/cargo/core/compiler/compilation.rs [hunk 3]
```diff
@@ -384,6 +375,48 @@ fn fill_rustc_tool_env(mut cmd: ProcessBuilder, unit: &Unit) -> ProcessBuilder {
...
+                        anyhow::anyhow!(
+                            "could not find specification for target \"{target}\".\n  \
+                            Dependency `{dependency}` requires to build for target \"{target}\"."
+                        )
+                    })?
+                    .sysroot_target_libdir
+                    .clone(),
+            ))
+        })
+        .collect::<CargoResult<HashMap<_, _>>>()
```
Comment (weihanglo) [inline src/cargo/core/compiler/compilation.rs:417]: rustc could inference this I believe.

```suggestion
        .collect()
```

File: src/cargo/core/compiler/compilation.rs [hunk 4]
```diff
@@ -384,6 +375,48 @@ fn fill_rustc_tool_env(mut cmd: ProcessBuilder, unit: &Unit) -> ProcessBuilder {
     cmd
 }
 
+fn get_sysroot_target_libdir(
+    bcx: &BuildContext<'_, '_>,
+) -> CargoResult<HashMap<CompileKind, PathBuf>> {
+    bcx.all_kinds
+        .iter()
+        .map(|&kind| {
```
Comment (weihanglo) [inline src/cargo/core/compiler/compilation.rs:383]: (nit: styling)

Inside this `map` call, I feel like abusing `let-else` makes things more readable, like:

```rust
            let Some(info) = bcx.target_data.get_info(kind) else {
                ...
                ...
                anyhow::bail!(...);
            };
            Ok((kind, info.sysroot_target_libdir.clone()))
```

File: src/cargo/core/compiler/compilation.rs [hunk 5]
```diff
@@ -384,6 +375,48 @@ fn fill_rustc_tool_env(mut cmd: ProcessBuilder, unit: &Unit) -> ProcessBuilder {
...
+                                    Some(format!("{} v{}", summary.name(), summary.version()))
+                                } else {
+                                    None
+                                }
+                            })
+                            .unwrap();
+
+                        anyhow::anyhow!(
+                            "could not find specification for target \"{target}\".\n  \
+                            Dependency `{dependency}` requires to build for target \"{target}\"."
```
Comment (weihanglo) [inline src/cargo/core/compiler/compilation.rs:410]: (nit: style)

Oops. That was my oversight. In Cargo by convention we use backtick to quote things. That should be followed here as well I guess.
However, it makes messages inconsistent between rustc and cargo 😆.

```suggestion
                            "could not find specification for target `{target}`.\n  \
                            Dependency `{dependency}` requires to build for target `{target}`."
```

**Review by weihanglo — COMMENTED** [review]
Really neat and complete! Love to see people putting more doc comments during development! Thank you!

Just some picky styling issues left. Let me know if you disagree or have a better idea :)

**Comment by ehuss** [comment]
I suggest that this doesn't entirely fix #11260. I would expect artifact dependencies to work, not generate an error message.

**Comment by weihanglo** [comment]
Oops that's my fault. I though it was just target spec not found but it turns out not. Cargo should learn all targets required by artifact dependencies, probably after unit graph is created.

Thanks Eric for calling out and sorry for the wrong pointer, @jofas 😞.

**Comment by jofas** [comment]
> I would expect artifact dependencies to work

Me too :sweat_smile: 

> sorry for the wrong pointer

No worries. In the issue it sounded like getting all the necessary targets for building artifact dependencies isn't trivial and I assumed a change like that required some more procedural overhead than a simple PR (does cargo have RFCs as well?). With some more hints on where I need to look in order to add the required targets for transitive artifact dependencies to `RustcTargetData`, I'd love to extent this PR!

**Comment by jofas** [comment]
https://github.com/rust-lang/cargo/blob/99b13692dd30d19caf4bfdb81edf9e65c9af0655/src/cargo/core/compiler/build_context/target_info.rs#L919-L925

AFAICT, if we make this function recursive and call it for each dependency, we should get all the necessary targets for transitive dependencies, no? I haven't found a way yet to get the `Package` or `Manifest` objects from `Dependency`. Maybe from the `BuildContext.packages`? If we could pass `BuildContext` down to the `RustcTargetData::new`, that is. I'll keep digging and see if I can find something more concrete. Any thoughts on my idea?

**Comment by weihanglo** [comment]
> if we make this function recursive and call it for each dependency, we should get all the necessary targets for transitive dependencies, no?

I am afraid it won't work, or requests for too many targets then it really needs. We should also consider optional dependencies and the feature resolution. I believe Cargo doesn't need every disabled target platform toolchain to exist on the host machine.

**Comment by jofas** [comment]
> I am afraid it won't work, or requests for too many targets then it really needs. We should also consider optional dependencies and the feature resolution. I believe Cargo doesn't need every disabled target platform toolchain to exist on the host machine.

Will that really be a problem? Sure, creating `TargetInfo` (which is where rustc must be executed) seems to be computationally expensive, so it would be unfortunate if we get it for more targets than needed during compilation. I'm asking, because I can't see how we'd be able to use the `UnitGraph` (which I'm assuming is the graph containing all the dependencies and how to compile them) for choosing the right targets for `RustcTargetData`, as for creating the `UnitGraph`, we need `RustcTargetData`.

**Review by weihanglo — APPROVED** [review]
Hi @jofas! As ehuss said, this is not a complete fix for #11260, but we can still ship this nicer error message. For fixing the root issue, I'll take a deep look next week and see if I can find anything useful.

Let's merge this. Thank you!

**Comment by ehuss** [comment]
I posted #11766 to fix the issue with CI failing.

**Comment by jofas** [comment]
> For fixing the root issue, I'll take a deep look next week and see if I can find anything useful.

Great, please [let me know](mailto:jonas@fassbender.dev) if you find anything I could help with.
