### PR TITLE
fix(build-std): make Resolve  align to what to build

### LINKED ISSUE #14935: `error: package ID specification `panic_unwind` did not match any packages` with `-Zbuild-std`
Update to latest rust nightly: `cargo 1.85.0-nightly (769f622e1 2024-12-14)` got `error: package ID specification `panic_unwind` did not match any packages` when build with `-Zbuild-std` option.

It happened only on today's update, all builds before have no problems.

What does it mean? And how to fix it...

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

Blocked on <https://github.com/rust-lang/cargo/pull/14943> (or can just merge this one).

Fixes #14935

#14935 failed because since 125e873dffc4b68b263c5decd88750ec10fd441e
[`std_resolve`][1] only includes `sysroot` as primary package.
When any custom Cargo feature is provided via `-Zbuild-std-feature`,
the default feature set `panic-unwind` would be gone, so no
`panic_unwind` crate presents in `std_resolve`.

When then calling [`std_resolve.query`][2] with the default set of
crates from [`std_crates`][3], which automatically includes
`panic_unwind` when `std` presents, it'll result in spec not found
because `panic_unwind` was not in `std_resolve` anyway.

[1]: https://github.com/rust-lang/cargo/blob/addcc8ca715bc7fe20df66afd6efbf3c77ef43f8/src/cargo/core/compiler/standard_lib.rs#L96
[2]: https://github.com/rust-lang/cargo/blob/addcc8ca715bc7fe20df66afd6efbf3c77ef43f8/src/cargo/core/compiler/standard_lib.rs#L158
[3]: https://github.com/rust-lang/cargo/blob/addcc8ca715bc7fe20df66afd6efbf3c77ef43f8/src/cargo/core/compiler/standard_lib.rs#L156

### How should we test and review this PR?

This patch is kinda a revert of 125e873dffc4b68b263c5decd88750ec10fd441e
in terms of the behavior.

With this, now `std_resolve` is always resolved to the same set of
packages that Cargo will use to generate the unit graph, (technically
the same set of crates + `sysroot`), by sharing the same set of primary
packages via `std_crates` functions.

Note that when multiple `--target`s provided, if std is specified or there
is one might support std, Cargo will always resolve std dep graph.

To test it manually, run

```
RUSTFLAGS="-C panic=abort" cargo +nightly-2024-12-15 b -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort
```

change to this PR's cargo with the same nightly rustc, it would succeed.

I am a bit reluctant to add an new end-2end build-std test, but I still did it.
A bit scared when mock-std gets out-of-sync of features in std in rust-lang/rust.

### CODE REVIEW

File: src/cargo/ops/cargo_compile/mod.rs [hunk 1]
```diff
@@ -289,15 +289,6 @@ pub fn create_bcx<'a, 'gctx>(
         resolved_features,
     } = resolve;
 
-    let std_resolve_features = if gctx.cli_unstable().build_std.is_some() {
```
[the remark this answers is not in the document]
Comment (weihanglo) [reply src/cargo/ops/cargo_compile/mod.rs:292]: Not relevant anymore.

**Comment by weihanglo** [comment]
@epage I hope this PR is in a more reviewable state :)

File: src/cargo/core/compiler/build_context/target_info.rs [hunk 2]
```diff
@@ -619,6 +619,13 @@ impl TargetInfo {
             .iter()
             .any(|sup| sup.as_str() == split.as_str())
     }
+
+    /// Checks if a target support core only.
+    ///
+    /// If no explictly stated in target spec json, we treat it as "maybe support".
+    pub fn support_core_only(&self) -> bool {
+        matches!(self.supports_std, Some(false))
```
Comment (epage) [inline src/cargo/core/compiler/build_context/target_info.rs:627]: Unsure if this is something inherent to build-std or something weird about how we have the code structured but looking at this function in isolated, it seems weird to say that something only supports `core` if `std` isn't supported.  There is also `alloc` and others, right?

Also, outside of the context of buiild-std, this makes it read like we have native support for no_std crates but this is separate from that.

**Review by epage — APPROVED** [review]

File: src/cargo/core/compiler/build_context/target_info.rs (hunk 2 above)
Comment (weihanglo) [reply src/cargo/core/compiler/build_context/target_info.rs]: Thanks for calling all these out.

Just updated the function name to `maybe_support_std` and called out that it is for `-Zbuild-std`.

> it seems weird to say that something only supports `core` if `std` isn't supported.  There is also `alloc` and others, right?

Yes, but core is like the fundamental of everything and `alloc` depends on `core`.

Anyway, this only affects `-Zbuild-std` to determine the default set of crate to build, if no value is provided to `-Zbuild-std`.

**Review by epage — APPROVED** [review]
