### PR TITLE
fix: only skip mtime check on `~/.cargo/{git,registry}`

### LINKED ISSUE #12090: `cargo run` and `cargo build` don't seem to reflect recent changes
### Problem

i've been using vscode and 
```
anand@anands-MacBook-Pro ~/.c/d/lorenz (main)> cargo -V
cargo 1.69.0 (6e9a83356 2023-04-12)
anand@anands-MacBook-Pro ~/.c/d/lorenz (main)> rustup -V
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.69.0 (84c898d65 2023-04-16)`
```
and i have a simple lib. when i change some stuff then rerun `cargo run` it runs the old code. 
i found this which seems similar to my issue
https://stackoverflow.com/questions/57087386/cargo-run-does-not-reflect-any-code-changes-in-main-rs

but in my case the only way that i reliably found to get cargo to register the changes is by deleting the `target` folder and rerunning. 

happy to provide more information if needed! i am probably doing something silly (pretty new to rust) but im confused

### Steps

_No response_

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by jo1gi**
Fixes #12090

Make cargo only skip mtime checks on `$CARGO_HOME/{git, registry}`.

### CODE REVIEW

File: src/cargo/core/compiler/fingerprint/mod.rs [hunk 1]
```diff
@@ -1860,11 +1860,18 @@ where
...
-            continue;
+        // Assuming anything in cargo_home/{git, registry} is immutable
+        // (see also #9455 about marking cargo_home readonly) which avoids rebuilds when CI caches
+        // $CARGO_HOME/registry/{index, cache} and $CARGO_HOME/git/db across runs, keeping the
+        // content the same but changing the mtime.
+        if let Ok(cargo_home) = home::cargo_home() {
+            let is_readonly = ["git", "registry"]
+                .into_iter()
+                .map(|subfolder| cargo_home.join(subfolder))
+                .any(|readonly_dir| path.starts_with(readonly_dir));
```
Comment (weihanglo) [inline src/cargo/core/compiler/fingerprint/mod.rs:1871]: * Maybe just a micro optimization. This `cargo_home.join` is in a hot loop over `paths`. Could we do the allocation out of the loop upfront?
* I am a big wary that we now duplicate the path construction logic. Do you feel it better if we reuse the code [here in `Config`](https://github.com/rust-lang/cargo/blob/20df9e40a4d41dd08478549915588395e55efb4c/src/cargo/util/config/mod.rs#L353-L361)?

**Review by weihanglo — COMMENTED** [review]
Thanks for the contribution! Could you add a test to verify that only registry and git path are ignored? Maybe by ensuring mtime check won't skip `~/.cargo/bin`.

**Comment by weihanglo** [comment]
Pardon my title editing 🙇🏾.

File: src/cargo/core/compiler/fingerprint/mod.rs (hunk 1 above)
Comment (jo1gi) [reply src/cargo/core/compiler/fingerprint/mod.rs:1871]: I will take a look at it. Should I combine the commits, when I'm done?

Comment (weihanglo) [reply src/cargo/core/compiler/fingerprint/mod.rs:1871]: My personal preference is making each commit atomic. Given the size of this change is not huge, it makes sense to me just rebase and leave one or two commits.

More personally, I may have the first commit to have a test first asserting the "bug behavior". Then the second contains the actual patch and the fixup of the test.

File: src/cargo/core/compiler/fingerprint/mod.rs [hunk 2]
```diff
@@ -1860,11 +1860,18 @@ where
     for path in paths {
         let path = path.as_ref();
 
-        // Assuming anything in cargo_home is immutable (see also #9455 about marking it readonly)
-        // which avoids rebuilds when CI caches $CARGO_HOME/registry/{index, cache} and
-        // $CARGO_HOME/git/db across runs, keeping the content the same but changing the mtime.
-        if let Ok(true) = home::cargo_home().map(|home| path.starts_with(home)) {
-            continue;
+        // Assuming anything in cargo_home/{git, registry} is immutable
+        // (see also #9455 about marking cargo_home readonly) which avoids rebuilds when CI caches
```
Comment (tamird) [inline src/cargo/core/compiler/fingerprint/mod.rs:1864]: FWIW: #9455 is not about marking CARGO_HOME readonly, but rather only a subdirectory of it.

File: tests/testsuite/build.rs [hunk 3]
```diff
@@ -5972,6 +5972,62 @@ fn build_with_relative_cargo_home_path() {
...
+    p.cargo("run")
+        .env("CARGO_HOME", &cargo_home)
+        .with_stdout("1")
+        .run();
+    // Run with cache
+    p.change_file("src/main.rs", r#"fn main() { println!("2"); }"#);
+    p.cargo("run")
+        .env("CARGO_HOME", &cargo_home)
+        .with_stdout("1")
+        .run();
```
Comment (weihanglo) [inline tests/testsuite/build.rs:6000]: The test looks like. Just some minor details:

* We usually assert `stderr` instead of `stdout`, so that we can avoid `cargo build` and instead use `cargo check`. That makes testsuite run a bit faster.
* When asserting the output for compilation freshness, we usually use `--verbose/-v` to assert `[FRESH]` status unless there is a need of verifying the behavior of final artifacts.
* Changed the `lib.rs` content to some illegal syntax so we can observe whether the build fails or not.
* `env` accepts `AsRef<OsStr>` so `to_str()` is unnecessary.


```suggestion
    let p = project()
        .at("cargo_home/registry/foo")
        .file("Cargo.toml", &basic_lib_manifest("foo"))
        .file("src/lib.rs", "")
        .build();
    let project_root = p.root();
    let cargo_home = project_root
        .parent()
        .unwrap()
        .parent()
        .unwrap();
    p.cargo("check -v")
        .env("CARGO_HOME", &cargo_home)
        .with_stderr(
            "\
[CHECKING] foo v0.5.0 ([CWD])
[RUNNING] `rustc --crate-name foo src/lib.rs [..]
[FINISHED] dev [..]",
        )
        .run();
    // Run with cache
    p.change_file("src/lib.rs", "illegal syntax");
    p.cargo("check -v")
        .env("CARGO_HOME", &cargo_home)
        .with_stderr(
            "\
[FRESH] foo v0.5.0 ([CWD])
[FINISHED] dev [..]",
        )
        .run();
```

File: tests/testsuite/build.rs [hunk 4]
```diff
@@ -5972,6 +5972,62 @@ fn build_with_relative_cargo_home_path() {
...
+        .file("src/main.rs", r#"fn main() { println!("1"); }"#)
+        .build();
+    let project_root = p.root();
+    let cargo_home = project_root
+        .parent()
+        .unwrap()
+        .parent()
+        .unwrap()
+        .to_str()
+        .unwrap();
```
Comment (weihanglo) [inline tests/testsuite/build.rs:6018]: Should be only one level up, right?

```suggestion
        .unwrap();
```

File: tests/testsuite/build.rs [hunk 5]
```diff
@@ -5972,6 +5972,62 @@ fn build_with_relative_cargo_home_path() {
...
+    // Run with cache
+    p.change_file("src/main.rs", r#"fn main() { println!("2"); }"#);
+    p.cargo("run")
+        .env("CARGO_HOME", &cargo_home)
+        .with_stdout("1")
+        .run();
+}
+
+#[cargo_test]
+fn use_mtime_cache_in_cargo_home() {
```
Comment (weihanglo) [inline tests/testsuite/build.rs:6004]: Could you apply the same suggestion gave to `skip_mtime_check_in_selected_cargo_home_subdirs` here?

**Review by weihanglo — COMMENTED** [review]
Thanks for adding tests! 

Could we move these two tests to `tests/testsuite/freshness.rs`. It makes more sense to put them there.

File: tests/testsuite/build.rs (hunk 5 above)
Comment (jo1gi) [reply tests/testsuite/build.rs]: Thank you for the help.

**Review by weihanglo — COMMENTED** [review]
We're almost there! Could you run `cargo fmt --all` to address the format error?

**Comment by weihanglo** [comment]
Thanks @jo1gi 

@bors r+
