### PR TITLE
Cap lints for upstream deps with `-vv`

### LINKED ISSUE #3823: cargo verbose = warning as error mode
I saw many times when `cargo build -v -v` failed, while `cargo build` work without problems.

For example if you use `iron` that depend on `typemap`, with `cargo build -v -v` you will see:

    error: defaults for type parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions., #[deny(invalid_type_param_default)] on by default
       --> /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/typemap-0.3.3/src/lib.rs:185:18
        |
    185 | impl<'a, K: Key, A: ?Sized + UnsafeAnyExt + 'a = UnsafeAny> Entry<'a, K, A> {
        |                  ^

And `cargo build` failed.

Or for example if you use `syntex` library, with `cargo build -v -v` you will see:

    error: unused `#[macro_use]` import
      --> /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_errors-0.54.0/src/lib.rs:22:1
       |
    22 | #[macro_use]
       | ^^^^^^^^^^^^

    error: aborting due to 2 previous errors

So is `cargo build -v -v` not only make output more verbose, but turn on something like "error on warning mode? Can it be at least documented.

### PR DESCRIPTION
**Pull request by alexcrichton**
Previously with `-vv` Cargo didn't pass `--cap-lints` at all, but with upstream
dependencies we still want to pass at least `--cap-lints warn` to make sure that
they're all still compiling.

Closes #3823

### CODE REVIEW

File: src/cargo/ops/cargo_rustc/mod.rs [hunk 1]
```diff
@@ -249,12 +249,20 @@ fn rustc(cx: &mut Context, unit: &Unit, exec: Arc<Executor>) -> CargoResult<Work
...
         if cx.config.rustc()?.cap_lints {
             rustc.arg("--cap-lints").arg("allow");
         } else {
             rustc.arg("-Awarnings");
         }
+
+    // If this is an upstream dep but we *do* want warnings, make sure that they
+    // don't fail compilation.
+    } else if !unit.pkg.package_id().source_id().is_path() {
+        rustc.arg("--cap-lints").arg("warn");
```
Comment (matklad) [inline src/cargo/ops/cargo_rustc/mod.rs]: We either should add a `if cx.config.rustc()?.cap_lints` guard here, or abandon support for older rustc's altogether.

File: tests/registry.rs [hunk 2]
```diff
@@ -1384,3 +1384,30 @@ fn toml_lies_but_index_is_truth() {
...
+            authors = []
+
+            [dependencies]
+            foo = "0.2"
+        "#)
+        .file("src/main.rs", "fn main() {}");
+    p.build();
+
+    assert_that(p.cargo("build").arg("-vv"),
+                execs().with_status(0));
```
Comment (matklad) [inline tests/registry.rs]: Let's also check that the warning **is** printed?

File: src/cargo/ops/cargo_rustc/mod.rs (hunk 1 above)
Comment (matklad) [inline src/cargo/ops/cargo_rustc/mod.rs]: Hm, and do we actually run Cargo's test suite with older compilers? It worries me that this currently passes Travis :)

**Comment by alexcrichton** [comment]
We've basically all but jettisoned support for older compilers, but yeah we definitely don't attempt to test older compilers as well. Note that --cap-lints was added in like 1.4, ages ago!

**Comment by matklad** [comment]
@bors: r+

Issue to jettison `--cap-lints` feature detection: https://github.com/rust-lang/cargo/issues/3828

File: src/cargo/ops/cargo_rustc/mod.rs [hunk 3]
```diff
@@ -249,12 +249,24 @@ fn rustc(cx: &mut Context, unit: &Unit, exec: Arc<Executor>) -> CargoResult<Work
...
         if cx.config.rustc()?.cap_lints {
             rustc.arg("--cap-lints").arg("allow");
         } else {
             rustc.arg("-Awarnings");
         }
+
+    // If this is an upstream dep but we *do* want warnings, make sure that they
+    // don't fail compilation.
+    } else if !unit.pkg.package_id().source_id().is_path() {
+        if cx.config.rustc?().cap_lints {
```
Comment (matklad) [inline src/cargo/ops/cargo_rustc/mod.rs]: `?()` -> `()?`. Or maybe drop this if in both cases :)

**Comment by alexcrichton** [comment]
rustc?

or rustc?()

or rustc()?

or ?rustc()

or ¿rustc()

or rustc¿()
