### PR TITLE
`cargo metadata` works with workspaces

### LINKED ISSUE #3003: Cargo metadata subcommand should work with workspaces
Currently it gives

```
error: manifest path `/home/matklad/projects/vulkano/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

Ideally it should return the info in the same format as `metadata` command for the non-virtual manifest. The only obstacle seems to be the `root` node in the `resolve`.

And perhaps for any package that is a part of the workspace `cargo metadata` should indicate it.

### PR DESCRIPTION
**Pull request by matklad**
Closes #3003

### CODE REVIEW

File: src/cargo/ops/cargo_output_metadata.rs [hunk 1]
```diff
@@ -53,28 +54,36 @@ fn metadata_full(ws: &Workspace,
...
+    resolve: Resolve,
+    root: Option<PackageId>,
+}
 
 impl Encodable for MetadataResolve {
     fn encode<S: Encoder>(&self, s: &mut S) -> Result<(), S::Error> {
         #[derive(RustcEncodable)]
         struct EncodableResolve<'a> {
-            root: &'a PackageId,
+            root: Option<&'a PackageId>,
```
Comment (matklad) [inline src/cargo/ops/cargo_output_metadata.rs]: I think this change is backwards compatible, because `root` would be null only in those cases, where previously `cargo metadata` did not work at all.

**Comment by alexcrichton** [comment]
@bors: r+ 578c1a11696b56cfe8321cb86d784bf2105104a2

Thanks!
