### PR TITLE
Fix `BorrowMutError` when calling `cargo doc --open`

### LINKED ISSUE #9530: cargo doc --open fails with 'already borrowed: BorrowMutError'
**Problem**

I'm unable to run `cargo doc --open` without

```
thread 'main' panicked at 'already borrowed: BorrowMutError', src/tools/cargo/src/cargo/util/config/mod.rs:342:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c1e8f3a5857c3c8d095fd212acc6ed442f4cc58b/library/core/src/result.rs:1355:5
   3: cargo::util::config::de::ConfigMapAccess::new_struct
   4: <cargo::util::config::de::Deserializer as serde::de::Deserializer>::deserialize_struct
   5: cargo::util::config::Config::get
   6: cargo::ops::cargo_doc::doc
   7: cargo::commands::doc::exec
   8: cargo::cli::main
   9: cargo::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Steps**
1. Go to any cargo project
2. Run `cargo doc --open`

**Possible Solution(s)**

I've already implemented a fix for this, to be careful to not keep the result of `ws.config()` around before we call `ws.config()` again, will make a pull request for that shortly.

**Notes**

Output of `cargo version`:

Happens on `cargo 1.54.0-nightly (e931e4796 2021-05-24)` as well as the latest git master, being checked out to 0cecbd6.

That being said, I have no idea why the tests didn't catch this. I do have `CARGO_TARGET_DIR` set to have a global target directory, but even unsetting that and running `cargo run -- doc --open` in the cargo git repo fails.

### PR DESCRIPTION
**Pull request by 5225225**
~~I'm not sure why the existing test suite didn't catch this, it definitely calls `cargo doc --open`.~~

I had 

```toml
[doc.extern-map]
std = "local"
```

in my `.cargo/config.toml`. Will write a test case that sets that and then tries to run `cargo doc --open`.

Closes #9530

### CODE REVIEW

**Comment by ehuss** [comment]
Thanks for opening the PR!  Let me know if you have any questions on how to add a test. There's some documentation in the [contributor guide](https://doc.crates.io/contrib/tests/index.html) for running and writing tests, and the [`doc.rs`](https://github.com/rust-lang/cargo/blob/master/tests/testsuite/doc.rs) file contains some examples of testing `--open` and [`rustdoc_extern_html.rs`](https://github.com/rust-lang/cargo/blob/master/tests/testsuite/rustdoc_extern_html.rs) contains the tests for `extern-map`.

**Comment by 5225225** [comment]
I can't seem to get the test to use `doc.extern-map`, it just always gives that warning that it's not being used. I did copy the usage from the extern-map test that works, that didn't seem to help anything.

I'm assuming that it's not used if the cargo version is stable, but I *am* calling `.masquerade_as_nightly_cargo()`, so that should be fixing it? And I'm running the tests using a nightly cargo, since it's not the assert at the top that's tripping.

Can someone who's more familiar with the codebase than I help me out here, because I'm lost as to why this test isn't working.

File: src/cargo/ops/cargo_doc.rs [hunk 1]
```diff
@@ -35,15 +35,16 @@ pub fn doc(ws: &Workspace<'_>, options: &DocOptions) -> CargoResult<()> {
             .join(&name)
             .join("index.html");
         if path.exists() {
+            let config_browser = {
+                let cfg = ws.config().get::<CargoDocConfig>("doc")?;
+
+                cfg.browser
+                    .map(|path_args| (path_args.path.resolve_program(ws.config()), path_args.args))
```
Comment (ehuss) [inline src/cargo/ops/cargo_doc.rs:42]: I think to remove the warning, the following can be changed to this:

```suggestion
                let cfg: Option<PathAndArgs> = ws.config().get("doc.browser")?;
                cfg.map(|path_args| (path_args.path.resolve_program(ws.config()), path_args.args))
```

and just delete the `CargoDocConfig` struct.  The issue is that the config system is expecting the `doc` config structure to only include the browser field.

Alternatively, `Config.doc_extern_map` could be changed to something that returns a struct that includes both fields (browser and extern-map).

**Comment by 5225225** [comment]
Okay, the test looks to be running fine, and I've tested that the test actually *works* (fails when it's meant to) by checking out the `cargo_doc.rs` file from origin/master and ran the test, and it failed as expected.

File: tests/testsuite/doc.rs [hunk 2]
```diff
@@ -1168,6 +1168,39 @@ fn doc_workspace_open_help_message() {
         .run();
 }
 
+#[cargo_test]
+#[cfg(not(windows))] // `echo` may not be available
+fn doc_extern_map_local() {
+    assert!(is_nightly());
```
Comment (ehuss) [inline tests/testsuite/doc.rs:1174]: This assert will cause the test to fail on stable.  To make the test conditional on being nightly, it should be something like the following:

```suggestion
    if !is_nightly() {
        // --extern-html-root-url is unstable
        return;
    }
```

File: tests/testsuite/doc.rs [hunk 3]
```diff
@@ -1168,6 +1168,39 @@ fn doc_workspace_open_help_message() {
...
+        .file("src/lib.rs", "")
+        .build();
+
+    p.change_file(
+        ".cargo/config.toml",
+        r#"
+[doc.extern-map]
+std = "local"
+    "#,
+    );
```
Comment (ehuss) [inline tests/testsuite/doc.rs:1194]: This can just be a call to `file()` above.  You might be able to fit it on one line with `.file(".cargo/config.toml", "doc.extern-map.std = 'local'")`

File: tests/testsuite/doc.rs [hunk 4]
```diff
@@ -1168,6 +1168,39 @@ fn doc_workspace_open_help_message() {
...
+
+    p.cargo("doc -v --no-deps -Zrustdoc-map --open")
+        .env("BROWSER", "echo")
+        .masquerade_as_nightly_cargo()
+        .with_stderr_contains("[..] Documenting foo v0.1.0 ([..])")
+        .with_stderr_does_not_contain("warning: unused config key `doc.extern-map` [..]")
```
Comment (ehuss) [inline tests/testsuite/doc.rs:1200]: `with_stderr_does_not_contain` can be dangerous to use, because there is no way to tell if it continues to work in the future (say, for example, the warning text was slightly changed).  Can this instead use a `with_stderr()` to just check all the output?  It would look something like [this](https://github.com/rust-lang/cargo/blob/1fc64069fd3b24c506b607fdc3404cf87014fa1a/tests/testsuite/doc.rs#L1659-L1667) (plus the "Opening" line).  That should help ensure that no warnings are emitted at all, and that nothing unexpected is displayed.

**Comment by ehuss** [comment]
Thanks!

@bors r+
