### PR TITLE
Ignore `workspace.default-members` when running `cargo install` on root package of a non-virtual workspace

### LINKED ISSUE #11058: `cargo install --git` builds `workspace.default-members` when it should not
### Problem

* This affects `--path` as well.
* It does not affect e.g. `crates.io` because the `Cargo.toml` there have `workspace` stripped from them.

When running a command like:

```
cargo install --locked --git https://github.com/model-checking/kani  kani-verifier
```

The "normal" behavior is to check out that repo, and only build the specified `kani-verifier` package from the workspace. Once we've added a `workspace.default-members` to `Cargo.toml`, however, cargo now seems to build those packages as well. (For Kani specifically, this fails, as other workspace members like `kani-compiler` should only be built against a specific Rust nightly...)

We did not expect `cargo install` behavior to change by changing workspace default members, and I believe this is a bug.

### Steps

1. Create a cargo workspace with multiple packages and `workspace.default-members`
2. `cargo install --path` or `--git` one package from that workspace.
3. Observe that all `default-members` get built as well.

### Possible Solution(s)

_No response_

### Notes

Suggested tags:

* Command-install
* A-workspaces

### Version

```text
cargo 1.65.0-nightly (4ed54cecc 2022-08-27)
release: 1.65.0-nightly
commit-hash: 4ed54cecce3ce9ab6ff058781f4c8a500ee6b8b5
commit-date: 2022-08-27
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 20.04 (focal) [64-bit]
```

### PR DESCRIPTION
**Pull request by tedinski**
### What does this PR try to resolve?

* Fixes #11058 

Two observable behaviors are fixed:

1. When running `cargo install` with `--path` or `--git` and specifically requesting the root package of a non-virtual workspace, `cargo install` will accidentally build `workspace.default-members` instead of the requested root package.
2. Further, if that `default-members` does not include the root package, it will install binaries from those other packages (the `default-members`) and claim they were the binaries from the root package! There is no way, actually, to install the root package binaries.

These two behaviors have the same root cause:

* `cargo install` effectively does `cargo build --release` in the requested package directory, but when this is the root of a non-virtual workspace, that builds `default-members` instead of the requested package.

### How should we test and review this PR?

I have included a test exhibiting this behavior. It currently fails in the manner indicated in the test, and passes with the changes included in this PR.

I'm not sure the solution in the PR is the _best_ solution, but the alternative I am able to come up with involves much more extensive changes to how `cargo install` works, to produce a distinct `CompileOptions` for every package built. I tried to keep the new workspace "API" `ignore_default_members()` as narrowly-scoped in its effect as possible.

### Additional information

The only way I could think this behavior change could impact someone is if they were somehow using `cargo install --path` (or `--git`) and wanting it to actually install the binaries from all of `default-members`. However, I don't believe that's possible, since if there are multiple packages with binaries, I believe cargo requires the packages to be specified. So someone would have to be additionally relying on specifying just the root package, but then wanting the binaries from more than just the root. I think this is probably an acceptable risk for merging!

### CODE REVIEW

File: src/cargo/core/workspace.rs [hunk 1]
```diff
@@ -552,6 +552,23 @@ impl<'cfg> Workspace<'cfg> {
...
+        // If we're building a virtual workspace, then there is no root package to build
+        if self.is_virtual() {
+            return self;
+        }
+        // If we're not building the root package, then the default members do not matter
+        if self.current_manifest != self.root_manifest() {
+            return self;
+        }
+
+        self.default_members = vec![self.current_manifest.clone()];
```
Comment (Muscraft) [inline src/cargo/core/workspace.rs:568]: I am concerned that this solution misuses how [Package Selection](https://doc.rust-lang.org/cargo/commands/cargo-build.html?highlight=default-members#package-selection) works within a non-virtual workspace with `default-features` set. This is because it works by relying on [this part](https://github.com/rust-lang/cargo/blob/9467f81fbf340b70f7ab7e3290146350133f3ea3/src/cargo/ops/cargo_compile.rs#L413-L420) of creating the build context. 

The Cargo book explains what I mean [here](https://doc.rust-lang.org/cargo/reference/workspaces.html#package-selection) by saying:
> The optional default-members key can be specified to set the members to operate on when in the workspace root and the package selection flags are not used

Given what the book says and what I linked to says in the build context it might be a better idea to modify the `CompileOptions` to act as though `-p` was passed in the command line. 

I could be wrong with my concerns so I would wait until someone from the [Cargo team](https://www.rust-lang.org/governance/teams/dev-tools#cargo) comments as well.

Comment (tedinski) [reply src/cargo/core/workspace.rs:568]: > it might be a better idea to modify the CompileOptions to act as though -p was passed in the command line.

It absolutely is the better idea. This solution is for-sure technical debt until someone can figure that out.

The problem is that `CompileOptions` owns a `BuildConfig` which ultimately owns a `RefCell` containing `TcpListener` (inside `RustfixDiagnosticServer`), so it's a totally non-trivial thing to e.g. clone. (And I'm not confident enough in how Cargo works to know if there's any easy solution to this...)

If there's an easy solution someone can point me to, I'm happy to switch over to it, but I saw that `TcpListener` and got spooked that there might be hidden architectural assumptions of only one `BuildConfig` in a `cargo` invocation, or something like that...

Comment (weihanglo) [reply src/cargo/core/workspace.rs:568]: Having a `fn ignore_default_members` in `core::workspace.rs` looks weird to me, as it only serves for `cargo-install` and no one use it (and shouldn't). 

Reusing `-p` might be an option. The problem is that cargo-install contains ad-hoc solution that reads into a workspace but not use the info everywhere. And that might break things if we reuse `-p` option. I always feel a headache looking into these small but significant differences.

**Comment by tedinski** [comment]
I hope to return to this if someone else doesn't beat me to a better solution, but I'm not certain what the best approach would be.

The trouble with the "build with different `-p` options" approach is that the `CompileOptions` isn't a clonable type, and ultimately (via `BuildConfig`) seems to contain some things that aren't clonable.

My guess at a path forward there is perhaps to write a `clone_as_template` method to both these types that `assert`s that certain problematic fields are `None` (and not `Some`thing unclonable). (I'm assuming we don't want to add a `Clone` implementation that's partial and might fail, hence the ad-hoc method.) Then we could clone and mutate the initial `CompileOptions` for each build, letting us (effectively) set `-p` appropriately for each one.

**Comment by ehuss** [comment]
I think it would be fine to `#[derive(Debug, Clone)]` on `CompileOptions` and `BuildConfig`, and just wrap `rustfix_diagnostic_server` in an `Arc` (as in `rustfix_diagnostic_server: Arc<RefCell<Option<RustfixDiagnosticServer>>>`). Can you say if you ran into any problems with that? I think it generally should be a one or two line change.

**Comment by tedinski** [comment]
I've updated the PR to the suggested approach. The change was smooth, I just wasn't sure if wrapping it in an `Arc` was the right approach to take, so that was helpful.

**Review by weihanglo — APPROVED** [review]
Looks good. Thank you for coming back taking care of this!

File: src/cargo/ops/cargo_install.rs [hunk 2]
```diff
@@ -167,7 +167,14 @@ impl<'cfg, 'a> InstallablePackage<'cfg, 'a> {
             }
         };
 
-        let (ws, rustc, target) = make_ws_rustc_target(config, opts, &source_id, pkg.clone())?;
+        // When we build this package, we want to build the *specified* package only,
+        // and avoid building e.g. workspace default-members instead. Do so by constructing
+        // specialized compile options specific to the identified package.
+        // See test `path_install_workspace_root_despite_default_members`.
+        let mut opts = original_opts.clone();
+        opts.spec = Packages::Packages(vec![pkg.name().to_string()]);
```
Comment (epage) [inline src/cargo/ops/cargo_install.rs:175]: Looks like this is the cause of #11999.  Would you be interested in working on a fix for it?
