### PR TITLE
Fix #3658 .cargo/config prevents freshness (sort after HashMap)

### LINKED ISSUE #3658: .cargo/config prevents fresh builds if there are multiple metadata entries
When using `openssl-sys` with `./.cargo/config`, Cargo prevents caching of the openssl-sys, causing a full rebuild. 

Issue reproduced with both  `cargo-0.18.0-nightly (d710222 2017-02-04)` and `cargo 0.13.0-nightly (717adc8 2016-11-02)`. 

To reproduce: 

`git clone https://github.com/nathanaeljones/bug-cargo-fingerprint-openssl && cd bug-cargo-fingerprint-openssl && ./test.sh && ./test.sh`

### PR DESCRIPTION
**Pull request by nathanaeljones**
The many vectors of BuildOutput are populated from a HashMap in cargo_compile... and later these vectors are hashed.

HashMaps are the bane of Cargo's existence. 

But for now, we sort.

### CODE REVIEW

**Comment by nathanaeljones** [comment]
Fixes #3658

One change to note (specific to TOML configuration only - this PR does not touch other sources, like build output)

While order between rustc-link-lib and rustc-flags values was always undefined, order of link paths/libs within a single rustc-flags value was maintained. Now we sort them all.

Thus, the order of link paths and libraries may change when specifying multiple values on a single line.

To preserve these, yet not destroy all caching, we would need order access (or duplicate, then sort) the TOML table used in scrape_target_config.

File: src/cargo/ops/cargo_rustc/custom_build.rs [hunk 1]
```diff
@@ -406,6 +406,17 @@ impl BuildOutput {
         }
         Ok((library_paths, library_links))
     }
+
+    /// Sort the contents of the struct for consistent hashing. 
+    /// Suggested if populated from a HashMap instead of an order-preserving data source
+    pub fn sort(&mut self){
+        self.library_paths.sort();
+        self.library_links.sort();
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_rustc/custom_build.rs]: This and `library_paths` above I believe can be quite significant in terms of ordering, would it be possible to preserve the original orderings rather than sorting these?

**Comment by alexcrichton** [comment]
Thanks for the PR! The fix looks right to me.

Can you clarify though for me where the nondeterminism is coming from? I don't quite see how that hash map would connect to nondeterminism in the output just yet.

**Comment by nathanaeljones** [comment]
If you run the failing unit test, you should see randomized ordering
(without the patch). From code review, the loss of order would have to
occur in toml parsing or the HashMap. Are you expecting deterministic
iteration order on HashMap keys? I was under the impression stdlib uses a
random seed.

**Comment by nathanaeljones** [comment]
FWIW, I would LOVE to preserve ordering. What should we replace HashMaps with?

**Comment by nathanaeljones** [comment]
Is there a way to use a custom build of cargo with an otherwise standard nightly toolchain from rustup?

**Comment by alexcrichton** [comment]
Yes hash maps introduce nondeterminism, but Cargo's full of hash maps and we shouldn't change them all! 

The actual problem here is not that all arrays need to be sorted (which is unfortunately incorrect wrt linking) but just [one array needs sorting](https://github.com/rust-lang/cargo/blob/fa1b12aa7ae188c430108383e570119328b5a023/src/cargo/ops/cargo_compile.rs#L528). That metadata array can be created in a nondeterministic order, but all other keys should always be deterministic.

Can you change this PR to only sort that one array in that one location? Other than that looks good to me!

**Comment by nathanaeljones** [comment]
If I understand correctly, multiple TOML files are merged, which means there can be duplicate keys. TOML tables should be sorted (assuming normal BTreeMap behavior), https://is.gd/f9rI49, but these are later dumped into a HashMap.

**Comment by alexcrichton** [comment]
Expanding an array is done deterministically, iteration of a map is not. The only case iteration shows up in the output is the `metadata` array, the other fields should all be deterministic already, right?

**Comment by nathanaeljones** [comment]
If you remove the hash of BuildOutput, then you can get informative output. For example: 

`|INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for foo v0.5.0 (file:///home/n/Documents/imazen/cargo/target/cit/t24/foo): precalculated components have changed: overridden build state with hash: BuildOutput { library_paths: ["./y", "./b"], library_links: ["z", "a"], cfgs: [], metadata: [], rerun_if_changed: [], warnings: [] } != overridden build state with hash: BuildOutput { library_paths: ["./b", "./y"], library_links: ["z", "a"], cfgs: [], metadata: [], rerun_if_changed: [], warnings: [] }|
`

Note that both library_links and library_paths are non-deterministic.

**Comment by nathanaeljones** [comment]
This approach no longer mutates BuildOutput at all.

Instead, it iterates over the HashMap in a deterministic order. A Vec is used to sort by key. As no other changes exist (anymore), this ensures order is always preserved within TOML arrays.

**Comment by alexcrichton** [comment]
Hm that feels like it may be an excessively big hammer for the problem at hand here? We don't need *everything* to be deterministic, just this one array?

**Comment by nathanaeljones** [comment]
Wouldn't it be the smallest possible hammer? See the 2nd test for why 3
arrays are affected.

**Comment by alexcrichton** [comment]
Ah right yeah good point about visiting the flags vs array fix. I feel like that's a bit overly pedantic, but hey it's fixing a bug!

@bors: r+
