### PR TITLE
Add report if `cargo fix --edition` changes features.

### LINKED ISSUE #9048: Prepare Cargo for `resolver = "2"` as the default in the 2021 edition
In the 2021 edition for Cargo we're planning on having `resolver = "2"` be the default for all projects (e.g. if omitted then `resolver = "2"` will be inferred if `edition = "2021"`). Some work items that need to be implemented for this are:

* [ ] Execution of `cargo fix --edition` where `resolver` is not specified needs to generate a warning if the 1/2 feature graphs differ. Ideally we'd also print differences here, but at the very least Cargo needs to recommend `resolver = "1"` be written down to avoid breakage in 2021.
* [X] We need to default to `resolver = "2"` if not otherwise specified in the 2021 edition.
* [X] Workspaces may need an `edition = "..."` specifier.
* [X] Documentation for the edition will need to be prepared about this change in Cargo, probably referencing the newly-rewritten features chapter.

### PR DESCRIPTION
**Pull request by ehuss**
This adds a small report if using `cargo fix --edition` to transition from 2018 to 2021 to determine if the new resolver will result in different features.

There is a gauntlet of checks that must pass before it even tries to show the differences:
* If the resolver is already specified, skip.
* If in a virtual workspace, skip (no way to specify global edition).
* If not migrating the root package, skip. The edition only changes the resolver in the root package.
* If not migrating all targets, skip. It's uncertain if the user intends to set the package edition or not.

Closes #9048

### CODE REVIEW

**Comment by ehuss** [comment]
Overall I'm not too happy with this. The code seems a little awkward, though I can't say specifically why. 

I am a little concerned that it is unreliable. Another concern is that the new resolver depends on many factors (the target, the `--features` flags used, and whether or not dev-dependencies are used). This report only captures a small snapshot of that (whatever settings the user provided to `cargo fix`).

Also, this doesn't actually run the final verification step with the new resolver. That will require significant changes to `cargo fix`, which I'm not sure how feasible that is.

I wanted to open this up for discussion to see if this is the direction we should go.

File: src/cargo/ops/fix.rs [hunk 1]
```diff
@@ -193,6 +200,114 @@ fn check_version_control(config: &Config, opts: &FixOptions) -> CargoResult<()>
...
+    // 2018 without `resolver` set must be V1
+    assert_eq!(ws.resolve_behavior(), ResolveBehavior::V1);
+    let specs = opts.compile_opts.spec.to_package_id_specs(ws)?;
+    let resolve_opts = ResolveOpts::new(
+        /*dev_deps*/ true,
+        RequestedFeatures::from_command_line(
+            &opts.compile_opts.features,
+            opts.compile_opts.all_features,
+            !opts.compile_opts.no_default_features,
+        ),
```
Comment (alexcrichton) [inline src/cargo/ops/fix.rs:242]: Drive-by comment not related to your PR, but this seems like it's ripe for a `opts.copmile_opts.requested_features()` method

**Review by alexcrichton — COMMENTED** [review]
This looks good to me, personally. Given the context of this, migrating between editions, I'd expect the code to be lossy, a bit odd, and possibly very specific to some situations. Also I would not expect 100% correctness guarantees from this code (just no false positive warnings).

I view the `cargo fix --edition` warnings as "best effort" where we do what we can for the 90% use case in theory, but there's likely to always be something that slips through the cracks or just isn't worth detecting and warning about.

The only thing I found surprising here was the check for `--all-targets`, was that necessary to reduce the warnings emitted?

**Comment by ehuss** [comment]
> The only thing I found surprising here was the check for `--all-targets`, was that necessary to reduce the warnings emitted?

My thinking was that if you run `cargo fix --edition --bin foo` to incrementally migrate a package, you're intending to set `edition` on the bin target.  I can probably remove that check, since I think that is a highly unlikely use case, and probably doesn't hurt to report differences.

**Comment by alexcrichton** [comment]
Want to go ahead and land this? We can presumably in the near-ish future try testing out `cargo fix --edition` for existing projects to see how it goes?

**Comment by ehuss** [comment]
Yea, I think it's ok to go.  It can always be tweaked or removed.  Hopefully we'll get enough people to test it before 2021 is stable.  I'll assume that was an approval.

@bors r=alexcrichton
