### PR TITLE
fix(resolver): Report invalid index entries 

### LINKED ISSUE #10623: cargo <1.60 failed to select a version of a dependency due to either `?` (weak) or `dep:` (namespaced) features
### Problem

I did a `cargo update` and my CI broke when verifying MSRV. 
```console
error: failed to select a version for the requirement `libgit2-sys = "^0.13.3"`
candidate versions found which didn't match: 0.13.2+1.4.2, 0.13.1+1.4.2, 0.13.0+1.4.1, ...
location searched: crates.io index
required by package `git2 v0.14.3`
    ... which satisfies dependency `git2 = "^0.14"` (locked to 0.14.3) of package `repor v0.1.0 (/home/epage/src/personal/repro)`
```

- cargo 1.60 works
- cargo 1.59 doesn't work

The error being from the resolver and being cargo-version specific is why I am posting here rather than on the git2 repo.

### Steps

```console
$ git clone git@github.com:crate-ci/committed.git
cd committed
cargo +1.59.0 check
cargo +1.60.0 update
cargo +1.59.0 check
```

### Possible Solution(s)

Track parse bad candidates when resolving and report them to the user if they are relevant

### Notes

Old cargo cannot see crates in the registry that use [weak or namespaced features](https://rust-lang.github.io/rfcs/3143-cargo-weak-namespaced-features.html) (or similar new index data).

### Version

```text
cargo 1.60.0 (d1fd9fe 2022-03-01)
release: 1.60.0
commit-hash: d1fd9fe2c40a1a56af9132b5c92ab963ac7ae422
commit-date: 2022-03-01
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Linux Mint 20.3 (una) [64-bit]
```

### LINKED ISSUE #14894: Index parsing errors are swallowed
### Problem

When using a private registry, I recently ran into a case where a crate version that _is_ in the index (confirmed by cURLing the registry directly) could not be resolved by Cargo, giving me an error like
```
error: no matching package named `something` found
location searched: `private-registry` index
```

I quickly suspected that the index entry was invalid somehow, but Cargo gave no errors or warnings, even with `CARGO_LOG=trace`. Furthermore, by tweaking `http_remote.rs`, I found that its query to the registry (with an `if-none-match` header) returned `NotModified`, indicating Cargo _did_ have the etag of the latest index file, which did include the crate/version in question. By removing the etag header, I also confirmed that the contents Cargo got from its request contained the version in question.

Long story short, I discovered that Cargo ends up swallowing errors related to invalid index entries. The first time Cargo downloads an index file with an invalid entry, it hits

https://github.com/rust-lang/cargo/blob/05f54fdc34310f458033af8a63ce1d699fae8bf6/src/cargo/core/summary.rs#L345-L348

However, that gets turned into a `tracing::info` in

https://github.com/rust-lang/cargo/blob/05f54fdc34310f458033af8a63ce1d699fae8bf6/src/cargo/sources/registry/index/mod.rs#L604-L619

The user is likely to miss this since Cargo tracing logs are off by default, so they will just observe that Cargo claims the version doesn't exist.

Unfortunately, the issue doesn't stop there. If the user _then_ tries to run with `CARGO_LOG=trace`, they will then see _no_ errors or warnings from Cargo. In fact, the logs will make it seem like the invalid entry doesn't exist at all. There will be no trace of it anywhere. This is because when Cargo parses an index entry, it caches the parsed lines so that it doesn't have to parse them again

https://github.com/rust-lang/cargo/blob/05f54fdc34310f458033af8a63ce1d699fae8bf6/src/cargo/sources/registry/index/mod.rs#L622

+

https://github.com/rust-lang/cargo/blob/05f54fdc34310f458033af8a63ce1d699fae8bf6/src/cargo/sources/registry/index/mod.rs#L627-L631

However, when a line can't be parsed, it doesn't cache that line (note the `continue` where the error gets turned into `tracing::info!`). It _also_ doesn't leave that line as "unparsed" somewhere. So on subsequent invocations, Cargo grabs the version list from the cache manager to avoid parsing lines again, doesn't observe the (invalid) index entry for the version in question so it doesn't warn, then downloads the file again because it doesn't find the requested version, that download yields and empty response because the etag _does_ match the latest index file, and so Cargo gives up.

So, two requests:

1. Cargo should be louder when it finds an invalid index entry.
2. Cargo should repeat the warning about an invalid index entry even if it's in an up-to-date cached version of the index file.

### Steps

1. Inject a new version with an invalid index entry into a registry.
2. Take a dependency on said version.
3. Run `cargo build`.
4. Observe that Cargo only says "version not found" with no further warnings.
5. Re-run `cargo build` with `CARGO_LOG=trace`.
6. Observe that there is no information in the logs about the invalid index entry which caused the version not to be found.

### Possible Solution(s)

_No response_

### Notes

In my case, the index entry parsing error I was eventually able to extract by disabling the `if-none-match` logic and then running with `CARGO_LOG=trace` was:

```
failed to parse "so/me/something" registry package: optional dependency `uom_0_35` is not included in any feature
Make sure that `dep:uom_0_35` is included in one of features in the [features] table.
```

I _suspect_, but am not quite sure, that this may be an erroneous index entry manipulation by the private registry provider we're using. Although it could also be that `cargo publish` allowed publishing something with a nonsensical optional dependency in the first place?

### Version

```text
cargo 1.85.0 (05f54fdc3 2024-12-03)
```

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

While #14897 reported packages with an unsupported index schema version,
that only worked if the changes in the schema version did not cause
errors in deserializing `IndexPackage` or in generating a `Summary`.

This extends that change by recoverying on error with a more lax,
incomplete parse of `IndexPackage` which should always generate a valid
`Summary`.

To help with a buggy Index, we also will report as many as we can.
This does not provide a way to report to users or log on cache reads if
the index entry is not at least `{"name": "<string>", "vers": "<semver>"}`.

Fixes #10623
Fixes #14894

### How should we test and review this PR?

My biggest paranoia is some bad interaction with the index cache including more "invalid" index entries.
That should be ok as we will ignore the invalid entry in the cache when
loading it.
Ignoring of invalid entries dates back to #6880 when the index cache was
introduced.

### CODE REVIEW

**Review by weihanglo — APPROVED** [review]
This is nice! Thank you.

File: tests/testsuite/registry.rs [hunk 1]
```diff
@@ -2940,6 +2942,103 @@ fn ignore_invalid_json_lines() {
...
+required by package `a v0.5.0 ([ROOT]/foo)`
+
+"#]])
+        .run();
+    p.cargo("generate-lockfile")
+        .with_status(101)
+        .with_stderr_data(str![[r#"
+[UPDATING] `dummy-registry` index
+[ERROR] failed to select a version for the requirement `foo = "^0.1.1"`
+  version 0.1.3 requires cargo 1.2345
```
Comment (weihanglo) [inline tests/testsuite/registry.rs:3030]: I wish we could perhaps have a log on disk recording all this internal error

**Review by weihanglo — APPROVED** [review]
