### PR TITLE
Periodically gc repos in Cargo

### LINKED ISSUE #4403: Cargo publish fails with 'Too many open files'
While trying to publish a crate to a local instance of crates.io, cargo fails with a 'Too many open files' error while creating its lock file:

```
$ cargo publish --host http://localhost:8888/git/index
    Updating registry `http://localhost:8888/git/index`
warning: spurious network error (2 tries remaining): [2/-1] failed to create locked file '/home/lperson/.cargo/registry/index/localhost-4f8d9a62b31a03f2/.git/objects/pack/pack_git2_Xiidx.lock': Too many open files
warning: spurious network error (1 tries remaining): [2/-1] failed to create locked file '/home/lperson/.cargo/registry/index/localhost-4f8d9a62b31a03f2/.git/objects/pack/pack_git2_Aoidx.lock': Too many open files
error: failed to update registry http://localhost:8888/git/index

Caused by:
  failed to fetch `http://localhost:8888/git/index`

Caused by:
  [2/-1] failed to create locked file '/home/lperson/.cargo/registry/index/localhost-4f8d9a62b31a03f2/.git/objects/pack/pack_git2_PPidx.lock': Too many open files
```

To put things into context, I have approximatively a thousand version of a single crate published in my local registry (maybe not a *legit* use-case per se, but I still think the problem is worth an issue).
By running the program with `strace`, we can see that cargo tries to open every git pack file in the registry:

```
open("/home/lperson/.cargo/registry/index/localhost-4f8d9a62b31a03f2/.git/objects/pack/pack-280d79e0d7e028bbd92b132a35b6aa2d5d862c91.pack", O_RDONLY) = 1022
```

One working wordaround is updating the file descriptor limit with `ulimit` to more than 1024.

I'm not familiar enough with cargo to know why it would need to have all these git pack files open at the same time. Is this an expected behaviour of cargo ? Would this happen with 1 published version for 1000 crates ?

Complete `strace -e open,close -f`'d cargo log:
https://gist.github.com/kureuil/989b1f4c6d283384c8b70fdd1ddf2e87

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit is targeted at improving the long-term management of git checkouts
and git repositories. Currently every time data is fetched from crates.io
libgit2 will create a new pack file in the repository. These pack files
accumulate over time and end up causing pathological behavior if there's lots of
them, causing libgit2 to open many file descriptors all at once, possibly
blowing the system's file descriptor limits.

To alleviate this problem you typically run `git gc`, but libgit2 doesn't have
this implemented. Instead what Cargo now does is detect this situation and run
literally the command line tool `git gc` in a best-effort attempt to compact the
repo. Failing that, for example when git isn't installed, Cargo will remove the
entire repo and do a full checkout again.

At the same time this commit also generalizes this logic, plus the existing fast
path github logic, to all git repositories and not just the index. That way all
git repositories can benefit from the "github fast path" as well as the
compaction steps.

Closes #4403

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @Mark-Simulacrum

File: src/cargo/sources/git/utils.rs [hunk 1]
```diff
@@ -557,29 +558,158 @@ fn with_authentication<T, F>(url: &str, cfg: &git2::Config, mut f: F)
...
+            return Ok(())
+        }
+    };
+    if entries < 100 {
+        debug!("skipping gc as there's only {} pack files", entries);
+        return Ok(())
+    }
+
+    // First up, try a literal `git gc` by shelling out to git. This is pretty
+    // likely to fail though as we may not have `git` installed. Note that
```
Comment (Mark-Simulacrum) [inline src/cargo/sources/git/utils.rs]: I'd imagine this isn't so "likely to fail"? In general, it seems like a valid assumption that most cargo installations will also happen to have git as well.

File: src/cargo/sources/git/utils.rs [hunk 2]
```diff
@@ -557,29 +558,158 @@ fn with_authentication<T, F>(url: &str, cfg: &git2::Config, mut f: F)
...
+            debug!("attempting github fast path for {}", url);
+            if github_up_to_date(&mut handle, url, &oid) {
+                return Ok(())
+            } else {
+                debug!("fast path failed, falling back to a git fetch");
+            }
+        }
+    }
+
+    // We reuse repositories quite a lot, so before we go through and update the
```
Comment (matklad) [inline src/cargo/sources/git/utils.rs]: Just to make sure we are on the same page, it's only the index repository which is frequently reused, because the crate repositories from git dependencies are write once?

File: src/cargo/sources/git/utils.rs [hunk 3]
```diff
@@ -557,29 +558,158 @@ fn with_authentication<T, F>(url: &str, cfg: &git2::Config, mut f: F)
...
+                return Ok(())
+            }
+        }
+        Err(e) => debug!("git-gc failed to spawn: {}", e),
+    }
+
+    // Alright all else failed, let's start over
+    if repo.is_bare() {
+        let path = repo.path().to_path_buf();
+        drop(fs::remove_dir_all(&path));
```
Comment (matklad) [inline src/cargo/sources/git/utils.rs]: Hm, are there any race conditions here? Would this fast path work: https://github.com/rust-lang/cargo/blob/053b634cd2c85a18b7b2568ef0056d649112a9e0/src/cargo/sources/registry/remote.rs#L58 ?

**Comment by matklad** [comment]
One thing that bothers me is that this is a code path that is executed rarely, and is untested, which sounds like a recite for mysterious bug reports. Perhaps we should try to write a test for this somehow? We can specify a lower gc threshold for test via env var, for example.

File: src/cargo/sources/git/utils.rs (hunk 2 above)
Comment (matklad) [reply src/cargo/sources/git/utils.rs]: Hm, yeah, this part bother me:

>At the same time this commit also generalizes this logic, plus the existing fast
path github logic, to all git repositories and not just the index. That way all
git repositories can benefit from the "github fast path" as well as the
compaction steps.

I was under the impression that this is relevant only for index?

File: src/cargo/sources/git/utils.rs (hunk 1 above)
Comment (alexcrichton) [reply src/cargo/sources/git/utils.rs]: In general we try to get Cargo working without git, so I'd just want to make sure that if you don't have `git` installed that there's at least *some* fallback

File: src/cargo/sources/git/utils.rs (hunk 2 above)
Comment (alexcrichton) [reply src/cargo/sources/git/utils.rs]: I think the databases for git repos otherwise are updated quite a lot, but yes it's mainly the index and checkouts of git deps should be write-once.

Comment (alexcrichton) [reply src/cargo/sources/git/utils.rs]: Oh but other repos on github will also benefit from the fast path "don't use git if we have an up-to-date copy" for cases where you don't have a `Cargo.lock` or you're running `cargo update`. The benefit is surely much more marginal, though.

File: src/cargo/sources/git/utils.rs (hunk 3 above)
Comment (alexcrichton) [reply src/cargo/sources/git/utils.rs]: Yeah that's a good point, I'll investigate.

**Comment by alexcrichton** [comment]
Yeah I was synthetically testing this locally, I'll see if I can work up a test.

**Comment by alexcrichton** [comment]
Ok I believe that comments should all be addressed
