### PR TITLE
fix(package): exclude target/package from backups

### LINKED ISSUE #16238: CACHEDIR.TAG not created for target directory with `cargo package` or `cargo publish`
### Problem

The `target` directory is not excluded from backups when created with `cargo package` or `cargo publish`.

### Steps

1. `cargo new foo`
2. `cd foo`
3. `cargo package --allow-dirty`
4. `ls -al target`

### Possible Solution(s)

There's probably a call to `create_dir_all` somewhere that is creating the `target/package` directory without using the normal "create target dir" logic that excludes it from backups.

### Notes

_No response_

### Version

```text
cargo 1.93.0-nightly (445fe4a68 2025-11-07)
release: 1.93.0-nightly
commit-hash: 445fe4a68f469bf936b2fd81de2c503b233a7f4f
commit-date: 2025-11-07
host: aarch64-apple-darwin
libgit2: 1.9.1 (sys:0.20.2 vendored)
libcurl: 8.7.1 (sys:0.4.83+curl-8.15.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 3.5.4 30 Sep 2025
os: Mac OS 15.6.1 [64-bit]
```

### PR DESCRIPTION
**Pull request by SepehrGanji**
### What does this PR try to resolve?

  The target directory is not excluded from backups when created with
  `cargo package` or `cargo publish`. This causes the `target/package`
  directory to be included in Time Machine backups on macOS and other
  backup systems that respect CACHEDIR.TAG files.

  The issue occurs because when `Filesystem::open()` creates parent
  directories in `src/cargo/util/flock.rs:336`, it uses
  `paths::create_dir_all()` instead of the backup-excluding version,
  bypassing the normal target directory creation logic.

  This commit adds a new `create_dir_with_backup_exclusion()` method to
  `Filesystem` and uses it to ensure the `target/package` directory is
  properly excluded from backups before creating files in it.

  Fixes #16238

  ### How to test and review this PR?

  Run the following:
  cargo new foo
  cd foo
  cargo package --allow-dirty
  ls -al target/package/

  Verify that `CACHEDIR.TAG` now exists in `target/package/`.

  All existing package tests pass.

### CODE REVIEW

File: src/cargo/ops/cargo_package/mod.rs [hunk 1]
```diff
@@ -1128,7 +1130,7 @@ struct TmpRegistry<'a> {
 
 impl<'a> TmpRegistry<'a> {
     fn new(gctx: &'a GlobalContext, root: Filesystem, upstream: SourceId) -> CargoResult<Self> {
-        root.create_dir()?;
+        root.create_dir_with_backup_exclusion()?;
```
Comment (epage) [inline src/cargo/ops/cargo_package/mod.rs]: This is being created one of of the above two and shouldn't need to be called

File: src/cargo/util/flock.rs [hunk 2]
```diff
@@ -211,6 +211,17 @@ impl Filesystem {
...
     }
 
+    /// Creates the directory pointed to by this filesystem, excluding it from backups.
+    ///
+    /// This should be used for target directories and other build artifacts that
+    /// should not be included in backups or Time Machine on macOS.
+    ///
+    /// Handles errors where other Cargo processes are also attempting to
+    /// concurrently create this directory.
+    pub fn create_dir_with_backup_exclusion(&self) -> CargoResult<()> {
```
Comment (epage) [inline src/cargo/util/flock.rs]: Why are we creating a wrapper method rather than just calling `create_dir_all_excluded_from_backups_at` directly like we do in other cases?

File: src/cargo/ops/cargo_package/mod.rs [hunk 3]
```diff
@@ -162,6 +162,7 @@ fn create_package(
 
     let filename = pkg.package_id().tarball_name();
     let dir = ws.build_dir().join("package");
+    dir.create_dir_with_backup_exclusion()?;
```
Comment (epage) [inline src/cargo/ops/cargo_package/mod.rs]: I believe that call should be on `build_dir()` and not `build_dir().join("package")`

File: src/cargo/ops/cargo_package/mod.rs [hunk 4]
```diff
@@ -226,6 +227,7 @@ pub fn package(ws: &Workspace<'_>, opts: &PackageOpts<'_>) -> CargoResult<Vec<Fi
     } else {
         // Uplifting artifacts
         let artifact_dir = target_dir.join("package");
+        artifact_dir.create_dir_with_backup_exclusion()?;
```
Comment (epage) [inline src/cargo/ops/cargo_package/mod.rs]: I believe that call should be on `target_dir` and not `target_dir.join("package")`

**Comment by epage** [comment]
Should we have automated tests for this?

Note that our contrib guide normally recommends creating a passing test in a commit before the fix, showing the old behavior.  Then the commit with the fix updates the test so it still passes, showing the new behavior.  Then the diff will show how the behavior changed.

**Comment by epage** [comment]
Looks like this needs `cargo fmt` run.  As a warning, force pushes don't always generate notifications, so be sure to post here when you do it so we know it is ready to merge.

**Comment by SepehrGanji** [comment]
> Looks like this needs `cargo fmt` run. As a warning, force pushes don't always generate notifications, so be sure to post here when you do it so we know it is ready to merge.

Thanks for all your help! I have did the `cargo fmt`, could you please take a look?

File: tests/testsuite/package.rs [hunk 5]
```diff
@@ -7807,3 +7807,33 @@ fn publish_to_alt_registry_warns() {
 "#]])
         .run();
 }
+
+#[cargo_test]
+fn package_dir_not_excluded_from_backups() {
+    // This test documents the current behavior where target directory is NOT excluded from backups.
+    // After the fix, this test will be updated to verify that CACHEDIR.TAG exists.
+    let p = project()
+        .file("src/main.rs", r#"fn main() { println!("hello"); }"#)
```
Comment (weihanglo) [inline tests/testsuite/package.rs]: nit: for faster test execution (avoid to binary linking)

```suggestion
        .file("src/lib.rs", "")
```

File: tests/testsuite/package.rs [hunk 6]
```diff
@@ -7804,3 +7804,38 @@ fn publish_to_alt_registry_warns() {
...
 }
+
+#[cargo_test]
+fn package_dir_not_excluded_from_backups() {
+    // Verify that target directory is excluded from backups by checking for CACHEDIR.TAG
+    let p = project()
+        .file("src/lib.rs", "")
+        .build();
+
+    p.cargo("package --allow-dirty -v")
```
Comment (weihanglo) [inline tests/testsuite/package.rs]: We probably don't need `-v` here, since we just want to check cachedir tag file existing 


You might need to change that , regenerate snapshots, and `cargo fmt`

File: tests/testsuite/package.rs (hunk 5 above)
Comment (SepehrGanji) [reply tests/testsuite/package.rs]: Thanks for the tip! Done.

File: tests/testsuite/package.rs (hunk 6 above)
Comment (SepehrGanji) [reply tests/testsuite/package.rs]: Done.

**Review by weihanglo — APPROVED** [review]
Thanks!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16272/19678fce85a64d0c12f0cb2a4fad0fc485167ed1..b8dc3939b9e38bcbe3cb998053d79f704ea11b42)*
