### PR TITLE
Rebased and fixed 4025: Apply --all if workspace is virtual

### LINKED ISSUE #4021: Imply `--all` argument for virtual manifest.
If I run `cargo build` in a workspace, I often get:

```
error: manifest path `/home/user/projects/fall/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

The fix is to run `cargo build --all` instead. I think Cargo can figure this out automatically? 

If the current package is virtual, and we are running one of `--all` enabled commands, `--all` should be the default.

The fix would involve changing [this logic](https://github.com/rust-lang/cargo/blob/80f19a8e240577d90caf38503bb3034ac7dd630d/src/bin/check.rs#L83-L96) in all relevant commands (there's quite a bit of duplication:( ).

### PR DESCRIPTION
**Pull request by debris**
- fixes #4021
- rebased #4025
- fixed issue issue described by @matklad in https://github.com/rust-lang/cargo/pull/4025#pullrequestreview-40660570
- added test `build_virtual_manifest_one_project` which covers the fix

### CODE REVIEW

File: tests/build.rs [hunk 1]
```diff
@@ -3039,6 +3039,74 @@ fn build_all_virtual_manifest() {
...
+        .file("bar/Cargo.toml", r#"
+            [project]
+            name = "bar"
+            version = "0.1.0"
+        "#)
+        .file("bar/src/lib.rs", r#"
+            pub fn bar() {}
+        "#);
+
+    // The order in which foo and bar are built is not guaranteed
```
Comment (matklad) [inline tests/build.rs]: The comment is a bit misleading, because we don' compile `bar` at all :)

File: tests/build.rs [hunk 2]
```diff
@@ -3039,6 +3039,74 @@ fn build_all_virtual_manifest() {
...
+    assert_that(p.cargo_process("build")
+                 .arg("-p").arg("foo"),
+                execs().with_status(0)
+                       .with_stderr_does_not_contain("[..] Compiling bar v0.1.0 ([..])")
```
Comment (matklad) [inline tests/build.rs]: Let's change this to `.with_stderr_does_not_contain("bar")` just to make this more robust in case we change the precise output format in the future.

File: tests/build.rs (hunk 1 above)
Comment (debris) [inline tests/build.rs]: fixed

**Comment by matklad** [comment]
Looks great now, thanks @debris and @rsertelon!

@bors r+
