### PR TITLE
fix(new): Print a note, rather than a comment, for more information

### LINKED ISSUE #12210: `cargo init` add option to remove default comment
### Problem

While initializing a new project using `cargo init`, a comment is automatically inserted at the top of the `Cargo.toml` file:

`# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html`

Although this is undoubtedly a helpful resource for newcomers and those unfamiliar with Cargo, for seasoned Rust developers this is not necessary and it adds an additional manual step of removing it every time a new project is initialized. Especially for developers working with automated systems or setting up multiple projects, the comment can be slightly annoying.

### Proposed Solution

I propose adding an option to the `cargo init` command, let's say `--no-comment`, that when used will not include the standard commented URL at the top of the `Cargo.toml` file. The command would look like this:

`cargo init --no-comment`

By providing this option, developers have the flexibility to opt-in or opt-out of having the comment in their `Cargo.toml` file as per their requirements or preferences. It wouldn't impact beginners as the default behavior would still be to include the comment, unless explicitly opted out using the `--no-comment` flag.

### Notes

I believe this minor enhancement would improve the developer experience by reducing manual interventions, particularly for those creating a large number of Rust projects or using automated tools to initialize Rust projects. This change should not affect the functionality of `cargo init`, and it would be backward compatible since it just introduces a new optional flag.

Please consider this request and let me know if you need any additional information. I am willing to try to implement it. Thanks!

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

For myself, I find it frustrating when tools add boilerplate that I have to remove after every use.  A `note:` on the command-line is more ephemeral, helping people who need it while not interfering with those that don't.

Fixes #12210

### CODE REVIEW

File: tests/testsuite/workspaces.rs [hunk 1]
```diff
@@ -1074,6 +1077,7 @@ fn new_warning_with_corrupt_ws() {
         .with_stderr(
             "\
 [CREATING] binary (application) `bar` package
+[NOTE] see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
```
Comment (weihanglo) [inline tests/testsuite/workspaces.rs:1080]: Could this be printed only when Cargo succeeds to create a new package?

Comment (epage) [reply tests/testsuite/workspaces.rs:1080]: In this case it does succeed, its just warning about the state of the workspace.

But I can move it later in case a spurious error happens through the process.

**Review by weihanglo — APPROVED** [review]

**Comment by weihanglo** [comment]
Though I still think the comment is helpful, I am under the impression that we're on the way towards #5151 and avoid adding more comments or Rust files for `cargo new`. 

Hence @bors r+
