### PR TITLE
Be more conservative about which files are linked to the output dir.

### LINKED ISSUE #5444: Race condition when trying to compile a lib multiple times for different purposes.
As part of #5384 I created some circumstances where the same lib may be built concurrently with different settings.  I thought this would be safe since they have different hashes in the filename, but I neglected to address this case when the library is hardlinked.  There is a race condition in `hardlink_or_copy` where one compilation will stomp on another via the hardlink.

<details><summary>Details for the curious.</summary>
<ol>
<li> One compilation creates a hardlink.
<li> The other compilation fails to create a hardlink with EEXIST.
<li> 2nd compilation copies its lib into the existing hardlink, modifying the first one's contents.
</ol>
</details>

<p>

This can happen in a variety of situations (mainly with `panic`), but here is a small repro:
```
cargo new --lib stomp
cd stomp
cat >> Cargo.toml <<EOL
[profile.dev]
panic = "abort"
EOL
cat > src/main.rs <<EOL
extern crate stomp;
fn main() {}
EOL

# This will fail some of the time on some platforms with wrong panic strategy.
# Note: This requires #5384.  Earlier versions would fail 100% of the time.
# This attempts to build `lib.rs` twice at the same time, once with `panic` 
# and once without (for tests).
cargo build --all-targets -v
```

I'm trying to think of a fix, but I haven't come up with anything, yet.  Generally I'm thinking that these "non-panic" dependencies should not be hard linked at all, but there's no obvious way to detect when a `Unit` is one of these.  We could add a flag to `Unit` to detect this scenario, but that would require adding some extra de-duplication logic and generally seems a little too complex.

I don't think it is worth it to try to fix the race condition itself since that is very tricky, and would end up with a random lib in the output directory anyway.

I'll keep trying to think of a solution, but if anyone has any thoughts I'd be happy to hear.

### PR DESCRIPTION
**Pull request by ehuss**
This changes it so that only top-level targets requested on the command-line will be included in the output directory.  Dependencies are no longer included.

Fixes #5444.

### CODE REVIEW

File: src/cargo/core/compiler/context/compilation_files.rs [hunk 1]
```diff
@@ -206,9 +210,7 @@ impl<'a, 'cfg: 'a> CompilationFiles<'a, 'cfg> {
         // we don't want to link it up.
         if out_dir.ends_with("deps") {
             // Don't lift up library dependencies
-            if self.ws.members().find(|&p| p == unit.pkg).is_none() && !unit.target.is_bin() {
-                None
-            } else {
+            if self.roots.contains(unit) {
```
Comment (alexcrichton) [inline src/cargo/core/compiler/context/compilation_files.rs]: I think this is a *little* suspect in the sense that this is pretty carefully crafted and I'm wary to switch wholesale to `roots`. Could we perhaps start off by basically skipping any rlib units? That is, we only care about binaries in the main workspace, mostly (and dylib/staticlib/cdylib/etc)

**Comment by ehuss** [comment]
> Let's hold this off until the beta is branched perhaps?

If we delay, we should probably temporarily disable the two `_build_all_targets` tests I added to avoid spurious CI errors.

**Comment by alexcrichton** [comment]
I think this is fixing active regressions, though, right? In that sense we may not want to delay it?

**Comment by ehuss** [comment]
> I think this is fixing active regressions, though, right?

Not exactly.  `cargo build --all-targets` with a `panic` profile didn't work at all in previous versions.  The only other way I can think of to trigger the race condition is to use the new `build-override` profile with a shared dependency in a workspace.

**Comment by alexcrichton** [comment]
Ah ok makes sense! Then yeah it's probably good to hold off until next week to merget (but we can sort out in the meantime)

File: src/cargo/core/compiler/context/compilation_files.rs (hunk 1 above)
Comment (ehuss) [reply src/cargo/core/compiler/context/compilation_files.rs]: We can do that, though I felt like that would be a bigger change.  It would still leave behind the race condition for the other output types (particularly `rmeta` files, though they don't cause catastrophic failures).  

I made an experimental branch to try this here:  https://github.com/ehuss/cargo/commit/68e7d2e9233b842740a9fc09c18df715f7aaff93
It seems more risky to me, though.

It seems like a pretty heavy change just to avoid these non-panic dependencies.  I'm still trying to think if there's an easier way...

Comment (alexcrichton) [reply src/cargo/core/compiler/context/compilation_files.rs]: Hm ok yeah it's definitely not worth this becoming a larger change. 

So today the logic for "should I hardlink this up" is basically "am I a workspace member or am I a binary". That encompasses far too much as workspace member rlibs/rmeta have no business being linked up.

So this is instead saying that "if you were originally requested you're linked up". That includes libraries and rmeta business but you can't request more than one (even though we may compile many), so we should be resolving the race this way.

Writing this all down, I *think* the only difference is that all other workspace members aren't automatically linked up. I don't think, however, that it was possible for a workspace member to generate a relevant binary/staticlib for us to link upwards.

Or well, in other words, I think that this *should* be correct. I can't think of a way in which it would be wrong at least! In light of that I think we should be good to merge as soon as beta is branched.

Comment (matklad) [reply src/cargo/core/compiler/context/compilation_files.rs]: I think what *might* go wrong are dynamic libraries. We add top target directory to `LD_LIBRARY_PATH`:

https://github.com/rust-lang/cargo/blob/6cd841fe4a55d21d8f9a74102e86acb9475d45da/src/cargo/core/compiler/compilation.rs#L154-L155

However, in the next line we add the `deps` dir as well, so we should be fine here as well!

File: src/cargo/core/compiler/context/compilation_files.rs [hunk 2]
```diff
@@ -109,9 +114,8 @@ impl<'a, 'cfg: 'a> CompilationFiles<'a, 'cfg> {
     }
 
     pub fn export_dir(&self, unit: &Unit<'a>) -> Option<PathBuf> {
-        let &(ref dir, ref roots) = self.export_dir.as_ref()?;
-        if roots.contains(unit) {
-            Some(dir.clone())
+        if self.roots.contains(unit) {
```
[the remark this answers is not in the document]
Comment (ehuss) [reply src/cargo/core/compiler/context/compilation_files.rs]: That sounds correct, I have removed it.

**Comment by ehuss** [comment]
I've been trying to think of a less risky way to implement this, but I haven't been able to come up with anything good.   Let me know if I should try something else.  Unfortunately I'm not familiar with the use cases where a crate would depend on a cdylib/staticlib, so I'm not clear if/how it might be a problem.
