### PR TITLE
fix(add): Don't select yanked versions when normalizing names

### LINKED ISSUE #14893: Unexpected failure in `cargo add` when mistyping "-" as "_" for packages with yanked versions
### Problem

Cargo has a feature that corrects mistyped hyphens and underscores, which are easy to get confused.

Both `cargo add utf8-parser` and `cargo add utf8_parser` will work as expected and pull the latest version of `utf8-parser` - that's great

However, I am experiencing some inconsistent behavior with `owo-colors`, whose latest release is a *yanked* 5.0.0

Running `cargo add owo-colors` produces:

```
avsdf $ cargo add owo-colors
    Updating crates.io index
      Adding owo-colors v4.1.0 to dependencies
             Features:
             - alloc
             - supports-color
             - supports-colors
    Updating crates.io index
     Locking 1 package to latest compatible version
      Adding owo-colors v4.1.0
```

This adds the latest non-yanked version of owo-colors, which is v4.1.0. Great!

However, when I run `cargo add owo_colors`:

```
avsdf $ cargo add owo_colors
    Updating crates.io index
warning: translating `owo_colors` to `owo-colors`
error: the crate `owo-colors@5.0.0` could not be found in registry index.
```

So it seems with the mistype, it tries to add the latest version, but the latest version is yanked.

For posterity, here is a screen shot of the current state of `owo-colors` versions:
Image

**Expected Behavior**: `cargo add owo_colors` and `cargo add owo-colors` have the same behavior
**Actual Behavior**:`cargo add owo_colors` fails while `cargo add owo-colors` does not

### Steps

0. `rustup update && rustup default nightly`
1. `cargo new avsdf`
2. `cd avsdf`
3. `cargo add owo_colors`

The last command will fail with `error: the crate 'owo-colors@5.0.0' could not be found in registry index`

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
cargo 1.85.0-nightly (05f54fdc3 2024-12-03)
```

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

Fixes #14893

In writing a test for this, I had a hard time finding the other tests as they mixed 
- Having an `add_` prefix
- Calling this fuzzy vs normalized

So I made the test names consistent

### CODE REVIEW

File: src/cargo/sources/registry/mod.rs [hunk 1]
```diff
@@ -856,7 +856,13 @@ impl<'gctx> Source for RegistrySource<'gctx> {
                     }
                     any_pending |= self
                         .index
-                        .query_inner(name_permutation, &req, &mut *self.ops, f)?
+                        .query_inner(name_permutation, &req, &mut *self.ops, &mut |s| {
+                            if !s.is_yanked() {
+                                f(s);
+                            } else if kind == QueryKind::Alternatives {
+                                f(s);
+                            }
```
Comment (weihanglo) [inline src/cargo/sources/registry/mod.rs:864]: I know at this moment `Alternatives` is for resolve to give a better suggestion, and `Normalized` is for `cargo add` to auto-normalize stuff. However, it is not clear why `Alternatives` deserves a special case here. To maximize the possibility to find an alternative to suggest?

Comment (weihanglo) [reply src/cargo/sources/registry/mod.rs:864]: Talked offline. This is more a path toward a bigger overhual. Since the change is small and well-understood, resolve this thread.

**Review by weihanglo — APPROVED** [review]
