### PR TITLE
reset lockfile information between resolutions

### LINKED ISSUE #8249: "cargo build" fails to select version for new dependency on first run
**Problem**
On the first run, cargo fails to select a version. on any following run it succeeds.
```
    Updating crates.io index
error: failed to select a version for `openblas-src`.
    ... required by package `blas-src v0.2.1`
    ... which is depended on by `ndarray v0.13.1`
    ... which is depended on by `ndarray-linalg v0.12.0`
    ... which is depended on by `verbug v0.1.0 (/tmp/verbug)`
versions that meet the requirements `^0.6` are: 0.6.1, 0.6.0

the package `openblas-src` links to the native library `openblas`, but it conflicts with a previous package which links to `openblas` as well:
package `openblas-src v0.9.0`
    ... which is depended on by `verbug v0.1.0 (/tmp/verbug)`

failed to select a version for `openblas-src` which could resolve this conflict
```

**Steps**
1. clone https://github.com/M1cha/rust-verbug
2. `cargo build` - this will fail
3. `cargo build` - this will succeed

if you want to create your own project:
1. create a new (binary) project
2. add these dependencies:
```
blas-src = { version = "*", features = ["openblas"] }
openblas-src = { version = "*", features = ["static"] }
```
3. `cargo build`
4. add this dependency: `ndarray-linalg = "0.12"`
5. `cargo build` - this will fail
6. `cargo build` - this will succeed

**Notes**
You don't have to actually finish building. the part where cargo regenerates `Cargo.lock` is important. (building openblas takes a long time)

Output of `cargo version`:
cargo 1.43.0 (2cbe9048e 2020-05-03), installed using rustup.

### PR DESCRIPTION
**Pull request by Eh2406**
#8249 pointed out that some kind of lockfile data was leaking between calls to the resolver. @ehuss made a reproducing test case. This PR resets the `LockedMap` data structure when calling `register_previous_locks`.

lets see if CI likes it.
fix #8249

### CODE REVIEW

File: src/cargo/core/registry.rs [hunk 1]
```diff
@@ -91,16 +91,13 @@ pub struct PackageRegistry<'cfg> {
...
-        // This next level is keyed by the name of the package...
-        String,
-        // ... and the value here is a list of tuples. The first element of each
-        // tuple is a package which has the source/name used to get to this
-        // point. The second element of each tuple is the list of locked
-        // dependencies that the first element has.
-        Vec<(PackageId, Vec<PackageId>)>,
-    >,
+    // The next level is keyed by the name of the package...
+    (SourceId, InternedString),
```
Comment (alexcrichton) [inline src/cargo/core/registry.rs:95]: This is just a small refactoring, right, not required for this change to be correct?

(ok either way, just wanted to confirm)

Comment (Eh2406) [reply src/cargo/core/registry.rs:95]: Yes, I did some refactorings to make debugging easier. This one felt worth keeping.

**Comment by ehuss** [comment]
I think this makes sense.  Can you tell me if my summary is correct?

In the test, it builds a Cargo.lock (`generate-lockfile`). The test then adds a new dependency, and Cargo then:

1. Loads Cargo.lock
2. Resolves workspace:
    2a. Locks things in PackageRegistry
    2b. Runs resolver  (update due to new dependency)
    2c. Writes new Cargo.lock
3. Build feature-specific resolver:
    3a. Locks things in PackageRegistry (again!)
    3b. Runs resolver with features selected on the command-line

The issue is that the locked entries in PackageRegistry from step 2a are no longer correct because step 2b updated the dependency graph. In step 3a, it is starting with stale entries.  The solution is in step 3a to clear PackageRegistry first.

Does that sound correct?  If so, I'm surprised this hasn't been a problem in the past.  `PackageRegistry` is one of the things that I struggle to understand.

**Comment by Eh2406** [comment]
> mind explaining a bit why this call is necessary?

I can try, it is not clear which layers of abstraction the explanation is best in. So it may take some back and forth.

[`register_previous_locks`](https://github.com/rust-lang/cargo/blob/61e592788c06b1213e1f71b41fc298b352101b29/src/cargo/ops/resolve.rs#L594) takes a previous resolution or lockfile and builds a [`LockedMap` by calling `register_lock`](https://github.com/rust-lang/cargo/blob/61e592788c06b1213e1f71b41fc298b352101b29/src/cargo/core/registry.rs#L204). 
- Note 1, that the package is added to the end of the list in `register_lock`.
- Note 2, before this PR the `LockedMap` was append only.

The `LockedMap` is read in 2 places [here](https://github.com/rust-lang/cargo/blob/61e592788c06b1213e1f71b41fc298b352101b29/src/cargo/core/registry.rs#L641-L643) and [here](https://github.com/rust-lang/cargo/blob/61e592788c06b1213e1f71b41fc298b352101b29/src/cargo/core/registry.rs#L730-L732).

- Note 3. in both `.iter().find(` is used get the first thing that matches.

Ok now we can step thru the bug, at this level of abstraction.

- The original lock file is read. The only thing in it is Foo has no dependencies. 
- The first [run of the resolver](https://github.com/rust-lang/cargo/blob/61e592788c06b1213e1f71b41fc298b352101b29/src/cargo/ops/resolve.rs#L91) looks at this `LockedMap` and figures out that it is outdated. (How? Different level of abstraction.) And builds the correct resolution, the same one as gened without a lockfile or with the full lockfile.
- The second [call to the resolver](https://github.com/rust-lang/cargo/blob/61e592788c06b1213e1f71b41fc298b352101b29/src/cargo/ops/resolve.rs#L118) calls `register_previous_locks` with the result of the first run.
- This adds a full lock to the *end* of the list for Foo specifying its dependencies. And it adds a full lock for all the transitive deps.
- The second call to the resolver sees an inconsistent `Foo has no dependencies` and locked versions of the dependencies. This looks like a bug at this level of abstraction. It should just use the results from the first run not a mix. (But why did this mix make the resolver fail? Different level of abstraction)

> I'm also interested in how we haven't ever noticed this until now?

IDK. One thing is that it only makes a problem for the first call to cargo after making a change to the dependencies. So it takes some clever debugging to notese it. I would have just bin like "it works now" and moved on with my life. Also the change to the dependencies need to make an inconsistent `LockedMap` that has a visibly different result. I wonder if we have had deps rebuilt on the second run and just not had it reported.

**Comment by Eh2406** [comment]
One of the questions asked yesterday was to follow up on "But why did this mix make the resolver fail?". So I instrumented the [`registry_cache`/`summary_cache`](https://github.com/rust-lang/cargo/blob/1eca786d7f215e0ac8b72844b7018230ae113887/src/cargo/core/resolver/dep_cache.rs#L35-L41), witch caches the results of questions to the registry. I converted that into a test for the resolver and pushed a test. The test shows that the "mix lockfile" as provided to the resolver should not have a resolution.

**Comment by alexcrichton** [comment]
@bors: r+

Ok I've thought about this enough that I'm ok with this. I unfortunately don't have the time right now to really dig deep into this. I can't really answer why this hasn't constantly come up in the past or how we haven't noticed this until now.
