### PR TITLE
fix: fetching non-standard git refspecs on non-github repos

### LINKED ISSUE #16767: cargo cannot use gerrit for git dependencies
### Problem

As per https://rust-lang.zulipchat.com/#narrow/channel/246057-t-cargo/topic/can.E2.80.99t.20use.20dependencies.20from.20gerrit.3F/with/580420299, `cargo` cannot checkout a git repo stored as a gerrit change request. It see

With a dependency like:

```toml
arm-fvp-base-pac = { git = "https://review.trustedfirmware.org/arm-firmware-crates/arm-fvp-base-pac", rev = "refs/changes/45/49345/2", default-features = false, features = [
    "swapped-memory-layout",
] }
```

`cargo` will print:

```console
$ cargo build
error: failed to get `arm-fvp-base-pac` as a dependency of package `armv8-r v0.0.0 (/Users/jonathan/Documents/aarch64-cpu/examples/armv8-r)`

Caused by:
  failed to load source for dependency `arm-fvp-base-pac`

Caused by:
  unable to update https://review.trustedfirmware.org/arm-firmware-crates/arm-fvp-base-pac?rev=refs%2Fchanges%2F45%2F49345%2F2#4b1c2512

Caused by:
  failed to fetch into: /Users/jonathan/.cargo/git/db/arm-fvp-base-pac-bc588fcbfc49ed02

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  unexpected return value from ssl handshake -9836; class=Ssl (16)
```

I have been able to 'trick' cargo into working by removing Cargo.lock, and replacing the dependency with:

```toml
arm-fvp-base-pac = { git = "https://review.trustedfirmware.org/arm-firmware-crates/arm-fvp-base-pac" }
```

Note, no `rev =`, and no `features = ` (because the `main` branch doesn't have that feature). With this dependency it will build, but we're using the wrong version of the library. Now restore the dependency as it was, and it will work! I think this is because the git checkout in `.cargo` now has some information in it that is missing when `rev = "..."` is specified. I don't fully understand why though.

### Steps

```sh
git clone https://github.com/rust-embedded/aarch64-cpu
cd aarch64-cpu
git checkout f868d61fd04e49ae9a5bbcaa024f4a75cc83e4a0
cd examples/armv8-r
cargo build
```

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
cargo 1.95.0-nightly (ce69df6f7 2026-02-12)
```

### PR DESCRIPTION
**Pull request by arlosi**
### What does this PR try to resolve?
Fixes #16767

After a lockfile is created, Cargo will attempt to fetch a git repo using the commit id. Since we only fetch the default refspecs in this case, the commit will be missing. This is not an issue for GitHub repos, since we have a GitHub fast path, and GitHub supports fetching by specific commit.

Fix by keeping track of the reference as written in the manifest, and pass it through to the portion that fetches.

### How to test and review this PR?
First commit shows broken behavior, second commit shows fix.

r? @weihanglo

### CODE REVIEW

File: src/cargo/sources/git/utils.rs [hunk 1]
```diff
@@ -1061,6 +1065,11 @@ pub fn fetch(
                 // The reason we write to `refs/remotes/origin/HEAD` is that it's of special significance
                 // when during `GitReference::resolve()`, but otherwise it shouldn't matter.
                 refspecs.push(format!("+{0}:refs/remotes/origin/HEAD", rev));
+            } else if let GitReference::Rev(rev) = manifest_reference
+                && rev.starts_with("refs/")
+            {
+                // If the lockfile has a commi
```
Comment (weihanglo) [inline src/cargo/sources/git/utils.rs]: nit:

```suggestion
                // If the lockfile has a commit
```

File: tests/testsuite/git.rs [hunk 2]
```diff
@@ -4488,95 +4480,3 @@ Caused by:
 "#]])
         .run();
 }
-
-#[cargo_test(requires = "git")]
```
Comment (weihanglo) [inline tests/testsuite/git.rs]: Why was this test added and removed?

Comment (arlosi) [reply tests/testsuite/git.rs]: I merged it into the existing test rather than create a new one. Removed it from the wrong commit.

**Review by weihanglo — APPROVED** [review]
Thanks! I hope one day we can stabilize shallow clones :)

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16768/73a788647a03fe044540d52bff91d1ffdd71e64d..a24052f0dfde720dd4ae19d1839bdbe2fe862584)*
