### PR TITLE
Fix env/cfg set for `cargo test` and `cargo run`.

### LINKED ISSUE #9100: Cargo set environment variables provided by build scripts randomly when running tests
Discovered in https://github.com/rust-lang/miri/issues/1661#issuecomment-765968857 by @RalfJung.

**Steps**
1. Setup a workspace like this:
```bash
cargo new --lib cargo-bug --vcs none
cd cargo-bug/
echo 'proc-macro-crate = { path = "proc-macro-crate" }
[lib]
doctest = false
[workspace]' >> Cargo.toml
cargo new --lib proc-macro-crate --vcs none
cd proc-macro-crate/
echo '[lib]
proc-macro = true
[dev-dependencies]
cargo-bug = { path = ".." }' >> Cargo.toml
cd ..
echo 'fn main() { println!("cargo:rustc-env=CRATE_TARGET={}", std::env::var("TARGET").unwrap()) }' > build.rs
echo '#[test]
fn target() {
    assert_eq!(env!("CRATE_TARGET"), "i686-unknown-linux-musl");
    assert_eq!(std::env::var_os("CRATE_TARGET"), None);
}' > src/lib.rs
```
2. Run `cargo clean && cargo test --workspace --target i686-unknown-linux-musl -vv` (with `--jobs 1` optionally).
3. The test always fails with (the random) one of the following messages (on `x86_64-unknown-linux-gnu`):
```
thread 'target' panicked at 'assertion failed: `(left == right)`
  left: `Some("i686-unknown-linux-musl")`,
 right: `None`', src/lib.rs:4:5
```
```
thread 'target' panicked at 'assertion failed: `(left == right)`
  left: `Some("x86_64-unknown-linux-gnu")`,
 right: `None`', src/lib.rs:4:5
```

**Version info**
```
cargo 1.51.0-nightly (783bc43c6 2021-01-20)
release: 1.51.0
commit-hash: 783bc43c660bf39c1e562c8c429b32078ad3099b
commit-date: 2021-01-20
```

cc @ehuss

### PR DESCRIPTION
**Pull request by ehuss**
There are some situations where a build script may need to run multiple times for the same package during the same `cargo` session.  There was a bug in that some of the values in the `Compilation` struct didn't handle this case.  The solution here is to be more careful about how this extra data is associated with `Unit`s, instead of assuming a package's build script only runs once.

The things that were not being handled properly:

* `Compilation::extra_env`, which is the output of `cargo:rustc-env` in build scripts.  The solution here is to use the `Metadata` hash which is used elsewhere for distinguishing build script outputs.
* `Compilation::cfgs`, which is the output of `cargo:rustc-cfg` in build scripts and the features to be set, and this is only used for doctests.  The solution here is to just add those `--cfg` flags directly in the `Doctest` struct.

The situations that cause a build script to be run multiple times:

* A package needed for both the host and target.  In the test here, this was accomplished with a proc-macro (which has to be `host`) and a cyclical dev dependency, but there are many other ways to trigger this.
* Something built with different features (with the new feature resolver), usually due to host/target differences.
* Something built with different profile settings, usually due to host/target differences.

Fixes #9100

### CODE REVIEW

File: src/cargo/core/compiler/custom_build.rs [hunk 1]
```diff
@@ -51,7 +51,7 @@ pub struct BuildOutput {
 /// `Unit` because this structure needs to be shareable between threads.
 #[derive(Default)]
 pub struct BuildScriptOutputs {
-    outputs: HashMap<(PackageId, Metadata), BuildOutput>,
+    outputs: HashMap<Metadata, BuildOutput>,
```
Comment (ehuss) [inline src/cargo/core/compiler/custom_build.rs:54]: I changed this to just be keyed off the Metadata to simplify things.  I don't remember why I originally included `PackageId`, as the PackageId hash is already included in the `Metadata`.  If we are uncomfortable with the possibility of a hash collision, I can switch it back, or we can consider using a stronger hash (like siphash 128?).

**Comment by ehuss** [comment]
I was also wondering if we should update the documentation for how environment variables are set for `cargo test` and `cargo run`.  Perhaps just a note that says certain environment variables (such as `cargo:rustc-env`) are also set for running executables for `cargo test` and `cargo run`, but that it is not recommended to rely on that since it ties the executable to Cargo's execution environment?  Or maybe just leave it undocumented?

**Comment by alexcrichton** [comment]
Looks good to me, thanks!

I think it makes sense to go ahead and document this but discourage usage. We've already got users depending  on it (probably accidentally?) so I don't think that we can change it anyway. If you'd prefer to do doc updates in a future PR that's ok too, r=me on this regardless.

**Comment by ehuss** [comment]
Ok, I added a small note.  Thanks Alex! 😄 

@bors r=alexcrichton
