### PR TITLE
Override target crate-type for `cargo rustc --crate-type`

### LINKED ISSUE #10356: --crate-type cdylib causes errors looking for rlib dependencies
### Problem

When running `cargo rustc --crate-type cdylib -Z unstable-options`, I see errors that dependencies were expected to be available in `rlib` format. If I put the crate-type in the `Cargo.toml`, I don't see these errors.

Output:

```
 ~/code/test.rs $ cargo rustc --crate-type cdylib -Z unstable-options
   Compiling scratchpad v0.0.0 (/home/sean/code/test.rs)
error: crate `http` required to be available in rlib format, but was not found in this form

```

### Steps

Here's a minimal repro:

1. Make a new crate, using any simple dependency. `http = "*"` works.
2. In `lib.rs`, add `pub extern "C" fn yeet() { println!("{:?}", http::StatusCode::OK) }`.
3. Run `cargo rustc --crate-type cdylib -Z unstable-options`.

I originally discovered this by trying to convert hyper to use it:

1. Removing the `[lib]` and `crate-type = ["cdylib", "staticlib", "lib"]` lines.
2. Run `cargo rustc --crate-type cdylib -Z unstable-options`.

### Possible Solution(s)

_No response_

### Notes

- If I keep the line in `Cargo.toml`, then hyper builds properly.
- When making a minimal repro, I noticed that it works without a dependency, and it also works with a dependency that isn't used. You must _use_ the dependency in the file.

### Version

```text
cargo 1.60.0-nightly (25fcb13 2022-02-01)
release: 1.60.0-nightly
commit-hash: 25fcb135d02ea897ce894b67ae021f48107d522b
commit-date: 2022-02-01
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Ubuntu 16.04 (xenial) [64-bit]
```

### LINKED ISSUE #10389: `--crate-type` didn't overwrite `target.kind` in json message output
### Problem

From https://github.com/rust-lang/cargo/issues/10083 The `--crate-type` from cli should take higher priority than the `crate-type` specified in `Cargo.toml`, but it does not changed the json message output as expected.

### Steps

copy and paste this shell into your terminal:
```bash
cargo new --lib crate-type && \ 
cd crate-type && \
printf '[lib]\ncrate-type = [ "cdylib", "rlib" ]' >> Cargo.toml && \
cargo rustc -Zunstable-options --crate-type=cdylib --message-format=json
```
output
```txt
{"reason":"compiler-artifact","package_id":"crate-type 0.1.0 (path+file:///Users/mac/repo/lark/crate-type)","manifest_path":"/Users/mac/repo/lark/crate-type/Cargo.toml","target":{"kind":["cdylib","rlib"],"crate_types":["cdylib","rlib"],"name":"crate-type","src_path":"/Users/mac/repo/lark/crate-type/src/lib.rs","edition":"2021","doc":true,"doctest":true,"test":true},"profile":{"opt_level":"0","debuginfo":2,"debug_assertions":true,"overflow_checks":true,"test":false},"features":[],"filenames":["/Users/mac/repo/lark/crate-type/target/debug/libcrate_type.dylib"],"executable":null,"fresh":false}
```
As you can see, `target.kind` is still `["cdylib","rlib"]`.

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

Fixes #10356, fixes #10389

This might not be the best solution, but at least it avoids duplicating 
overridden rules all over the compilation logic.

r? @ehuss since you're the reviewer of #10093

### How should we test and review this PR?

Perform reproducible steps as #10356 described. 

This PR includes a new test `rustc::build_with_crate_type_for_foo_with_deps`
to validate the behavior of overridden crate-types with dependencies.

### CODE REVIEW

**Comment by lqd** [comment]
I've tested this PR both on the repro (but that was included in tests already) and on `hyper` where the issue was discovered, and of course both worked.

As part of the [initiative to improve compile times](https://blog.rust-lang.org/inside-rust/2022/02/22/compiler-team-ambitions-2022.html#faster-builds-initiatives--%EF%B8%8F) I've also benchmarked it, since #10356 is currently preventing cargo's pipelining from working with both `hyper`'s dependencies and the crates depending on it (as one can see e.g. in this [cargo timing example](https://lqd.github.io/rustc-benchmarking-data/results/round-13-cargo-timing-opt-j8/cargo-timing-warp-0.3.2-opt-j8.html)). 

As a testament to the great work done on cargo's pipelining, my measurements show that building `hyper` itself with this PR (from `-j2` to `-j12`) results in 7-8% improved build times in debug, and 18-29% in release (only `-j2` was at 18%, the mean was 26%) which is super cool. So great job @weihanglo on fixing the issue, it will have a big impact on the entire `hyper` ecosystem, the contributors to the crate itself, as well as CI improvements all around.

@weihanglo @ehuss is there something more I can do to help this PR along ? I can try to build the 800 or so popular crates we've been looking at in our extended benchmarks for example ?

**Comment by ehuss** [comment]
Thanks!  

@bors r+

File: src/cargo/ops/cargo_compile.rs [hunk 1]
```diff
@@ -1867,3 +1848,49 @@ fn remove_duplicate_doc(
...
+        target.set_kind(f(crate_types));
+        interner.intern(
+            &unit.pkg,
+            &target,
+            unit.profile.clone(),
+            unit.kind,
+            unit.mode,
+            unit.features.clone(),
+            unit.is_std,
+            unit.dep_hash,
```
Comment (lqd) [inline src/cargo/ops/cargo_compile.rs:1881]: The `intern` API has recently been updated on master, so something similar to this looks to be needed now

```suggestion
            unit.dep_hash,
            unit.artifact,
```

Comment (weihanglo) [reply src/cargo/ops/cargo_compile.rs:1885]: Thanks! Just found that and rebased to master

**Comment by lqd** [comment]
Thanks @weihanglo. I have a branch ready to fix `hyper` and will open a PR once this hits nightly. 
cc @seanmonstar
