### PR TITLE
Detail dep name in invalid version error

### LINKED ISSUE #2146: Non-`--verbose` error message for an invalid version constraint should mention this
``` rust
[package]
authors = []
name = "test"
version = "0.1.0"

[dependencies]
crossbeam = "x"
```

```
$ cargo build 
failed to parse manifest at `.../Cargo.toml`

To learn more, run the command again with --verbose.
$ failed to parse manifest at `/home/huon/projects/test-rust/test-af/Cargo.toml`

Caused by:
  version components must be numeric
```

It would be helpful if it also informed the user of the line number and/or the name of the crate.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #2146

I struggled with some aspects of Rust's pattern matching syntax & the borrow-checker, as well as the types and API of failure, so... this is the "I got it to compile" version-I'd love tips/advice to clean it up. (soft-cc @withoutboats?).

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Looks good to me, thanks! Style-wise it seems fine by me as well, I don't see any low-hanging fruit at least!

File: src/cargo/core/dependency.rs [hunk 1]
```diff
@@ -86,19 +86,18 @@ pub enum Kind {
...
     req: &str,
     extra: Option<(&PackageId, &Config)>,
 ) -> CargoResult<VersionReq> {
     match VersionReq::parse(req) {
-        Err(e) => {
+        Err(ReqParseError::DeprecatedVersionRequirement(requirement)) => {
             let (inside, config) = match extra {
                 Some(pair) => pair,
-                None => return Err(e.into()),
+                None => return Err(ReqParseError::DeprecatedVersionRequirement(requirement).into()),
```
Comment (dwijnand) [inline src/cargo/core/dependency.rs]: Deconstructing and reconstructing the `ReqParseError` is unfortunate.

File: src/cargo/core/dependency.rs [hunk 2]
```diff
@@ -109,18 +108,25 @@ This will soon become a hard error, so it's either recommended to
...
+        },
+        Err(e) => {
+            let err: CargoResult<VersionReq> = Err(e.into());
+            let v: VersionReq = err.chain_err(|| {
+                format!(
+                    "failed to parse the version requirement `{}` for dependency `{}`",
+                    req, name
+                )
+            })?;
+            Ok(v)
```
Comment (dwijnand) [inline src/cargo/core/dependency.rs]: This is just confusing.  The "CargoResult" is always an `Err` so `?` will never result in an actual `VersionReq`.
