### PR TITLE
fix(add): Clarify which version the features are added for

### LINKED ISSUE #11073: cargo add package@version shows features from oldest instead of current version
### Problem

When adding `cargo add` with an explicit minimal version, `cargo add` will show features from the specific version, while actually adding the latest semver-compatible version. This seems misleading and/or confusing.

### Steps

1. `cargo add chrono@0.4`

Actual result:

```
```

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

This gives a hint to users that we might not be showing the feature list
for the latest version but the earliest version.

Also when using a workspace dependency, this is a good reminder of what the version requirement is that was selected.  That could also be useful for reused dependencies but didn't want to bother with the relevant plumbing for that.

ie we are going from
```console
$ cargo add chrono@0.4
    Updating crates.io index
      Adding chrono v0.4 to dependencies.
             Features:
             - rustc-serialize
             - serde
```
to
```console
$ cargo add chrono@0.4
    Updating crates.io index
      Adding chrono v0.4 to dependencies.
             Features as of v0.4.2:
             - rustc-serialize
             - serde
```

### How should we test and review this PR?

I'd recommend looking at this commit-by-commit.  This is broken up into several refactors leading up the main change.  The refactors are focused on pulling UI logic out of dependency editing so we can more easily evolve the UI without breaking the editing API.  I then tweaked the behavior in the final commit to be less redundant / noisy.

The existing tests are used to demonstrate this is working.

### Additional information

I'm also mixed on whether the meta version should show up.

Fixes #11073

### CODE REVIEW

File: src/cargo/ops/cargo_add/mod.rs [hunk 1]
```diff
@@ -596,12 +600,68 @@ fn populate_dependency(mut dependency: Dependency, arg: &DepOp) -> Dependency {
     dependency
 }
 
+pub struct DependencyEx {
```
Comment (Muscraft) [inline src/cargo/ops/cargo_add/mod.rs:602]: I'm not sold on `DependencyEx`. The name doesn't make sense to me. This appears to be only used for displaying with features, so maybe `DisplayDependency` or something similar.

Comment (epage) [reply src/cargo/ops/cargo_add/mod.rs]: `Ex` / `Ext` are common suffixes for "extension", conveying that this is an extension on the `Dependency` type.  This dates past long before `ResultExt` type names in Rust.  iirc a lot of old Microsoft APIs use it.

That said, I named it that not because I liked it but because I needed a name and wanted to move forward.

`DisplayDependency` implies the purpose is for the `Display`.

I've gone ahead and renamed it `DependencyUI` even though that still isn't quite accurate, bit is at least a little more specific.

**Review by weihanglo — APPROVED** [review]
I am good with this. Thank you!

@Muscraft do you have any other suggestion?

**Review by Muscraft — APPROVED** [review]
