### PR TITLE
fix(publish): Block until it is in index

### LINKED ISSUE #9507: publish multiple crates, races with dependencies
**Problem**

My project has multiple crates in a cargo workspace.  I use a shell loop to run cargo publish on each of the crates in dependency order.

I get output like this:

```
+ cargo publish --no-verify
    Updating crates.io index
   Packaging otter-api-tests v0.6.0 (/volatile/rustcargo/Rustup/Game/server/apitest)
   Uploading otter-api-tests v0.6.0 (/volatile/rustcargo/Rustup/Game/server/apitest)
nailing-cargo: finished.  status 0.
+ nailing-cargo --no-nail --linkfarm=git --- sh -xec 
          find . ! -type l ! -type d ! -path './target/*' -print0               | xargs -0r rm --
          cd wdriver; cargo publish --no-verify 
        
nailing-cargo: out-of-tree, building in: `/home/ian/Rustup/Game/Build/server'
nailing-cargo: using really to run as user `rustcargo'
nailing-cargo: invoking: sh -xec 
          find . ! -type l ! -type d ! -path './target/*' -print0               | xargs -0r rm --
          cd wdriver; cargo publish --no-verify 
        
+ find . ! -type l ! -type d ! -path ./target/* -print0
+ xargs -0r rm --
+ cd wdriver
+ cargo publish --no-verify
    Updating crates.io index
   Packaging otter-webdriver-tests v0.6.0 (/volatile/rustcargo/Rustup/Game/server/wdriver)
error: failed to prepare local package for uploading

Caused by:
  failed to select a version for the requirement `otter-api-tests = "=0.6.0"`
  candidate versions found which didn't match: 0.5.1
  location searched: crates.io index
  required by package `otter-webdriver-tests v0.6.0 (/volatile/rustcargo/Rustup/Game/server/wdriver)`
```

As you can see, `cargo publish` for `otter-api-tests v0.6.0` succeeded.  But `cargo publish` for `otter-webdriver-tests` then failed, complaining that `otter-api-tests = "=0.6.0"` could not be resolved.

I tried working around this with `sleep 10`.  That wasn't enough.

I looked in `cargo help publish` to see if there was a way to turn off the dependency check, but I didn't see one.  I also looked at various commands to see if I could perhaps poll the registry, but nothing seemed relevant.  `cargo search` seems too dwim, even with postprocessing of the ouptut, and I am not convinced (from my experiences with publishing otter 0.5.1) that this would necessarily work.

**Steps**

1. Make two crates, A and B, where B depends on the precise version of A.
2. cd A && cargo publish && cd ../B && cargo publish

**Possible Solution(s)**

Ideally whatever service `cargo publish` talks to wouldn't say "yes" until it had done it.  Or maybe `cargo publish` could at least have an option to wait.

**Notes**

Output of `cargo version`:

```
cargo 1.54.0-nightly (e51522ab3 2021-05-07)
```

I am slightly perplexed since I don't understand how large Rust projects with multiple crates do their publish.

### PR DESCRIPTION
**Pull request by epage**
Originally, crates.io would block on publish requests until the publish
was complete, giving `cargo publish` this behavior by extension.  When
crates.io switched to asynchronous publishing, this intermittently broke
people's workflows when publishing multiple crates.  I say interittent
because it usually works until it doesn't and it is unclear why to the
end user because it will be published by the time they check.  In the
end, callers tend to either put in timeouts (and pray), poll the
server's API, or use `crates-index` crate to poll the index.

This isn't sufficient because
- For any new interested party, this is a pit of failure they'll fall
  into
- crates-index has re-implemented index support incorrectly in the past,
  currently doesn't handle auth, doesn't support `git-cli`, etc.
- None of these previous options work if we were to implement
  workspace-publish support (#1169)
- The new sparse registry might increase the publish times, making the
  delay easier to hit manually
- The new sparse registry goes through CDNs so checking the server's API
  might not be sufficient
- Once the sparse registry is available, crates-index users will find
  out when the package is ready in git but it might not be ready through
  the sparse registry because of CDNs

So now `cargo` will block until it sees the package in the index.
- This is checking via the index instead of server APIs in case there
  are propagation delays.  This has the side effect of being noisy
  because of all of the "Updating index" messages.
- This blocks by default but there is an unstable `publish.timeout` config field that will disable blocking when set to 0.  See #11222 for stablization

Blocking is opt-out as that is the less error prone case for casual users while those doing larger integrations are also likely to do the testing needed to make more complicated scenarios work where blocking is disabled.

Right now we block after the publish.  An alternative would be to block until all dependencies are in the index which makes the blocking only happen when needed
- Blocking on dependencies can be imprecise to detect when to block vs propagate an error up
- This is the less error prone case for users.  For example I recently publish a crate in one tab and immediately switched to another tab to use it and this only worked because `cargo-release` blocked until it was ready to use

In reviewing this change, be sure to look at the individual commits
- The first makes it possible to write the tests for this
- The second adds a test that shows the current behavior
- The third updates the test to the expected behavior, showing all of this works

In addition to the publish tests:
- We want to maximize the nightly-to-stable time to collect feedback
- We will put this in TWiR's testing section to raise visibility

Fixes #9507

### CODE REVIEW

File: tests/testsuite/publish.rs [hunk 1]
```diff
@@ -2048,3 +2049,187 @@ error: package ID specification `bar` did not match any packages
...
+[UPDATING] `dummy-registry` index
+[WARNING] using `registry.token` config value with source replacement is deprecated
+This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/xxx>.
+Use the --token command-line flag to remove this warning.
+[WARNING] manifest has no documentation, [..]
+See [..]
+[PACKAGING] delay_with_underscore v0.0.1 ([CWD])
+[UPLOADING] delay_with_underscore v0.0.1 ([CWD])
+[UPDATING] `dummy-registry` index
+[WAITING] on registry `dummy-registry` to finish publish
```
Comment (epage) [inline tests/testsuite/publish.rs:2204]: Calling out the waiting message since its likely people will have feedback on it

Current behavior:
- If the publish is complete before the wait, no waiting message will be shown
- If the publish isn't complete, we'll show the message immediately but only once

I was tempted to put the message on a time delay but
- Since we show the "Updating" messages, I wanted there to be context for them (I was tempted to put the "Waiting" before the first message because of this)
- It'd make it more annoying to test

File: tests/testsuite/publish.rs [hunk 2]
```diff
@@ -2048,3 +2049,187 @@ error: package ID specification `bar` did not match any packages
...
+[WARNING] using `registry.token` config value with source replacement is deprecated
+This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/xxx>.
+Use the --token command-line flag to remove this warning.
+[WARNING] manifest has no documentation, [..]
+See [..]
+[PACKAGING] delay v0.0.1 ([CWD])
+[UPLOADING] delay v0.0.1 ([CWD])
+[UPDATING] `dummy-registry` index
+[WAITING] on registry `dummy-registry` to finish publish
+[UPDATING] `dummy-registry` index
```
Comment (epage) [inline tests/testsuite/publish.rs:2112]: Since this isn't ideal, I wanted to call out that we'll post an "Updating" message each time we poll.

This is because we are going through the registry source path instead of the registry API path in hopes to wait out any CDN propagation delays.

I'd like to silence these but can't think of any good option.  I could temporarily make the `Shell` "quiet" and then re-enable the previous verbosity level but the risks with that make me unsure if its worth it.

(see my other post about the "Waiting" message wording)

File: src/cargo/ops/registry.rs [hunk 3]
```diff
@@ -374,6 +382,61 @@ fn transmit(
...
+
+    let now = std::time::Instant::now();
+    let sleep_time = std::time::Duration::from_secs(1);
+    let mut logged = false;
+    loop {
+        let registry_description;
+        {
+            let mut registry = PackageRegistry::new(config)?;
+            let _lock = config.acquire_package_cache_lock()?;
+            registry.lock_patches();
```
Comment (epage) [inline src/cargo/ops/registry.rs:402]: Wanted to call out that I'm recreating a `PackageRegistry` on each pass of the wait because I didn't see a way to clear it to force a new update.  Didn't see downsides to this (performance of it shouldn't be an issue with everything else going on) so I went with it

File: src/cargo/ops/registry.rs [hunk 4]
```diff
@@ -374,6 +382,61 @@ fn transmit(
...
+    config: &Config,
+    registry_src: SourceId,
+    pkg: &Package,
+    timeout: std::time::Duration,
+) -> CargoResult<()> {
+    let version_req = format!("={}", pkg.version());
+    let query = Dependency::parse(pkg.name(), Some(&version_req), registry_src)?;
+
+    let now = std::time::Instant::now();
+    let sleep_time = std::time::Duration::from_secs(1);
```
Comment (epage) [inline src/cargo/ops/registry.rs:395]: Wanted to call out the current sleep time

File: src/cargo/ops/registry.rs [hunk 5]
```diff
@@ -183,6 +187,10 @@ pub fn publish(ws: &Workspace<'_>, opts: &PublishOpts<'_>) -> CargoResult<()> {
         reg_id,
         opts.dry_run,
     )?;
+    if !opts.dry_run {
+        let timeout = std::time::Duration::from_secs(300);
```
Comment (epage) [inline src/cargo/ops/registry.rs:191]: Wanted to call out the current timeout.

File: src/cargo/ops/registry.rs [hunk 6]
```diff
@@ -374,6 +382,61 @@ fn transmit(
...
+            }
+        }
+
+        if timeout < now.elapsed() {
+            config.shell().warn(format!(
+                "publishing {} took longer than expected",
+                pkg.name(),
+            ))?;
+            break;
+        }
```
Comment (epage) [inline src/cargo/ops/registry.rs:425]: As the current behavior doesn't error on the publish taking too long, I figured that'd be the safest behavior to use for now.

**Comment by epage** [comment]
Hmm, hadn't run all of the tests before posting and hadn't considered there isn't a functioning-enough registry to pull from.

Open to people's thoughts on doing some kind of hack for this (env variable, unstable flag to not block, etc) or to try to add an insta-stable flag for controlling blocking.

**Comment by ehuss** [comment]
> Hmm, hadn't run all of the tests before posting and hadn't considered there isn't a functioning-enough registry to pull from.

How hard would it be to implement a real publish API? I suspect a simplified implementation should be relatively short (maybe 40-50 lines?). I think the steps would roughly be:

1. Read the data sent by cargo, and deserialize the JSON.
2. Save the `.crate` file into the correct directory.
3. Convert the publish JSON to the index JSON. I think this should be relatively basic copy of fields into a new `serde_json::Value`. The only one I think that needs real translation is the `registry` field of a dependency. I think the `cksum` would also need to be computed.
4. Add that JSON to the index, and commit it.

**Comment by Eh2406** [comment]
The fact that almost all of our tests do not require actually running a web server, it's kind of nice for performance and reliability. An alternative implementation to support the tests, would be to add a flag for skipping the new delay.

We should also keep in mind in designing this that not all registries necessarily publish promptly. it is perfectly reasonable for a registry that accepts the publish API to require some kind of intervention before it appears in the index. I could see a registry requiring a user to review the package they just uploaded to verify that it looks correct before adding it to the index. A registry could also do an automated or manual security audit before it is added.

**Comment by epage** [comment]
> We should also keep in mind in designing this that not all registries necessarily publish promptly. 

For this use case, it seems like we'd want this to be part of registry configuration as passing in a `--wait=no` every time doesn't seem right.

Maybe we should start out with both an unstable flag and an unstable config value so any users can unblock themselves and we can also use this as a way to collect feedback on what is needed and not block this on naming or other details like that.

File: src/cargo/ops/registry.rs [hunk 7]
```diff
@@ -374,6 +382,61 @@ fn transmit(
...
+                }
+            };
+            if !summaries.is_empty() {
+                break;
+            }
+        }
+
+        if timeout < now.elapsed() {
+            config.shell().warn(format!(
+                "publishing {} took longer than expected",
```
Comment (arlosi) [inline src/cargo/ops/registry.rs:421]: Should this message be clearer? We actually timed out waiting for the publish to be listed on the registry.

File: tests/testsuite/publish.rs [hunk 8]
```diff
@@ -2048,3 +2049,187 @@ error: package ID specification `bar` did not match any packages
...
+        .file("src/main.rs", "fn main() {}")
+        .build();
+
+    p.cargo("build -Z sparse-registry")
+        .masquerade_as_nightly_cargo(&["sparse-registry"])
+        .with_status(0)
+        .run();
+}
+
+/// A separate test is needed for package names with - or _ as they hit
```
Comment (arlosi) [inline tests/testsuite/publish.rs:2143]: This is a bit unfortunate. Would it make sense to plumb the `QueryKind::Exact` all the way to `load_summaries()` and skip the `UncanonicalizedIter` for that case?

File: src/cargo/ops/registry.rs [hunk 9]
```diff
@@ -183,6 +187,10 @@ pub fn publish(ws: &Workspace<'_>, opts: &PublishOpts<'_>) -> CargoResult<()> {
         reg_id,
         opts.dry_run,
     )?;
+    if !opts.dry_run {
+        let timeout = std::time::Duration::from_secs(300);
+        wait_for_publish(opts.config, reg_id, pkg, timeout)?;
```
[the remark this answers is not in the document]
Comment (epage) [reply src/cargo/ops/registry.rs:192]: We are talking about potentially adding a `--no-wait` for other reasons but I'm personally not as sympathetic to this case.   They would need to know, not matter, and pass in a flag.  That seems like a fairly specialized case to add a flag for.

File: tests/testsuite/publish.rs (hunk 8 above)
Comment (epage) [reply tests/testsuite/publish.rs:2143]: imo this is an existing problem that we should address decoupled from this discussion.  I'd recommend opening an issue for us to track this.

File: src/cargo/ops/registry.rs (hunk 7 above)
Comment (epage) [reply src/cargo/ops/registry.rs]: I've updated it to `"timed out waiting for publishing of {} to complete"`.  imo listing in the registry is published for the user.  If we can find a messaged that is both more technically correct and as clear / succinct to users, I'm game.

File: src/cargo/ops/registry.rs (hunk 3 above)
Comment (epage) [reply src/cargo/ops/registry.rs]: Thanks! I overlooked that after getting burned with `cargo add` for not looking things up in the right layer

File: tests/testsuite/publish.rs (hunk 2 above)
Comment (epage) [reply tests/testsuite/publish.rs]: Now that we are polling on the `Source` rather than `PackageRegistry`, this has gone away

File: tests/testsuite/publish.rs (hunk 1 above)
Comment (epage) [reply tests/testsuite/publish.rs]: This is now
```
[WAITING] on `delay_with_underscore` to be in `dummy-registry` index
```
Because we switched from `PackageRegistry` to a `Source`, the desciption changed from `registry 'dummy-registry'` to `'dummy-registery' index`, so I re-worded to better fit that.

File: src/cargo/ops/registry.rs (hunk 7 above)
Comment (epage) [reply src/cargo/ops/registry.rs]: With the change in the waiting message, I felt like it gave the user enough context for the message to be `timed out waiting for 'delay' to be in 'dummy-registry' index`

**Comment by Eh2406** [comment]
> We should also keep in mind in designing this that not all registries necessarily publish promptly.

To start speculating on an RFC...
Thinking about this more, I think the right place for a registry to tell us how long to wait is in the response to the `/api/v1/crates/new` call. Either in the response object or in headers.
I see a couple of reasonable things a registry could want to tell a user about how long to wait:
- Retry for some expected period of time (the behavior you're adding here) possibly with the ability for a registry to estimate how long the retries should run for.
- A URL that needs to be interacted with in order for progress to be made. For the cases where it requires the author to do a manual review.
- A URL that can be used to track the progress of publication. (Possibly with some specification for how cargo can use it as a retry loop.)
- Clarification that the retry loop is unlikely to be productive. Say if all publishes require manual review by the registry.

On the other hand, we can change the default behavior now and add such configurability in a backwards compatible way in the future.

File: tests/testsuite/publish.rs (hunk 1 above)
Comment (epage) [reply tests/testsuite/publish.rs]: Maybe a minor tweak
```
[WAITING] on `delay_with_underscore` to propagate to `dummy-registry` index
```

**Comment by jonhoo** [comment]
I wonder if we could express all of these with semi-standard HTTP response codes + headers:

> Retry for some expected period of time (the behavior you're adding here) possibly with the ability for a registry to estimate how long the retries should run for.

```
202 Accepted
Retry-After: Fri, 07 Nov 2022 23:59:59 GMT
Content-Location: https://crates.io/api/v1/crates/$crate/$new_version
```

> A URL that needs to be interacted with in order for progress to be made. For the cases where it requires the author to do a manual review.

```
202 Accepted
Location: https://registry.example.com/approve/$crate/$new_version
```

> A URL that can be used to track the progress of publication. (Possibly with some specification for how cargo can use it as a retry loop.)

```
202 Accepted
X-Cargo-Track-Progress: v1
Content-Location: https://crates.io/api/v1/crates/$crate/$new_version
```

> Clarification that the retry loop is unlikely to be productive. Say if all publishes require manual review by the registry.

```
202 Accepted
```

And to add one: "available now" could be

```
201 Created
```

**Comment by ehuss** [comment]
I was curious why this waits after publish, instead of waiting for dependencies to be available?  The original intent I had for #9507 is to only block publishing to wait for dependencies to become available. That way, it doesn't affect the majority of cases where someone is publishing a single package. Do you have any thoughts on those approaches?

I'm a little concerned about always blocking until it is available. There are times where there can be a significant delay, and the user may not care, but would be bothered if publishing gets "stuck".

I can see some benefit of blocking before finishing, such as someone wanting to publish an announcement. But I'm a bit wary of forcing that behavior.

**Comment by ijackson** [comment]
> We should also keep in mind in designing this that not all registries necessarily publish promptly. it is perfectly reasonable for a registry that accepts the publish API to require some kind of intervention before it appears in the index. I could see a registry requiring a user to review the package they just uploaded to verify that it looks correct before adding it to the index. A registry could also do an automated or manual security audit before it is added.

Indeed.  But right now such a registry would be unuseable with cargo, because to publish a workspace of interdependent crates one would have to wait for the huma review cycle to complete before publishing the next crate.

To support a registry with this kind of behaviour, it would be necessary to allow `cargo publish` of a crate whose dependencies are not yet available via the published view of the regsitry.

File: src/cargo/ops/registry.rs (hunk 5 above)
Comment (ehuss) [reply src/cargo/ops/registry.rs:189]: I feel like 5 minutes is probably a little too long.  I would think 1 minute is usually more than long enough (assuming https://github.com/rust-lang/crates.io/pull/5200 is merged), and if it takes longer than 1 minute then it is going to take *way* longer (like there is a GitHub outage, or a major internal failure on the heroku side). Unless you have observed significantly longer delays under normal operation?  I wonder if crates.io keeps track of how long that queue usually takes.

File: src/cargo/ops/registry.rs [hunk 10]
```diff
@@ -374,6 +380,70 @@ fn transmit(
...
+    let mut logged = false;
+    loop {
+        {
+            let _lock = config.acquire_package_cache_lock()?;
+            // Force re-fetching the source
+            //
+            // As pulling from a git source is expensive, we track when we've done it within the
+            // process to only do it once, but we are one of the rare cases that needs to do it
+            // multiple times
+            config.updated_sources().remove(&registry_src);
```
Comment (epage) [inline src/cargo/ops/registry.rs:405]: This was a surprising find and might be relevant for #1169 depending on how its implemented.

cargo makes the assumption its doing things in one pass and little ever becomes invalidated but `publish` breaks one of those cases when using a git remote and I have to hack in this line to invalidate things.

This had been masked because originally no other tests worked.  A previous PR got sparse index tests working but still not git indexes.  I had chalked the timeouts to the git index tests not working but this was also broken

File: tests/testsuite/publish.rs [hunk 11]
```diff
@@ -192,12 +179,14 @@ See [..]
         )
         .run();
 
-    validate_upload_foo();
+    // Skip `validate_upload_foo` as we just cared we got far enough for verify the token behavior.
+    // Other tests will verify the endpoint gets the right payload.
```
Comment (weihanglo) [inline tests/testsuite/publish.rs:186]: Sorry I did't get it. Could you guide me through the place that verifies this?

File: tests/testsuite/publish.rs [hunk 12]
```diff
@@ -2337,3 +2337,211 @@ fn http_api_not_noop() {
...
+    let arc2 = arc.clone();
+
+    // Registry returns an invalid response.
+    let registry = registry::RegistryBuilder::new()
+        .http_index()
+        .http_api()
+        .add_responder("/index/de/la/delay", move |req, server| {
+            let mut lock = arc.lock().unwrap();
+            *lock += 1;
+            // if the package name contains _ or
```
Comment (weihanglo) [inline tests/testsuite/publish.rs:2385]:
```suggestion
            // if the package name contains _ or -
```

**Review by weihanglo — APPROVED** [review]
Overall looks good to me! I will start an FCP soon.

File: tests/testsuite/publish.rs (hunk 11 above)
Comment (epage) [reply tests/testsuite/publish.rs:186]: Context: this is the `old_token_location` test

This test is focused on authentication.  Once we have been authenticated, the token location should not make a difference to formatting of the output we give to the payload.  We verify the publish succeeds using `with_stderr` and seeing the `[UPLOADING]` without any errors after it.  At that point, we know the old location works.  Other tests, like `simple` focus on verifying we give the right data to the end point.

**Comment by weihanglo** [comment]
This patch changes the behaviour of `cargo publish` as listed below:

- By default, synchronously wait for the publish propagating to crates.io index.
  - The default timeout is 60 seconds. Polling interval is 1 second.
- To opt out, set the unstable config `publish.timeout = 0`.

Ed summarizes this feature very well in the PR description. I'd recommend taking a look.

I am going to propose this to be merged, but 1.65.0 is going to release on November 3rd, do we want to postpone the merge after that to maximize the test window?

@rfcbot merge

**Comment by epage** [comment]
> I am going to propose this to be merged, but 1.65.0 is going to release on November 3rd, do we want to postpone the merge after that to maximize the test window?

If we quickly get votes and don't wait for the 10 day period, we'll get 9 weeks of testing.  7 or so if votes take some time and we wait for the full FCP period.

Seeing as we've discussed this and the plan, I'm assuming the vote on this is uncontroversial and we can forego the 10 day waiting period.

Either way, if people want to wait until after November 3rd, I can understand.  I would ask that we just change the default to 0 and merge as-is because this has already had 3 different semantic merge conflicts, one that took a decent amount of time to resolve.

**Comment by ehuss** [comment]
@rfcbot concern update-issue

I'm trying to test this out, but I can't seem to get it to work. I opened #11253 for what I'm seeing. Can someone take a look?

**Comment by ehuss** [comment]
@rfcbot resolve update-issue

**Comment by ehuss** [comment]
One thing we may want to look at separately is the UI while it is waiting. Cargo just keeps repeating `Updating crates.io index`. I'm wondering if it might be better to suppress the `Updating` message? That could maybe be implemented by temporarily enabling quiet mode.  I'm also wondering about maybe showing some kind of busy indicator (maybe a progress bar that ticks forward for each second)? 

I'm also a little concerned that it feels like there is essentially no test for this feature (that exercises what users will experience). Would someone be willing to follow up with a test for it?  I think it shouldn't be too difficult to change the `PUT` handler to optionally delay the `write_to_index` call (it could maybe toss it into a thread or something to run in the background).

**Comment by weihanglo** [comment]
The recent Cargo meeting concluded that we want to move forward and maximize the testing period for this default timeout setting before it hits next stable version. I'll merge it now then.

@bors r+
