### PR TITLE
fix(fingerprint): force update mtime of cargo-check artifacts

### LINKED ISSUE #16104: If an empty build script's output's mtime is newer than the build script binary, it's always considered to be dirty
### Problem

(Originally reported as https://github.com/oxidecomputer/crucible/issues/1790.)

In the situation where:

* a build script is a trivial `fn main() {}`
* its output's mtime is newer than the build script binary

then the build script is always considered to be dirty, leading to many excessive rebuilds.

It wasn't clear to me how the mtime of the output ended up being newer in this way, but it did in the case of my coworker, and the only way to get out of it was to run `cargo clean`.

Seems like Cargo should refresh the mtime of the output file to avoid this scenario.

### Steps

Minimal repro with instructions is at https://github.com/sunshowers/output-build-script-test.

Normally:

```
% cargo check -v
   Compiling output-build-script-test v0.1.0 (/home/rain/dev/output-build-script-test)
     Running `/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name build_script_build --edition=2021 build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=176 --crate-type bin --emit=dep-info,link -C embed-bitcode=no --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=79dbd0af7880cfc3 -C extra-filename=-74601695fb5010e2 --out-dir /home/rain/dev/output-build-script-test/target/debug/build/output-build-script-test-74601695fb5010e2 -C incremental=/home/rain/dev/output-build-script-test/target/debug/incremental -L dependency=/home/rain/dev/output-build-script-test/target/debug/deps`
     Running `/home/rain/dev/output-build-script-test/target/debug/build/output-build-script-test-74601695fb5010e2/build-script-build`
     Running `/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name output_build_script_test --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=176 --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=139407a758b9a61d -C extra-filename=-0c40631603a3198e --out-dir /home/rain/dev/output-build-script-test/target/debug/deps -C incremental=/home/rain/dev/output-build-script-test/target/debug/incremental -L dependency=/home/rain/dev/output-build-script-test/target/debug/deps`
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.06s
% cargo check -v
       Fresh output-build-script-test v0.1.0 (/home/rain/dev/output-build-script-test)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s```
```

But if you do:

```
touch target/debug/build/*/output
```

Then:

```
% cargo check -v
       Dirty output-build-script-test v0.1.0 (/home/rain/dev/output-build-script-test): the precalculated components changed
   Compiling output-build-script-test v0.1.0 (/home/rain/dev/output-build-script-test)
     Running `/home/rain/dev/output-build-script-test/target/debug/build/output-build-script-test-74601695fb5010e2/build-script-build`
     Running `/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name output_build_script_test --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=176 --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=139407a758b9a61d -C extra-filename=-0c40631603a3198e --out-dir /home/rain/dev/output-build-script-test/target/debug/deps -C incremental=/home/rain/dev/output-build-script-test/target/debug/incremental -L dependency=/home/rain/dev/output-build-script-test/target/debug/deps`
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.02s
% cargo check -v
       Dirty output-build-script-test v0.1.0 (/home/rain/dev/output-build-script-test): the dependency build_script_build was rebuilt (1760409718.149356849s, 23s after last build at 1760409695.958999891s)
    Checking output-build-script-test v0.1.0 (/home/rain/dev/output-build-script-test)
     Running `/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name output_build_script_test --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=176 --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=139407a758b9a61d -C extra-filename=-0c40631603a3198e --out-dir /home/rain/dev/output-build-script-test/target/debug/deps -C incremental=/home/rain/dev/output-build-script-test/target/debug/incremental -L dependency=/home/rain/dev/output-build-script-test/target/debug/deps`
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.02s
```

and so on, i.e. the build script is never considered to be fresh.

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
% cargo --version --verbose
cargo 1.90.0 (840b83a10 2025-07-30)
release: 1.90.0
commit-hash: 840b83a10fb0e039a83f4d70ad032892c287570a
commit-date: 2025-07-30
host: x86_64-unknown-linux-gnu
libgit2: 1.9.1 (sys:0.20.2 vendored)
libcurl: 8.14.1-DEV (sys:0.4.82+curl-8.14.1 vendored ssl:OpenSSL/3.5.0)
ssl: OpenSSL 3.5.0 8 Apr 2025
os: Ubuntu 24.4.0 (noble) [64-bit]
```

Also repros on nightly:

```
% cargo +nightly --version --verbose
cargo 1.92.0-nightly (81c3f77a4 2025-10-10)
release: 1.92.0-nightly
commit-hash: 81c3f77a467359c8be6bc747dc93ec66a6e4ce11
commit-date: 2025-10-10
host: x86_64-unknown-linux-gnu
libgit2: 1.9.1 (sys:0.20.2 vendored)
libcurl: 8.15.0-DEV (sys:0.4.83+curl-8.15.0 vendored ssl:OpenSSL/3.5.4)
ssl: OpenSSL 3.5.4 30 Sep 2025
os: Ubuntu 24.4.0 (noble) [64-bit]
```

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

This mtime shift for .rmeta is a workaround as rustc incremental build
since rust-lang/rust#114669 (1.90.0) skips unnecessary rmeta generation.

The situation is like this:

1. When build script execution's external dependendies
   (rerun-if-changed, rerun-if-env-changed) got updated,
   the execution unit reran and got a newer mtime.
2. rustc type-checked the associated crate, though with incremental
   compilation, no rmeta regeneration. Its `.rmeta` stays old.
3. Run `cargo check` again. Cargo found build script execution had
   a new mtime than existing crate rmeta, so re-checking the crate.
   However the check is a no-op (input has no change), so stuck.

Fixes #16104 

### How to test and review this PR?

Tests pass.

There is a reproduction in <https://github.com/rust-lang/cargo/issues/16104#issuecomment-3530739039>,but actually a minimal one is touching a file of build script dependency, than `cargo check`. It'll easily get stuck.

This is an ugly workaround. And `-Zchecksum-freshness` doesn't help because build script is involved.

### CODE REVIEW

**Comment by epage** [comment]
It would be nice for us to have a way to have early cut off but we can look into how to get both later

The next question is what to do about beta
- backport
- disable incremental compilation

Thoughts?

**Comment by weihanglo** [comment]
We probably want to backport to beta ASAP, as this affects rust-lang/rust developers.

**Review by epage — APPROVED** [review]
Sorry, doing this on mobile seemed to have failed me

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16262/8363559a4d19d8aee53bbd9a7e063a4f1e3ec230..9e7e29e56da473c60d821764dea57fbca5ca18df)*

File: src/cargo/core/compiler/mod.rs [hunk 1]
```diff
@@ -477,6 +477,25 @@ fn rustc(
...
+        //
+        // 1. When build script execution's external dependendies
+        //    (rerun-if-changed, rerun-if-env-changed) got updated,
+        //    the execution unit reran and got a newer mtime.
+        // 2. rustc type-checked the associated crate, though with incremental
+        //    compilation, no rmeta regeneration. Its `.rmeta` stays old.
+        // 3. Run `cargo check` again. Cargo found build script execution had
+        //    a new mtime than existing crate rmeta, so re-checking the crate.
+        //    However the check is a no-op (input has no change), so stuck.
+        if mode.is_check() {
```
Comment (RalfJung) [inline src/cargo/core/compiler/mod.rs:493]: Wouldn't it make sense to do this for all modes?

I guess eventually we have to clarify the contract between rustc and cargo here: is rustc allowed to just do nothing if an output file is up-to-date, or is it required to always at least update the mtime?

Comment (weihanglo) [reply src/cargo/core/compiler/mod.rs:493]: I personally don't think rustc should care and update mtime. 

keeping this patch small and suitable for backport, but yeah to be more robust and future proof, we probably want to do it for all modes, or at least adding tests to capture possible regression in a full  `cargo build`.

Comment (bjorn3) [reply src/cargo/core/compiler/mod.rs:493]: Other build systems will probably get confused by the exact same issue, so perhaps this should actually be changed in rustc itself.

Comment (RalfJung) [reply src/cargo/core/compiler/mod.rs:493]: True, though OTOH a build system also shouldn't get into an internally inconsistent state (like what we saw in https://github.com/rust-lang/cargo/issues/16104) just because a tool it invokes has slightly odd behavior.

Comment (bjorn3) [reply src/cargo/core/compiler/mod.rs:493]: Make can't have any other behavior than continuous rebuilding as it doesn't store any information and only uses the mtime stored in the filesystem as would ninja I believe (which together with make are the main backends of cmake and which is the only backend of meson that supports Linux). Basically any mtime based build system (which is the fast majority of the build systems that are used) is broken when a build doesn't update the mtime of output files.

Comment (epage) [reply src/cargo/core/compiler/mod.rs:493]: imo not updating on no difference in output is great in terms of early cut off.  It is just getting all of the semantics right that is the issue.

Comment (RalfJung) [reply src/cargo/core/compiler/mod.rs:493]: Let's not discuss this in a closed PR... I have opened https://github.com/rust-lang/rust/issues/148948.

**Comment by weihanglo** [comment]
Beta backport is filed: <https://github.com/rust-lang/cargo/pull/16273>.
