### PR TITLE
bail before packaging on same version 

### LINKED ISSUE #3662: Fail fast when package version is already published
For example instead of validating the version when uploading, let's do so before we even start building the project, or better yet launch the build process concurrently as we check the version. I just ran `cargo publish`, waited for a while while the build was in progress only to get an error message saying the version was already published on crates.io.

See #4377 for more fail-fast cases

### PR DESCRIPTION
**Pull request by stupendoussuperpowers**
Fixes #3662. Cleaned up commits from #14338.

### CODE REVIEW

**Comment by stupendoussuperpowers** [comment]
r? @epage 

Comments are rebased into 3 like we discussed on the last PR.

File: tests/testsuite/publish.rs [hunk 1]
```diff
@@ -158,23 +162,17 @@ fn duplicate_version() {
         .file("src/main.rs", "fn main() {}")
         .build();
 
+    p.cargo("publish")
+        .replace_crates_io(registry_dupl.index_url())
+        .without_status()
+        .run();
```
Comment (epage) [inline tests/testsuite/publish.rs:155]: This is publishing the package to ensure we get the error.

Does
```rust
    Package::new("too_new_child", "0.0.1")
        .rust_version("1.2345.0")
        .file("src/lib.rs", "fn other_stuff() {}")
        .publish();
```
work with the `RegistryBuilder` created earlier?

File: tests/testsuite/publish.rs [hunk 2]
```diff
@@ -132,14 +132,18 @@ You may press ctrl-c to skip waiting; the crate should be available shortly.
...
-                .to_vec(),
+        .add_responder("/index/3/f/foo", move |req, server| {
+            let mut lock = arc.lock().unwrap();
+            *lock += 1;
+            if *lock <= 1 {
+                server.not_found(req)
+            } else {
+                server.index(req)
+            }
         })
```
Comment (epage) [inline tests/testsuite/publish.rs]: If we have a published package, would `RegistryBuilder` do this for us or does it not correctly handle these cases?

**Comment by epage** [comment]
> Cleaned up commits

FYI what would be very helpful in reviewing would be
- Have the full structure of the tests in place in the test commit.  This would mean having the extra publish in that commit and the `RegistryBuilder` changes
- Squashing the text change into the primary commit
- Ensuring every commit passes tests

**Comment by ehuss** [comment]
I do not think this fixes https://github.com/rust-lang/cargo/issues/3662. We have been using that as a general-purpose issue to track validation of all sorts. There's a more detailed description of the pre-flight validation that we were considering in https://github.com/rust-lang/crates-io-cargo-teams/issues/82 that I think would need to be addressed to close #3662.

**Comment by stupendoussuperpowers** [comment]
This fix is one of many pre-flight checks mentioned in https://github.com/rust-lang/crates-io-cargo-teams/issues/82. Should all those checks be worked on separately or should they be all be added in the same PR? The discussion on #3662 mostly mentioned just the same version pre-flight check.

**Comment by ehuss** [comment]
I think it is good to land this PR; I don't think we need to block incremental improvements. The registry-based validation would be nice, and in theory could address all of the issues in one go, but I think is also significantly more work and will likely take a very long time even if someone worked hard on it.

**Comment by epage** [comment]
@ehuss what do you see the difference is between #3662 and #4377?

**Comment by ehuss** [comment]
Those look like duplicates of one another, though #4377 has more details.

File: tests/testsuite/publish.rs (hunk 1 above)
Comment (epage) [reply tests/testsuite/publish.rs]: This works with the fix, replacing the extra `cargo publish` call.

File: tests/testsuite/publish.rs (hunk 2 above)
Comment (epage) [reply tests/testsuite/publish.rs]: We do need a custom responder before the fix because our dev registry does not report duplicate package errors, so we can't just double publish to hit the test case.

**Comment by epage** [comment]
I went ahead and resolved the rebase and applied my review feedback

@bors r+
