### PR TITLE
Adjust submodule updating failure reporting

### LINKED ISSUE #3922: When updating dependency with submodules fails, make error source more apparent
Given a dependency `foo` which in it's dependent revision depends on a submodule revision that no longer exists the error message currently looks like this (only error part):

```
error: failed to load source for a dependency on `foo`
Caused by:
  Unable to update <foo-url>?rev=hash
```

and only with `--verbose` you see (only error part):

```
error: failed to load source for a dependency on `foo`
Caused by:
  Unable to update <foo-url>?rev=hash
Caused by:
  failed to update submodules
Caused by:
  [9/-3] object not found - no match for id (another_hash)
```

where `another_hash` is the submodule revision that cannot be found in the case of git.

This is a rather contrived example, but I think other people than me could achieve this as well if you happen to have:
 1. your own crate which...
 2. ...depends on a custom fork of a library where you develop a PR
 3. rebasing your PR on top of latest changes and force-pushing deletes the old revision

@alexcrichton noted that [error here should be more visible without needing `--verbose`](https://github.com/rust-lang/cargo/issues/3561#issuecomment-293947103) so I am opening an issue not to highjack the original issue in which this was discussed for any longer.

For the initial error without `--verbose`, perhaps the output should had been:

```
-error: failed to load source for a dependency on `foo`
+error: failed to update submodules for a dependency on `foo`
 Caused by:
-  Unable to update <foo-url>?rev=hash
+  Failed to update submodules of <foo-url>?rev=hash
```

I am hoping to fix this myself with some mentoring from alexcrichton. Does the proposed new error output look good enough?

### PR DESCRIPTION
**Pull request by koivunej**
This PR changes output of cargo when updating a dependency fails because of it's submodules cannot be loaded. In my original example this was caused by submodule pointing to a revision which was deleted by force pushing. Fixes #3922.

Before:

```
$ cargo check
    Updating git repository `<foo-url>`
error: failed to load source for a dependency on `foo`
Caused by:
  Unable to update <foo-url>?rev=hash
To learn more, run the command again with --verbose.
```

After:

```
$ cargo check
    Updating git repository `<foo-url>`
error: failed to load source for a dependency on `foo`
Caused by:
  Unable to update <foo-url>?rev=hash
Caused by:
  Failed to update submodule `submodule`
To learn more, run the command again with --verbose.
```

`--verbose` showing an additional `[9/-3] object not found - no match for id (hash)` has not been changed.

@alexcrichton since we have this nice timezone difference there was no chance of mentoring so far but any comments/suggestions are highly welcome. I'll likely check back on this next week.

### CODE REVIEW

File: src/cargo/sources/git/utils.rs [hunk 1]
```diff
@@ -296,52 +294,61 @@ impl<'a> GitCheckout<'a> {
             info!("update submodules for: {:?}", repo.workdir().unwrap());
 
             for mut child in repo.submodules()?.into_iter() {
-                child.init(false)?;
-                let url = child.url().chain_error(|| {
-                    internal("non-utf8 url for submodule")
+                update_submodule(repo, &mut child, cargo_config).chain_error(|| {
+                    human(format!("Failed to update submodule `{}`",
```
Comment (alexcrichton) [inline src/cargo/sources/git/utils.rs]: Idiomatically cargo errors start with a lowercase letters, could that be updated here?

Comment (koivunej) [inline src/cargo/sources/git/utils.rs]: After very small sampling I understood that `human` variants start with uppercase but `internal` with lowercase but I will fix this soonish.

I made this a `human` variant as it needs to be shown without `--verbose` without checking any of the reporting code.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks again @koivunej!
