### PR TITLE
Load credentials only when needed

### LINKED ISSUE #7624: cargo build fails when ~/.cargo/credentials is unreadable
**Problem**

When running cargo inside a sandbox that rejects access to ~/.cargo/credentials, `cargo build` fails. I prefer to run VScode in a sandbox and not give it access to confidential files such as ~/.cargo/credentials. `cargo build` really shouldn't need access to my credentials, so this seems like it should be avoidable.

**Steps**

1. Change permissions such that ~/.cargo/credentials is unreadable
2. Do some cargo action that does *not* require credentials
3. You get: `error: Permission denied (os error 13)`

~~The error message is quite bad as it doesn't even say which file is affected! I had to use `strace` to determine that (which was hard because strace is blocked in the sandbox...)~~

> EDIT: Error message fixed via #7649.

**Possible Solution(s)**

Only read credentials when needed, i.e., in  `cargo publish`.

**Notes**

Output of `cargo version`:
```
cargo 1.41.0-nightly (8280633db 2019-11-11)
```

### PR DESCRIPTION
**Pull request by giraffate**
Credentials are always loaded, even if these are not used. If
access to confidential files such as credentials is not given,
`cargo build` fails despite not using credentials.

Fixes #7624.

### CODE REVIEW

File: src/cargo/util/config/mod.rs [hunk 1]
```diff
@@ -1006,7 +1004,28 @@ impl Config {
             }
         }
 
-        cfg.merge(value, true)?;
+        if let CV::Table(mut map, _) = value {
```
[the remark this answers is not in the document]
Comment (giraffate) [reply src/cargo/util/config/mod.rs]: This function is modified not to receive `cfg: &mut ConfigValue` as an argument, so I think that merge can not be used. However, I may simply not know how to use merge in `Config`, so could you tell me if there is any good way?

[the remark this answers is not in the document]
Comment (ehuss) [reply src/cargo/util/config/mod.rs]: Ah, I see.  Would it be possible to just loop over the key/values of the map and merge/insert all of them instead of hard-coding the keys here?

[the remark this answers is not in the document]
Comment (giraffate) [reply src/cargo/util/config/mod.rs]: Thanks for your advice! I fixed it.

File: tests/testsuite/yank.rs [hunk 2]
```diff
@@ -0,0 +1,47 @@
+//! Tests for the `cargo yank` command.
+
+use std::fs::{self, File};
+use std::io::prelude::*;
+
+use cargo_test_support::project;
+use cargo_test_support::registry::{self, api_path, registry_url};
+
+fn setup(name: &str, version: &str) {
+    fs::create_dir_all(&api_path().join(format!("api/v1/crates/{}/{}", name, version))).unwrap();
```
Comment (ehuss) [inline tests/testsuite/yank.rs]: I think this can be simplified a little with:

```rust
    let dir = api_path().join(format!("api/v1/crates/{}/{}", name, version));
    dir.mkdir_p();
    fs::write(dir.join("yank"), r#"{"ok": true}"#).unwrap();
```

`mkdir_p` needs `use cargo_test_support::paths::CargoPathExt;`

File: tests/testsuite/owner.rs [hunk 3]
```diff
@@ -0,0 +1,53 @@
+//! Tests for the `cargo owner` command.
+
+use std::fs::{self, File};
+use std::io::prelude::*;
+
+use cargo_test_support::project;
+use cargo_test_support::registry::{self, api_path, registry_url};
+
+fn setup(name: &str) {
+    fs::create_dir_all(&api_path().join(format!("api/v1/crates/{}", name))).unwrap();
```
Comment (ehuss) [inline tests/testsuite/owner.rs]: Similar to yank.

```rust
    let dir = api_path().join(format!("api/v1/crates/{}", name));
    dir.mkdir_p();
    // ...
    fs::write(dir.join("owners"), content).unwrap();
```

File: tests/testsuite/publish.rs [hunk 4]
```diff
@@ -1261,3 +1261,40 @@ repository = "foo"
         )],
     );
 }
+
+#[cargo_test]
+fn credentials_ambiguous_filename() {
+    registry::init();
+
+    let credentials_toml = paths::home().join(".cargo/credentials.toml");
+    File::create(&credentials_toml)
```
Comment (ehuss) [inline tests/testsuite/publish.rs]: `fs::write` here too.

File: src/cargo/util/config/mod.rs [hunk 5]
```diff
@@ -1006,7 +1004,16 @@ impl Config {
             }
         }
 
-        cfg.merge(value, true)?;
+        if let CV::Table(map, _) = value {
```
Comment (ehuss) [inline src/cargo/util/config/mod.rs]: Can this maybe be simplified a little instead of removing and reinserting?  Maybe something like this?

```rust
        if let CV::Table(map, _) = value {
            let base_map = self.values_mut()?;
            for (k, v) in map {
                match base_map.entry(k) {
                    Vacant(entry) => { entry.insert(v); }
                    Occupied(mut entry) => { entry.get_mut().merge(v, true)? }
                }
            }
        }
```

**Comment by giraffate** [comment]
Thanks for your review! I fixed it.

**Comment by ehuss** [comment]
Great, thanks!
@bors r+
