### PR TITLE
Fix sparse registry lockfile urls containing 'registry+sparse+'

### LINKED ISSUE #10963: sparse registry: incorrect SourceID URL serialization for alt registries
### Problem

When using sparse-registry with an alternative registry, the SourceID is rendered as `registry+sparse+https://...`. That doesn't look correct to me, I would assume it should be `sparse+https://…`.

### Steps

The following cargo test illustrates the example where the SourceID gets shown to the user.

```rust
#[cargo_test]
fn sparse_alt_registry() {
    let _server = RegistryBuilder::new().http_index().alternative().build();

    let p = project()
        .file(
            "Cargo.toml",
            r#"
                [project]
                name = "foo"
                version = "0.0.1"
                authors = []

                [dependencies]
                bar = {registry="alternative", version=">= 0.0.0"}
            "#,
        )
        .file("src/main.rs", "fn main() {}")
        .build();

    Package::new("bar", "0.0.1").alternative(true).publish();

    cargo_http(&p, "build --message-format=json")
        // SourceID issue is here...
        .with_stderr("")
        .run();
}
```

Here the JSON will have things like `"package_id":"bar 0.0.1 (registry+sparse+http://127.0.0.1:61095/index/)"`

### Possible Solution(s)

The issue is that the serialization code [here](https://github.com/rust-lang/cargo/blob/e6827eee9b6720a1bd69c6115cac22f8125b24aa/src/cargo/core/source/source_id.rs#L679-L683) doesn't know anything about sparse registries.

My intuition is that `SourceKind` should have another variant to track sparse indexes (instead of reusing SourceKind::Registry). This is related to the comment [here](https://github.com/rust-lang/cargo/pull/10470#discussion_r832484967) about it being a little strange that `sparse+` is being tacked into the URL.

### Notes

I would also like to see more tests for alt registries using sparse registries.

### Version

```text
cargo 1.64.0-nightly (85b500cca 2022-07-24)
release: 1.64.0-nightly
commit-hash: 85b500ccad8cd0b63995fd94a03ddd4b83f7905b
commit-date: 2022-07-24
host: x86_64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.79.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.4.0 [64-bit]
```

### PR DESCRIPTION
**Pull request by arlosi**
The `Cargo.lock` file for alternative sparse registries incorrectly lists the url as `registry+sparse+` rather than `sparse+`.

Fixes #10963

### CODE REVIEW

File: src/cargo/core/source/source_id.rs [hunk 1]
```diff
@@ -680,7 +680,13 @@ impl<'a> fmt::Display for SourceIdAsUrl<'a> {
                 kind: SourceKind::Registry,
                 ref url,
                 ..
-            } => write!(f, "registry+{}", url),
+            } => {
+                if url.scheme().starts_with("sparse+") {
+                    write!(f, "{}", url)
+                } else {
+                    write!(f, "registry+{}", url)
+                }
```
Comment (weihanglo) [inline src/cargo/core/source/source_id.rs:688]: (nit)
Looks reasonable but a bit subtle. Should we document the output URL as comments? Such as

```suggestion
                // For sparse http registry the URL already contains the prefix.
                if url.scheme().starts_with("sparse+") {
                    // e.g. sparse+http://example.com
                    write!(f, "{url}")
                } else {
                    // e.g. registry+http://example.com
                    write!(f, "registry+{url}")
                }
```

**Review by weihanglo — APPROVED** [review]
Make sense. Thanks for the patch!

File: src/cargo/core/source/source_id.rs (hunk 1 above)
Comment (arlosi) [reply src/cargo/core/source/source_id.rs]: Yes, thanks!

**Comment by weihanglo** [comment]
Thank you so much!

@bors r+

**Comment by ehuss** [comment]
I'm wondering if it might help to add a new `SourceKind` variant instead of trying to check string values. I don't recall if this was discussed anywhere, but I was wondering what you think about that?
