### PR TITLE
Iteratively construct target cfg

### LINKED ISSUE #6858: Enabling target features in .cargo/config does not work for cfg statements in Cargo.toml
Originally reported in RustCrypto/stream-ciphers#11

Create a project with following files. Cargo.toml:
```toml
[target.'cfg(target_feature="aes")'.dependencies]
either = "*"
```

.cargo/config:
```toml
[target.'cfg(any(windows, unix))']
rustflags = ["-Ctarget-feature=+aes"]
```

src/main.rs:
```rust
#[cfg(target_feature="aes")]
fn main() { println!("aes enabled"); }

#[cfg(not(target_feature="aes"))]
fn main() { println!("aes disabled"); }
```

Running `cargo run` outputs "aes disabled" as expected, but `either` crate does not get downloaded, i.e. `cfg` statement in `Cargo.toml` does not work as expected. And as a consequence adding `#[cfg(target_feature="aes")] extern crate either;` to `main.rs` results in a compilation error. Meanwhile `RUSTFLAGS="-C target-feature=+aes" cargo run` works as expected without any issues.

### PR DESCRIPTION
**Pull request by matklad**
When setting target features via rustflags via `[build]` config key, cargo correctly propagates them to rustc (via -C flag) and to build.rs (via CARGO_CFG_TARGET_FEATURE env var).

However, if `[target.cfg]` is used instead, build.rs doesn't get the flags (rustc still gets them though).

This changes it so that cargo will call `rustc` up to two times to collect the `cfg` values, updating which flags to use on the second call based on the cfg discovered in the first call.

Closes #6858.

### CODE REVIEW

**Comment by matklad** [comment]
Ok, I think I've debugged what is happening here.  The core of the issue is that we get an inconsistent `TargetInfo` at some point, which looks like this: 

```
TargetInfo {
  rustflags: ["-Ctarget-feature=+sse4.1,+sse4.2"]
  cfg: debug_assertions,panic = "unwind",target_arch = "x86_64",target_endian = "little",target_env = "gnu",target_family = "unix",target_feature = "fxsr",target_feature = "sse",target_feature = "sse2",target_has_atomic = "16",target_has_atomic = "32",target_has_atomic = "64",target_has_atomic = "8",target_has_atomic = "ptr",target_os = "linux",target_pointer_width = "64",target_vendor = "unknown",unix
}
```

that is, rusflags says that we have sse4.2, but cfg say we don't. When we run build.rs, we look at the cfg. When we run the actual compiler, we use RUSTFLAGS, hence the discrepancy. 


I think the issue lies in this logic: 

https://github.com/rust-lang/cargo/blob/8dea81918bed56025b7b1b4ecd02a3a850bf5eab/src/cargo/core/compiler/build_context/target_info.rs#L236-L245

What happens here is that rustflags and cfgs are mutually dependent: rustflags determine rustc's cfgs, and cfgs determine which config sections apply, which might affect rustflags. The code currently does one-and-a-half iterations of fixed point algorithm.

**Comment by matklad** [comment]
The last commit adds a fixed-point iteration loop, as a crude hack. That looks somewhat amusing, in not a good way, so I think I'll pause here and wait for feedback from Cargo team on this one!

**Comment by ehuss** [comment]
There is some more background on this general problem in #6858. I've been reluctant to run `rustc` in a loop because it can take hundreds of milliseconds to run each time. I would be a little more comfortable doing that if it could bypass rustup (#10986, https://github.com/rust-lang/rustup/issues/3031, https://github.com/rust-lang/rustup/issues/3035).  However, I believe this should only be a problem if `rustflags` is explicitly set in a `target` config table, right? And that should only affect the first uncached run, right?

It might be good to also give some careful consideration on the backwards compatibility hazards with this change. Will it change the behavior for existing projects in a meaningful way? 

The overall approach seems reasonable to me.

File: src/cargo/core/compiler/build_context/target_info.rs [hunk 1]
```diff
@@ -138,122 +138,133 @@ impl TargetInfo {
...
+                    &rustc.host,
+                    Some(&cfg),
+                    kind,
+                    Flags::Rustdoc,
+                )?,
+                cfg,
+                supports_split_debuginfo,
+            });
+        }
+        anyhow::bail!("diverging rustflags")
```
Comment (ehuss) [inline src/cargo/core/compiler/build_context/target_info.rs:267]: Before merging, I think it would be good to make this error a little more descriptive.

I also wouldn't say it is necessarily diverging. It could just be that it requires more steps to finish.

**Comment by matklad** [comment]
Yeah, this all sounds reasonable. We indeed should only run this when needed, and it indeed should be cached. Given that the use-case here is essentially "set cfgs based on other cfgs", I don't see a better fundamental solution. 

For my specific use-case (setting target_features), I would imagine a more specialized solution (like a dedicated key in the profile or what not) would work, but, even if we had that, it still is very surprising that today's code observes inconsistent information between build.rs and rustc. 

Regarding backwards compatibility, yeah.... This definitely would affect some builds, probably not too many, and probably by making them more correct, but "fixing builds" tends annoy people also :) I guess my value judgement is that this is a rather obscure corner case, so few folks would be affected, and it feels like its' worth fixing (in our case, we get a significant but suble perf regression due to sse flags not propagating to our C deps). 

Thats why, after sleeping on it, I figured that outright erroring-out is probably not the right call here, so:

* I restricted us to do only 2 iterations
* I warn, rather than error, if that's not enough

This, at least, is guaranteed to not outright bork any existing builds. I've also added a test which fixes the current behavior.

**Comment by ehuss** [comment]
Sounds reasonable to me.  Thanks!

@bors r+
