### PR TITLE
fix(info): resolve underscore vs hyphen mismatch in schema lookup

### LINKED ISSUE #16442: Cargo info does not support underscore (_) for packages named with hyphen (-)
### Problem

I expected the commands to be equivalent:

```bash
cargo info esp_println # with _ 
cargo info esp-println # with -
```

The latter is the actual name and runs fine. The former (with underscore) instead, says:

> error: could not find `esp_println` in registry `https://github.com/rust-lang/crates.io-index`

### Steps

```bash
cargo info esp_println # with _ 
cargo info esp-println # with -
```

### Possible Solution(s)

Both should return the same output.

But if this is intentional a help message here suggesting replacing `_` with `-` would be helpful. 

I would say the same about `-F` flag, they should both be consistent with `add` imho and check for both `_` and `-`.

---------

Thanks for this great software, it's one of my favourites ever.

### PR DESCRIPTION
**Pull request by dhruv-38**
### What does this PR try to resolve?

_This PR makes `cargo info` handle crate names with underscores (`_`) the same way as cargo add, by translating underscores to_ _hyphens (`-`) and emitting a warning and also the other way around._

_Currently, `cargo info my_package` and `cargo info my-crate` fails even when the actual crate name is `my-package` and `my_crate` respectively, which is surprising and inconsistent with other Cargo commands. This change aligns cargo info with_
_existing behavior and improves usability._

Fixes #16442 
### How to test and review this PR?

_Run the added tests:_
_`cargo test --test testsuite -- cargo_info::crate_name_normalization_from_hyphen_to_underscore`_
_`cargo test --test testsuite -- cargo_info::crate_name_normalization_from_underscore_to_hyphen`_

_Manually verify behavior:_
_`cargo info esp_println`_
_`cargo info big-s`_

_This should succeed, show a warning about translating `_` to `-` and also `-` to `_`, and display the crate info._

_The change includes a test that captures the previous failing behavior and verifies the new expected output._

### CODE REVIEW

**Comment by dhruv-38** [comment]
i will add one more commit for the functionality change, before that please check this code if it is good or not?

File: tests/testsuite/cargo_info/mod.rs [hunk 1]
```diff
@@ -16,6 +16,7 @@ mod specify_version_with_url_but_registry_is_not_matched;
 mod specify_version_within_ws_and_conflict_with_lockfile;
 mod specify_version_within_ws_and_match_with_lockfile;
 mod transitive_dependency_within_ws;
+mod underscore_alias;
```
Comment (ranger-ross) [inline tests/testsuite/cargo_info/mod.rs]: nit: personally I think naming the test `crate_name_normalization` might be a bit more descriptive

Comment (ranger-ross) [reply tests/testsuite/cargo_info/mod.rs]: this is technically not an "alias" and more of cargo trying to be helpful by guessing what you meant

Comment (ranger-ross) [reply tests/testsuite/cargo_info/mod.rs]: Another thought, do we want to have a test for going in the other direction? Underscore to hyphen

Comment (dhruv-38) [reply tests/testsuite/cargo_info/mod.rs]: I think we don't have, but i can create for another direction. I think we should have it. So it will be normalised regarless of direction.

**Comment by ranger-ross** [comment]
From discussion in [#general > writing test for cargo @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/122651-general/topic/writing.20test.20for.20cargo/near/566195204)

> One question about the selection behavior (MSRV) is: If there are 2 crates foo-bar (MSRV 1.91) and foo_bar (MSRV 1.70) and I execute cargo info foo-bar from a workspace that has an MSRV lower than 1.91 which crate should be selected. For me I feel cargo info should not change the crate name if there is an exact match, even if that exact match does not satisfy the MSRV of the current workspace.

Currently Cargo will prioritize crates that match the current workspace's MSRV ([ref](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/registry/info/mod.rs#L144)) when selecting the package.
This is less noticable when we have an `Exact` query as it only affects versions.
With normalized queries its possible for Cargo have an exact match that does not satisfy the MSRV, so we could potentially select a different crate even though the exact match exists. (which feels like the wrong behavior for `cargo info` to me)

Not sure how others feel about this behavior but I wanted to call this out during review. 

Edit: Apparently crates.io does not allow publishing crates with the same name as an existing crate with hyphens instead of underscores and vise versa. So my concern here might not be a problem in practice. Though unsure if we need to worry about 3rd party registries. I don't see this behavior specified in the [Cargo registry API docs](https://doc.rust-lang.org/cargo/reference/registry-web-api.html).

File: src/cargo/ops/registry/info/mod.rs [hunk 2]
```diff
@@ -188,18 +206,24 @@ fn query_summaries(
...
             std::task::Poll::Pending => registry.block_until_ready()?,
         }
-    }
+    };
+
+    let normalized_name = normalized
+        .first()
+        .map(|s| s.package_id().name().to_string());
+
+    Ok((normalized, normalized_name))
```
Comment (ranger-ross) [inline src/cargo/ops/registry/info/mod.rs]: I feel like this is overly complicated? 

Why not just remove the `.filter()` in `find_pkgid_in_summaries()`.

File: src/cargo/ops/registry/info/mod.rs [hunk 3]
```diff
@@ -188,18 +206,24 @@ fn query_summaries(
...
     registry: &mut PackageRegistry<'_>,
     source_ids: &RegistrySourceIds,
-) -> CargoResult<Vec<IndexSummary>> {
+) -> CargoResult<(Vec<IndexSummary>, Option<String>)> {
     // Query without version requirement to get all index summaries.
     let dep = Dependency::parse(spec.name(), None, source_ids.original)?;
-    loop {
-        // Exact to avoid returning all for path/git
-        match registry.query_vec(&dep, QueryKind::Exact) {
+    let normalized = loop {
```
Comment (ranger-ross) [inline src/cargo/ops/registry/info/mod.rs]: nit: I think `results` would be a better variable name here, as this is querying the registry, not just normalizing the crate name

File: src/cargo/ops/registry/info/mod.rs
Comment (ranger-ross) [inline src/cargo/ops/registry/info/mod.rs:1]: Looks like some other `cargo info` tests are failing now. ([ref](https://github.com/rust-lang/cargo/actions/runs/20692063431/job/59401597213?pr=16455))

```
failures:
    cargo_info::specify_version_with_url_but_registry_is_not_matched::case
    cargo_info::specify_version_within_ws_and_conflict_with_lockfile::case
```

For `specify_version_with_url_but_registry_is_not_matched` this test is failing as previously specifying the full URL for a crate would not work. 
```
cargo info https://crates.io/crates/esp-println
error: could not find `https://crates.io/crates/esp-println` in registry `https://github.com/rust-lang/crates.io-index`
```
However a side effect of `QueryKind::Normalized` is that this now works.
Interestingly, `cargo add` does not appear to support URL crate format:
```
cargo add 'https://crates.io/crates/esp-println'
error: invalid character `:` in package name: `https://crates.io/crates/esp-println`, characters must be Unicode XID characters (numbers, `-`, `_`, or most letters)
```

We might need to add some additional validation on the input similar to `cargo add`. 
See [`PackageName::new()`](https://github.com/rust-lang/cargo/blob/master/crates/cargo-util-schemas/src/manifest/mod.rs#L1450)

File: src/cargo/ops/registry/info/mod.rs (hunk 2 above)
Comment (dhruv-38) [reply src/cargo/ops/registry/info/mod.rs]: I didn't remove the `.filter()` because what if we run `cargo info foo@1.2.8` and the latest is `foo@2.1.4`, so it will be taken as the latest one, not for that specific version.

File: src/cargo/ops/registry/info/mod.rs (hunk 3 above)
Comment (dhruv-38) [reply src/cargo/ops/registry/info/mod.rs]: ok i will do it

File: src/cargo/ops/registry/info/mod.rs
Comment (ranger-ross) [reply src/cargo/ops/registry/info/mod.rs:1]: See this reply in Zulip [#general > writing test for cargo @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/122651-general/topic/writing.20test.20for.20cargo/near/566543308)

File: src/cargo/core/package_id_spec.rs [hunk 4]
```diff
@@ -38,7 +42,15 @@ impl PackageIdSpecQuery for PackageIdSpec {
     }
 
     fn matches(&self, package_id: PackageId) -> bool {
-        if self.name() != package_id.name().as_str() {
+        self.matches_opts(package_id, false)
+    }
```
Comment (ranger-ross) [inline src/cargo/core/package_id_spec.rs]: nit: this could be a default impl in the `PackageIdSpecQuery`, but I suppose it does not matter

**Review by ranger-ross — APPROVED** [review]
These changes look good to me.

Given that @0xPoe is the one that added this command originally, I'll assign them for a Cargo team member review :)

r? @0xPoe 

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16455/1436cf98c4cd6104995f9fb919b918c8cdd23c33..3e8367f6842c18804c3fa7a068475a5d04b73726)*

File: tests/testsuite/cargo_info/crate_name_normalization/mod.rs [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+        .stderr_eq(file!["stderr1.term.svg"]);
+
+    snapbox::cmd::Command::cargo_ui()
+        .arg("info")
+        .arg("my-crate") //hyphen on purpose to show the error
+        .arg("--registry=dummy-registry")
+        .assert()
+        .failure()
+        .stdout_eq(file!["stdout2.term.svg"])
+        .stderr_eq(file!["stderr2.term.svg"]);
```
Comment (epage) [inline tests/testsuite/cargo_info/crate_name_normalization/mod.rs]: These seem like independent test cases, is there a reason they are in the same test?

File: src/cargo/core/package_id_spec.rs [hunk 6]
```diff
@@ -38,7 +42,15 @@ impl PackageIdSpecQuery for PackageIdSpec {
...
+
+    fn matches_opts(&self, package_id: PackageId, normalize_name: bool) -> bool {
```
Comment (epage) [inline src/cargo/core/package_id_spec.rs]: Not thrilled with boolean parameters

Comment (epage) [inline src/cargo/core/package_id_spec.rs]: Why do we need this?  I see we do a `.matches` but I'm confused as to why

File: tests/testsuite/cargo_info/crate_name_normalization/mod.rs (hunk 5 above)
Comment (dhruv-38) [reply tests/testsuite/cargo_info/crate_name_normalization/mod.rs]: Yes they come under the same test for checking the normalization of crate name which checks  `_` ->`-` and `-`to -> `_`

They are very much similar work so i kept under the same test.

File: src/cargo/core/package_id_spec.rs (hunk 6 above)
Comment (dhruv-38) [reply src/cargo/core/package_id_spec.rs]: Yes we do have `.match` but this handle it very differently and don't check for the normalised crate name like `cargo info foo_bar` but in registry it is present `foo-bar` so it will reject it but it should not since this is a minor error. This should run with a warning of converting.

File: tests/testsuite/cargo_info/crate_name_normalization/mod.rs (hunk 5 above)
Comment (epage) [reply tests/testsuite/cargo_info/crate_name_normalization/mod.rs]: We generally would have these as separate tests
- their fixtures are different
- their UI is being tested separately

File: src/cargo/core/package_id_spec.rs (hunk 6 above)
Comment (epage) [reply src/cargo/core/package_id_spec.rs]: What I'm wondering about is why the `.match` call is present.  We already have a `query_summaries` before we find among them.  Doesn't that do the filtering for us?

File: tests/testsuite/cargo_info/crate_name_normalization/mod.rs (hunk 5 above)
Comment (dhruv-38) [reply tests/testsuite/cargo_info/crate_name_normalization/mod.rs]: ok i can do that also. Should i go ahead?

File: src/cargo/core/package_id_spec.rs (hunk 6 above)
Comment (dhruv-38) [reply src/cargo/core/package_id_spec.rs]: Yes `query_summary` is present to find out the normalized one, so there is this line `package_id` if this is not present while checking the crate in the registry, it finds `package_id`  in `find_pkgid_in_summaries` here, we do filtering with the name

Comment (dhruv-38) [reply src/cargo/core/package_id_spec.rs]: The purpose of this is for checking whether any normalization happened or not. Should I do something like a variable `isnormalized_name` or leave it like that?

File: tests/testsuite/cargo_info/crate_name_normalization/mod.rs (hunk 5 above)
Comment (epage) [reply tests/testsuite/cargo_info/crate_name_normalization/mod.rs]: Yes, please split this test

File: src/cargo/core/package_id_spec.rs (hunk 6 above)
Comment (epage) [reply src/cargo/core/package_id_spec.rs]: So there are two problems with this function
- the name does not convey what it does (it has opts, ok but what?)
- it takes a boolean which can make it unclear what this function does at the call site (`matches_opts(something, true)`, what does that do?)

One philosophy of API design is if a function's parameter is static then it should really be a separate function.  We don't do that with `query_vec`, largely because that was how it started and it has a fairly deep stack for parallel calls.

Another approach for improving this is to have a `QueryKind` parameter which will make the bool's behavior clear.

In this case, I would likely just go with a unique function name though not too sure what I would call it at this point.  Having "normalized" in there would help create a connection with `QueryKind`.  So `matches_normalized`?

Comment (epage) [reply src/cargo/core/package_id_spec.rs]: Ah, I think what is happening is `query_summaries` is returning all summaries for a source + name.  In `find_pkgid_in_summaries` we are then filtering by version within the spec but also running into the problem that the name didn't match exactly.

Maybe what we should do is check what name was returned in the summaries (they should all be the same) and rewrite the `spec` to use the normalized name.

Comment (dhruv-38) [reply src/cargo/core/package_id_spec.rs]: That makes sense, I agree the boolean hurts readability. I’ll split this into a `matches_normalized` helper so the intent is clear at the call site.

Comment (dhruv-38) [reply src/cargo/core/package_id_spec.rs]: if we rewrite the `spec` that would be great, i thought of it initially, i was unsure that is it a good thing to change the spec  to use the nomalized name then all these functions and would not be required to create. Just change the `QueryKind::Normalized` and update the `spec`; that's it, no changes are required elsewhere.

Comment (dhruv-38) [reply src/cargo/core/package_id_spec.rs]: Which one should i go with making of `matches_normalized` one or changing the `spec` name parameter?

Comment (epage) [reply src/cargo/core/package_id_spec.rs]: I lean towards changing the spec as it is the least intrusive

**Comment by 0xPoe** [comment]
I just renamed the PR title, as we usually only include one type in the Conventional Message.

File: src/cargo/core/package_id_spec.rs (hunk 6 above)
Comment (dhruv-38) [reply src/cargo/core/package_id_spec.rs]: the spec is of type `&PackageIdSpec` which is not mutable either we have to change the mutability at the call or we have to initailze a new `PackageIdSpec` for it clone the other things then pass to the `find_pkgid_in_summaries`
i am not sure to whether i should change the mutability or not? for now i going with the clone.

File: src/cargo/ops/registry/info/mod.rs [hunk 7]
```diff
@@ -78,10 +78,33 @@ pub fn info(
     // For workspace members, `cargo tree --package <SPEC> --invert` is useless. It only prints itself.
     let suggest_cargo_tree_command = package_id.is_some() && !is_member;
 
-    let summaries = query_summaries(spec, &mut registry, &source_ids)?;
+    let (summaries, normalized_name) = query_summaries(spec, &mut registry, &source_ids)?;
+    let new_spec = if let Some(name) = normalized_name {
```
Comment (epage) [inline src/cargo/ops/registry/info/mod.rs]: `new_spec` -> `normalized_spec`

File: src/cargo/ops/registry/info/mod.rs [hunk 8]
```diff
@@ -78,10 +78,33 @@ pub fn info(
...
+        if name != spec.name() {
```
Comment (epage) [inline src/cargo/ops/registry/info/mod.rs]: Can these ifs be merged?

File: tests/testsuite/cargo_info/crate_name_normalization_from_hyphen_to_underscore/mod.rs
Comment (epage) [inline tests/testsuite/cargo_info/crate_name_normalization_from_hyphen_to_underscore/mod.rs:1]: Please remember to clean up the commits to reflect what should be reviewed and merged and not the development process

Comment (dhruv-38) [reply tests/testsuite/cargo_info/crate_name_normalization_from_hyphen_to_underscore/mod.rs:1]: Done

Comment (dhruv-38) [reply tests/testsuite/cargo_info/crate_name_normalization_from_hyphen_to_underscore/mod.rs:1]: Anything else is also required?

**Review by epage — APPROVED** [review]
Thanks @dhruv-38 for implementing this and @ranger-ross for reviewing it!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16455/c9895a1b0cc25c85db6b2a03c0e30e940ebc3253..dea0635a6c2e783c5ba1034dfc6e94f514d58693)*
