### PR TITLE
Fix false positive about unused replace

### LINKED ISSUE #3861: Cargo workspaces and `[replace]` may give a spurious warning
(accidentally raised at https://github.com/rust-lang/rfcs/issues/1957)

### Repro

https://github.com/chriscoomber/workspace_replace_example

### Symptoms

If I'm using workspaces, and I put a `[replace]` block in the workspace's `Cargo.toml`,  

then any crates within my workspace directory that **don't** depend on the crate being replaced produce the warning:

```
warning: package replacement is not used: ...
```

This is spurious because I've done nothing wrong. This exact usage is [what the rfc recommends](https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md#lockfile-and-override-interactions) (unless I'm reading it wrong). Indeed, `[replace]` is totally ignored on non-workspace `Cargo.toml` files if a workspace exists (I just tested this).

This is undesirable because warnings like these may causes automatic builds to fail, which look for warnings.

### Workaround

So far I haven't figured out a workaround. For example - is the a flag I can pass to cargo to ignore this warning in particular? Is there a way to undo the `[replace]` on the crates that aren't affected?

### PR DESCRIPTION
**Pull request by matklad**
closes #3861 
@chriscoomber thanks for the great repro!

### CODE REVIEW

File: src/cargo/ops/resolve.rs [hunk 1]
```diff
@@ -49,6 +49,14 @@ pub fn resolve_ws_precisely<'a>(ws: &Workspace<'a>,
 
         add_overrides(&mut registry, ws)?;
 
+        for &(ref replace_spec, ref dep) in ws.root_replace() {
+            if !resolve.iter().any(|r| replace_spec.matches(r) && !dep.matches_id(r)) {
```
Comment (matklad) [inline src/cargo/ops/resolve.rs]: Not sure that this is 100% correct: the idea is that replacement should match at least one package in the graph, but we also want to filter out the cases where replacement matches only itself. 

So for something like

```
[replace]
foo = bar
bar = foo
```

this won't report an error, but presumably such cases are unrealistic.

**Comment by alexcrichton** [comment]
@bors: r+

Looks great, thanks @matklad! Also yeah that seems like an ok case to not worry about, false positives are much worse than false negatives in this regard.
