### PR TITLE
Config file loaded via CLI takes priority over env vars

### LINKED ISSUE #10992: Environment variables override cargo --config <filename> in precedence
### Problem

If both an environment variable and `cargo --config <filename>` are specified at the same time, the environment variable overrides the file passed in over the CLI. This is counter-intuitive and also the documentation at https://doc.rust-lang.org/cargo/reference/config.html#command-line-overrides is unclear about this:

> Configuration values specified this way take precedence over environment variables, which take precedence over configuration files.

### Steps

Create `.cargo/foo.toml`:

```toml
[build]
target-dir = "from-foo-toml"
```

Then, run:

```
CARGO_BUILD_TARGET_DIR=from-env cargo build --config .cargo/foo.toml
```

Notice that the build happens in "from-env" rather than the expected "from-too-toml".

### Possible Solution(s)

I think the behavior should be changed so that config files passed in over `--config` come first and environment variables come later.

(Unlike #10991, this I think is straight-up incorrect and should be fixed.)

### Notes

I'm guessing this is a regression from #10755 and specifically [this change](https://github.com/rust-lang/cargo/pull/10755/files#diff-2798557959dfa91ff5779c9aabb6d536dec3219465e53ab7e101570bf2899468), though I could be wrong. cc @jonhoo, @ehuss 

### Version

```text
cargo 1.63.0 (fd9c4297c 2022-07-01)
release: 1.63.0
commit-hash: fd9c4297ccbee36d39e9a79067edab0b614edb5a
commit-date: 2022-07-01
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1n)
os: Pop!_OS 22.04 (jammy) [64-bit]
```

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

Fixes #10992

Behaviour changes: After this commit, config files loaded via CLI take
priority over env vars. Config files loaded via [`config-include`]
feature also get a higher priority over env vars, if the initial config
file is being loaded via CLI.

Cargo knows why it loads a specific config file with `WhyLoad` enum,
and store in the field of `Definition::Cli(…)`. With this additional data,
config files loaded via `--config <path>` get a `Definition::Cli(Some(…))`.
In contrast, `--config <value>` with ordinary values become `Definition::Cli(None)`.

The error message of the `Definition::Cli(Some(…))` is identical to
`Definition::Path(…)`, so we won't lose any path information to debug.

[`config-include`]: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#config-include

### How should we test and review this PR?

Reviewing commit by commit is probably fine. The first two commits adding tests to `config-cli` and `config-include`, which exercises the expected behaviour we are going to fix in the next commits.

To check the precedence, set up a project with an extra config file, such as

```
# Expect to have a target-dir named `foo`
CARGO_BUILD_TARGET_DIR='env' cargo c --config 'build.target-dir = "cli"' --config .cargo/foo.toml

# Inside .cargo/foo.toml
[build]
target-dir = "foo"
```

### Additional information

This is a bit hacky IMO. I don't like leaking the path info to `Definition::Cli`. However, it is really tricky to provide information for deserialization before values get merged.

### CODE REVIEW

File: tests/testsuite/config_include.rs [hunk 1]
```diff
@@ -254,3 +254,31 @@ Caused by:
   expected array, but found string",
     );
 }
+
+#[cargo_test]
+fn cli_include_take_prioirty_over_env() {
```
Comment (jonhoo) [inline tests/testsuite/config_include.rs:259]:
```suggestion
fn cli_include_take_priority_over_env() {
```

**Review by jonhoo — APPROVED** [review]
Looks good to me, subject to one typo in the test name :sweat_smile:

**Comment by ehuss** [comment]
Thanks!

@bors r+
