### PR TITLE
fix(resolver): Don't do git fetches when updating workspace members

### LINKED ISSUE #8821: `cargo update --package X` updates other git repositories
**Problem**

`cargo update -p` should only update the specify package. Instead, it updates git repositories as well.

**Steps**

1. `git clone https://github.com/rust-lang/crater/`
2. `cd crater`
3. `git checkout dcc54566d5ec82cabca435c0145cbd06f32d3602`
4. `cargo update -p crater`

```
$ cargo update -p crater
    Updating crates.io index
    Updating git repository `https://github.com/rust-lang/team`
    Updating rust_team_data v1.0.0 (https://github.com/rust-lang/team#8d8902d7) -> #a3c474be
```

Output of `cargo version`: cargo 1.47.0 (f3c7e066a 2020-08-28)

### LINKED ISSUE #12599: Cargo update -p <localcrate> in a workspace has inconsistent behaviors
Cargo's handling of `cargo update -p <cratename>` is **extremely** inconsistent. Depending on how local crates are named or how up-to-date the Cargo.toml is compared to the Cargo.lock file, it will behave very differently with regards to git dependencies.

I have created a repository explaining the problems I found @ https://github.com/roblabla/cargo-wtf-why-are-you-drunk/

In that repository, you'll find two examples of inconsistencies in the behavior of `cargo update -p`:

- In the first one, we show that cargo seems to handle git dependencies differently depending on whether it's got "work" to do on local crates or not. In particular, in my local monorepo, if I bump the version of a local crate in Cargo.toml, then `cargo update -p <crate>` will update the local lockfile to bump the versions of `crate` and nothing else. However, if I *don't* bump the version and run the same `cargo update -p <crate>` command, cargo will update the git dependencies.

  This discrepancy is especially frustrating, as it complicates our release process by making bumping the version more complicated.

- In the second one, we show that whether or not cargo updates the git dependencies after bumping the version seem to depend on how your local crates in your workspace are named. This makes any call to `cargo update -p <crate>` inherently fragile, as what it does will depend on how your dependencies are named.

# Possible Solutions

IMO, `cargo update -p <crate>` should never update an unrelated git dependency, as it does not match what the user intended.

# Rust version:

rust 1.71.0 (8ede3aae2 2023-07-12)

### PR DESCRIPTION
**Pull request by epage**
### What does this PR try to resolve?

Before, when running `cargo update <member>`, we'd not reuse the
previous resolve result and when the resolver started walking into the
dependencies, it would do a git fetch.

Now, we won't even try to resolve the workspace members and so we won't
look at those dependencies and do git fetch.

This will make `cargo update <workspace-member>`
match `cargo update --workspace`.

Fixes #12599
Fixes #8821

### How should we test and review this PR?

I considered whether there were other ways of handling this but I
figured aiming for consistency in approaches was the best way.
We can investigate improving those approaches separately.

There are other discrepancies in the different code paths (handling of
patches, adding sources) but I'm deferring looking over those.

I added a test to demonstrate the `--workspace` behavior to use as a base line to compare with.

### Additional information

Between this and #12602, this should finally resolve #12599.

### CODE REVIEW

File: src/cargo/ops/cargo_generate_lockfile.rs [hunk 1]
```diff
@@ -122,6 +122,26 @@ pub fn update_lockfile(ws: &Workspace<'_>, opts: &UpdateOptions<'_>) -> CargoRes
...
+        // Filtering them out here so the above processes them normally
+        // so their dependencies can be updated as requested
+        to_avoid = to_avoid
+            .into_iter()
+            .filter(|id| {
+                for package in ws.members() {
+                    let member_id = package.package_id();
+                    // Skip checking the `version` because `previous_resolve` might have a stale
+                    // value.
+                    // When dealing with workspace members, the other fields should be a
```
Comment (weihanglo) [inline src/cargo/ops/cargo_generate_lockfile.rs:135]: This fix looks fairly easy and straightforward, though I have a scenario in mind. If a member depends on its own old version on crates.io, but now seems it cannot update to the latest version?

Comment (epage) [reply src/cargo/ops/cargo_generate_lockfile.rs:135]: We should be protected against this with the source check. In fact, the source check should be sufficient, without a name check, because it points to the directory for the package.

Comment (weihanglo) [reply src/cargo/ops/cargo_generate_lockfile.rs:135]: Fair. I missed the source check part

**Review by weihanglo — APPROVED** [review]

**Comment by weihanglo** [comment]
Thanks for the fix!

@bors r+
