### PR TITLE
Reject manifest with duplicate dependencies in different targets

### LINKED ISSUE #2023: Duplicate dependency in manifest ignored
If I have a `Cargo.toml` manifest with a duplicate dependency name, I get a parse error as expected:

```
[package]
name            = "foo"
version         = "1.0.0"

[dependencies]
bar             = { path = "../shim-bar" }
bar             = { path = "../linux-bar" }
```

> `cargo build`
> 
> ```
> failed to parse manifest at `/home/daniel/repos/test2/foo/Cargo.toml`
> 
> Caused by:
>   could not parse input as TOML
> Cargo.toml:7:1-7:4 duplicate key: `bar`
> ```

However, if I put the second `bar` dependency in a separate section, then it doesn't complain at all.

```
[package]
name            = "foo"
version         = "1.0.0"

[dependencies]
bar             = { path = "../shim-bar" }

[target.x86_64-unknown-linux-gnu.dependencies]
bar             = { path = "../linux-bar" }
```
> `cargo build --target=x86_64-unknown-linux-gnu`

From my tests I find that the second `bar` dependency is ignored.

I would expect either an error, or that the target-specific dependency overrides the general dependency (which would be really useful).

### PR DESCRIPTION
**Pull request by JIghtuse**
Closes #2023

### CODE REVIEW

**Comment by JIghtuse** [comment]
This solution looks a bit mouthful and its correctness depends on the order of `process_dependencies` calls: common deps should be processed before platform-specific ones. But all other fixes I tried was even uglier. Any thoughts how to improve the code?

Ah, also, test will most likely fail. I don't know how to make it platform-agnostic. Or should we just call it on one platform instead?

**Comment by alexcrichton** [comment]
I think that we may want to tweak this a bit actually. So right now Cargo actually supports duplicate names just fine (between dev, build, deps, target-specific deps, etc), *so long as the same name resolves to the same crate*. 

Maybe this check could be placed after all the dependencies have been shoved into a vector? That way it could ensure that all dependencies with the same name come from the same source (regardless of kind)

**Comment by JIghtuse** [comment]
@alexcrichton ok, I'll try to do that.
Btw, looks like test fails due to recent concurrency runs fixes.

**Comment by alexcrichton** [comment]
Oops! Should be fixed in https://github.com/rust-lang/cargo/pull/2496

**Comment by JIghtuse** [comment]
Would it be enough to check that all dependencies with the same `name()` has the same `source_id()`? If so, new commit follows.

**Comment by JIghtuse** [comment]
The weird and funny thing about #2023 is that it builds first time, and fails second time when we have `Cargo.lock`. Really confusing behavior.

File: src/cargo/util/toml.rs [hunk 1]
```diff
@@ -540,6 +540,18 @@ impl TomlManifest {
             }
         }
 
+        {
+            let mut names_sources = HashMap::new();
+            for dep in deps.iter() {
+                let name = dep.name();
+                let sources = names_sources.entry(name).or_insert(HashSet::new());
+                if sources.insert(dep.source_id()) && sources.len() > 1 {
```
Comment (alexcrichton) [inline src/cargo/util/toml.rs]: Couldn't this be `if !sources.insert(source_id)`? I think `insert` returns false if it was already present

**Comment by alexcrichton** [comment]
Looks good to me! Just one minor nit.

File: src/cargo/util/toml.rs (hunk 1 above)
Comment (JIghtuse) [inline src/cargo/util/toml.rs]: Yes, it is. But this line means "if insertion was successful, and we now has more than 1 source". So we check sources length only if we inserted something. Actually, I thought to split this line on two because we mostly care about number of sources (second part of the condition).

We can miss different sources if we will check it with `!sources.insert(source_id)`. Say, we have source1 and source2 for the same package. On both iterations it will return `false` and if-branch will not be executed.

So, would it be better to leave it as is or split it on two lines?

Comment (alexcrichton) [inline src/cargo/util/toml.rs]: Oh, right! In that case we don't need the value here to be a `HashSet<SourceId>`, right? If it's just a `SourceId` we could just compare against what was already there.

Comment (JIghtuse) [inline src/cargo/util/toml.rs]: Ah, indeed. Will fix it asap.

**Comment by JIghtuse** [comment]
@alexcrichton any update on this? =) I've removed unneeded `HashSet`.

**Comment by alexcrichton** [comment]
Oh oops! Thanks for the ping, and feel free to ping the PR whenever you update it, unfortunately github doesn't send out notifications for that...

@bors: r+ 12dbfa30644aebde671e9b20553706c9e1b493aa

**Comment by wagenet** [comment]
What if the targets are mutually exclusive? It seems like that should be allowed.

**Comment by alexcrichton** [comment]
@wagenet oh this was definitely not intended to error out on legitimate cases, if that's happening please feel free to file an issue!

**Comment by wagenet** [comment]
@alexcrichton see #3195. Thanks!
