### PR TITLE
Warn if using hash in git URL, Fixes #8241

### LINKED ISSUE #8241: If rev is added to git url cargo gives no warnings and has unexpected behavior
**Problem**
I have 2 git repos in my `Cargo.toml`:
```toml
[dependencies]
juniper-actix = { git = "https://github.com/graphql-rust/juniper#91a33539", package = "juniper_actix" }
juniper = { git = "https://github.com/graphql-rust/juniper#91a33539" }
```
When cargo downloads / compiles these packages it shows the `#91a33539` 2 times:
```
> cargo build
    Updating git repository `https://github.com/graphql-rust/juniper#91a33539`
   Compiling juniper_codegen v0.14.2 (https://github.com/graphql-rust/juniper#91a33539#91a33539)
   Compiling juniper v0.14.2 (https://github.com/graphql-rust/juniper#91a33539#91a33539)
   Compiling juniper_actix v0.1.0 (https://github.com/graphql-rust/juniper#91a33539#91a33539)
```

**Steps**
1. Run `cargo init`
2. Add the deps shown above to the dependencies
3. Run `cargo build`

**Possible Solution(s)**
Show an error with a note to add `rev = ".."` to the dep or support adding a rev to the URL

**Notes**

Output of `rustup show`:
```
> rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/mark/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (directory override for '/home/mark')
rustc 1.45.0-nightly (7ced01a73 2020-04-30)
```

### PR DESCRIPTION
**Pull request by mjarkk**
This fixes an issue where if the user wants to set the git rev but doesn't know how and as results tries to set the ref in the url hash as also shown when downloading the dependency.  
Now cargo returns a warning notifying the user about the correct way to set the ref.  

Fixes #8241

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could a test be added for this as well?

File: src/cargo/util/toml/mod.rs [hunk 1]
```diff
@@ -1611,6 +1611,18 @@ impl DetailedTomlDependency {
             }
         }
 
+        if let Some(git) = self.git.clone() {
```
Comment (ehuss) [inline src/cargo/util/toml/mod.rs:1614]: I think it would be simpler to move this down into the section where the git dependency is handled, just after the line `let loc = git.into_url()?;`.  That way, there's no need to convert it to a URL twice, and would remove 4 lines of code.

File: src/cargo/util/toml/mod.rs [hunk 2]
```diff
@@ -1611,6 +1611,18 @@ impl DetailedTomlDependency {
...
+            if let Ok(url) = git.into_url() {
+                if url.fragment().is_some() {
+                    let msg = format!(
+                        "hash in git url is ignored for dependency ({}). \
+                        if you were trying to specify a specific git revision, use rev = \"revision\".",
```
Comment (ehuss) [inline src/cargo/util/toml/mod.rs:1619]:
```suggestion
                        If you were trying to specify a specific git revision, use rev = \"revision\".",
```

**Comment by ehuss** [comment]
Oh, and another thought, it might be clearer to specifically mention the URL fragment, and also say where the `rev` should go. Maybe something like this:

```rust
format!("URL fragment `#{}` in git URL is ignored for dependency ({}). \
    If you were trying to specify a specific git revision, \
    use `rev = \"{}\"` in the dependency declaration.", fragment, name_in_toml, fragment);
```

File: src/cargo/util/toml/mod.rs (hunk 1 above)
Comment (mjarkk) [reply src/cargo/util/toml/mod.rs:1614]: Good idea, will do that

**Comment by mjarkk** [comment]
@alexcrichton I've added a test

**Comment by ehuss** [comment]
Thanks!

@bors r+

**Comment by rofrol** [comment]
Added this to Cargo.toml:

```
typed-html = { git = "https://github.com/bodil/typed-html", rev = "4c13ecca" }
typed-html-macros = { git = "https://github.com/bodil/typed-html", rev = "4c13ecca" }
```

Now I got urls like `?rev=4c13ecca#4c13ecca`:

```
   Compiling typed-html-macros v0.2.2 (https://github.com/bodil/typed-html?rev=4c13ecca#4c13ecca)
   Compiling typed-html v0.2.2 (https://github.com/bodil/typed-html?rev=4c13ecca#4c13ecca)
```
