### PR TITLE
config: Deny CARGO_HOME in [env] table (fixes #11590)

### LINKED ISSUE #11590: Deny setting CARGO_HOME in `[env]` table
After some discussion (and tying into #10094 and #11589), we should consider denying setting CARGO_HOME in `[env]` now. Cargo itself does not change its home directory based on that value. Recursive calls to cargo *will* use that new value. We suspect that the likelyhood of someone already doing this is low, and we'd like to close off the possibility sooner rather than later. We think it is the wrong behavior to only pass it to recursive invocations, we'd like more control over this, particularly until we decide the semantics of #11589.

### PR DESCRIPTION
**Pull request by basile-henry**
Fixes #11590

### CODE REVIEW

File: src/cargo/util/config/mod.rs [hunk 1]
```diff
@@ -1685,8 +1685,15 @@ impl Config {
...
 
     pub fn env_config(&self) -> CargoResult<&EnvConfig> {
-        self.env_config
-            .try_borrow_with(|| self.get::<EnvConfig>("env"))
+        let env_config = self
+            .env_config
+            .try_borrow_with(|| self.get::<EnvConfig>("env"))?;
+
+        if env_config.get("CARGO_HOME").is_some() {
+            bail!("`CARGO_HOME` environment variable should be not be set in `.cargo/config` via `env.CARGO_HOME` as cargo does not use this value directly (only recursive calls to cargo would)");
```
Comment (ehuss) [inline src/cargo/util/config/mod.rs:1693]: Can you wrap this string so that it is under 100 characters wide?

Also, I'd like to suggest a little bit different wording for this error. I don't think the user needs to know how it would break. Also, the canonical config filename is `config.toml`, the `config` is only accepted for backwards compatibility. (Also, technically it can also be passed in through the command-line.) Perhaps something like this:

> setting the `CARGO_HOME` environment variable is not supported in the `[env]` configuration table

Comment (basile-henry) [reply src/cargo/util/config/mod.rs:1693]: Much nicer wording! Thanks for the suggestion ☺️

**Comment by ehuss** [comment]
Thanks!

@bors r+
