### PR TITLE
Retry command invocation with argfile

### LINKED ISSUE #10381: `cargo test` rustc error on Windows: The filename or extension is too long
### Problem

Hi all!

I originally opened over on [rust-lang](https://github.com/rust-lang/rust/issues/93920) but realized it probably fits better over here.

We have a project where we noticed that any PRs that introduce a new dependency were causing our `cargo test` invocations in Windows CI builds to fail with:

```
Caused by:
  The filename or extension is too long. (os error 206)
```

I think we are running into the same issue described by https://github.com/rust-lang/rust/issues/39644 but with `rustc.exe` rather than `link.exe` for `cargo test`'s invocation of `rustc`.

In the example failure below, it does seem like the `rustc` command is 33,184 characters, which would be over the 32,767 character limit mentioned in https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation.

Example failure:

https://github.com/vectordotdev/vector/runs/5157867395?check_suite_focus=true

Does that sound right to people? Do we need the same fix from https://github.com/rust-lang/rust/pull/44094 but for the `rustc` invocation from `cargo`?

### Steps

On Windows:

1. `git clone https://github.com/vectordotdev/vector`
2. `make test`

### Possible Solution(s)

I think we are running into the same issue described by https://github.com/rust-lang/rust/issues/39644 but with `rustc.exe` rather than `link.exe` for `cargo test`'s invocation of `rustc`?

### Notes

_No response_

### Version

```text
cargo 1.58.0 (f01b232bc 2022-01-19)
release: 1.58.0
commit-hash: f01b232bc7f4d94f0c4603930a5a96277715eb8c
commit-date: 2022-01-19
host: x86_64-pc-windows-msvc
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:Schannel)
os: Windows 10.0.17763 (Windows Server 2019 Datacenter) [64-bit]
```

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

Fixes #10381

The goal is to invoke `rustc` and `rustdoc` with `@path` arg file as a fallback.

Since the `-Zcheck-cfg-features`[^1] has already been implemented, in the foreseeable future cargo will probably hit the “**command line too big**” more often on Windows. `rustdoc` and `rustc` both support `@path` argfile [^2][^3], so we can leverage the feature for the fallback logic.

The idea behind this PR is that we put the **retry logic** in `ProcessBuilder::exec*` functions and reuse them as much as possible.

### How should we test and review this PR?

Review it commit by commit is recommended.

Argfile fallback is hard to tested with integration tests, so I added some unit tests for `cargo_util::ProcessBuilder` and `cargo::ops::fix::FixArgs`.

If you do want to test the support of argfile manually, a new environment variable `__CARGO_TEST_FORCE_ARGFILE` is added for the sake of forcing cargo to use argfile for rustc invocations. For example, `__CARGO_TEST_FORCE_ARGFILE cargo test --test testsuite -- fix::` is usually a good start to test this feature.

[^1]: https://doc.rust-lang.org/beta/cargo/reference/unstable.html?highlight=check#check-cfg-features
[^2]: https://doc.rust-lang.org/rustc/command-line-arguments.html#path-load-command-line-flags-from-a-path
[^3]: https://doc.rust-lang.org/rustdoc/command-line-arguments.html#path-load-command-line-flags-from-a-path

### Additional information

Should we escape line feed when writing into argfile and unescape while reading? 82781929b8fffd65f363aab1549e1b8f6773920f implements that but I am not sure whether it is necessary.

### CODE REVIEW

File: crates/cargo-util/src/process_builder.rs [hunk 1]
```diff
@@ -340,9 +369,68 @@ impl ProcessBuilder {
...
+    fn build_command_with_argfile(&self) -> io::Result<(Command, NamedTempFile)> {
+        use std::io::Write as _;
+
+        let mut tmp = tempfile::Builder::new()
+            .prefix("cargo-argfile.")
+            .tempfile()?;
+
+        let path = tmp.path().display();
+        let mut cmd = self.build_command_without_args();
+        cmd.arg(format!("@{path}"));
```
Comment (epage) [inline crates/cargo-util/src/process_builder.rs:411]: Observation: This won't break wrappers that don't understand argfiles because they already weren't spawning.

File: crates/cargo-util/src/process_builder.rs [hunk 2]
```diff
@@ -340,9 +369,68 @@ impl ProcessBuilder {
...
+    /// * `apply`: Modify the command before invoking. Useful for updating [`Stdio`].
+    fn build_and_spawn(&self, apply: impl Fn(&mut Command)) -> io::Result<Child> {
+        let mut cmd = self.build_command();
+        apply(&mut cmd);
+
+        match cmd.spawn() {
+            Err(ref e) if self.should_retry_with_argfile(e) => {
+                let (mut cmd, _argfile) = self.build_command_with_argfile()?;
+                apply(&mut cmd);
+                cmd.spawn()
```
Comment (epage) [inline crates/cargo-util/src/process_builder.rs:389]: Aren't we closing / removing the tempfile before the process has completed, racing with the application that is accessing it?

And should we explicitly close the tempfile, identifying any errors from the clean up?

File: crates/cargo-util/src/process_builder.rs [hunk 3]
```diff
@@ -398,23 +496,35 @@ impl ProcessBuilder {
...
     use std::os::unix::process::CommandExt;
 
     pub fn exec_replace(process_builder: &ProcessBuilder) -> Result<()> {
         let mut command = process_builder.build_command();
-        let error = command.exec();
+
+        let mut error = command.exec();
+        if process_builder.should_retry_with_argfile(&error) {
+            let (mut command, _argfile) = process_builder.build_command_with_argfile()?;
+            error = command.exec()
```
Comment (epage) [inline crates/cargo-util/src/process_builder.rs:505]: While this doesn't have the race condition between the process accessing the tempfile and us closing it, should we check for an error with close?

File: src/cargo/util/rustc.rs [hunk 4]
```diff
@@ -93,18 +93,24 @@ impl Rustc {
...
+        cmd.retry_with_argfile(true);
+        cmd
     }
 
     pub fn process_no_wrapper(&self) -> ProcessBuilder {
-        ProcessBuilder::new(&self.path)
+        let mut cmd = ProcessBuilder::new(&self.path);
+        cmd.retry_with_argfile(true);
+        cmd
     }
```
Comment (epage) [inline src/cargo/util/rustc.rs:114]: How comes `retry_with_argfile` isn't chained

File: src/cargo/ops/fix.rs [hunk 5]
```diff
@@ -774,35 +777,65 @@ struct FixArgs {
...
+                .map(PathBuf::from)
+                .ok_or_else(|| anyhow::anyhow!("expected rustc as first argument"))?;
+            for arg in iter {
+                handle_arg(arg)?;
+            }
+        } else {
+            for arg in argv {
+                handle_arg(arg)?;
+            }
         }
```
Comment (epage) [inline src/cargo/ops/fix.rs:840]: Side note: While I'm assuming this is doing things like in other places, there is now the [argfile crate](https://docs.rs/argfile/latest/argfile/)

File: crates/cargo-util/src/process_builder.rs [hunk 6]
```diff
@@ -550,14 +547,87 @@ mod imp {
...
+                    },
+                    c => s.push(c),
+                }
+            }
+            Cow::Owned(s)
+        } else {
+            Cow::Borrowed(&self.arg)
+        }
+    }
+}
```
Comment (epage) [inline crates/cargo-util/src/process_builder.rs:619]: I'm always paranoid of doing escaping wrong.  Is there an existing escaping mechanism in the stdlib that would be useful?

File: src/cargo/ops/fix.rs [hunk 7]
```diff
@@ -822,17 +822,20 @@ impl FixArgs {
             }
             let contents = fs::read_to_string(argfile_path)
                 .with_context(|| format!("failed to read argfile at `{argfile_path}`"))?;
-            let mut iter = contents.lines().map(OsString::from);
+            let mut iter = contents.lines().map(|x| ArgEscape::from(x));
+
             rustc = iter
                 .next()
-                .map(PathBuf::from)
+                .map(|a| PathBuf::from(a.unescape().as_ref()))
```
Comment (epage) [inline src/cargo/ops/fix.rs:829]: Even if we don't use argfile, it seems like abstracting this into a function that handles the escaping would be helpful

File: crates/cargo-util/src/process_builder.rs [hunk 8]
```diff
@@ -340,9 +369,68 @@ impl ProcessBuilder {
...
+            let arg = arg
+                .to_str()
+                .ok_or_else(|| {
+                    io::Error::new(
+                        io::ErrorKind::Other,
+                        "argument contains invalid UTF-8 characters",
+                    )
+                })?;
+            // TODO: Shall we escape line feed?
+            buf.push_str(arg);
```
[the remark this answers is not in the document]
Comment (epage) [reply crates/cargo-util/src/process_builder.rs]: Looks like a later commit addressed this

File: crates/cargo-util/src/process_builder.rs [hunk 9]
```diff
@@ -411,21 +412,17 @@ impl ProcessBuilder {
...
-            // TODO: Shall we escape line feed?
-            buf.push_str(arg);
-            buf.push('\n');
+            let arg = arg.to_str().ok_or_else(|| {
+                io::Error::new(
+                    io::ErrorKind::Other,
+                    "argument contains invalid UTF-8 characters",
+                )
+            })?;
+            writeln!(buf, "{}", ArgEscape::from(arg))?;
```
Comment (epage) [inline crates/cargo-util/src/process_builder.rs:423]: I guess the other question to escaping is what do rustc and similar tools support?

File: src/cargo/util/rustc.rs (hunk 4 above)
Comment (weihanglo) [reply src/cargo/util/rustc.rs:114]: I followed the existing pattern from both `ProcessBuilder` and `std::process::Command`. It is worth making it more chainable, but a dedicated PR should better IMO.

File: crates/cargo-util/src/process_builder.rs (hunk 9 above)
Comment (weihanglo) [reply crates/cargo-util/src/process_builder.rs:423]: This is [how rustc generates argfiles for ld](https://github.com/rust-lang/rust/blob/8c1fb2eb23964b56bd279b12aa925935d8559870/compiler/rustc_codegen_ssa/src/back/link.rs#L1442-L1480). As I read it so far, they just follow the specification. rustc uses only newlines to determine so I guess escaping `\r` `\n` and `\\` might be sufficient.

However, I found that [rustc_driver just naively reads line by line from argfile](https://github.com/rust-lang/rust/blob/1.60.0/compiler/rustc_driver/src/args.rs#L7-L18), they won't do any unescaping. As long as rustc does nothing special and our primary use case is serving rustc, I decide to **remove the escape part and error out** if someone passes line feeds in, as you recommended earlier. 

BTW there is [a test case](https://github.com/rust-lang/cargo/blob/5f400f098ba6bd76eb57c11bbe7c39a443146afe/tests/testsuite/rustdocflags.rs#L101-L123) validating that behaviour, which unfortunately accept whitespaces in `RUSTDOCFLAGS`.

File: crates/cargo-util/src/process_builder.rs (hunk 6 above)
Comment (weihanglo) [reply crates/cargo-util/src/process_builder.rs:619]: Yes there is a [`std::ascii::escape_default`](https://doc.rust-lang.org/stable/std/ascii/fn.escape_default.html) but we need an unescape counterpart and it seems not existing. Will remove this whole escaping part as your advice. See https://github.com/rust-lang/cargo/pull/10546#discussion_r846788690

File: src/cargo/ops/fix.rs (hunk 7 above)
Comment (weihanglo) [reply src/cargo/ops/fix.rs:829]: Sorry I don't understand what to abstract. Can you say it a bit clear?

**Comment by weihanglo** [comment]
Addressed issues in review comments. Ready to re-review :)

- Drop escape/unescape (commit 82781929b8fffd65f363aab1549e1b8f6773920f) because rustc doesn't understand how to unescape escaped characters.
- Add `__CARGO_TEST_FORCE_ARGFILE` env var to force using argfile for rustc invocation in debug mode. 5e8827f26e599f249da01db8cf8ac6ae195f3bb8
- Add a CI test to check argfile operability by force rustc to use `@path` argfile. Only test `cargo fix` because it is the only place reading from argfile. 275b0c68d4157045bc17341ff31422f1248c1dc0

File: crates/cargo-util/src/process_builder.rs (hunk 2 above)
Comment (weihanglo) [reply crates/cargo-util/src/process_builder.rs]: Fixed with 9155c0062bb6fcde2d8d727705841327dbe56e3f. It also removes the awkward `build_and_spawn` function as a side effect.

File: crates/cargo-util/src/process_builder.rs [hunk 10]
```diff
@@ -340,9 +369,68 @@ impl ProcessBuilder {
...
+    /// - https://doc.rust-lang.org/rustdoc/command-line-arguments.html#path-load-command-line-flags-from-a-path
+    /// - https://doc.rust-lang.org/rustc/command-line-arguments.html#path-load-command-line-flags-from-a-path>
+    fn build_command_with_argfile(&self) -> io::Result<(Command, NamedTempFile)> {
+        use std::io::Write as _;
+
+        let mut tmp = tempfile::Builder::new()
+            .prefix("cargo-argfile.")
+            .tempfile()?;
+
+        let path = tmp.path().display();
```
[the remark this answers is not in the document]
Comment (weihanglo) [reply crates/cargo-util/src/process_builder.rs]: Cargo conventionally constructs argument for rustc with OsString, so I feel like we should  and it has been fixed with 3f749f615b6bd5afcb076fcb623f48c9f1c5701e. (Though rustc [rejects to handle non Unicode arguments 🥲](https://github.com/rust-lang/rust/blob/1.60.0/compiler/rustc_driver/src/lib.rs#L1319-L1329))

File: crates/cargo-util/src/process_builder.rs [hunk 11]
```diff
@@ -363,46 +510,80 @@ impl ProcessBuilder {
...
+    }
+}
 
-        let args = once(self.program).chain(self.args.into_iter()).collect();
+/// Forces the command to use `@path` argfile.
+///
+/// You should set `__CARGO_TEST_FORCE_ARGFILE` to enable this.
+fn debug_force_argfile(retry_enabled: bool) -> bool {
+    cfg!(debug_assertions) && env::var("__CARGO_TEST_FORCE_ARGFILE").is_ok() && retry_enabled
+}
```
Comment (epage) [inline crates/cargo-util/src/process_builder.rs:529]: Observation: I could see in the future providing a flag in release mode as a way for people to workaround or debug problems.

**Review by epage — APPROVED** [review]
Looks good!
