### PR TITLE
Correctly handle a case where build dependencies are also declared as non-build dependencies

### LINKED ISSUE #876: Build dependencies fail if also declared as non-build dependencies.
```
#Cargo.toml

[package]

name = "foo"
version = "0.1.0"
build = "build.rs"
authors = ["David Renshaw"]

[lib]
name = "foo"
path = "lib.rs"


[build-dependencies.splay]
git = "https://github.com/alexcrichton/splay-rs.git"

[dependencies.splay]
git = "https://github.com/alexcrichton/splay-rs.git"
```

```
// build.rs

extern crate splay;

fn main() {}
```

```
// lib.rs

#![crate_name="foo"]
#![crate_type="lib"]

extern crate splay;
```

```
$ cargo build
   Compiling foo v0.1.0 (file:///Users/dwrensha/Desktop/test-cargo)
   Compiling splay v0.1.0 (https://github.com/alexcrichton/splay-rs.git#3b1e342a)
build.rs:3:1: 3:20 error: can't find crate for `splay`
build.rs:3 extern crate splay;
           ^~~~~~~~~~~~~~~~~~~
```

It succeeds if I comment out the `[dependencies.splay]` part.

### PR DESCRIPTION
**Pull request by mohtar**
Fix #876.

### CODE REVIEW

File: src/cargo/ops/cargo_rustc/job_queue.rs [hunk 1]
```diff
@@ -245,12 +245,7 @@ impl<'a> Dependency for (&'a PackageId, Stage) {
         let (id, stage) = *self;
         let pkg = packages.iter().find(|p| p.package_id() == id).unwrap();
         let deps = resolve.deps(id).into_iter().flat_map(|a| a)
-                          .filter(|dep| *dep != id)
-                          .map(|dep| {
-                              (dep, pkg.dependencies().iter().find(|d| {
-                                  d.name() == dep.name()
-                              }).unwrap())
-                          });
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_rustc/job_queue.rs]: Could this logic be left here actually? It's still used in multiple places below, and the call to `find` could be replaced with `filter` and then the cases below could use the iterator if necessary.

File: src/cargo/ops/cargo_rustc/context.rs [hunk 2]
```diff
@@ -339,22 +339,22 @@ impl<'a, 'b: 'a> Context<'a, 'b> {
         };
         let mut ret = deps.map(|id| self.get_package(id)).filter(|dep| {
             let pkg_dep = pkg.dependencies().iter().find(|d| {
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_rustc/context.rs]: You should be able to replace `.find().is_some()` with `.any()` I think

File: src/cargo/ops/cargo_rustc/context.rs [hunk 3]
```diff
@@ -339,22 +339,22 @@ impl<'a, 'b: 'a> Context<'a, 'b> {
...
-            }).unwrap();
-
-            // If this target is a build command, then we only want build
-            // dependencies, otherwise we want everything *other than* build
-            // dependencies.
-            let is_correct_dep = target.is_custom_build() == pkg_dep.is_build();
-
-            // If this dependency is *not* a transitive dependency, then it
-            // only applies to test/example targets
-            let is_actual_dep = pkg_dep.is_transitive() ||
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_rustc/context.rs]: Could you keep these variable names for now? Reading large multi-line conditionals is sometimes a little tough.

**Comment by alexcrichton** [comment]
Nice! Thanks for fixing this!

Could you add some tests for this as well?

File: src/cargo/ops/cargo_rustc/job_queue.rs (hunk 1 above)
Comment (mohtar) [inline src/cargo/ops/cargo_rustc/job_queue.rs]: I tried to do that, but then the compiler complains: `dep` does not live long enough

Comment (alexcrichton) [inline src/cargo/ops/cargo_rustc/job_queue.rs]: You may have to use the `move` keyword on the closure to ensure it doesn't try to capture a local reference

Comment (mohtar) [inline src/cargo/ops/cargo_rustc/job_queue.rs]: OK that's fine. But the cases would be rewritten like this

    base.extend(deps.filter(|&(_, dep)| dep.any(|d| d.is_build()))
                                    .map(|(id, _)| (id, Stage::Libraries)));

And the compiler compains again "cannot move out of borrowed content". I tried `ref dep` and `ref mut dep` but still it won't work out.

Comment (alexcrichton) [inline src/cargo/ops/cargo_rustc/job_queue.rs]: Could you generate a patch that I could apply locally? I may have to poke a bit as well

Comment (mohtar) [inline src/cargo/ops/cargo_rustc/job_queue.rs]: OK. See here https://github.com/rust-lang/cargo/compare/master...mohtar:dupdepsbug

Comment (alexcrichton) [inline src/cargo/ops/cargo_rustc/job_queue.rs]: Ah I see what's going on, I guess this won't work out as nicely as I hoped :(

Oh well, sorry for the runaround!

File: src/cargo/ops/cargo_rustc/job_queue.rs [hunk 4]
```diff
@@ -259,8 +254,11 @@ impl<'a> Dependency for (&'a PackageId, Stage) {
             // dependencies (making them available to us).
             Stage::BuildCustomBuild => {
                 let mut base = vec![(id, Stage::Start)];
-                base.extend(deps.filter(|&(_, dep)| dep.is_build())
-                                .map(|(id, _)| (id, Stage::Libraries)));
+                base.extend(deps
+                    .filter(|id| pkg.dependencies().iter()
+                        .find(|d| d.name() == id.name() && d.is_build())
+                        .is_some())
+                    .map(|id| (id, Stage::Libraries)));
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_rustc/job_queue.rs]: This formatting is a bit confusing because the alignment of `.filter` with `.extend` normally indicates that the `filter` is happening on the return value of `extend`, perhaps this could be formatted as:

```rust
                base.extend(deps.filter(|id| {
                    pkg.dependencies().iter().find(|d| {
                        d.name() == id.name() && d.is_build()
                    }).is_some()
                }).map(|id| (id, Stage::Libraries)));

```

Comment (mohtar) [inline src/cargo/ops/cargo_rustc/job_queue.rs]: Done. I also replaced `find(...).is_some()` with `any(...)`

**Comment by jakerr** [comment]
I'm really glad someone found the time to pick this up, thanks @mohtar !!
I've pulled your patch and am noticing some failure when building `libz-sys` in it's custom build which doesn't occur at master


```
Build failed, waiting for other jobs to finish...
failed to run custom build command for `libz-sys v0.1.2`
Process didn't exit successfully: `/Users/jakerr/code/rustws/rustecspong/target/debug/build/libz-sys-bab95f842f454018/build-script-build` (signal: 5)
--- stderr
dyld: Symbol not found: __ZN11collections4hash5table26RawTable$LT$K$C$$u20$V$GT$16first_bucket_raw10_FILE_LINE20h536f24f1e96e3184q4cE
  Referenced from: /Users/jakerr/code/rustws/rustecspong/target/debug/build/libz-sys-bab95f842f454018/build-script-build
  Expected in: /Users/jakerr/.multirust/toolchains/nightly/lib/libstd-4e7c5e5c.dylib
 in /Users/jakerr/code/rustws/rustecspong/target/debug/build/libz-sys-bab95f842f454018/build-script-build
```

I'm going to try to distill into a failing test case or at the least a minimal cargo project exhibiting the bug.

**Comment by jakerr** [comment]
Sorry, false alarm! This had to do with me trying to compile for a target architecture without updating my `DYLD_LIBRARY_PATH` as per https://github.com/brson/multirust/issues/43

**Comment by alexcrichton** [comment]
@bors: r+ 45965546fe79c589a15e057a6c44d197c4c7d4dd

Thanks!
