### PR TITLE
Warn instead of error in `cargo package` on empty `readme` or `license-file` in manifest

### LINKED ISSUE #11522: Impossible to publish: failed to prepare local package for uploading
### Problem

When trying to publish my crate:
```
PS C:\repos\tensorism> cargo publish -vv
    Updating crates.io index
   Packaging tensorism v0.1.0 (C:\repos\tensorism)
   Archiving
error: failed to prepare local package for uploading

Caused by:
  failed to open for archiving: `C:\repos\tensorism`

Caused by:
  Access is denied. (os error 5)
```

### Notes

I tried to publish it from a friend's machine, suspecting the problem was related to something about my local environment but I got exactly the same error.

### Version

```text
cargo 1.67.0-nightly (f6e737b1e 2022-12-02)
release: 1.67.0-nightly
commit-hash: f6e737b1e3386adb89333bf06a01f68a91ac5306
commit-date: 2022-12-02
host: x86_64-pc-windows-msvc
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:Schannel)
os: Windows 10.0.19045 (Windows 10 Pro) [64-bit]
```

### PR DESCRIPTION
**Pull request by kylematsuda**
### What does this PR try to resolve?

Fixes #11522. The cause of the problem is that `cargo package` and `cargo publish` fail if `readme = ""` or `license-file = ""` in the manifest.

This PR changes the `build_ar_list` function to check that the `readme` and `license-file` paths point to a file (instead of checking if the paths simply exist), and emits a warning if not. This should also catch the related failure case when either value is a valid path to a directory (e.g., `readme = "./src"`).

Changes to warnings:
- `license-file`: extends the existing warning when `license-file` points to a non-existent path to also cover the case where it points to a directory
- `readme`: new warning when `readme` is not a path to a file

### How should we test and review this PR?

Please see the new integration tests in `testsuite/package.rs`. Thanks!

### CODE REVIEW

File: tests/testsuite/package.rs [hunk 1]
```diff
@@ -1774,6 +1774,142 @@ fn exclude_dot_files_and_directories_by_default() {
...
+        )
+        .file("src/lib.rs", "")
+        .build();
+
+    p.cargo("package --no-verify")
+        .with_stderr(
+            "\
+[WARNING] readme `` does not appear to exist (relative to `[..]/foo`).
+Please update the readme setting in the manifest at `[..]/foo/Cargo.toml`
+This may become a hard error in the future.
```
Comment (kylematsuda) [inline tests/testsuite/package.rs:1802]: For the wording here, I just copied the existing warning when `license-file` doesn't exist. Not sure if it's appropriate for `readme` or if it needs to be tweaked. If I understand correctly, one of `license` or `license-file` is required for crates.io, but it's okay for the `readme` to be missing, so not sure that the "hard error" caution is accurate here

Comment (epage) [reply tests/testsuite/package.rs:1802]: I think a hard error caution is warranted because the user told us to do something and we couldn't do it.
