### PR TITLE
prompt the use of `--nocapture` flag if `cargo test` process is terminated via a signal.

### LINKED ISSUE #10855: Suggest `--nocapture` flag when a test fails with abort
### Problem

Consider the following test 

```rust
#[test]
fn rayon_panic() {
    rayon::spawn(|| panic!("o_O"));
    loop {}
}
```

`cargo test` for it produces the following output: 

```console
λ cargo t
   Compiling rt v0.1.0 (/home/matklad/tmp/rt)
    Finished test [unoptimized + debuginfo] target(s) in 0.17s
     Running unittests src/lib.rs (target/debug/deps/rt-fb003f4fc4a43299)

running 1 test
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/home/matklad/tmp/rt/target/debug/deps/rt-fb003f4fc4a43299` (signal: 6, SIGABRT: process abort signal)
```

Note how it's super unclear what exactly failed and why. Passing `--nocapture` flags helps a bit, but only an expert user would realize that such a flag might be helpful!

```console
λ cargo t -- --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running unittests src/lib.rs (target/debug/deps/rt-fb003f4fc4a43299)

running 1 test
thread '<unnamed>' panicked at 'o_O', src/lib.rs:3:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/home/matklad/tmp/rt/target/debug/deps/rt-fb003f4fc4a43299 --nocapture` (signal: 6, SIGABRT: process abort signal)
```

---

What happens here is that the test calls `std::process::abort`. Because, by default, `cargo test` captures stderr, and because abort doesn't unwind, libtest doesn't get a chance to flush stderr. This seems like a fundamental limitation of libtest.

### Proposed Solution

It'd be cool if cargo realised that `cargo test` process was killed with a singnal, and suggested re-running with `--nocapture` in this case. Note that this won't *always* help (it might be the case that a test died without printing anything to stderr), but it doesn't seem that the note like the following would hurt: 

```
error: test failed, to rerun pass '--lib'
 note: test was terminated by the signal, stderr might be truncated, pass `--nocapture` disable output buffering.
```

### Notes

_No response_

### PR DESCRIPTION
**Pull request by stupendoussuperpowers**
Fixes #10855 

As per the discussion on this issue, we want to prompt the user to use `--nocapture` if a test is terminated abnormally. The motivation for this change is described in the issue.

We check for 3 things before we display this flag. - 
- `!is_simple` (if the test ended with a non 101 status code)
- `harness` (if the standard test harness was used), and
- `!nocapture` (whether or not the `--nocapture` flag was already passed to the test)

There's further tests added to `test::nonzero_exit_status` that check that the `stderr` is correct for the various combinations possible when a test ends with a non-101 status code.

The new expected behavior is - 
- Display `--nocapture` note for only non-zero exit statuses, when the `--nocapture` flag is not passed. 
- Only display the note if we use a standard test harness since custom test harnesses do not implement the `--nocapture` flag.

To implement the check for the `--nocapture` flag, the function definition for `report_test_errors` was changed to add the `test_args: &[&str]` parameter. This parameter is passed from the immediate calling function. This private function is only called twice change and is not causing regression after making the appropriate changes to both the places it's called in.

### CODE REVIEW

File: src/cargo/ops/cargo_test.rs [hunk 1]
```diff
@@ -431,9 +431,6 @@ fn report_test_error(
 
     crate::display_error(&err, &mut ws.config().shell());
 
-    // println!("{:#?}", opts);
-    // println!("{:#?}", test_args);
```
Comment (epage) [inline src/cargo/ops/cargo_test.rs]: Could you squash this commit?

File: tests/testsuite/test.rs [hunk 2]
```diff
@@ -4792,6 +4792,21 @@ error: test failed, to rerun pass `--test t1`
...
 
+Caused by:
+  process didn't exit successfully: `[ROOT]/foo/target/debug/deps/t2[..]` (exit [..]: 4)
+note: test was terminated via a signal. stderr might be truncated. use `--nocapture` flag to disable output buffering.
+",
+        )
+        .with_status(4)
+        .run();
+
+    p.cargo("test --test t2 -- --nocapture")
```
Comment (epage) [inline tests/testsuite/test.rs:4803]: Can you split these new test cases out into a commit (first in the PR).  It should pass, showing the behavior of `master`.  The commit with all of the other changes should then update the test to still pass.  This will make it easier to see (1) the tests work and (2) what behavior changed

File: src/cargo/ops/cargo_test.rs [hunk 3]
```diff
@@ -429,4 +430,13 @@ fn report_test_error(
     }
 
     crate::display_error(&err, &mut ws.config().shell());
+
+    let harness: bool = unit_err.unit.target.harness();
+    let nocapture: bool = test_args.contains(&"--nocapture");
+
+    if !is_simple && harness && !nocapture {
+        drop(ws.config().shell().note(
+            "test was terminated via a signal. stderr might be truncated. use `--nocapture` flag to disable output buffering."
```
Comment (epage) [inline src/cargo/ops/cargo_test.rs:439]: I feel like this is long enough that its going to lose users (and technically a test can exist from something besides a signal, like `std::process::exit`)

How about

> "test exited abnormally; to see the full output pass `--nocapture` to the harness"

**Comment by stupendoussuperpowers** [comment]
I've split the changes into 2 commits as you asked, and changed the display string. 

The tests are failing right now because it is outputting the --nocapture note even if there's an exec failure. Looking into a fix for this.

**Comment by ehuss** [comment]
r? epage

Hope you don't mind taking this.

File: tests/testsuite/test.rs [hunk 4]
```diff
@@ -4792,6 +4792,35 @@ error: test failed, to rerun pass `--test t1`
...
 
+Caused by:
+  process didn't exit successfully: `[ROOT]/foo/target/debug/deps/t2[..]` (exit [..]: 4)
+note: test exited abnormally; to see the full output pass --nocapture to the harness.
+",
+        )
+        .with_status(4)
+        .run();
+
+    p.cargo("test --test t2 -- --nocapture")
```
Comment (epage) [inline tests/testsuite/test.rs:4803]: Looks like there was a merge problem and the second commit re-adds the test cases the first commit added.

Comment (stupendoussuperpowers) [reply tests/testsuite/test.rs:4803]: Let me take a look at all these commits once, they've gotten a bit confusing. Will push with correct changes in a bit.

**Comment by stupendoussuperpowers** [comment]
Hi @epage need some help with this. 

`cargo test -p cargo` for `linux x86_64 beta` is passing, but the test fails for `linux x86_64 nightly.` Looks like the `--no-fail-fast --nocapture` are outputting different things for these two. Not sure how to deal with this.

**Comment by epage** [comment]
> Hi @epage need some help with this.
> 
> `cargo test -p cargo` for `linux x86_64 beta` is passing, but the test fails for `linux x86_64 nightly.` Looks like the `--no-fail-fast --nocapture` are outputting different things for these two. Not sure how to deal with this.

`[..]` are a type of wildcard.  You can adjust these wildcards to make it still show the relevant information (`t1.rs`) while hiding the information that is tied to a specific rust version

**Comment by epage** [comment]
@stupendoussuperpowers could you rebase, instead of merge, so I can more easily browse the individual commits?

**Comment by stupendoussuperpowers** [comment]
give me a day or so to work on this, really embarrassing but i'm running into multiple git issues on my local machine. will mark it ready once it's done.

**Comment by epage** [comment]
btw I'm hosting office hours right now but also available at other times in case you want to do a call.  See https://github.com/rust-lang/cargo/wiki/Office-Hours

**Comment by epage** [comment]
Hmm, forgot to look back at this.  @stupendoussuperpowers anything left or is this good to go?

**Comment by epage** [comment]
@bors r+

Thanks for all the work you did on this!

**Comment by weihanglo** [comment]
```
 thread 'git_auth::ssh_something_happens' panicked at '
test failed running `/home/runner/work/cargo/cargo/target/debug/cargo check -v`
error: expected to find:
[..]Connection [..] by [..]

did not find in output:
    Updating git repository `ssh://127.0.0.1:37377/foo/bar`
warning: spurious network error (3 tries remaining): failed to fill whole buffer
error: failed to get `bar` as a dependency of package `foo v0.0.1 (/home/runner/work/cargo/cargo/target/tmp/cit/t99/foo)`

Caused by:
  failed to load source for dependency `bar`

Caused by:
  Unable to update ssh://127.0.0.1:37377/foo/bar

Caused by:
  failed to clone into: /home/runner/work/cargo/cargo/target/tmp/cit/t99/home/.cargo/git/db/bar-d4c725e0d0110fc9

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  An IO error occurred when talking to the server

Caused by:
  ssh: connect to host 127.0.0.1 port 37377: Connection refused
', tests/testsuite/git_auth.rs:301:10
```

Not sure what's going on. Could be the TCP connection accidentally closed.

Let's @bors retry and see.
