### PR TITLE
fix(core): use `closest_msg` to suggest similar member name for mistyped `-p`

### LINKED ISSUE #15561: Misleading error message/diagnostic when package name is wrong
### Problem

I just ran into an issue where I mistyped the name of a package in my workspace, and got an error message that is completely unrelated, which is confusing and led me into a complete different direction than what would have fixed the issue.

### Steps

1. Try to `cargo build -p nonexisting-pkg --all-features` a package that does not exist in the workspace
2. Get `error: cannot specify features for packages outside of workspace` 

### Possible Solution(s)

I would expect an error message along the lines of

"Did not find package `nonexisting-pkg` in workspace"

### Notes

_No response_

### Version

```text
cargo 1.85.0 (d73d2caf9 2024-12-31)                                                                                                                                                                                                            
release: 1.85.0                                                                                                                                                                                                                                
commit-hash: d73d2caf9e41a39daf2a8d6ce60ec80bf354d2a7                                                                                                                                                                                          
commit-date: 2024-12-31                                                                                                                                                                                                                        
host: x86_64-unknown-linux-gnu                                                                                                                                                                                                                 
libgit2: 1.8.1 (sys:0.19.0 vendored)                                                                                                                                                                                                           
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)                                                                                                                                                                         
ssl: OpenSSL 1.1.1w  11 Sep 2023                                                                                                                                                                                                               
os: NixOS 24.11.0 [64-bit]
```

### PR DESCRIPTION
**Pull request by raushan728**
Fixes: #15561 

Use `closest_msg` to suggest similar workspace member name when `-p <typo>` triggers the outside-of-workspace features error.

### CODE REVIEW

File: src/cargo/core/workspace.rs [hunk 1]
```diff
@@ -1890,7 +1890,24 @@ impl<'gctx> Workspace<'gctx> {
...
+                    .iter()
+                    .find_map(|spec| {
+                        self.members()
+                            .filter_map(|member| {
+                                edit_distance(spec.name(), member.name().as_str(), 2)
+                                    .map(|distance| (distance, member))
+                            })
+                            .min_by_key(|(distance, _)| *distance)
+                            .map(|(_, member)| {
+                                format!(
```
Comment (arlosi) [inline src/cargo/core/workspace.rs]: Can we use `closest` and `closest_msg` from `edit_distance.rs` for this?

Comment (raushan728) [reply src/cargo/core/workspace.rs]: Tried `closest_msg` first but it uses distance 3 which caused false positives in `non_member` and `non_member_feature` tests. Kept distance 2 to avoid noisy hints.

Comment (epage) [reply src/cargo/core/workspace.rs]: We should then either
- change the tests so we remain consistent in our closest matching logic
- change `closest_msg` to be smarter about matches

I would view changing `closest_msg` to be out of scope for this change though

Comment (raushan728) [reply src/cargo/core/workspace.rs]: switching to closest_msg and updating the affected test assertions.

Comment (raushan728) [reply src/cargo/core/workspace.rs]: Done

**Review by weihanglo — APPROVED** [review]
Thanks

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16844/35f8202bfe47f954a4613a846cfd406bda9d3b8c..d4660ffffa35686712795b7562ce1d15ae4fcc7e)*
