### PR TITLE
fix(package): report lockfile / workspace manifest is dirty 

### LINKED ISSUE #14967: `cargo package` VCS dirty check corner cases
### Problem

During the investigation of #14955 and #14962, we found more corner cases that `cargo package` doesn't consider dirty. You don't even need to pass `--allow-dirty` flag to explicitly allow it. `.cargo_vcs_info.json` shows no dirty at all. However, the actual packaged `.crate` file contains dirty files. 

Let's consider this virtual workspace:

```
./
├── foo/
│   ├── src/
│   ├── Cargo.toml
│   └── README.md -> ../README.md
├── Cargo.toml
├── LICENSE
└── README.md
```

```toml
# foo/Cargo.toml
[package]
name = "foo"
edition.workspace = true
license-file = "../LICENSE" # link to parent LICENSE
```

```toml
# Cargo.toml
[workspace]
members = ["foo"]
[workspace.package]
edition = "2015"
```

There are at least three corner cases:

* [x] Symlinks — if you change README.md at workspace root level, when packaging it would be included. However, since [`PathSource::list_files`](https://github.com/rust-lang/cargo/blob/59b2ddd4484a04a0c202052202cc9f30ac48165c/src/cargo/sources/path.rs?plain=1#L97) list symlink as ordinary file. When doing dirty check, the [naive path prefix check](https://github.com/rust-lang/cargo/blob/59b2ddd4484a04a0c202052202cc9f30ac48165c/src/cargo/sources/path.rs?plain=1#L97) is not able to find the symlink source file dirty.
  * Fixed by https://github.com/rust-lang/cargo/pull/14981
* [x] `package.license-file` and `package.readme` — they are copied during `cargo package`. `PathSource::list_files` doesn't even report them because they are not under the directory of the package. 
  * Fixed by https://github.com/rust-lang/cargo/pull/14966
* [x] Workspace inheritance — like changing `workspace.package.edition` to `2021` would actually make foo's Cargo.toml dirty, but the current dirty status check doesn't capture that.
  * Fixed by <https://github.com/rust-lang/cargo/pull/15276> and <https://github.com/rust-lang/cargo/pull/15341>. We do an aggressively check that if the workspace Cargo.toml is dirty, consider it dirty.
* [ ] Symlinks linking to Git submodules. See #15384.
  * It also has a performance issue and needs refactor. When considering performance, also keep in mind large monorepo-level workspace performance like #14955

### Steps

See https://github.com/rust-lang/cargo/pull/14966

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
cargo 1.85.0-nightly (769f622e1 2024-12-14)
```

9c17646f8a9699bc26dd33b7652b0d52c20b74ba

### PR DESCRIPTION
**Pull request by weihanglo**
### What does this PR try to resolve?

Workspace manifest and lockfile might not be under the package root,
but workspace inheritance and outdated lockfile entries
may still affect what is packaged into the `.crate.` tarball.
We take a conservative action that if any of them is dirty,
then all workspace members are considered dirty.

Fixes #14967

### How should we test and review this PR?

Workspace manifest case is simple.

Lockfile requires a bit more works.
It is allowed to be missing, and can be generated during packaging.
We skip checking when it is missing in both workdir and git index,
otherwise cargo will fail with git2 not found error.

### CODE REVIEW

File: tests/testsuite/package.rs [hunk 1]
```diff
@@ -1432,6 +1426,133 @@ edition = "2021"
...
+
+to proceed despite this and include the uncommitted changes, pass the `--allow-dirty` flag
+
+"#]])
+        .run();
+
+    // Now check if it is considered dirty when removed.
+    p.cargo("clean").run();
+    fs::remove_file(p.root().join("Cargo.lock")).unwrap();
+    p.cargo("package --workspace --no-verify")
```
Comment (weihanglo) [inline tests/testsuite/package.rs:1543]: Might be some path normalization issues on Windows.

```
thread 'package::dirty_ws_lockfile_dirty' panicked at tests\testsuite\package.rs:1553:10:
test failed running `D:\a\cargo\cargo\target\debug\cargo.exe package --workspace --no-verify`
error: process exited with code 0 (expected 101)
--- stdout
--- stderr
   Packaging isengard v0.0.0 (D:\a\cargo\cargo\target\tmp\cit\t2239\foo\isengard)
    Updating `dummy-registry` index
    Packaged 5 files, 1.5KiB (986B compressed)
```

Comment (weihanglo) [reply tests/testsuite/package.rs:1543]: Fixed by <https://github.com/rust-lang/cargo/compare/4c0e42dac2b05d52b52ef2435a9a25d73dd92c5e..f0907fca16a84101d69fc53272a955e8bb53d9fe>.

It was failing because removed files can't be canonicalized, so when comparing path prefix with a canonicalized `workdir` it will never pass.

File: src/cargo/ops/cargo_package/vcs.rs [hunk 2]
```diff
@@ -248,20 +254,50 @@ fn dirty_files_outside_pkg_root(
...
+        None
+    };
+
     for rel_path in src_files
         .iter()
         .filter(|p| p.is_symlink_or_under_symlink())
         .map(|p| p.as_ref().as_path())
         .chain(metadata_paths.iter().map(AsRef::as_ref))
         .chain([ws.root_manifest()])
+        .chain(lockfile_path.as_deref().into_iter())
```
Comment (epage) [inline src/cargo/ops/cargo_package/vcs.rs:300]: I'm trying to think through how this PR might be disruptive to people's workflows and the most likely case I can come ip with is people being sloppy with version bumps and publishing which can run into #5979.

**Review by epage — APPROVED** [review]
