### PR TITLE
Print colored warnings when build script panics

### LINKED ISSUE #3672: Print & color build script warnings, even when build script panics
Currently, when the build script panics, the stdout of the build script is written out to show what happened. However, this means that any warnings emitted during the build script (using cargo:warning= from #2630) won't be printed nicely like they are when the build script succeeds.

It would be nice if these warnings could be printed prettily even when the build script fails to execute due to a panic.

### PR DESCRIPTION
**Pull request by aleksator**
Fixes #3672

### CODE REVIEW

File: src/cargo/core/compiler/custom_build.rs [hunk 1]
```diff
@@ -429,6 +447,29 @@ fn build_work<'a, 'cfg>(cx: &mut Context<'a, 'cfg>, unit: &Unit<'a>) -> CargoRes
...
+    let build_output_with_only_warnings = BuildOutput {
+        warnings,
+        library_paths: Vec::new(),
+        library_links: Vec::new(),
+        linker_args: Vec::new(),
+        cfgs: Vec::new(),
+        env: Vec::new(),
+        metadata: Vec::new(),
+        rerun_if_changed: Vec::new(),
+        rerun_if_env_changed: Vec::new(),
```
Comment (ehuss) [inline src/cargo/core/compiler/custom_build.rs]: Maybe derive Default on BuildOutput, and then use default() here to avoid specifying all these fields.

File: src/cargo/core/compiler/custom_build.rs [hunk 2]
```diff
@@ -359,7 +365,19 @@ fn build_work<'a, 'cfg>(cx: &mut Context<'a, 'cfg>, unit: &Unit<'a>) -> CargoRes
...
+            .chain_err(|| format!("failed to run custom build command for `{}`", pkg_name));
+
+        if output.is_err() {
+            insert_warnings_in_build_output(
+                build_script_outputs,
+                id,
+                metadata_hash,
+                warnings_in_case_of_panic,
+            );
+            return output.map(|_| ());
```
Comment (ehuss) [inline src/cargo/core/compiler/custom_build.rs]: Instead of using a closure here, perhaps do something like:
```rust
if let Err(e) = output {
    …
    return Err(e);
}
```

Just seems a slightly clearer to me.

Comment (aleksator) [reply src/cargo/core/compiler/custom_build.rs]: Ah, this was actually the first version I wrote, but changed it to this one to avoid needless wrapping/unwrapping. Will change back
