### PR TITLE
Fix interpretation of `--features a b` on the CLI

### LINKED ISSUE #7418: Parsing of `cargo run --features a b` has regressed
Given a package that has the feature `a` but not the feature `b`, I get:

```
$ cargo run --features a b
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/wut b`
Hello, world!
$ cargo +beta run --features a b
error: Package `wut v0.1.0 (/home/alex/code/wut)` does not have these features: `b`
```

```
$ cargo --version
cargo 1.37.0 (9edd08916 2019-08-02)
$ cargo +beta --version
cargo 1.38.0-beta (23ef9a4ef 2019-08-20)
```

I suspect this is an accidental regression from #7084

### PR DESCRIPTION
**Pull request by alexcrichton**
Fixes an accidental regression from #7084 where `--features a b` was
erroneously mistinterpreted as `--features "a b"`.

Closes #7418

### CODE REVIEW

**Comment by alexcrichton** [comment]
While technically a regression from stable to beta so we should backport, the stable release is going out this week so it's probably fine to just regress for one cycle.

File: src/cargo/util/command_prelude.rs [hunk 1]
```diff
@@ -100,11 +100,11 @@ pub trait AppExt: Sized {
     }
 
     fn arg_features(self) -> Self {
-        self._arg(
-            opt("features", "Space-separated list of features to activate")
-                .multiple(true)
-                .value_name("FEATURES"),
-        )
+        self._arg(optional_multi_opt(
```
Comment (ehuss) [inline src/cargo/util/command_prelude.rs]: Why is this `optional_multi_opt` and not just `multi_opt`?  This change will make an empty features flag valid (`cargo run --features`).

**Comment by ehuss** [comment]
I think it would be good to backport this to 1.39 (so only 1.38 will be affected).  I'd also like to backport #7394 to 1.39, too!

File: src/cargo/util/command_prelude.rs (hunk 1 above)
Comment (alexcrichton) [reply src/cargo/util/command_prelude.rs]: Oops, good point. Misread the options!

**Comment by alexcrichton** [comment]
1.39.0 has now been branched, so I'll send a backport for this once it lands (and can include  #7394 too)
