### PR TITLE
Fix recursion in build_path_deps

### LINKED ISSUE #3330: Stackoverflow on Fedora 25 when building a project with cargo
When I run the command `cargo build` I get the following output 

```
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
Aborted (core dumped)
```

After running the core file through gdb I get the following output: 

```
[New LWP 11488]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `cargo build'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58	}
```

Not 100% if this is an issue with cargo as other projectors I have seem to build fine. However, this is the only clue I have. Let me know If I can help further debug.

### PR DESCRIPTION
**Pull request by alexcrichton**
We were slightly too eager to follow pointers!

Closes #3330

### CODE REVIEW

File: src/cargo/core/resolver/encode.rs [hunk 1]
```diff
@@ -172,25 +172,28 @@ fn build_path_deps(ws: &Workspace) -> HashMap<String, SourceId> {
...
-             ret: &mut HashMap<String, SourceId>) {
+             ret: &mut HashMap<String, SourceId>,
+             visited: &mut HashSet<SourceId>) {
         let replace = pkg.manifest().replace();
         let deps = pkg.dependencies()
                       .iter()
                       .chain(replace.iter().map(|p| &p.1))
-                      .filter(|d| !ret.contains_key(d.name()))
                       .map(|d| d.source_id())
+                      .filter(|d| !visited.contains(d))
```
Comment (matklad) [inline src/cargo/core/resolver/encode.rs]: micronit: the parameter can is better be called `d`, and it can be combined with the `filter` that follows.
