### PR TITLE
Fix some issues with `cargo doc` and the new feature resolver.

### LINKED ISSUE #9064: Panic in `cargo doc` with resolver = "2" when indirectly depending on proc-macro2
**Problem**
`cargo doc` panics when run on crate A that depends on crate B, when crate B depends on `proc-macro2`. This does _not_ happen when directly running `cargo doc` on crate B.

<details>
<summary>Error & Backtrace</summary>

```
thread 'main' panicked at 'activated_features for invalid package: features did not find PackageId { name: "proc-macro2", version: "1.0.24", source: "registry `https://github.com/rust-lang/crates.io-index`" } false

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: std::backtrace::Backtrace::capture
   2: cargo::core::resolver::features::ResolvedFeatures::activated_features_int
   3: cargo::core::compiler::unit_dependencies::new_unit_dep_with_profile
   4: cargo::core::compiler::unit_dependencies::compute_deps
   5: cargo::core::compiler::unit_dependencies::deps_of
   6: cargo::core::compiler::unit_dependencies::deps_of
   7: cargo::core::compiler::unit_dependencies::build_unit_dependencies
   8: cargo::ops::cargo_compile::create_bcx
   9: cargo::ops::cargo_compile::compile_ws
  10: cargo::ops::cargo_compile::compile
  11: cargo::ops::cargo_doc::doc
  12: cargo::commands::doc::exec
  13: cargo::cli::main
  14: cargo::main
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal
  18: _main', src/tools/cargo/src/cargo/core/resolver/features.rs:235:14
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_none_failed
   3: cargo::core::compiler::unit_dependencies::new_unit_dep_with_profile
   4: cargo::core::compiler::unit_dependencies::compute_deps
   5: cargo::core::compiler::unit_dependencies::deps_of
   6: cargo::core::compiler::unit_dependencies::deps_of
   7: cargo::core::compiler::unit_dependencies::build_unit_dependencies
   8: cargo::ops::cargo_compile::create_bcx
   9: cargo::ops::cargo_compile::compile_ws
  10: cargo::ops::cargo_compile::compile
  11: cargo::ops::cargo_doc::doc
  12: cargo::commands::doc::exec
  13: cargo::cli::main
  14: cargo::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Steps**
1. Clone the minimal example at https://github.com/nerosnm/proc-macro-resolver-bug
2. Run `cargo doc` (or, more explicitly, `cargo +nightly-2021-01-10 doc`)

**Possible Solution(s)**
This looks similar to rust-lang/cargo#8774 to me, although from what I can tell it's not explicitly relying on any features specific to the new resolver.

**Notes**
Output of `cargo version`: cargo 1.51.0-nightly (329895f5b 2021-01-06)

### PR DESCRIPTION
**Pull request by ehuss**
This contains two related commits fixing some issues with `cargo doc` and the new feature resolver.

The first commit fixes a panic. The old code was using `UnitFor::new_normal` when computing doc units, but this was wrong. That essentially circumvents the new feature resolver, and breaks determining the correct features to use. I don't remember exactly what I was thinking when I wrote that, other than "rustdoc shouldn't care", but it does matter.

Unfortunately changing that makes collisions worse because it aggravates #6313, so the second commit adds some logic for removing some collisions automatically. Specifically:

- Prefers dependencies for the target over dependencies for the host (such as proc-macros).
- Prefers the "newest" version if it comes from the same source.

There are still plenty of situations where there can be collisions, but I'm uncertain on the best way to handle those.

Fixes #9064

### CODE REVIEW

**Comment by alexcrichton** [comment]
Oof. 

I was gonna review this before heading out for today, but I think it might be best if I left this for next week. FWIW I'll be out until next Tuesday, but I'll get to this then! If this is urgent to fix in nightly, however, feel free to land and I'll review after-the-fact. A quick skim and seems fine to me, but I'd like to review the pruning of the unit graph more closely.

**Comment by ehuss** [comment]
No worries, and no rush, next week is plenty fast.

There is a comment at the start of `remove_duplicate_doc`, where I am uncertain about creating orphans in the tree.  I'm fine with adding something to prune the orphans, I just wasn't certain if it was justified.

This feels a bit hacky, but I couldn't really think of a cleaner solution (other than redesigning rust, cargo, and rustdoc from scratch 😜 ).

File: src/cargo/ops/cargo_compile.rs [hunk 1]
```diff
@@ -1455,3 +1462,108 @@ fn opt_patterns_and_names(
...
+/// on one another's files.
+///
+/// Unfortunately this does not remove all duplicates, as some of them are
+/// either user error, or difficult to remove. Cases that I can think of:
+///
+/// - Same target name in different packages. See the `collision_doc` test.
+/// - Different sources. See `collision_doc_sources` test.
+///
+/// Ideally this would not be necessary.
+fn remove_duplicate_doc(build_config: &BuildConfig, unit_graph: &mut UnitGraph) {
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_compile.rs:1481]: FWIW long-term I don't think that this function should exist. Ideally rustdoc would have a feature that we could specify the directory/lookup name and we could pass that in to avoid all duplication issues.

File: src/cargo/ops/cargo_compile.rs [hunk 2]
```diff
@@ -1455,3 +1462,108 @@ fn opt_patterns_and_names(
...
+                reason,
+                unit.pkg,
+                unit.target.name()
+            );
+            unit_graph.remove(unit);
+        }
+        for unit_deps in unit_graph.values_mut() {
+            unit_deps.retain(|unit_dep| !units.iter().any(|unit| *unit == unit_dep.unit));
+        }
+    };
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_compile.rs:1513]: I'm slightly worried about the performance of this since this could be in the worst case O(n^2). Would it be possible to maintain a set of units to remove and they're all processed together at the very end?

File: src/cargo/ops/cargo_compile.rs [hunk 3]
```diff
@@ -1455,3 +1462,108 @@ fn opt_patterns_and_names(
...
+            // shouldn't hurt to remove them early (although the report in the
+            // log might be confusing).
+            remove(to_remove, "host/target merger");
+            units = remaining_units;
+            if units.len() == 1 {
+                continue;
+            }
+        }
+        // Prefer newer versions over older.
+        let mut source_map: HashMap<(InternedString, SourceId, CompileKind), Vec<Unit>> =
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_compile.rs:1538]: Could the key here perhaps be `BTreeMap<Version, Unit>`? (to avoid the extra sort later)

File: src/cargo/ops/cargo_compile.rs [hunk 4]
```diff
@@ -1455,3 +1462,108 @@ fn opt_patterns_and_names(
...
+        }
+        let mut remaining_units = Vec::new();
+        for (_key, mut units) in source_map {
+            if units.len() > 1 {
+                units.sort_by(|a, b| a.pkg.version().partial_cmp(b.pkg.version()).unwrap());
+                // Remove any entries with version < newest.
+                let newest_version = units.last().unwrap().pkg.version().clone();
+                let (to_remove, keep_units): (Vec<Unit>, Vec<Unit>) = units
+                    .into_iter()
+                    .partition(|unit| unit.pkg.version() < &newest_version);
```
Comment (alexcrichton) [inline src/cargo/ops/cargo_compile.rs:1556]: Given a source it's not possible to have multiple crates of the same name at the same version, right? 

Is it possible for `keep_units` to have length greater than 1? (I'm probably missing something...)

**Review by alexcrichton — COMMENTED** [review]
Oh dear this is indeed quite subtle. I do think the best solution here is some extra flags to rustdoc, but that's more of a long-term issue than one to solve right now.

Otherwise can you beef up the documentation for each of the cases where duplicates are removed? Explaining in words a small example of what we're deduplicating is sort of what I'm thinking.

This is definitely going to be buggy in the sense that by selecting the newest version that means that broken links could be generated if links are supposed to reference an older version. Again though this is all just an artifact of rustdoc's current design which wasn't intended to cover cases like this (it was designed in a simpler time...)

File: src/cargo/ops/cargo_compile.rs (hunk 4 above)
Comment (ehuss) [reply src/cargo/ops/cargo_compile.rs:1556]: I think it should be very rare, but it is possible.

One example is `cargo doc --bins --lib`.  This will try to document both the library and the binary, which have the same name and thus end up colliding.  

I'm not sure how that *should* behave.  Should it be an error?  Should it ignore the binary?  Should rustdoc put those in separate directories?  

There are a bunch of collision opportunities, and this isn't intended to cover all of them, just a few that seemed reasonable.

File: src/cargo/ops/cargo_compile.rs (hunk 1 above)
Comment (ehuss) [reply src/cargo/ops/cargo_compile.rs:1481]: I agree. However, it is not clear to me how that should work.  Because the directories are exposed as URLs, I think it would be unpleasant for those to have Cargo-style hashes in them.  There could be some pattern like $NAME-$VERSION and then have extra disambiguators when necessary like $NAME-$VERSION-bin-foo.  But there are some collisions that are harder (like when they only differ in the features).

What do you think about having a hash in the URL?  

This feels like a bit of a mess, and I'm uncertain how to climb out of it.

File: src/cargo/ops/cargo_compile.rs (hunk 3 above)
Comment (ehuss) [reply src/cargo/ops/cargo_compile.rs:1538]: I don't think so (per the other comment, there can be multiple entries with the same version).

File: src/cargo/ops/cargo_compile.rs (hunk 2 above)
Comment (ehuss) [reply src/cargo/ops/cargo_compile.rs:1514]: Oops, yea. Pushed a change to filter them once.

File: src/cargo/ops/cargo_compile.rs (hunk 1 above)
Comment (alexcrichton) [reply src/cargo/ops/cargo_compile.rs:1481]: At least for `cargo doc` locally I feel like the hash doesn't matter too much since you'll just be clicking on links anyway (assuming we generate some well-known landing page which we don't already do today). For everything else though (like doc.rust-lang.org or docs.rs) I wouldn't want Cargo-style hashes in URLs. 

This function is likely gonna be here for a long long time which is by no means the end of the world. I think it'll take some more thinking to figure out what it might look like to not have this function.
