### PR TITLE
fix: add source replacement info when no matching package found

### LINKED ISSUE #14697: Misleading error message when crates.io is `replace-with` a local source
### Problem

When using a local source via a `replace-with` in `config.toml` and there is a missing package, `cargo build` gives confusing errors saying that it searched `crates-io` for the package when it only looked in the local file system. The error it gives is identical to the error from an actually missing package:
```
error: no matching package named `<package name>` found
location searched: registry `crates-io`
required by package `example v0.1.0`
```

### Possible Solution(s)

If you run `cargo seach` it gives much more specific information:
```
$ cargo search ahash
error: crates-io is replaced with non-remote-registry source dir /.../cargo-bug/vendor;
include `--registry crates-io` to use crates.io
```
It would be great if the original error included this "crates-io is replaced with non-remote-registry source" remark.

### Steps

1. Unpack this zip archive: [cargo-bug.zip](https://github.com/user-attachments/files/17397502/cargo-bug.zip)
2. Run `cargo build` in root
3. Get error:
    ```
    error: no matching package named `ahasha` found
    location searched: registry `crates-io`
    required by package `example v0.1.0 (/home/rchatham/Documents/programming/tmp/cargo-bug)`
    ```

As an alternative, instead of unpacking, make an empty folder, cd into it, make the following files and then do the following shell instructions:

#### `Cargo.toml`
```toml
[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = { version = "^0.8.9" }
```

#### `.cargo/config.toml`

```toml
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
```

#### Shell instructions

Then:
```sh
mkdir src
touch src/lib.rs
mkdir vendor
cargo build
```

### Version

cargo 1.84.0-nightly (15fbd2f60 2024-10-08)
release: 1.84.0-nightly
commit-hash: 15fbd2f607d4defc87053b8b76bf5038f2483cf4
commit-date: 2024-10-08
host: x86_64-unknown-linux-gnu
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.9.0-DEV (sys:0.4.74+curl-8.9.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 22.4.0 (jammy) [64-bit]

### PR DESCRIPTION
**Pull request by chentodd**
### What does this PR try to resolve?

Fixes #14697 

I updated error message in `resolver/errors` with [Registry::describe_source](https://doc.rust-lang.org/nightly/nightly-rustc/cargo/core/registry/trait.Registry.html#tymethod.describe_source)

- Use message from `Registry::describe_source` as default message
- If the message is empty, use `SourceId` message

and I also updated related test cases.

### How should we test and review this PR?

1. Run following test cases:

- resolver-tests
- source_replacement
- build
- directory
- local_registry
- offline
- package
- publish
- registry
- update

2. Run [cargo-bug.zip](https://github.com/user-attachments/files/17493272/cargo-bug.zip)

- Unpack the zip archive
- Run `cargo build` in the root

following message should be seen:
```
error: no matching package named `ahasha` found
location searched: directory source `/home/foo/Desktop/cargo-bug/vendor` (which is replacing registry `crates-io`)
required by package `example v0.1.0 (/home/foo/Desktop/cargo-bug)`
```

### CODE REVIEW

File: tests/testsuite/build.rs [hunk 1]
```diff
@@ -6043,7 +6043,7 @@ fn avoid_dev_deps() {
         .with_stderr_data(str![[r#"
 [UPDATING] `dummy-registry` index
 [ERROR] no matching package named `baz` found
-location searched: registry `crates-io`
+location searched: `dummy-registry` index (which is replacing registry `crates-io`)
```
Comment (epage) [inline tests/testsuite/build.rs:6046]: As there is no production change, I assume this belongs in the previous commit?

Each commit should be atomic which includes passing all tests

File: tests/testsuite/source_replacement.rs [hunk 2]
```diff
@@ -294,3 +294,47 @@ fn source_replacement_with_registry_url() {
 "#]])
         .run();
 }
+
+#[cargo_test]
+fn source_replacement_with_no_package_in_directoy() {
```
Comment (epage) [inline tests/testsuite/source_replacement.rs:299]: I'm not seeing this test updated in a later commit, so I assume this commit will fail on its own.

We ask for
- Commits to be atomic, including tests passing
- New tests to be added before a fix or feature that shows the existing behavior so that we can then see how the behavior changes with the fix (where possible)

Comment (chentodd) [reply tests/testsuite/source_replacement.rs:299]: Sorry for the inconvenience I caused. I'll try to redo the work and follow the practice.

File: tests/testsuite/offline.rs [hunk 3]
```diff
@@ -383,30 +383,39 @@ fn update_offline_not_cached() {
...
+    }
+
     p.cargo("update --offline")
         .with_status(101)
-        .with_stderr_data(
+        .with_stderr_data(&format!(
             "\
 [ERROR] no matching package named `bar` found
-location searched: registry `crates-io`
+location searched: {location_searched_message}
```
Comment (epage) [inline tests/testsuite/offline.rs:400]: We should try to keep snapshotting where possible.

Looking at this, I don't think the location is critical to the test and we could replace it with the `[..]`  wildcard

Comment (chentodd) [reply tests/testsuite/offline.rs:400]: Thanks for the feedback. I'm new to cargo test,  I want to make sure I fully understand your suggestion. Do I need to replace all instances of the hard-coded `location searched: XXX` with `[..]` in the `offline.rs` test cases, or only in this specific test case (`update_offline_not_cached`)?

Comment (epage) [reply tests/testsuite/offline.rs:400]: Only in this specific case to make it work in both situations

**Comment by epage** [comment]
Thanks!

@bors r+

**Comment by hoodmane** [comment]
Thanks @chentodd!
