### PR TITLE
cargo install with specific yanked version gives confusing "not found" error

### LINKED ISSUE #8171: cargo install with specific yanked version gives confusing "not found" error
`cargo install` with a specific version that has been yanked gives a slightly confusing error:

```
> cargo install cargo-tarpaulin --version 0.10.1
error: could not find `cargo-tarpaulin` in registry `https://github.com/rust-lang/crates.io-index` with version `=0.10.1`
```

I think maybe it would be good to at least mention that it is yanked.

This is similar to #4260, where specified as a dependency also says "no matching version". In general, the yanked crates become invisible to resolution, and I'm wondering if maybe it should at least provide a hint.

### PR DESCRIPTION
**Pull request by pawanbisht62**
Resolves #8171

### CODE REVIEW

File: src/cargo/ops/common_for_install_and_uninstall.rs [hunk 1]
```diff
@@ -544,12 +544,19 @@ where
...
-        None => bail!(
-            "could not find `{}` in {} with version `{}`",
-            dep.package_name(),
-            source.source_id(),
-            dep.version_req(),
-        ),
+        None => {
+            for pkg_id in deps.iter() {
+                if source.is_yanked(pkg_id.package_id()).unwrap_or(false) {
+                    bail!("provided package has been yanked `{}`", pkg_id.package_id())
```
Comment (ehuss) [inline src/cargo/ops/common_for_install_and_uninstall.rs:550]: Just a small note on the wording, perhaps it could be written as:

```cannot install package `{}`, it has been yanked from {}```

Comment (pawanbisht62) [reply src/cargo/ops/common_for_install_and_uninstall.rs:550]: Thanks for suggestion, I'll definitely update the message and yes can please help me out to add test for this?

**Comment by ehuss** [comment]
For Cargo's testsuite, there is some high-level documentation in https://github.com/rust-lang/cargo/blob/master/CONTRIBUTING.md#running-tests for running tests.  See https://github.com/rust-lang/cargo/blob/master/crates/cargo-test-support/src/lib.rs for an introduction to writing tests.  

The test should probably go in https://github.com/rust-lang/cargo/blob/master/tests/testsuite/install.rs.  There are a bunch of other tests in there that you can look at for examples. The `simple` test up top is a good, basic example.

Essentially it needs to call `Package::new` to create a new package in the registry, and call [`yanked`](https://github.com/rust-lang/cargo/blob/c4e93dc5ed3422faf2eb0264fd2488f3d14c3577/crates/cargo-test-support/src/registry.rs#L347-L351) to set its yanked status.

Then call `cargo_process("install foo")` and check that it fails `with_status(101)` and that check the output using `with_stderr("...")`.

**Comment by bishtpawan** [comment]
Hi @ehuss,I've updated the PR by updating the code and also added one new test-case. 
Can you please have a look at the CI/test the failed one. I'm unable to get details like why 2 tests are failing. Thanks

File: tests/testsuite/install.rs [hunk 2]
```diff
@@ -1555,3 +1555,12 @@ fn install_git_with_symlink_home() {
         )
         .run();
 }
+
+#[cargo_test]
+fn install_yanked_cargo_package() {
+    Package::new("baz", "0.0.1").yanked(true).publish();
+    cargo_process("install baz --version 0.0.1")
+        .with_status(101)
+        .with_stderr_contains("error: cannot install package `baz`, it has been yanked from registry `https://github.com/rust-lang/crates.io-index`")
```
Comment (ehuss) [inline tests/testsuite/install.rs:1564]: Can you split up this line so it is less than 100 characters long?  Just add some `\` characters to split the string across a few lines.

File: tests/testsuite/install_upgrade.rs [hunk 3]
```diff
@@ -799,11 +799,8 @@ fn already_installed_updates_yank_status_on_upgrade() {
 
     cargo_process("install foo --version=1.0.1")
         .with_status(101)
-        .with_stderr(
-            "\
-[UPDATING] `[..]` index
-[ERROR] could not find `foo` in registry `[..]` with version `=1.0.1`
-",
+        .with_stderr_contains(
+            "error: cannot install package `foo`, it has been yanked from registry `https://github.com/rust-lang/crates.io-index`",
```
Comment (ehuss) [inline tests/testsuite/install_upgrade.rs:803]: This string could be split up, too.

File: src/cargo/ops/common_for_install_and_uninstall.rs [hunk 4]
```diff
@@ -544,12 +544,33 @@ where
...
         }
-        None => bail!(
-            "could not find `{}` in {} with version `{}`",
-            dep.package_name(),
-            source.source_id(),
-            dep.version_req(),
-        ),
+        None => {
+            let version: String = dep.version_req().to_string();
+            match PackageId::new(dep.package_name(), &version[1..], source.source_id()) {
```
Comment (ehuss) [inline src/cargo/ops/common_for_install_and_uninstall.rs:549]: I'm a little uncomfortable just blindly stripping the first character from the version req.  Perhaps only do the check if `version_req().is_exact()`?  I think that should guarantee that it is `=` followed by an exact version.

Which reminds me that this doesn't help for non-specific versions (like `*` or `~2`). That's probably a bigger can of worms, though.

File: src/cargo/ops/common_for_install_and_uninstall.rs [hunk 5]
```diff
@@ -544,12 +544,33 @@ where
...
+                        bail!(
+                            "could not find `{}` in {} with version `{}`",
+                            dep.package_name(),
+                            source.source_id(),
+                            dep.version_req(),
+                        )
+                    }
+                }
+                Err(_) => bail!(
+                    "could not find `{}` in {} with version `{}`",
```
Comment (ehuss) [inline src/cargo/ops/common_for_install_and_uninstall.rs:567]: Can this be restructured to avoid the duplication of these two cases?  Maybe something like:

```rust
let maybe_pkg_id = PackageId::new(dep.package_name(), &version[1..], source.source_id());
let is_yanked = maybe_pkg_id.map_or(false, |pkg_id| source.is_yanked(pkg_id).unwrap_or(false));
if is_yanked {
    // ...yanked error
} else {
    // ...not found error
}
```

**Comment by ehuss** [comment]
>  Can you please have a look at the CI/test the failed one. I'm unable to get details like why 2 tests are failing. Thanks

This was just something that changed in nightly, it should be fixed now (via #8576).  If you rebase on the latest master, it should be fixed.

File: tests/testsuite/install.rs (hunk 2 above)
Comment (bishtpawan) [reply tests/testsuite/install.rs]: Thanks for the suggestion. I've updated the PR, please have a look.

File: tests/testsuite/install_upgrade.rs (hunk 3 above)
Comment (bishtpawan) [reply tests/testsuite/install_upgrade.rs]: Thanks for the suggestion. I've updated the PR, please have a look.

File: src/cargo/ops/common_for_install_and_uninstall.rs (hunk 5 above)
Comment (bishtpawan) [reply src/cargo/ops/common_for_install_and_uninstall.rs:565]: Yes, you are correct. Thanks for the snippet. I've incorporated this in the PR. Please have a look once you get time.

File: src/cargo/ops/common_for_install_and_uninstall.rs [hunk 6]
```diff
@@ -544,12 +544,31 @@ where
...
-            source.source_id(),
-            dep.version_req(),
-        ),
+        None => {
+            let version: String = dep.version_req().to_string();
+            let pkg_id;
+            if dep.version_req().is_exact() {
+                pkg_id = PackageId::new(dep.package_name(), &version[1..], source.source_id());
+            } else {
+                pkg_id = PackageId::new(dep.package_name(), &version[..], source.source_id());
```
Comment (ehuss) [inline src/cargo/ops/common_for_install_and_uninstall.rs:553]: Since this line is almost guaranteed to fail, I think it is a little misleading to try to create the PackageId here. Maybe be a little more explicit here?  For example, something like the following:

```rust
let is_yanked = if dep.version_req().is_exact() {
    let version: String = dep.version_req().to_string();
    PackageId::new(dep.package_name(), &version[1..], source.source_id())
        .map_or(false, |pkg_id| source.is_yanked(pkg_id).unwrap_or(false))
} else {
    false
};
```

Comment (bishtpawan) [reply src/cargo/ops/common_for_install_and_uninstall.rs:553]: okay got it, like if we don't have exact version then control will always go to the else part. Let me update the PR. Thanks again for explaining your point with the code snippet, which really helps me to get your point.

**Comment by ehuss** [comment]
Thanks!  And thanks for putting up with my pickiness. 😄 

@bors r+
