### PR TITLE
fix: rebuild rustdoc json for different versions of a same crate

### LINKED ISSUE #16291: `cargo rustdoc --output-format=json` sometimes doesn't rebuild for different versions of same crate name.
### Problem

When multiple dependencies have the same name,
running `cargo rustdoc --output-format=json -p <pkg>@<ver>`
sometimes won't re-run rustdoc if the version has changed.

### Steps

(For a repo containing this, see <https://codeberg.org/adot/cargo-rustdoc-json-bug>).

We have a crate `entry` that depends both on `dep@1.0.0` and `dep@2.0.0`

**File: `entry/Cargo.toml`**
```toml
[package]
name = "entry"
version = "0.1.0"
edition = "2024"

[dependencies]
dep_v1 = { path = "../dep_v1", package = "dep" }
dep_v2 = { path = "../dep_v2", package = "dep" }
```

**File: `dep_v1/Cargo.toml`**
```toml
[package]
name = "dep"
version = "1.0.0"
edition = "2024"
```

**File: `dep_v2/Cargo.toml`**
```toml
[package]
name = "dep"
version = "2.0.0"
edition = "2024"
```

Then in `entry/` run:

1. Make sure we're doing a clean build

    ```console
    $ cargo clean
     Removed 120 files, 637.0KiB total
    ```
2. Build rustdoc-json for `dep@1.0.0`:

    ```console
    $ cargo rustdoc --output-format=json -Zunstable-options --package=dep@1.0.0
     Documenting dep v1.0.0 (/home/alona/tmp/cargo-rustdoc-json-bug/dep_v1)
        Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.11s
       Generated /home/alona/tmp/cargo-rustdoc-json-bug/entry/target/doc/dep.json
    ```

    This runs `rustdoc`, as expected.

2. Build rustdoc-json for `dep@2.0.0`:

    ```console
    $ cargo rustdoc --output-format=json -Zunstable-options --package=dep@2.0.0
     Documenting dep v2.0.0 (/home/alona/tmp/cargo-rustdoc-json-bug/dep_v2)
        Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.56s
       Generated /home/alona/tmp/cargo-rustdoc-json-bug/entry/target/doc/dep.json
    ```

    Even though it's outputting the same path, in re-run `rustdoc`, because the package being documented has changed.

3. Re-build rustdoc-json for `dep@1.0.0`:

    ```console
    $ cargo rustdoc --output-format=json -Zunstable-options --package=dep@1.0.0
        Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.02s
    Generated /home/alona/tmp/cargo-rustdoc-json-bug/entry/target/doc/dep.json
    ```

    For some reason this time, it doesn't re-run `rustdoc`.
    The file `dep.json` now contains output for `dep@2.0.0`, not `dep@1.0.0`

### Possible Solution(s)

Either cargo could somehow re-build in step 3 (as well as 2, as it currently does).
I'm not familiar enough with cargo's caching logic to say why this happens.

Alternatively we could resolve this in rustdoc, by fixing https://github.com/rust-lang/rust/issues/142370.
This would involve rustdoc adding the value of `-Cmetadata` or `-Cextra-filename`.
I think this is preferable because it means that a user can switch between building `dep@1.0.0` and `dep@2.0.0`
without having to rebuild each time, because they're not the same.

### Notes

_No response_

### Version

```text
cargo 1.93.0-nightly (5c0343317 2025-11-18)
release: 1.93.0-nightly
commit-hash: 5c0343317ce45d2ec17ecf41eaa473a02d73e29c
commit-date: 2025-11-18
host: x86_64-unknown-linux-gnu
libgit2: 1.9.1 (sys:0.20.2 vendored)
libcurl: 8.15.0-DEV (sys:0.4.83+curl-8.15.0 vendored ssl:OpenSSL/3.5.4)
ssl: OpenSSL 3.5.4 30 Sep 2025
os: Ubuntu 25.4.0 (plucky) [64-bit]
```

### PR DESCRIPTION
**Pull request by motorailgun**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/cargo/pull/16773)*

Fix #16291.

### What does this PR try to resolve?

As discussed in the linked issue, `cargo rustdoc --output-format=json` doesn't rebuild for same crate name but with different versions. This is because current cargo implementation around rustdoc only specifies output paths/names by only its crate names, but not with version(hash) info.

This PR forces new layout for json output, and uplift the file into backward-compatible place.

### How to test and review this PR?

- Can we consider just forcing new layout for `--output-format=json`? (and stop uplifting) 
- Uplifting will always happen even if uplifted json is fresh, and/or new layout is manually specified. (could not figure out how to prevent); however it is just a copy operation if docs JSON are already built and fresh.

### CODE REVIEW

File: src/cargo/core/compiler/build_runner/compilation_files.rs [hunk 1]
```diff
@@ -513,8 +513,12 @@ impl<'a, 'gctx: 'a> CompilationFiles<'a, 'gctx> {
             }
             CompileMode::Doc => {
                 let path = if bcx.build_config.intent.wants_doc_json_output() {
+                    let hash = self.metadata(unit).unit_id();
+                    let crate_name = unit.target.crate_name();
                     self.output_dir(unit)
```
Comment (weihanglo) [inline src/cargo/core/compiler/build_runner/compilation_files.rs]: Haven't yet thought harder on this (and haven't yet started a thorough review), though I wonder if this can somehow leverage per-unit directory layout

* https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#build-dir-new-layout
* https://blog.rust-lang.org/2026/03/13/call-for-testing-build-dir-layout-v2/

Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs]: `-Zrustdoc-mergrable-info` also puts things to new layout dir btw

Comment (motorailgun) [reply src/cargo/core/compiler/build_runner/compilation_files.rs]: Interesting, will it be somewhere around `<build_dir>/<profile>/build/<pkg_name>/<hash>/out/`?

Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs]: These were the past relevant discussions

* https://github.com/rust-lang/cargo/pull/16309#discussion_r2570360992
* https://github.com/rust-lang/cargo/pull/16527

And if we want to put this under things like `<build_dir>/<profile>/build/<pkg_name>/<hash>/out/` it might be better to move doc parts JSON into a sub-dir, and so does rustdoc output JSON, such as

* `<build_dir>/<profile>/build/<pkg_name>/<hash>/out/parts/` for doc-parts
* `<build_dir>/<profile>/build/<pkg_name>/<hash>/out/json/` for JSON output

I had a experimental commit here moving things <https://github.com/weihanglo/cargo/pull/87/changes/f53fd1e9846ae5f5569f4f15c186bd99fc044c1c>.

If we ever did this, we might want to note this in the tracking rustdoc JSON output tracking issue.

Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs]: cc @ranger-ross
 what do you think?

Comment (ranger-ross) [reply src/cargo/core/compiler/build_runner/compilation_files.rs]: In the v2 `build-dir` layout the `build/<pkg_name>/<hash>/out` is the correct place for this. (it's meant to be a [general purpose output](https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/layout.rs#L162-L165) location for a given build units)

As for including a sub-directory, I don't have strong feelings on this but one of the considerations in the new layout was keeping the total path length short for windows. 

Also as a side note, which ever direction we end up going it would probably be nice to add a test to [`testsuite/build_dir.rs`](https://github.com/rust-lang/cargo/blob/master/tests/testsuite/build_dir.rs) and [`testsuite/build_dir_legacy.rs`](https://github.com/rust-lang/cargo/blob/master/tests/testsuite/build_dir_legacy.rs) verify the new file locations.

Comment (motorailgun) [reply src/cargo/core/compiler/build_runner/compilation_files.rs]: Thank you for all the feedback! As per reading about new layouts, I think (1) always put json into `build/<pkg_name>/<hash>/out` and (2) uplift if new layout is not specified - is a good option. For parts I am not sure, but if it's not something that changes by depend-ers, they could also just be at  `build/<pkg_name>/<hash>/out` .

Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs]: `-Zrustdoc-mergeable-info` already puts the doc pards in `.../out/`. However, cargo later includes them via `rustdoc --include-parts-dir` which points to the `.../out/` directory. I am not sure if rustdoc is smarter enough the two different types of JSON files. That's why I think a sub dir might be needed.

Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs]: Oh I think I was wrong. A unit that outputs JSON format won't be the same unit that output doc parts. I must have been brain dead.

No. No subdirectory needed unless one day JSON output also has doc parts JSON, which is unlikely.

Comment (motorailgun) [reply src/cargo/core/compiler/build_runner/compilation_files.rs]: Oh I see, then `build/<pkg_name>/<hash>/out` would be right for this PR I guess...?

Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs]: yes

**Comment by motorailgun** [comment]
Updated to use new directory layout.

File: src/cargo/core/compiler/build_runner/mod.rs [hunk 2]
```diff
@@ -235,6 +236,11 @@ impl<'a, 'gctx> BuildRunner<'a, 'gctx> {
         for unit in &self.bcx.roots {
             self.collect_tests_and_executables(unit)?;
 
+            // Uplift rustdoc
+            if unit.mode.is_doc() {
```
Comment (weihanglo) [inline src/cargo/core/compiler/build_runner/mod.rs]: Should we do the `is_json_output(self)` here instead, and keep `uplift_rustdoc` always uplift?

File: src/cargo/core/compiler/rustdoc.rs [hunk 3]
```diff
@@ -242,6 +242,12 @@ pub fn add_root_urls(
     Ok(())
 }
 
+/// Checks whether JSON output should be enabled for rusdoc invocation
+pub fn is_json_output(build_runner: &BuildRunner<'_, '_>) -> bool {
```
Comment (weihanglo) [inline src/cargo/core/compiler/rustdoc.rs]: It is a bit confusing as we import this as `is_json_output` in `compiler/mod.rs`. Should we make the function name more explicit, like `is_rustdoc_json_output`?

File: tests/testsuite/build_dir.rs [hunk 4]
```diff
@@ -501,6 +501,46 @@ fn cargo_doc_should_output_to_target_dir() {
     assert_exists(&docs_dir.join("foo/index.html"));
 }
 
+#[cargo_test(nightly, reason = "--output-format is unstable")]
+fn cargo_rustdoc_json_should_output_to_target_dir() {
```
Comment (weihanglo) [inline tests/testsuite/build_dir.rs:505]: Can we add new tests first, and the fix and snapshots in the second commit? So that we can see the behavior change in the snapshot updates. See <https://epage.github.io/dev/pr-style/#c-test>.

Comment (motorailgun) [reply tests/testsuite/build_dir.rs:505]: Ugh, sorry about my stupidness of forgetting atomic commits again... thank you for pointing out!

**Comment by motorailgun** [comment]
Note: updated PR message reflecting changes.

File: src/cargo/core/compiler/build_runner/mod.rs (hunk 2 above)
Comment (BMG042) [reply src/cargo/core/compiler/build_runner/mod.rs]: Yes

File: tests/testsuite/build_dir.rs (hunk 4 above)
Comment (BMG042) [reply tests/testsuite/build_dir.rs:505]: 😂😂

**Review by BMG042 — APPROVED** [review]

File: src/cargo/core/compiler/build_runner/compilation_files.rs [hunk 5]
```diff
@@ -524,8 +524,10 @@ impl<'a, 'gctx: 'a> CompilationFiles<'a, 'gctx> {
             }
             CompileMode::Doc => {
                 let path = if bcx.build_config.intent.wants_doc_json_output() {
-                    self.output_dir(unit)
```
Comment (BMG042) [inline src/cargo/core/compiler/build_runner/compilation_files.rs:527]: // Before:
self.output_dir(unit).join(format!("{}.json", unit.target.crate_name()))

// After:
self.out_dir_new_layout(unit).join(format!("{crate_name}.json"))

**Review by BMG042 — COMMENTED** [review]
cd /path/to/cargo
git fetch origin pull/16773/head:pr-16773
git checkout pr-16773


*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16773/7046015748b7d3254e34b19fd53eabf36ad7baaa..79399ac672bc1996ce4aba844795a529fbecf525)*

File: src/cargo/core/compiler/build_runner/compilation_files.rs (hunk 5 above)
Comment (weihanglo) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:527]: @rust-lang/mods 

spam likely throughout this PR and <https://github.com/rust-lang/cargo/issues/15921#issuecomment-3272909172>

Thanks.

Comment (jieyouxu) [reply src/cargo/core/compiler/build_runner/compilation_files.rs:527]: Blocked.

File: src/cargo/core/compiler/build_runner/mod.rs [hunk 6]
```diff
@@ -235,6 +236,11 @@ impl<'a, 'gctx> BuildRunner<'a, 'gctx> {
         for unit in &self.bcx.roots {
             self.collect_tests_and_executables(unit)?;
 
+            // Uplift rustdoc
+            if is_rustdoc_json_output(&self) {
```
Comment (weihanglo) [inline src/cargo/core/compiler/build_runner/mod.rs]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16773/7046015748b7d3254e34b19fd53eabf36ad7baaa..79399ac672bc1996ce4aba844795a529fbecf525)*

Sorry I didn't really review this carefully until this round.

I feel like this is the not the correct place to uplift. In Cargo we track whether a `OutputFile` will be uplifted through its `hard_link`. If we make rustdoc JSON as part of that, we'll get uplifting logic for free. We would probably get uplifting logic for free if we set it here:

https://github.com/rust-lang/cargo/blob/428d32615a746f2e972d20cb5f889bfb0efbb2d0/src/cargo/core/compiler/build_runner/compilation_files.rs?plain=1#L537

---

Also, this seems to unconditionally uplift rustdoc JSON for every root unit. Not wrong but a bit error-prone as it assumes every root unit is rustdoc (which is true actually as `output-format` is available only in `cargo rustdoc`.

File: src/cargo/core/compiler/build_runner/mod.rs [hunk 7]
```diff
@@ -787,4 +793,21 @@ impl<'a, 'gctx> BuildRunner<'a, 'gctx> {
...
+    //       but there is no way we can collect new out dir paths from ops.
+    //       Thus we here always do uplifting.
+    fn uplift_rustdoc(&self, unit: &Unit) -> CargoResult<()> {
+        let doc_dir = self.files().output_dir(unit);
+        let doc_json_dir = self.files().out_dir_new_layout(unit);
+        let crate_name = unit.target.crate_name();
+        let filename = format!("{crate_name}.json");
+
+        let src_path = doc_json_dir.join(&filename);
+        copy(src_path, doc_dir.join(&filename))?;
```
Comment (weihanglo) [inline src/cargo/core/compiler/build_runner/mod.rs]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16773/7046015748b7d3254e34b19fd53eabf36ad7baaa..79399ac672bc1996ce4aba844795a529fbecf525)*

We have `cargo_util::paths::link_or_copy` though we should leverage `OutputFile::hardlink`

File: src/cargo/core/compiler/rustdoc.rs [hunk 8]
```diff
@@ -250,15 +256,13 @@ pub fn add_output_format(
     build_runner: &BuildRunner<'_, '_>,
     rustdoc: &mut ProcessBuilder,
 ) -> CargoResult<()> {
-    let gctx = build_runner.bcx.gctx;
-    if !gctx.cli_unstable().unstable_options {
-        tracing::debug!("`unstable-options` is ignored, required -Zunstable-options flag");
-        return Ok(());
-    }
```
Comment (weihanglo) [inline src/cargo/core/compiler/rustdoc.rs:257]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16773/7046015748b7d3254e34b19fd53eabf36ad7baaa..79399ac672bc1996ce4aba844795a529fbecf525)*

I wonder if we actually don't need this guard `unstable_optionts` here?

The place we set `UserIntent::Doc { json: true }` has already checked `-Zunstable-options` presence:

https://github.com/rust-lang/cargo/blob/35f8202bfe47f954a4613a846cfd406bda9d3b8c/src/bin/cargo/commands/rustdoc.rs?plain=1#L56-L72

So that may imply we also don't need the `is_rustdoc_json_output` at all

File: src/cargo/core/compiler/build_runner/mod.rs (hunk 6 above)
Comment (motorailgun) [reply src/cargo/core/compiler/build_runner/mod.rs]: Sounds right & I didn't know about this. Thank you!

File: src/cargo/core/compiler/rustdoc.rs (hunk 8 above)
Comment (motorailgun) [reply src/cargo/core/compiler/rustdoc.rs:257]: Ooh, right. `is_rustdoc_json_output` is removed now!

File: src/cargo/core/compiler/mod.rs [hunk 9]
```diff
@@ -1055,12 +1066,17 @@ fn rustdoc(build_runner: &mut BuildRunner<'_, '_>, unit: &Unit) -> CargoResult<W
             }
         }
 
-        let crate_dir = doc_dir.join(&crate_name);
+        let crate_dir = if is_json_output {
```
Comment (weihanglo) [inline src/cargo/core/compiler/mod.rs]: We don't need to clean up doc.json file for the new layout, as they are isolated by units.

That said, I do want to know how this would affect `cargo clean --doc`. We should at least track it in the tracking issue

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16773/80abaf48e734eac117da67432e7b2a833c7576d3..be0b9930be7185ff757d378b7a7564a1e643bf80)*

File: tests/testsuite/build_dir.rs [hunk 10]
```diff
@@ -501,6 +501,46 @@ fn cargo_doc_should_output_to_target_dir() {
...
+            ".cargo/config.toml",
+            r#"
+            [build]
+            target-dir = "target-dir"
+            build-dir = "build-dir"
+            "#,
+        )
+        .build();
+
+    p.cargo("-Zbuild-dir-new-layout rustdoc -Zfine-grain-locking -Zunstable-options --output-format json")
```
Comment (weihanglo) [inline tests/testsuite/build_dir.rs]: is fine grain locking required here?

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16773/80abaf48e734eac117da67432e7b2a833c7576d3..be0b9930be7185ff757d378b7a7564a1e643bf80)*

File: tests/testsuite/build_dir_legacy.rs [hunk 11]
```diff
@@ -459,6 +459,45 @@ fn cargo_doc_should_output_to_target_dir() {
...
+            r#"
+            [build]
+            target-dir = "target-dir"
+            build-dir = "build-dir"
+            "#,
+        )
+        .build();
+
+    p.cargo("rustdoc -Zunstable-options --output-format json")
+        .masquerade_as_nightly_cargo(&["new build-dir layout", "rustdoc-output-format"])
```
Comment (weihanglo) [inline tests/testsuite/build_dir_legacy.rs]:
```suggestion
        .masquerade_as_nightly_cargo(&["rustdoc-output-format"])
```


*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16773/80abaf48e734eac117da67432e7b2a833c7576d3..be0b9930be7185ff757d378b7a7564a1e643bf80)*

File: tests/testsuite/build_dir.rs (hunk 10 above)
Comment (motorailgun) [reply tests/testsuite/build_dir.rs]: My bad, I think I left this when I copy-pased from another test case. Will fix

File: src/cargo/core/compiler/mod.rs (hunk 9 above)
Comment (motorailgun) [reply src/cargo/core/compiler/mod.rs]: From my quick observation, doc.json file will escape normal `cargo clean --doc` operation? Will dig into tomorrow.

https://github.com/rust-lang/cargo/blob/f4f977ff6fc657b3bcf3ac1addd4fd62387ddd46/src/cargo/ops/cargo_clean.rs#L88-L100

Comment (weihanglo) [reply src/cargo/core/compiler/mod.rs]: Tracking issue btw: https://github.com/rust-lang/cargo/issues/13283

Though I feel like we probably don't need to deal with `cargo clean --doc`. So the behavior doesn't need to be "cleaning anything related to artifacts."

```
--doc
    This option will cause cargo clean to remove only the doc directory in the target directory.
```

That makes me wonder [`-Zrustdoc-mergeable-info`](https://github.com/rust-lang/cargo/issues/16306) also doesn't need to support `cargo clean`.

@ranger-ross any thoughts?

File: tests/testsuite/build_dir.rs (hunk 10 above)
Comment (motorailgun) [reply tests/testsuite/build_dir.rs]: Uh oh, do we actually need `-Zfine-grain-locking` here? #16155 added this on most (if not all) test cases for new build layout, through I can't find discussion or documentation whether this should be always on for new build-dir layout right now.

Comment (weihanglo) [reply tests/testsuite/build_dir.rs]: The new layout feature shouldn't depend on the new locking feature IIUC

Comment (motorailgun) [reply tests/testsuite/build_dir.rs]: Got it, thank you!

File: src/cargo/core/compiler/mod.rs (hunk 9 above)
Comment (weihanglo) [reply src/cargo/core/compiler/mod.rs]: I meant, we may leave it for future. No need to worry about it now

File: src/cargo/core/compiler/mod.rs [hunk 12]
```diff
@@ -1055,13 +1065,15 @@ fn rustdoc(build_runner: &mut BuildRunner<'_, '_>, unit: &Unit) -> CargoResult<W
...
         }
 
-        let crate_dir = doc_dir.join(&crate_name);
-        if crate_dir.exists() {
-            // Remove output from a previous build. This ensures that stale
-            // files for removed items are removed.
-            debug!("removing pre-existing doc directory {:?}", crate_dir);
-            paths::remove_dir_all(crate_dir)?;
-        }
+        if !is_json_output {
```
Comment (weihanglo) [inline src/cargo/core/compiler/mod.rs:1068]: `rustdoc --output-format` currently only accepts one format and each option is mutually exclusive, so this check should be fine for now. 

If it ever changes to accepts muliple, we'll need to update this (and this place is unlikely the only place need an update).

File: src/cargo/core/compiler/rustdoc.rs [hunk 13]
```diff
@@ -250,12 +250,6 @@ pub fn add_output_format(
     build_runner: &BuildRunner<'_, '_>,
     rustdoc: &mut ProcessBuilder,
 ) -> CargoResult<()> {
-    let gctx = build_runner.bcx.gctx;
```
Comment (weihanglo) [inline src/cargo/core/compiler/rustdoc.rs:253]: nit: This is a better to be a refactor commit.

File: tests/testsuite/rustdoc.rs [hunk 14]
```diff
@@ -434,6 +434,6 @@ fn rustdoc_json_same_crate_different_version() {
         .run();
 
     let dep_json = fs::read_to_string(entry.root().join("target/doc/dep.json")).unwrap();
-    assert!(!dep_json.contains("dep_v1_fn"));
-    assert!(dep_json.contains("dep_v2_fn"));
+    assert!(dep_json.contains("dep_v1_fn"));
+    assert!(!dep_json.contains("dep_v2_fn"));
```
Comment (weihanglo) [inline tests/testsuite/rustdoc.rs:438]: Nice test that makes cargo replaces outdated uplifted content!

**Review by weihanglo — APPROVED** [review]
Thanks for working on this!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16773/b7de9d4e3ac870e1d7f5f9f97a3ac80533d499d9..9e895e1218a58ae7109766eb67f210c9fc6f2d4e)*

**Comment by weihanglo** [comment]
BTW, if follows conventional commit message stricter, the first commit should be `test:` and the second one should be `fix:`.

Anyway, thanks!

**Comment by motorailgun** [comment]
Oh, is that failing test just flaky? If so I'd love to take some time to amend the commits (messages and histories).

**Comment by weihanglo** [comment]
> Oh, is that failing test just flaky? If so I'd love to take some time to amend the commits (messages and histories).

Yeah definitely flaky. 

Feel free to amend the commits if you'd like to. I will merge this on Friday anyway before the next Cargo submodule sync in rust-lang/rust (which is probably tomorrow within 24hrs)


```
---- util::local_poll_adapter::tests::deferred_success stdout ----

thread 'util::local_poll_adapter::tests::deferred_success' (9550) panicked at src/cargo/util/local_poll_adapter.rs:177:9:
assertion `left == right` failed
  left: Ready(Ok(50))
 right: Pending

```

**Comment by motorailgun** [comment]
Thank you, fixed & updated PR title!

**Review by weihanglo — APPROVED** [review]
