### PR TITLE
fix(toml): show required rust-version in unstable edition error

### LINKED ISSUE #15305: More helpful error message for unsupported editions: display the required `rust-version`
### Problem

When cargo encounters an unsupported edition, the error message it displays isn't actionable, where the action in this case is to upgrade cargo/rustc to 1.85 or newer:

```
Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.81.0 (2dbb1af80 2024-08-20)).
```

### Proposed Solution

In the event an edition is unsupported, It would be more helpful if cargo printed the standard error for an out-of-date rust version by extracting `package.rust-version` when specified:

```
error: rustc 1.81.0 is not supported by the following package:
  mypackage@0.1.0 requires rustc 1.85
```

### Notes

_No response_

### PR DESCRIPTION
**Pull request by yash-kumarx**
## What does this PR try to resolve?

Fixes the unhelpful error when a package declares an unstable edition on a 
stable Cargo toolchain. Previously the error told the user to "try a newer 
version of Cargo" but gave no indication of *which* version, forcing them to 
dig through docs.

This PR adds a `help:` line that names the required toolchain version,
derived from the package's `rust-version` field (or from
`Edition::first_version()` once that is set at unstable time).

Before:
```
Consider trying a newer version of Cargo (this may require the nightly release).
See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#unstable-editions
```

After:
```
Consider trying a newer version of Cargo (this may require the nightly release).
help: mypackage@0.1.0 requires rustc 1.90
See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#unstable-editions
```

Also fixes a latent bug in `edition_unstable_gated`: it expected
`feature 'edition{next}'` but current code emits `feature 'unstable-editions'`.
The test was silently skipping because `Edition::LATEST_UNSTABLE` is `None`.

Fixes #15305

### CODE REVIEW

**Comment by yash-kumarx** [comment]
> > Also fixes a latent bug in edition_unstable_gated: it expected
> > feature 'edition{next}' but current code emits feature 'unstable-editions'.
> > The test was silently skipping because Edition::LATEST_UNSTABLE is None.
> 
> Not having time reviewing the diff, though with that "and" I would assume this PR has at least two commits but I only saw commit. We recommend atomic commits for Git history management.
> 
> _[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16653/8cc0cb136772b8f54eafe0d163fcb7226a06af0c..6a5139baa3fb9d5ea0812e338e097cea16a0a65e)_

@weihanglo Done, Split into two atomic commits:

- fix(test): corrects the edition_unstable_gated test which was expecting the wrong feature name and silently skipping

- fix(toml): the actual fix — adds the help: hint derived from rust-version

Thank you for your feedback

File: tests/testsuite/edition.rs [hunk 1]
```diff
@@ -55,27 +55,32 @@ fn edition_unstable_gated() {
...
+    //      happens at stabilisation time), so `required_rustc` is None.
     p.cargo("check")
         .with_status(101)
         .with_stderr_data(format!(
             "\
 [ERROR] failed to parse manifest at `[ROOT]/foo/Cargo.toml`
 
 Caused by:
-  feature `edition{next}` is required
+  feature `unstable-editions` is required
```
Comment (epage) [inline tests/testsuite/edition.rs]: How did you verify this output with the test still being skipped?

File: tests/testsuite/edition.rs [hunk 2]
```diff
@@ -247,6 +247,43 @@ Caused by:
         .run();
 }
 
+#[cargo_test]
+fn future_edition_with_rust_version_hint() {
```
Comment (epage) [inline tests/testsuite/edition.rs:246]: We would prefer new tests to be added in their own commit before features/fixes, with them passing (ie atomic, showing current behavior).  This commit would then only show how the test needed updating which helps to show how behavior changed.

See https://doc.crates.io/contrib/process/working-on-cargo.html#submitting-a-pull-request

**Comment by epage** [comment]
FYI I believe this is addressing #15305.  Please link out to relevant issues in the PR description.  If you say `Fixes #15305` on its own line, github will automatically close it on merge.

File: src/cargo/util/toml/mod.rs [hunk 3]
```diff
@@ -1359,7 +1359,21 @@ pub fn to_real_manifest(
...
-        features.require(Feature::unstable_editions())?;
+        // Build a help hint pointing the user at the required toolchain version.
+        // Prefer the edition's known minimum version (if it was set at unstable time);
+        // fall back to the package's `rust-version` field.
+        let pkg_version = normalized_package
+            .normalized_version()
+            .expect("previously normalized");
+        let required_rustc = edition
+            .first_version()
+            .map(|v| format!("{}.{}", v.major, v.minor))
```
Comment (epage) [inline src/cargo/util/toml/mod.rs]: If its unstable, then it doesn't have a `first_version` I believe

File: src/cargo/util/toml/mod.rs [hunk 4]
```diff
@@ -1359,7 +1359,21 @@ pub fn to_real_manifest(
...
+            .or_else(|| rust_version.as_ref().map(|rv| rv.to_string()));
+        let hint = required_rustc.map(|rv| match pkg_version {
+            Some(v) => format!("help: {}@{} requires rustc {}", package_name, v, rv),
```
Comment (epage) [inline src/cargo/util/toml/mod.rs]: I believe we generally say `rust` and not `rustc`

Comment (epage) [inline src/cargo/util/toml/mod.rs]: Please use string interpolation

File: src/cargo/util/toml/mod.rs [hunk 5]
```diff
@@ -1359,7 +1359,21 @@ pub fn to_real_manifest(
...
+        // Prefer the edition's known minimum version (if it was set at unstable time);
+        // fall back to the package's `rust-version` field.
+        let pkg_version = normalized_package
+            .normalized_version()
+            .expect("previously normalized");
+        let required_rustc = edition
+            .first_version()
+            .map(|v| format!("{}.{}", v.major, v.minor))
+            .or_else(|| rust_version.as_ref().map(|rv| rv.to_string()));
+        let hint = required_rustc.map(|rv| match pkg_version {
```
Comment (epage) [inline src/cargo/util/toml/mod.rs]: Instead of duplicating messages, what we tend to do is:
```
let version = pkg_version.map(...).unwrap_or_default();
let hint = format!("help: {package_name}{version} ...");
```

File: tests/testsuite/edition.rs [hunk 6]
```diff
@@ -276,6 +277,7 @@ Caused by:
 
   The package requires the Cargo feature called `unstable-editions`, but that feature is not stabilized in this version of Cargo ([..]).
   Consider trying a newer version of Cargo (this may require the nightly release).
+  [HELP] foo@0.1.0 requires rust 1.90
   See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#unstable-editions for more information about the status of this feature.
```
Comment (epage) [inline tests/testsuite/edition.rs]: The `HELP` section going before `See` implies that the `See` is part of it when it isn't.

File: tests/testsuite/edition.rs (hunk 1 above)
Comment (epage) [reply tests/testsuite/edition.rs]: FYI this question is still outstanding

Comment (yash-kumarx) [reply tests/testsuite/edition.rs]: Truly sorry @epage,
Since LATEST_UNSTABLE is None right now, the test always returns early so runtime verification is not possible. I verified it by reading the source: unstable_editions is defined in `features.rs` and `require()` applies .replace("_", "-") to the name, which gives unstable-editions. The docs URL fragment is also hardcoded in the same feature definition. Both are constants so I'm fairly confident the expected output is right, but if you say I can revert this change and leave the test untouched if you would prefer to revisit it when LATEST_UNSTABLE gets set again.

Comment (epage) [reply tests/testsuite/edition.rs]: As an old coworker said "if it isn't tested, then it is broken".  That is going to a bit of an extreme imo but I think it applies here.  You found that the output is incorrect for your reading of the code but the same kind of inspection is the only way to check if the new version of the code is correct.  I would lean towards not changing it.  On top of that, this doesn't seem to be related to this PR.

**Review by epage — APPROVED** [review]
Thanks!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/cargo/16653/f298b8c82da0cba538516b45b04a480fc501d4c0..2866bb6c0890b83803d86e7aa85ca5fa912dafd1)*
